### ISSUE TITLE
Menu cannot be opened on Android browser on deed pages

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.org#1007]
Issue reported on Samsung Galaxy J2 with Android version 5.1.1: the triple line in the right corner of the page (looked at from my position) could not be opened

Example deed page: [Creative Commons — Attribution 4.0 International — CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

The template used: [cc.engine/standard_deed.html at master · creativecommons/cc.engine](https://github.com/creativecommons/cc.engine/blob/master/cc/engine/templates/licenses/standard_deed.html)

**Comment by hugosolar** [comment]
I can't reproduce the error
I tested in: 
- Android Browser - Android 4.4
- Android Browser - Android 5.1
- Android default Browser - Android 9

In all these versions hamburger menu works

**Comment by kgodey** [comment]
I'll follow up with the user, can you assign to me once the latest deed changes are deployed?

**Comment by kgodey** [comment]
Since we cannot reproduce this, I haven't received further reports, and we're redesigning this, I'm going to close this issue.
