### ISSUE TITLE
Share preview plugin for blog

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#1010]
I may be mistaken, but it is currently not possible to share draft blog post previews with people who are not logged in to the CC site. This makes it difficult to prepare and get approval for announcements that include outside parties (or even inside ones that don't yet have logins, etc.) There appear to be a number of WP plugins that enable this -- can we look into it?

**Comment by hugosolar** [comment]
Ok @ericsteuer 
I install a plugin called [Public Post Preview](https://wordpress.org/plugins/public-post-preview/) 
it seems to be the best option in the WP plugin repository.
To enable a public preview you should click on the checkbox on the right box 

<img width="279" alt="Screen Shot 2019-08-24 at 12 18 55 AM" src="https://user-images.githubusercontent.com/894708/63632524-91841780-c605-11e9-9cd0-281bfcd737f4.png">
