### ISSUE TITLE
Make Korean 4.0 translations temporarily inaccessible.

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/creativecommons.org#1011]
There are some problems with the newly released Korean translations.

1. The links to the legalcode in the deed have not been updated in Transifex, so they lead to the English legalcode.
2. The Korean legalcode has a number of typos and inaccuracies and will need to be fixed.

As a result, we will be making the Korean legalcode temporarily inaccessible.

**Comment by kgodey** [comment]
This is done.
