### ISSUE TITLE
update website banner to highlight KS campaign

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#102]
Will you update the donate banner on the homepage to say: "We're almost there - push us to the finish line! Back CC's Kickstarter book on open business models today" Leave the donate button there, but redirect it to KS. Time sensitive with 7 days left in the campaign so hoping to ship ASAP!

**Comment by rebeccalendl** [comment]
@sarahpearson

**Comment by mattl** [comment]
That's going to be hard. Too much text. A quick test reveals the text will be very small.

I suggest "Almost there — CC's book on open business models" and "Back us on Kickstarter" for the button. That won't change the text size.

**Comment by rebeccalendl** [comment]
Great suggestion. Let's do it.

Rebecca Lendl
Director of Development
Creative Commons
rebecca@creativecommons.org

**Comment by mattl** [comment]
Great, I'll get it up in the morning.

---
Matt Lee
Creative Commons
Boston, MA, USA

**Comment by rebeccalendl** [comment]
Will you also temporarily (through next Thurs EOD) redirect this page:
https://donate.creativecommons.org/
To this page:
https://www.kickstarter.com/projects/creativecommons/made-with-creative-commons-a-book-on-open-business

**Comment by mattl** [comment]
Hmm, are we sure about that? That's going to likely break a lot of things, and annoy people. We should point the donation menu links on the website to KS instead.

**Comment by rebeccalendl** [comment]
Yeah, thought about that but feels like our best workaround and short term.
Goal is to capture the increased traffic coming through the deed pages.
Would the donation menu redirect accomplish that?

Rebecca Lendl
Director of Development
Creative Commons
rebecca@creativecommons.org

**Comment by mattl** [comment]
If we want people to go from the human-readable summary to the Kickstarter,
we should link there, not mess with our main donation page and do
redirects. Also, when it comes to taking all this stuff down in the middle
of in-town week, it'll be way less prone to missing something.

---
Matt Lee
Creative Commons
Boston, MA, USA

**Comment by rebeccalendl** [comment]
Feel like we will then need to loop in Trilogy and that will weigh down the process. What about adding that big orange banner that's on the home page to the donate page as well?

**Comment by mattl** [comment]
The orange banner will go Kickstarter colors, but I don't think adding it
to the already crowded donation page is a good idea.

We won't need to involve Trilogy to add it to the human readable summary
pages though.

**Comment by mzeinstra** [comment]
Could you do something about the outline of the banner, it looks quite unprofessional at the moment.

I believe the button and the H1 need a 
```
    line-height: normal;
```
to better line up.

![screen shot 2015-08-07 at 11 02 17](https://cloud.githubusercontent.com/assets/5627431/9132442/df895b1a-3cf3-11e5-99c7-cc580b347bde.png)

vs

![screen shot 2015-08-07 at 11 02 49](https://cloud.githubusercontent.com/assets/5627431/9132445/e2b47e28-3cf3-11e5-8ea9-262eb01de142.png)

**Comment by rebeccalendl** [comment]
Time sensitive! Clicking on "Donate to CC" under the Support CC menu is still redirecting to Kickstarter, should go to donate.creativecommons.org

**Comment by mattl** [comment]
Update the banner in both the WP theme repo and in the Python_env templates for the licenses page.

**Comment by robmyers** [comment]
Looking.

**Comment by robmyers** [comment]
Theme repo updated and pushed. Front page Support CC / Donate to CC now points to donate.cc .

**Comment by robmyers** [comment]
And chooser page updated.

Complete.

**Comment by robmyers** [comment]
@mattl There's something screwy with the git state of cc.org on the server, we should discuss that when I'm back next week.
