### ISSUE TITLE
"Related News" module on cc.org displays a strange line break

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#1023]
For instance at the bottom of https://creativecommons.org/about/bassel-khartabil-fellowships-memorial-fund/

"RELATE
D NEWS"

<img width="953" alt="Screen Shot 2019-08-30 at 6 01 27 AM" src="https://user-images.githubusercontent.com/8919762/64022777-c7d10380-caeb-11e9-8871-2b61a8ae9682.png">

**Comment by hugosolar** [comment]
There was a problem with our new self hosted fonts paths.
It's fixed now
