### ISSUE TITLE
Word breaks / line breaks in blog post titles

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#1025]
A really annoying thing about the CC blog is that words in post titles often break in the middle

Here's an example:
https://creativecommons.org/2019/09/04/creative-commons-for-educators-and-librarians/

Here's another:
https://creativecommons.org/2019/09/05/welcome-creative-commons-team/

Sometimes I force a line break by adding a break tag, but it feels like this isn't a thing that typically happens on blogs / news sections of websites like ours, and I'm wondering if there is some solution ? 

THANKS

**Comment by ifylala** [comment]
I would be appreciate if this task is assigned to me so I fix it. I look forward to hearing from you.

**Comment by hugosolar** [comment]
Hey @ifylala go ahead if you like to work in this issue

**Comment by ifylala** [comment]
Thanks so much @hugosolar

**Comment by ericsteuer** [comment]
FYI here's another example of this:

https://creativecommons.org/2019/10/11/robin-mckennas-gift-documentary-opens-today/

<img width="740" alt="Screen Shot 2019-10-11 at 11 32 14 AM" src="https://user-images.githubusercontent.com/8919762/66675779-e4984500-ec1a-11e9-9971-e73ac1934a13.png">

FWIW, this doesn't ever happen on the news/blog post main page (https://creativecommons.org/blog/)

thanks

**Comment by ifylala** [comment]
> FYI here's another example of this:
> 
> https://creativecommons.org/2019/10/11/robin-mckennas-gift-documentary-opens-today/
> 
> <img alt="Screen Shot 2019-10-11 at 11 32 14 AM" width="740" src="https://user-images.githubusercontent.com/8919762/66675779-e4984500-ec1a-11e9-9971-e73ac1934a13.png">
> 
> FWIW, this doesn't ever happen on the news/blog post main page (https://creativecommons.org/blog/)
> 
> thanks

I tried this url but it didn't break.

**Comment by hugosolar** [comment]
@ifylala only happens on WebKit.
We should force the title to avoid hyphenation using CSS
