### ISSUE TITLE
Create a different template for guest authors

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/creativecommons.org#1029]
We welcome guest authors to the CC blog. When there's a guest author, [this is the way it's displayed](https://creativecommons.org/author/spencerhyman/) if you look for the author's name in Google. 

![image](https://user-images.githubusercontent.com/390030/65704738-7457c400-e05d-11e9-914b-b7a3c9ed590d.png)

That's confusing in 2 ways:

1. Just looking at that page, it's not clear for the audience whether this person is part of the "Team" or not. Just looking at the navigation, gives the idea he is. 
2. The Author page is similar to the [real team people](https://creativecommons.org/author/kriticreativecommons-org/). 

Is there any way to create a different template for guest authors?

One more thing:

* If you go to a random author URL (say, [this](https://creativecommons.org/author/asdadeasdadasdasdasdasdasddasd/)), it does not show a 404 page but a very odd page of "Articles by: Jennie Rose Halperin"

**Comment by hugosolar** [comment]
About the 404 issue, I'm going to create a separate ticket
