### ISSUE TITLE
grey content blocks are not responsive

### ISSUE THREAD

**Issue by nasirkhan** [creativecommons/creativecommons.org#103]
In the homepage, there are several content blocks needed to taken care of. they are not responsive and needed to fix. there are  other pages which has the same type of issues.

I want to help fixing this issues, can you please tell me how can i do so?

**Comment by mattl** [comment]
You can check out our WordPress theme, github.com/creativecommons/cc-wp-theme -- but we're currently working on a new design so it may not be worth anything but crucial fixes right now.
