### ISSUE TITLE
Remove "Teach" from Education/OER Resources menu

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#1032]
A page from a very old version of the CC site (https://creativecommons.org/about/program-areas/education-oer/education-oer-resources/teach/) got incorrectly nested under the current site's "Program areas > Education / OER > Education / OER Resources".

The page is no longer relevant, so I unpublished it. But the URL for it is now redirecting to this old blog post: https://creativecommons.org/2006/02/14/teachccinvitesyoutoaspecialscreening/

And "Teach" is still showing up in the menu. 

It's fine for the blog post to stay online, but the "Teach" URL should not redirect to it, and "Teach" should be removed from the Education menu altogether.

Hope this makes sense. Thanks

<img width="322" alt="Screen Shot 2019-10-04 at 7 54 40 AM" src="https://user-images.githubusercontent.com/8919762/66217517-4d604a00-e67c-11e9-9472-f6671712a1e6.png">

**Comment by khyati18** [comment]
Can I work on this ?

**Comment by kgodey** [comment]
This issue is not marked "help wanted" and is not suitable for external contribution.

**Comment by hugosolar** [comment]
Seems to be a cache related issue becaue I can't see the option anymore. closing this issue.
