### ISSUE TITLE
cc.org/blog ordering of posts + displaying dates

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#1033]
hi, re: https://creativecommons.org/blog/

blog posts on this page display in this order:
1 hero post
then 4 featured posts
then all posts, from most to least recent

the effect of this ordering has always struck me as odd. if you go to this page, i feel you would expect to see a more straightforward view, with the most recent news at the top. i understand having Hero and Featured hierarchy for how posts appear on CC's homepage, but having that hierarchy carry over to /blog is confusing. especially because posts end up appearing twice on this page if they are selected as Hero or Featured.

at any rate, i would like to change things so that this page simply shows the most recent blog post up at the top, and does away with elevating Hero and Featured posts

ALSO, i would like each post on this page to show the date it was published. Currently, the date shows up for the Hero and (three of the four?) Featured posts, but it should show up for all of them.

THANKS

cc @victoriaheath @jennryn

**Comment by hugosolar** [comment]
"featured news" widget removed and date added to the entries list
![Screen Shot 2019-12-11 at 10 38 46 AM](https://user-images.githubusercontent.com/894708/70626100-8a0f6b00-1c02-11ea-9c91-b2c4bd7bc65b.png)

**Comment by kgodey** [comment]
I think it would be good to remove leading 0s from the date @hugosolar. It should just say "December 9, 2019".

**Comment by jennryn** [comment]
Hi all,

Not sure if anyone else is experiencing this, but I was looking at my blog
posts and realized not all are listed anymore. Here are two that do not
come up under my name:
https://creativecommons.org/2018/05/15/certificates-updates/
https://creativecommons.org/2018/04/14/announcing-open-registration-for-cc-certificates/

Maybe some have been lost in the shuffle for others too?

Best,
Jennryn
Jennryn Wetzler
Assistant Director of Open Education
Creative Commons <https://creativecommons.org/>

   - Learn: CC Certificate <https://certificates.creativecommons.org/>
   - Join: CC Open Education Platform
   <https://creativecommons.org/2017/09/05/invitation-join-cc-open-education-platform/>
   - Sign up: CC newsletter
   <https://creativecommons.org/about/contact/newsletter>
   - Read: Creative Commons for Educators and Librarians
   <https://www.alastore.ala.org/content/creative-commons-educators-and-librarians?_zs=pbaiW1&_zl=1XGC6>
   - Tw: @jennrynw
   - ICDE Ambassador for the global advocacy of OER

**Comment by kgodey** [comment]
Reopening issue so we can investigate @jennryn's issue.

**Comment by hugosolar** [comment]
Jennryn's issue isn't related to this
I create a new issue to fix that problem: #1054 
I'll keep this issue open until I fix the date format pointed by @kgodey
