### ISSUE TITLE
Remove "Articles by:" from Team/bio breadcrumbs

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#1035]
Sorry if "breadcrumbs" isn't the right word for this

It would be good to remove "Articles by:" from each person's bio page (for example, in: Creative Commons > About CC > Team > Articles by: Hugo Solar" (see image attached)

Most people don't write Articles for the site, and so this is confusing/misleading. And even for people who do write posts for the site, it would be better for these to be presented more strictly as bio pages, and not to frame the pages as being how to read what each person has written for the site

<img width="698" alt="Screen Shot 2019-10-08 at 7 25 50 AM" src="https://user-images.githubusercontent.com/8919762/66404220-e3f27b00-e99c-11e9-823b-06f7b0f4132c.png">

cc @victoriaheath so she is in the loop

**Comment by ericsteuer** [comment]
cc @victoriaheath

**Comment by hugosolar** [comment]
This is part of the settings of the `Breadcrumb NavXT Settings` in the miscellaneous tab. 
Now you can see only the name.

<img width="1255" alt="Screen Shot 2019-12-06 at 6 30 11 PM" src="https://user-images.githubusercontent.com/894708/70357794-87092900-1856-11ea-8d8a-40a868c72dc2.png">
