### ISSUE TITLE
Remove "Team" from cc.org profile pages of users who are not on staff, board, or advisory board

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#1040]
This may require a discussion outside of GitHub

But I noticed that anyone who has a user profile on cc.org also has a public facing profile page (e.g. https://creativecommons.org/author/alessandro/) with "Creative Commons > About CC > Team >" above their bio and photo (if they have one).

This is confusing, and my feeling is that only current CC staff, board, and advisory council profiles should have the "About CC > Team" categorization

This may actually be a conversation about separating out staff/board/advisory council bio pages from whatever function creates these pages for everyone who has an account, because I also don't see a reason for blog posts to show up under staff profiles at all

**Comment by claudioruiz** [comment]
Related with this, if you go visit [this URL](https://creativecommons.org/author/tvolcreativecommons-org/), there's nothing there showing that Tim is no longer part of the team. We should come out with a way to address that that is less confusing.

**Comment by hugosolar** [comment]
- I change the breadcrumb by making a relationship between the non-staff author and the blog
- Remove the extra information below the avatar when user is a guest

For instance: 
![Screen Shot 2020-01-03 at 12 13 26 PM](https://user-images.githubusercontent.com/894708/71731440-83e86500-2e23-11ea-8a50-1d273dc78c92.png)
