### ISSUE TITLE
Translation issue – Dutch translation

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#1049]
Hi,

I just noticed that the 4.0 translation, that I was responsible for, has a small error. 

In article 1(c) of the licenses we translate 'Effective Technological Measures'  as 'Doeltreffende Technische Maatregelen' which translates to "Effective Technical Measures"

In the relevant article 2(4-5) we used a correct translation "Doeltreffende Technologische Maatregelen".

```
1. Doeltreffende Technische Maatregelen
2. Doeltreffende Technologische Maatregelen
```

@peterspdx is it possible to change this?

**Comment by peterspdx** [comment]
We're evaluating a policy change that would allow us to change small errors in official translations of 4.0 (not the English, however) rather than noting on the errata page (https://wiki.creativecommons.org/wiki/Legalcode_errata). If you'd like it on the errata page right away, we can accommodate that. Otherwise, we should have a decision on the policy shortly. Let us know.

**Comment by mzeinstra** [comment]
Let's work it in into the errata. How about:

**Dutch translation - Effective Technological Measures**
In the Dutch translation of the 4.0 license suite 'Effective Technological Measures' has been translated in two different ways. 

Article 1(c) provides the definition of the term 'Effective Technological Measures'. This has been erroneously translated to 'Doeltreffende Technische Maatregelen' which translates to 'Effective Technical Measures'.

In the use of this defined term in article 2(4-5) the correct translation ' Doeltreffende Technologische Maatregelen' has been used.

The use of ' Doeltreffende Technologische Maatregelen'  in the 4.0 licenses is intended to refer to the definition provided in article 1(c).

**Comment by sarahpearson** [comment]
Done! [](https://wiki.creativecommons.org/wiki/Legalcode_errata#Dutch_official_translation)

**Comment by peterspdx** [comment]
Thanks @sarahpearson . Closing out the issue. @mzeinstra let us know if there's anything else for the time being.
