### ISSUE TITLE
French: "Cette page existe aussi dans les langues suivantes"

### ISSUE THREAD

**Issue by Chealer** [creativecommons/creativecommons.org#1051]
Pages such as [CC BY's](https://creativecommons.org/licenses/by/4.0/deed.fr) are offered in several languages. In French, the language chooser has the following label:

> Cette page existe aussi dans les langues suivantes

This label is followed by the option "français", which is in fact the default value. This looks strange (in English, this would read "This page is also available in the following languages").

The English version is:

> This page is available in the following languages

...which would translate to French as simply:
> Cette page existe dans les langues suivantes

**Comment by kgodey** [comment]
Our translations are crowdsourced via https://www.transifex.com/creativecommons/public/. I've updated this particular translation according to your suggestion (thank you!) and it should sync with the website in the next day automatically.

If you have the time, I'd encourage you to directly contribute to French translations via Transifex :)

**Comment by kgodey** [comment]
Looks like the translation has synced: https://github.com/creativecommons/cc.i18n/commit/5af479a2fb707e6bd017f228550379d9c0a2ce9d. Closing this issue.

**Comment by Chealer** [comment]
Thank you kgodey, that did fix the issue. However, a space should be kept before each colon in French.
