### ISSUE TITLE
What’s New in 4.0: "ready-to-use around the world, without porting" link anchor broken

### ISSUE THREAD

**Issue by Chealer** [creativecommons/creativecommons.org#1052]
Section "A more global license" of [the _What’s New in 4.0_ page](https://creativecommons.org/version4/) contains:

> The 4.0 licenses are ready-to-use around the world, without porting.

"ready-to-use around the world, without porting" is a link to https://wiki.creativecommons.org/Frequently_Asked_Questions#What_if_CC_licenses_have_not_been_ported_to_my_jurisdiction.3F

That URL works, but not its anchor. Yet the target section still exists: https://creativecommons.org/faq/#what-if-cc-licenses-have-not-been-ported-to-my-jurisdiction
It seems underscores were simply replaced with dashes.

**Comment by kgodey** [comment]
Thanks for reporting this. I've fixed it.

**Comment by Chealer** [comment]
> Thanks for reporting this. I've fixed it.

My pleasure. Thanks to you, that fixed it indeed.
