### ISSUE TITLE
No pagination in author post list

### ISSUE THREAD

**Issue by hugosolar** [creativecommons/creativecommons.org#1054]
## Describe the bug
Related to [Jennryn's comment](https://github.com/creativecommons/creativecommons.org/issues/1033#issuecomment-565033947)
The authors page doesn't have pagination and it seems to be hidden in favor of infinite scrolling set up which isn't working either.

## To Reproduce
1. Go to [Jennryn's profile](https://creativecommons.org/author/jennryncreativecommons-org/)
2. Go to the bottom of the post list
3. Go to [Jennryn's profile page 2](https://creativecommons.org/author/jennryncreativecommons-org/page/2/)
4. See pagination at the bottom

**Comment by mercyikpe** [comment]
Hello @hugosolar 
with this task cc.org/blog ordering of posts + displaying dates #1033 marked closed.
Does it mean this task 1054 is closed?
If not, I would like to work on it.

**Comment by hugosolar** [comment]
Hello @mercyikpe, It's not related to the closed issued you're refering, but also think this issue it's not that simple because it's a bug shich only happens in production and it's related with the infinite scroll provided by jetpack. Sorry but this issue it's not ready for contribution :(

**Comment by kgodey** [comment]
This is not relevant with the new design coming in the next couple of months.
