### ISSUE TITLE
Update 'Our Supporters' page 

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#106]
http://creativecommons.org/supporters 
-Remove right side bar with search, email signup, and recent blog
-Remove all supporters $999 and under
-Remove table of contents/categories
-Remove segmentation by type (foundation, corp, indiv)
-New categories: 1000-4999, 5000-9999, 10000-24999, 25000-49999, 50000-99999, 100000+
-Update Copy:
Thank you to our Supporters!
On behalf of the entire Creative Commons’ community -  Board, staff, affiliates, and contributors from all over the world - thank you for your meaningful contribution to CC’s mission and programs. We gratefully acknowledge our donor community.

**Comment by mattl** [comment]
You're already on this, but have a ticket about it anyway.

**Comment by robmyers** [comment]
Done!

**Comment by rebeccalendl** [comment]
I love it, thanks!!!

Rebecca Lendl
Director of Development
Creative Commons
rebecca@creativecommons.org
