### ISSUE TITLE
text-shadow on nav items looks bad

### ISSUE THREAD

**Issue by tennysonholloway** [creativecommons/creativecommons.org#108]
Current:
<img width="202" alt="screen shot 2015-09-10 at 11 47 07 am" src="https://cloud.githubusercontent.com/assets/4596069/9793357/1939aa98-57b3-11e5-921c-e96d0ff36153.png">

With text shadow removed:
<img width="205" alt="screen shot 2015-09-10 at 11 47 13 am" src="https://cloud.githubusercontent.com/assets/4596069/9793365/211399c2-57b3-11e5-815d-42adc5115d42.png">

I can't find where this css is in this repo (maybe [here?](https://github.com/creativecommons/creativecommons.org/blob/5ee57defe84bff4c84752a0f82e710f565269317/docroot/wp-content/themes/cc-2014/css/style.css#L1266)), so it may have already been removed but not deployed. 
The offending rule is: `text-shadow: 0px -1px 0px rgba(0, 0, 0, 0.25);` under the selector `.navbar-default` in `style.css`.
Removing the rule resolves this issue.

**Comment by mattl** [comment]
This has been fixed and will be pushed up later today.
