### ISSUE TITLE
Review CC Wiki's Privacy policy

### ISSUE THREAD

**Issue by fakoor** [creativecommons/creativecommons.org#1082]
The Privacy policy page is by default referenced from all MediaWiki pages. In CC wiki It  was missing, Hence I created an initial version and referenced the relevant terms such as terms of use and master privacy policy. 
 
I wanted to request a peer review to be performed on it and possibly increase its protection level in order to prevent unwanted changes if desired.

The page to review is located at:

-   [Privacy policy](https://wiki.creativecommons.org/wiki/CCWiki:Privacy_policy)  in CC Wiki.

**Comment by sarahpearson** [comment]
Thank you for flagging this! I've reviewed and made a couple of changes.
