### ISSUE TITLE
More options in license

### ISSUE THREAD

**Issue by musicpanda** [creativecommons/creativecommons.org#1088]
As maintainer of the index of freely downloadable classical music (www.classiccat.net) I have a rather good overview of the lack of success of the CC license in that field. Occasionally sites arise that use such licenses. But they stay marginal and disappear again after some time.

Recently I noticed that some photo sharing sites such as Unsplash and Pexels have a model that seems to work. I specially like the requirement in the Pexels license that you are free to redistribute and use for commercial purposes but that you are only allowed to sell when the photo has been modified in a way that added value. This applies to the picture itself but also to products that carry it like wallpapers and t-shirts.

I would like to see a similar option in the CC license. In my opinion this requirement better covers what many people who distribute want than credits and non-commercial clauses.

**Comment by Aspie96** [comment]
A license like that does exist but has been revoked.
The problem is that this kind of license ultimately is more restrictive than it looks. It is "almost" free but very much not free.

**Comment by sarahpearson** [comment]
Thanks for the suggestion. We will keep your ideas in mind going forward. CC has no immediate plans for new versions of the license along those lines, but we have seen people use the CC's NonCommercial licenses and then grant permissions to use for commercial purposes under particular circumstances (such as the circumstances you describe above).

**Comment by musicpanda** [comment]
The main use I see for music is in video's, on radio and as samples. In neither case the CC licenses work. 

Many video's on Youtube are short and don't have a credits section. If there is any text it is meant to engage the visitor, not to be some attribution legalese that doesn't interest him. In radio too attribution is a problem. Can you imagine the presenter saying "you heard ... by ... that was released under the Creative Commons license no.4 share alike"?

Share alike isn't attractive neither in video nor in sampling. Many sharers would be perfectly happy with that as value is added in both cases.

So in my opinion the ideal license should look something like:
 - no attribution needed
 - if you mention the artist name(s) there should be some indication that the work is shared. My idea at the moment is to use in writing some abbreviation like "(sul)" - what would abbreviate "shared-under-license" after the name of the artist. On radio that would instead become "shared by" before his name. That will leave the exact nature of the sharing unknown but I don't don't think that is a problem. There is a slight complication that the artist is not always the sharer - for example with digitized recordings from the 1920s - but I don't have a solution for that at the moment.
 - everyone is free to distribute the work for free. But you are only allowed to sell it when you have added some value to it. This could be restricted to "artistic value" - what would exclude digital processing to remove background noise and coughs. 

My goal is to have performances of all classical works that are at least a century old available for free on the internet and having people feeling free to use them for whatever they want and make their own additions. I am sure there are enough people willing to share their performances. It is the absence of a suitable license that is the main obstacle.
