### ISSUE TITLE
Issue campaign email to full list - Tuesday 9/15

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#109]
Advocacy action #1 - Open Textbooks

@tvol to draft content, review/finalize with Trilogy
@tvol to think on potential partners to help with list building
@mattl to draft landing pages, review/finalize with Trilogy
@mattl to setup in civi, send to full list

Possible second email to follow a few days after if good response rate

**Comment by tvol** [comment]
@rebeccalendl Here is a first draft. Adding @cablegreen for ideas and to review tone. 
https://docs.google.com/document/d/1Bt8r400Vkqrg2TPIVqslKQEqbSSOulk-k3K39ri9HSc/edit#

**Comment by cablegreen** [comment]
I edited - thanks for the opportunity to do so.

**Comment by tvol** [comment]
@cablegreen thanks

**Comment by rebeccalendl** [comment]
looks great to me. tvol I'm out today for the jewish holiday. are you ok
working with trilogy and matt directly on this to review and send?

Rebecca Lendl
Director of Development
Creative Commons
rebecca@creativecommons.org

**Comment by tvol** [comment]
hi @rebeccalendl I will send the draft to Trilogy today to get their feedback. There is a big OER announcement today at the Department of Education, so we should wait until later this week to send this out. Let's coordinate with @cablegreen to figure out the best timing, and potentially include a reference to the announcements from today. cc @mattl

**Comment by cablegreen** [comment]
agree - please hold until tomorrow or later.  The Duncan post will be the headline today. Thanks!

**Comment by rebeccalendl** [comment]
@tvol copy looks great to me. thoughts on partners for list building?
@mattl how is the landing page coming along?

**Comment by mattl** [comment]
I've not been working on the landing page yet. Been trying to take care of
other things.

**Comment by rebeccalendl** [comment]
@mattl can you give us ETA so we can plan around it?

**Comment by mattl** [comment]
I don't have any details on it. @tvol -- isn't this something we could use https://action.creativecommons.org/ for?

**Comment by tvol** [comment]
@rebeccalendl i updated the draft. regarding partners, do you mean organizations that we'd want to share this issue campaign in order to get more people looking at it and sign up?

**Comment by rebeccalendl** [comment]
@tvol yep. I'm also happy to jump on a call to resolve the landing page issue. From my call with Matt last week sounded like an easy one, but if it's not we can troubleshoot. Really eager to ship something asap.

**Comment by tvol** [comment]
@mattl yes the action center would potentially work. i've put the text in there but there are some irregularities. 1) the text does not fit within the page (perhaps this is a forcing technique for it to not be too long?) 2) i am not able to upload any images.

**Comment by tvol** [comment]
@rebeccalendl @mattl do you need any more input from me on the copy for the open textbooks page?

**Comment by mattl** [comment]
All the links need to be moved to the bottom, so the main copy is link-free.

**Comment by tvol** [comment]
@mattl ok i'll do it.

**Comment by mattl** [comment]
Great. Also, we need body copy for an email, or maybe we can just use the same text? A subject line and a one line intro also needed.

**Comment by tvol** [comment]
@mattl done with footnotes. and yes can we simply use the same text for the email? https://docs.google.com/document/d/1Bt8r400Vkqrg2TPIVqslKQEqbSSOulk-k3K39ri9HSc/edit

**Comment by cablegreen** [comment]
added a comment to the gdoc

**Comment by rebeccalendl** [comment]
@cablegreen and @tvol do you have suggestions for partners who would be willing to share out message? we could reframe copy so we are sharing out both orgs success in the open textbook movement (so as to avoid any big asks/favors, more a mutual shout out to our lists)?

**Comment by tvol** [comment]
@rebeccalendl @cablegreen 
student pirgs
ethan senack
sparc
lumen 
boundless
open textbook summit participants
dave ernst
r2rc
hewlett
ck-12

**Comment by rebeccalendl** [comment]
Thanks! I added draft outreach copy to doc (also pasted here). This sound like the right messaging to you?:

I wanted to reach out to see if X would be interested in partnering with Creative Commons on some back to school outreach around the Open Textbook movement. We’ve drafted a letter to share on e-newsletters and social media to help raise awareness and rally support. If you’re interested in joining us, please let me know and I’ll send along a dedicated link with copy for you to share on social media and other channels as works for you (draft messaging pasted below for your reference). We’d track source and share back all email signups with you.

**Comment by mattl** [comment]
Assigning this back to you until this is figured out.

**Comment by tvol** [comment]
@rebeccalendl your copy looks fine to me. ask @cablegreen
