### ISSUE TITLE
main page serving mixed http/https content

### ISSUE THREAD

**Issue by tennysonholloway** [creativecommons/creativecommons.org#110]
```
23:50:50.908 Blocked loading mixed active content "http://s0.wp.com/wp-content/js/devicepx-jetpack.js?ver=201538"[Learn More] creativecommons.org
23:50:50.909 Blocked loading mixed active content "http://s.gravatar.com/js/gprofiles.js?ver=2015Sepaa"[Learn More] creativecommons.org
23:50:50.911 Blocked loading mixed active content "http://stats.wp.com/e-201538.js"[Learn More] creativecommons.org
```
It's giving (some) users a scary unlocked sign in the address bar! 

All these URLs have working https counterparts, just a matter of finding the offending wp-plugin and messing with the settings. Looks like the first one is in Jetpack, second one is Gravatars (are gravatars even used? could just disable), third one I'm not sure.

**Comment by mattl** [comment]
This has been resolved now.
