### ISSUE TITLE
extend allowable size for body text on https://action.creativecommons.org

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#112]
In test, text is cut off on the bottom.

**Comment by mattl** [comment]
It would be good to know the state of action too.

**Comment by robmyers** [comment]
Still "ready for testing".

**Comment by mattl** [comment]
Okay, and the image stuff works now? If so, make a ticket for the people to test it.

**Comment by robmyers** [comment]
The image stuff is where we left it, with S3 not playing nicely. There is nothing in Rails' or Apache's logs that indicates an error, and we can uplaod files from the command line and via the web.

If you give me access to the account I can poke it, the CORS stuff that we need to tweak may be the problem.

**Comment by mattl** [comment]
Okay, let's take some time to look at it next Tuesday.

**Comment by robmyers** [comment]
Thanks, that's great.
