### ISSUE TITLE
Integrate Web Monetization on Select Pages

### ISSUE THREAD

**Issue by annatuma** [creativecommons/creativecommons.org#1124]
We're going to start the first phase of experimenting with Web Monetization.

The tag needs to be put in the `<head>` of the website, and is
`<meta name="monetization" content="$ilp.uphold.com/edR8erBDbRyq">`

For CC.org, we'll do these three pages initially:
https://creativecommons.org/about/program-areas/arts-culture/arts-culture-resources/legalmusicforvideos/
https://creativecommons.org/share-your-work/
https://creativecommons.org/use-remix/

**Comment by annatuma** [comment]
@hugosolar Coil does have a WordPress plugin for this:
https://wordpress.org/plugins/coil-web-monetization/

I don't know if it's preferred to use the plugin, or code this directly into the `<head>`. Also, if this is something that I can do (e.g. by installing the plugin and making settings) I am happy to help with this, but I defer to you.

**Comment by kgodey** [comment]
We probably do not want to use the plugin; integrating web monetization directly will allow us to support all web monetization providers, not just Coil.

**Comment by hugosolar** [comment]
Yes! I agree with @kgodey, I added a PR with a short function that should do the trick
