### ISSUE TITLE
make the following additions/changes to the language list at the bottom of the license deeds

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#113]
(1) Czech (česky) should be changed to čeština
(2) Farsi (پارسی) should be changed to  فارسی
(3) Indonesia should be changed to Bahasa Indonesia
(4) Melayu should be changed to Bahasa Malaysia
(5) Norsk should be changed to norsk
(6) Suomeksi should be changed to suomeksi
(7) te reo Māori should be added to the list with a link to the translation

Thank you!

**Comment by sarahpearson** [comment]
Just rediscovered this open issue when going through Github. @georgehari Is this something you can change in Transifex? If not, we can reassign to Rob.

**Comment by georgehari** [comment]
What Web page and/or translation does this refer to?

**Comment by georgehari** [comment]
I made all changes on Transifex.com. For those with the status CHANGED, they shoould go live on the website next Monday, when the automatic script is scheduled to run.

(1) Czech (česky) should be changed to čeština - CHANGED
(2) Farsi (پارسی) should be changed to فارسی - ALREADY CHANGED
(3) Indonesia should be changed to Bahasa Indonesia - CHANGED
(4) Melayu should be changed to Bahasa Malaysia - CHANGED
(5) Norsk should be changed to norsk - CHANGED
(6) Suomeksi should be changed to suomeksi - CHANGED
(7) te reo Māori should be added to the list with a link to the translation - IT WILL BE ADDED AUTOMATICALLY WHEN THE TRANSLATION HITS AT LEAST 85%; IT’S AT 35% NOW

**Comment by robmyers** [comment]
Thank you that's awesome!
