### ISSUE TITLE
Invalid reCAPTCHA response when trying to subscribe to CC newsletter

### ISSUE THREAD

**Issue by pemo11** [creativecommons/creativecommons.org#1141]
I am not able to subscribe to the CC newsletter:

1. Subscribe to CC newsletter
2. Type in e mail address
3. Select options
4. Select I am not a robot
5. Select Submit

Result is always Invalid reCAPTCHA response.

When using IE I was presented the usual picture box but same result.

Peter

**Comment by hugosolar** [comment]
This was already notified here: creativecommons/tech-support#635 (private repo)
the problem seems to be the url on the website, the correct URL should be this one 

https://us.e-activist.com/page/6747/subscribe/1

this was already updated on the website
thank you for flagging this!
