### ISSUE TITLE
decide where translations of the considerations page will live

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#115]
Here is the relevant page in English: https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees 

Right now, it's on the wiki, but it seems like it makes more sense to have it on the main site.

**Comment by mattl** [comment]
This page will be translated?

**Comment by peterspdx** [comment]
Yes. Ideally. We have asked teams that have completed translations of the licenses to also please consider translating this page. It is linked to from every translation of every 4.0 license. In the future, possibly linked to from 3.0 and prior versions and ports.

**Comment by sarahpearson** [comment]
The Italian team has a translation of it ready to publish when they publish their 4.0 official translation soon. @mattl you assigned this to me. What should I do? I think it should be a new page on the main site.

**Comment by mattl** [comment]
I assign to you when I need you to do something :) Now I have a sense of this, I'll take it back.

**Comment by sarahpearson** [comment]
gotcha, sounds good.

**Comment by peterspdx** [comment]
mattl: we have an opportunity for funding for a French version of this same page, plus these additional pages:

(1) FAQs
(2) What's new in 4.0
(3) Public domain tool main page
(4) CC0 FAQ
(5) PDM FAQ

This same issue applies to all of these pages as well. I would expect the French translations to be done before the end of the year. The Italian "considerations" page will be the first; but we should have in place an established practice for all of these plus a decision on whether they belong on the wiki or main website. Thx.

**Comment by peterspdx** [comment]
Closing this until we develop a translation plan for pages that support the licenses.
