### ISSUE TITLE
'Apparel' misspelled on CC Store

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.org#1186]
## Description
The word 'apparel' is misspelled on the [CC Store](https://creativecommons.org/about/store/).

## Reproduction

1. Visit the CC Store.
2. See error.

## Expectation
The correct spelling 'apparel' should be used. It is actually used in the subsequent button.

## Screenshots

![Screenshot 2020-11-01 at 12 35 44 AM](https://user-images.githubusercontent.com/16580576/97787846-99145880-1bda-11eb-97db-1e8f146efc6f.png)

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by pranavvp10** [comment]
Hi @dhruvkb  can I work on this?

**Comment by dhruvkb** [comment]
Sure @pranavvp10, please do

**Comment by pranavvp10** [comment]
Hi @dhruvkb  actually I'm a starter to open source. I couldn't find the html file (../about/store)

**Comment by dhruvkb** [comment]
@pranavvp10 I don't know how the site is put together either. Maybe @TimidRobot knows and can help you out.

**Comment by ericsteuer** [comment]
Thanks - done!
