### ISSUE TITLE
update fundraising notifications

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#119]
@mattl please update all fundraising notifications to include me, working with Scott S if needed
Paypal, 
Stripe, 
Shopify, 
Email group donor@creativecommons.org (which should be renamed development@creativecommons.org)

**Comment by rebeccalendl** [comment]
Don't think I've been added yet to paypal or shopify. I can see Stripe now in Freshdesk.

**Comment by mattl** [comment]
Closing this. Going to make tickets in Freshdesk. @rebeccalendl let's keep financial stuff there, where we can loop Scott in.

**Comment by mattl** [comment]
I think you're getting all the stuff now
