### ISSUE TITLE
License deed pages have malformed comment appearing above header

### ISSUE THREAD

**Issue by Ythan** [creativecommons/creativecommons.org#1190]
All of the license deed pages have a malformed comment which is appearing above the header:

`!-- Google Tag Optimize --> `

Example URLs:
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by-sa/4.0/
https://creativecommons.org/licenses/by-nd/4.0/
https://creativecommons.org/licenses/by-nc/4.0/
https://creativecommons.org/licenses/by-nc-sa/4.0/
https://creativecommons.org/licenses/by-nc-nd/4.0/

The legal code pages for the licenses are not affected.

According to web.archive.org it looks like this error was just introduced today (December 1).

![Screenshot_2020-12-01 Creative Commons — Attribution 4 0 International — CC BY 4 0](https://user-images.githubusercontent.com/593361/100792600-de4dc500-33e8-11eb-86c1-c6cda5d835a9.png)

**Comment by kgodey** [comment]
thanks for reporting this, @Ythan, we're on it.
