### ISSUE TITLE
Pagination icons broken in the blog

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/creativecommons.org#1193]
## Description
The 'previous page' and 'next page' icons are broken in the blog section of the website.

## Reproduction

1. Visit the [blog](https://creativecommons.org/blog/).
2. Scroll to bottom.
4. See boxes in place of icons.

## Expectation
The 'previous page' (&larr;) and 'next page' (&rarr;) icons should be there.

## Screenshots
<img width="823" alt="Screenshot 2020-12-16 at 9 56 58 PM" src="https://user-images.githubusercontent.com/16580576/102376570-c762c180-3fe9-11eb-8ae2-3580002b2925.png">

## Environment

 - MacBook Pro
 - macOS 11 Big Sur
 - Vivaldi (built on Chromium)
 - v3.5.2115.81

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by frappelatte28** [comment]
Hey! Can I start working on this issue?

**Comment by dhruvkb** [comment]
Sure @frappelatte28. Please do.

**Comment by frappelatte28** [comment]
@dhruvkb I have just started here. It would be helpful if I could get an installation guide for this repo.

**Comment by dhruvkb** [comment]
I'm not well aware of how this project works myself, so I'll just tag in @TimidRobot who might be able to help with that.

**Comment by HarshitMeda** [comment]
@dhruvkb can I work on this bug? it looks like an easy fix, will be great as a first issue for me.

**Comment by HarshitMeda** [comment]
For some reason I am unable to find the html file which has rendered this blog page. Any idea where is it?

**Comment by dhruvkb** [comment]
@HarshitMeda I don't have knowledge of how this site is built, so unfortunately I cannot provide any help. You might consider picking a different issue from our [Issue Finder](https://opensource.creativecommons.org/contributing-code/issue-finder/).

**Comment by hugosolar** [comment]
So sorry for that but this repo/website isn't open source friendly. this is a WordPress install but the current theme lives in another repo and it's kind of confusing. I hope in the future could have proper documentation so people can contribute without blockers. For now, I'll take this issue. Thanks to everyone for your interest in solving the problem 😄
