### ISSUE TITLE
Cloudflare CDN issue in China: Assets from mirrors.creativecommons.org can not be loaded

### ISSUE THREAD

**Issue by Phuker** [creativecommons/creativecommons.org#1197]
## Description

Button & icon images in mirrors.creativecommons.org can not be loaded, blocked by Cloudflare captcha. The settings in Cloudflare CDN might be inappropriate.

*I'm not sure whether here is the right place to report this problem, if it's not then I'm sorry.*

## Reproduction

1. Create a simple HTML file with these contents:

```html
<img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" />
<img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nc-nd.svg" />
```
2. Open a incognito private window in your browser to simulate a new visitor, and open this file.
3. Boom, images can not be loaded. If a new visitor has not solved a captcha, the images can not be loaded.

## Expectation

Images be loaded

## Screenshots

![error](https://user-images.githubusercontent.com/11596611/98036121-742b1a00-1e54-11eb-8026-8ef8dc6a15d3.png)

## Environment

 - Device: Laptop
 - OS: Windows & macOS
 - Browser: Chrome, Firefox, Safari
 - Version: all latest

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by stevenjoezhang** [comment]
Is it possible to publish an official package containing cc button & icon images to npm? In this way, users will be able to load images through CDN providers such as jsdelivr or unpkg

**Comment by obulat** [comment]
The assets are part of the Vocabulary package, and you can actually use them through jsdelivr /unpkg. Here you can find some more information: https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-usage--page

**Comment by stevenjoezhang** [comment]
Thanks very much! I have confirmed that the badge can be loaded like this
```html
<img src="https://cdn.jsdelivr.net/npm/@creativecommons/vocabulary@2020.11.3/assets/license_badges/big/by.svg">
```
