### ISSUE TITLE
finalize KS data import

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#120]
@mattl ensure all KS data made it into civi successfully, ensure source is noted as KS, ensure they are added to general email list, ensure wherever possible that they are matched with their existing record

**Comment by mattl** [comment]
@sarahpearson Do we want to write a note to people, welcoming them to our newsletter list? I have most of this done, but not their donation amount imported.

**Comment by sarahpearson** [comment]
yes, good idea. I'll do this. I'm going to talk to Rebecca later this afternoon first.

**Comment by rebeccalendl** [comment]
pretty sure the welcome note went out; it was scheduled to send in advance of the global summit program announcement. I think just the donation data is outstanding. Please confirm

**Comment by mattl** [comment]
Yeah, this was the email that went: https://donate.creativecommons.org/civicrm/mailing/report?mid=492&reset=1

**Comment by rebeccalendl** [comment]
@mattl I'm finding some KS donors whose contribution is not attached to their record despite their contribution email address matching their civi email address. can you look into this?

**Comment by rebeccalendl** [comment]
any update here?

**Comment by mattl** [comment]
No update. This might be a good use for a profile

**Comment by rebeccalendl** [comment]
Possible to close this out this week latest? See first post on this issue: ensure all KS data made it into civi successfully, ensure source is noted as KS, ensure they are added to general email list, ensure wherever possible that they are matched with their existing record. Let me know what you need to make this happen.

**Comment by mattl** [comment]
I'll probably be spending almost all of this week on SOTC.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccalendl** [comment]
Do you want to set a reasonable deadline and let me know?

**Comment by mattl** [comment]
Let's see how long all the other stuff takes first. I don't want to commit
to a deadline if I'm stuck doing other stuff.

Alternate idea would be to ask Scott to import them.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccalendl** [comment]
-"Kickstarter" attached to individual donation itself under "Source" (not the overall donor record)
-Consolidate all KS-related groups and tags into one 
-Correct synch with existing contact records where there's an email address match
-Confirm KS-sourced donors added to mailing list 

Let me know if/when I can help with manual data entry, cleaning, etc, happy to help!

**Comment by rebeccalendl** [comment]
per discussion, aiming for Friday 2/3 deadline

**Comment by rebeccalendl** [comment]
@mattl can you provide an update please?

**Comment by mattl** [comment]
I have a log in that works for this. Now constructing a CSV file which will
DTRT.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC
