### ISSUE TITLE
[BUG] Image not fit properly in the article's panel

### ISSUE THREAD

**Issue by RiyaJ2311** [creativecommons/creativecommons.org#1201]
**What is the growth opportunity you want to see solved?**
 [The organization](https://creativecommons.org/) is the most easily accessible and is considered as the most reliable [source](https://www.smartinsights.com/user-experience/website-design/what-is-the-importance-of-web-design-for-your-audience/#:~:text=A%20well%2Ddesigned%20website%20can,navigate%20your%20website%20with%20ease.).
![image](https://user-images.githubusercontent.com/48223671/108588159-bc2b6980-737d-11eb-8fc2-b378ff16e195.png)
The red marked square shows the bug, I am talking about. 
The complete logo is not visible, the upper and bottom corners are cropped in the image

**How do you know that this problem exists today? Why is this important?**
After visiting [Creative Commons](https://creativecommons.org/), I realized that one bug caught my attention more than the complete website and then carried out having a [Questionnaire testing](https://www.pewresearch.org/methods/u-s-survey-research/questionnaire-design/) on the same to classmates.

**How to measure design's effectiveness?**
[A/B testing](https://www.optimizely.com/optimization-glossary/ab-testing/) - A quick A/B with my acquaintances (who cover major sections of people using the internet) with a high-fidelity version.

**Comment by Saikat-Mandal** [comment]
hey @RiyaJ2311 is this issue fixed ?

**Comment by possumbilities** [comment]
Closing this, as it's not going to be fixed as it will be irrelevant with the new site that's launching.
