### ISSUE TITLE
[Bug] The Trademark Policy is gendered

### ISSUE THREAD

**Issue by Jayman2000** [creativecommons/creativecommons.org#1216]
## Description

[The Creative Commons Trademark Policy](https://creativecommons.org/policies/#trademark) says “[…]the creator has applied a Creative Commons license to her work.” For consistency with #1143, the word “her” should be replaced with the word “their”.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by sarahpearson** [comment]
Corrected. Thank you!
