### ISSUE TITLE
Update automated copy for email sign up thank you and donation thank you

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#124]
Email sign up automatic reply + thanks page (note that link didn't stick when I pasted below but "Your donation at any level" should link to donate page):

Welcome to the CC community!

We are thrilled to have you join us on the road to realizing the full potential of the Internet—universal access to research, education, and full participation in culture. We can’t do this without you.

I hope you’ll help us build a bigger and more vibrant commons by supporting Creative Commons today. Your donation at any level will help us offer greater access to knowledge for everyone, everywhere. 

Thank you for investing in Creative Commons and a more open vibrant future.

Warmly,
Ryan Merkley
CEO, Creative Commons

Online contribution automatic reply (note that link didn't stick when I pasted below but "State of the Commons" should link to SOTC report page):

Thank you for your support of Creative Commons and for being a part of the CC donor community!

Your donation to CC is put to very good use on projects ranging from open education, to advocating for open policies, to building a more vibrant commons, and much more. Check out our State of the Commons report for just a snapshot of what we’re able to accomplish with the support of advocates like you. 

Thank you for investing in Creative Commons and for helping us provide greater access to knowledge for everyone, everywhere. We look forward to sharing all our big wins with you.

Warmly,
Ryan Merkley
CEO, Creative Commons

Creative Commons is a 501(c)(3) nonprofit organization. 
Your contribution is tax-deductible to the extent allowed by law.

**Comment by mattl** [comment]
Do we want to do this now the page is in Civi? Seems like we might direct people away to the State of the Commons report, which presumably we'd link to.

For links, you can paste the URL, or do this:

    [This text should be a link](https://www.google.com)

**Comment by rebeccalendl** [comment]
Not sure what you mean, can you share more?
