### ISSUE TITLE
by adding some padding at left its look more proper than its look now.

### ISSUE THREAD

**Issue by mohitparmar1** [creativecommons/creativecommons.org#1259]
[##](![item not aligned](https://user-images.githubusercontent.com/100152343/209759325-c09d367e-a3f5-4572-a0ed-a34ef37c5ad0.png)) Problem

 photos are not aligned at proper form.

## Description

so we can solve this issue by adding some padding on both side so it can look good.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by mohitparmar1** [comment]
if we add some padding both side its look more attractive

**Comment by mohitparmar1** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/100152343/209761737-90f9525f-3db5-4d16-a07f-9f9135e308d7.png)

**Comment by possumbilities** [comment]
@mohitparmar1 Thank you for pointing this out!  ❤️ 

You're right, and it's a good suggestion, but this design is in the process of being replaced so it's not something we'll be addressing directly.
