### ISSUE TITLE
Add two new donors to supporters page at 1K level

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#126]
Please confirm that 1K has been received from each of the below (I am not yet added to notifications). If confirmed, please update Supporters page with these two new donors at 1K:

[redacted]

(moving forward I will set up a monthly update report for you so that all updates get bundled into a single monthly update)

Thanks!

**Comment by Scott-CC** [comment]
Rebbecca,

I cannot confirm either donation as of yet.  Yesterday we received 1,000
from www.Jobcase.com which I informed Rob to add, today we received 1,000
from Lauren McNeil of lauren@exclusivelegalmarketing.com.  I had not
informed Rob of this yet.  I am not seeing the other two yet.

Scott

**Comment by mmoreshead** [comment]
One of Lauren's donations came through last week, we've just been slow getting it up on the page (much confusion about some silly things).

**Comment by mattl** [comment]
I don't think a monthly bundle is very useful. If someone donates on October 1st and has to wait a month to get a link, that doesn't seem very good. It's easy to add a link to the website. Anyone can do it.

**Comment by rebeccalendl** [comment]
I'm working on a few new processes to help streamline our donor
communications internally (finance to civi to devo) and externally (devo to
donors to website); feels like there are a few needs there. I'll figure out
where/how this piece works best. I've seen as common practice a yearly
funder update that synchs with an annual report, also seen none at all, so
monthly doesn't feel like a crazy long time to wait. Goal is to create as
easy/automated as possible, will share back more after calls with Scott and
Matt this week.

**Comment by mmoreshead** [comment]
I'm also not sure if here (github) is the best place for these requests.  Maybe freshdesk is better since we can assign the ticket based on the successful donation instead of asking Scott to confirm the donation.  We actually had one donor ask us to remove the github issue (because it was showing up in his search results and we'd had some confusion about his display name) a while back.

**Comment by mattl** [comment]
We have people right now emailing us after a few days asking why weren't not linking to them.

@mmoreshead -- agreed. Once I get my new card in the mail, I'll add Rebecca to Freshdesk.

**Comment by rebeccalendl** [comment]
Thanks, Freshdesk suggestion is helpful. I'll work on getting a process doc
together as soon as I gather the info I need, and will send it your way for
edits and suggestions. Goal is for each piece of the donor stewardship
process to work well for our workflow needs, keep donors happy, and fit
into an overall devo strategy.

Until we get any new processes agreed upon and in place, it would be great
if you can continue as is and update links as often as works for you. Going
forward, I'm happy to (and should be) receiving all donor communications,
so feel free to send those requests my way.

**Comment by robmyers** [comment]
I've added both, with their names as well as their descriptions.
