### ISSUE TITLE
Add sentence to text version of license to be consistent with html version

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#128]
Via info@, we got word that the following sentence from the bottom disclaimer was not included in the text version of the 4.0 licenses: 

The text of the Creative Commons public licenses is dedicated to the public domain under the CC0 Public Domain Dedication. 

@peterspdx There is no reason why this would intentionally be different, is there?

**Comment by peterspdx** [comment]
No.

**Comment by mattl** [comment]
https://github.com/creativecommons/creativecommons.org/pull/132/files

**Comment by mattl** [comment]
@sarahpearson Take a look at my pull request when you get a chance.

**Comment by sarahpearson** [comment]
@mattl it looks good except that I'm not sure why the line about prior written consent is grayed out. Does that just mean it was in both versions? In any case, assuming that line is in the new version, looks good. Thanks!
