### ISSUE TITLE
Create alias(es) so that all fundraising related communications to go to rebecca@creativecommons.org

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#129]
@mattl @robmyers @mmoreshead 

Please redirect all inquiries to donate@creativecommons.org, donor@creativecommons.org, development@creativecommons.org, and any other similar addresses or devo-related correspondence that I may not be aware of to my own email address rebecca@creativecommons.org. Please have these addresses bypass the Freshdesk system entirely. Reasoning is that I'd like to keep all my donor communications close and personal, easier for my workflow, and also trackable alongside my other donor communications. And I'll be on point for all supporters page inquiries and updates.

**Comment by robmyers** [comment]
Assigned to Matt, who controls the email system.

**Comment by mattl** [comment]
These things already come into Freshdesk as emails from our payment
providers, and we don't want to put requests for donation related items
onto GitHub, so we should be assigning them in Freshdesk.

**Comment by rebeccalendl** [comment]
From a fundraising strategy standpoint, I'd prefer they don't go through Freshdesk so sounds like it's worth a discussion. I'll add to our next weekly.

**Comment by mattl** [comment]
I'm sorry, it would require changing far too much of the way our current email set up is configured, and negates the way other people are working with requests.

**Comment by rebeccalendl** [comment]
That may very well be. I'd like an opportunity to learn more, share my process and goals, and make a collaborative decision.

**Comment by mattl** [comment]
Sorry, but we're not going to reconfigure our email system any time soon.

**Comment by rebeccalendl** [comment]
Sounds good. Looking forward to being convinced when we connect next week :)
