### ISSUE TITLE
Fix RTL (Arabic) CSS in deeds page.

### ISSUE THREAD

**Issue by AAbouZaid** [creativecommons/creativecommons.org#13]
![fix rtl arabic css in deeds page](https://f.cloud.github.com/assets/6760103/2239360/d5ba66ca-9c2b-11e3-9212-7489e9f90af0.png)
Hello,

The CSS in deeds page not prepared well to suit RTL languages like Arabic, specially the margins, and "Free Cultural seal" (should be in same deeds languages too) Attached image spot some flaws.

And there is a possibility to change font? it's not that good.

Thank you very much.

**Comment by robmyers** [comment]
The new template fixes this.
