### ISSUE TITLE
develop nov issue campaign text (open policy)

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#133]
share with @cablegreen and @rebeccalendl; preview messaging with OERUSA list first

**Comment by tvol** [comment]
cleaning up the draft here: https://docs.google.com/document/d/1imXZ-USyWo0KjKBRWyENl9CTmOjA4zw7_jLrEXFPzT0/edit

**Comment by tvol** [comment]
@cablegreen can you review again please https://docs.google.com/document/d/1imXZ-USyWo0KjKBRWyENl9CTmOjA4zw7_jLrEXFPzT0/edit#

**Comment by cablegreen** [comment]
Done. Looks great!

Cable

**Comment by tvol** [comment]
@mattl does this have everything you need for the webpage and form? https://docs.google.com/document/d/1imXZ-USyWo0KjKBRWyENl9CTmOjA4zw7_jLrEXFPzT0/edit#

**Comment by tvol** [comment]
@mattl @rebeccalendl I drafted the campaign page https://creativecommons.org/campaigns/open-licensing-policy-at-department-of-education, but it needs the form signup with the fields listed on https://docs.google.com/document/d/1imXZ-USyWo0KjKBRWyENl9CTmOjA4zw7_jLrEXFPzT0/edit
