### ISSUE TITLE
Email to full list on Tuesday 10/13 to kick off Global Summit

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#134]
Please prep test email in civi by next Friday AM for review on Trilogy call. Review specs below to make sure all looks feasible from tech perspective. I'll be on point for copy.

Flag the start of the summit and offer ways to follow along online
Share are our 5 big themes
“We want to hear from you. What do you think is the most important theme we’ll be addressing? Click here to share thoughts” 
5 radio buttons with name/email/submit
Register to follow along on live stream (that would help us tackle other github issue around live streaming)?
Follow up for survey responders: send to a fundraising upsell page

**Comment by robmyers** [comment]
Heya @rebeccalendl I'll have to do this.

Please can you provide me with a for the live streaming issues, I'm failing at the internet trying to find that. Thanks.
