### ISSUE TITLE
Action Default Email

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#136]
As per here: https://github.com/robmyers/action-center-platform/issues/4

We need to change the default email to something from CC rather than the EFF:

https://raw.githubusercontent.com/robmyers/action-center-platform/master/config/action_email.md

Is that something you can/would like to do? If not please assign it back to me and I can mash-up something from the about page. :-)

**Comment by rebeccalendl** [comment]
I think building a campaign landing page template is on Tim's list?
