### ISSUE TITLE
can you make me an editor of the FAQ please? 

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#138]
I need to make changes to reflect the GPL compatibility determination, but I see that I no longer have editing access for this page: https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions

Thanks!

**Comment by robmyers** [comment]
That's weird you should have edit access as a member of the staff group.

Can you please try to create a random page (search for "Random Test" and see if you get a link on the results page that allows you to create it) and let me know if it lets you.

**Comment by sarahpearson** [comment]
Very strange! I used to be able to edit them. 

The wiki will let me create/edit this page: https://wiki.creativecommons.org/wiki/Randomtest

**Comment by robmyers** [comment]
OK that's really weird. Investigating...

**Comment by robmyers** [comment]
Ah the FAQ is protected so only administrators can edit it. I've added you to that group.
