### ISSUE TITLE
Lossless image compression

### ISSUE THREAD

**Issue by fasouto** [creativecommons/creativecommons.org#139]
While I was compressing some images for a website I discover that this button http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc.eu.png can be reduced more than a 50% with lossless compression. I tested with some images from [this page](https://creativecommons.org/about/downloads) and most of them could be reduced.

It's not a huge change :) but it's easy to do and it can save some bandwidth.

Here's the original (9 KB):
![by-nc eu](https://cloud.githubusercontent.com/assets/194200/10431455/729845f2-7105-11e5-9eac-18cc8ea80a2a.png)

And the compressed one (4 KB):
![by-nc eu_compressed](https://cloud.githubusercontent.com/assets/194200/10431465/7ebf3cfa-7105-11e5-9562-2e74f34b122b.png)

I used [ImageOptim](https://github.com/pornel/ImageOptim) let me know if you want me to create a PR with the compressed images.

**Comment by mattl** [comment]
I don't really worry about the bandwidth of those images, but hopefully our licensebuttons from licensebuttons.net are optimized well.

**Comment by fasouto** [comment]
Well, I tried to compress some of the images from licensebuttons and they could be compressed a bit (around ~8%) without losing quality. Not a big deal anyway because they are fairly small, so feel free to close this.

**Comment by mattl** [comment]
One thing you may be interested in: we're looking at providing the various license icons in a variety of sizes and colors. 

You'll see a set we have here: https://licensebuttons.net/i/cc-gift-guide/

We made this crude tool for generating them: https://github.com/creativecommons/mp/tree/master/src/genimg

One PR I'd love to to see would be the various icons bundled into their respective license bundles (we want to serve a single image for each license, not 2-3) in a variety of sizes from something useful in a print publication, much like the images previously seen in this issue, right down to very small icons for a mobile app or similar. And of course, in a variety of foreground and background colors.

**Comment by fasouto** [comment]
It's doable and interesting, will take a look after christmas.

**Comment by mattl** [comment]
That sounds great.
