### ISSUE TITLE
Email to all non-newsletter non-opted out contacts

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#142]
@rebeccalendl Are we planning to add them to the newsletter directly?

**Comment by rebeccalendl** [comment]
Yes, the same 'invite to opt out' email is going to be sent to:

1) Contacts in civi who are not already on email list, but have not actively opted out
2) CC staff contacts who are not already on the mailing list

I feel like we've discussed this so very many times, so want to make sure I'm not misunderstanding your question. Can you confirm?

**Comment by mattl** [comment]
Okay. I just want to make sure we get this right because undoing it will be a lot of work :)

Some staff contacts are explicitly not for the newsletter. How do we want to handle those? Just mark them as Do not email?

**Comment by rebeccalendl** [comment]
Anyone who has opted out should be marked as such, yes.

I agree we want to get this right and that it's a big project. I'd be happy to have a call tomorrow to run through any details.
