### ISSUE TITLE
Radio buttons on chooser don't work

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#143]
There's a missing JS function, chooselicense.

For example: https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;vers... 

there are radio buttons to let me select which style I want to put on 
my website. Unfortunately, when I click the button to select the 
smaller style it does nothing. It should change the style in 
the preview box and in the website code.

**Comment by brodybits** [comment]
+1 thanks!

**Comment by mattl** [comment]
Rob, can you take a look at this one today?

**Comment by robmyers** [comment]
license-results.js had been missing since before our time. I've re-added it:

https://github.com/creativecommons/creativecommons.org/commit/a0a0b8b596c8b289e4cd5b79a0bee6757ad077aa

**Comment by brodybits** [comment]
Thanks for your attention and efforts. Unfortunately when I try the example and click on the radio buttons, it updates the preview but *not* the HTML code that the user can copy to his/her website.

**Comment by mattl** [comment]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/33296/12457618/17e3956c-bf6b-11e5-8e97-57bf7ec4f71f.gif)

It is a subtle change...

**Comment by brodybits** [comment]
My mistake, I see the subtle change now. Thanks for fixing!
