### ISSUE TITLE
Write copy for Lessig feature on new homepage

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#144]
About 65 words plus a title.

Also, what's the action people can take? Donate?

**Comment by rebeccalendl** [comment]
I'm just waiting for the copy here to be final (EOD today) and then I will adapt from that. Timing ok for you?

https://docs.google.com/document/d/1LmRua-Eb7E3h8c7QKQdfpJWRf-XSpigx_KDuAVRmYtM/edit

**Comment by mattl** [comment]
That should be okay. I'm a little concerned about the length, and how we'll get those Korean characters in an email to look good, but should be okay.

**Comment by rebeccalendl** [comment]
Was thinking of using the first few sentences, not the whole thing, plus a short call to action. I'll draft something for you to have, and will stick it on the same doc following the email draft.

**Comment by mattl** [comment]
Cool. Can you post a heads up here when it's there?

**Comment by rebeccalendl** [comment]
k. draft is there. again, won't be final until eod. let me know if too long and I can chop.

**Comment by mattl** [comment]
Locked myself out. I noticed that anyone with the link could edit, which means anyone reading this ticket :)

**Comment by rebeccalendl** [comment]
oopsies! updated thx

**Comment by rebeccalendl** [comment]
we are still before the eod deadline but everyone involved has weighed in so I think we are good to go. let me know what else you need to send along a test and draft homepage
