### ISSUE TITLE
Action vs Civi

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#149]
I didn't see this on the agenda for the meeting. Let's discuss more next week, but it sounds like the problem with Civi is simply one of basic layout?

@tvol @rebeccalendl

**Comment by mattl** [comment]
Thinking more about this, is this related only to forms generated by Civi (aka Profiles)?

**Comment by mattl** [comment]
@rebeccalendl Any thoughts on this?

**Comment by rebeccalendl** [comment]
Sorry, I had updated my comment on this in a googledoc to you and not here. I though we decided to hold on Action for now, so not pressing, that seemed to be the consensus. Let me know if I'm missing something.
