### ISSUE TITLE
civi list size in December 2013, 2014 and now 2015?

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#151]
@mattl can you pull these 3 data points for me? I want to plan for our year end campaign and build on what we know from previous years about who received our fundraising emails. Thanks.

**Comment by mattl** [comment]
I can pull the numbers on how many emails were sent at various times, but we sent a lot of emails for some of these. I'll try and get some better numbers soon.

**Comment by rebeccalendl** [comment]
To clarify, I just need total # of recipients of our general YE campaign outreach (not a specific breakdown by each email sent). So should be three numbers total (for example, list size = 20K in 2013, 30K in 2014, 40K in 2015) so I have a sense of our YE campaign income in relation to list growth. Make sense?

**Comment by mattl** [comment]
Yep, however we don't have historical records like that so I'll need to go
back through all the emails we sent around that time and find the numbers.

**Comment by rebeccalendl** [comment]
Any progress here? I'd like to share with Trilogy on the call tomorrow. For context, we had 480 donors under $500 each totaling 36k in 2013, and 535 donors under $500 each totaling 27k total in 2014. I'd like to have the total # of YE campaign recipients to go with each of those years, as well as total # of YE campaign recipients we are planning for this year.

**Comment by mattl** [comment]
I'll try and get some numbers together for tomorrow's call. Been working on
legal stuff all afternoon.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccalendl** [comment]
@mattl any numbers here or not yet?

**Comment by rebeccalendl** [comment]
I need this at the latest for tomorrow's 11:30am PST call on YE campaign, or please let me know if there's some reason why it's just too complicated and/or time consuming.

**Comment by mattl** [comment]
2013: 12k
2014: 20k 
2015: 38k (likely to go down a bit)

**Comment by rebeccalendl** [comment]
Thank you!!
