### ISSUE TITLE
Image for small run of new CC tote?

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#152]
@mattl I'd like to do a small run of tote bags of the awesome graphic you created for the recent goodbye gifts. Same multi-color graphic, but text below would say I love to share / Creative Commons (white on black tote). What do you think? File type would be photoshop hi res. psd file, or vector artwork as an ai or eps file, or vector artwork in pdf format

**Comment by mattl** [comment]
I can make a PDF without problem for sure. When do you need this?

**Comment by rebeccalendl** [comment]
Is Monday doable?

**Comment by rebeccalendl** [comment]
Printer requesting receipt of artwork no later than Friday and ideally sooner in order to have totes in hand by Thanksgiving. Let me know if doable.

**Comment by mattl** [comment]
Sure, do you have dimensions? I can get this to you today.

**Comment by rebeccalendl** [comment]
9 inches tall x 8.5 inches wide

**Comment by mattl** [comment]
![tote](https://cloud.githubusercontent.com/assets/33296/11070367/e3d17d9a-87a0-11e5-8a2c-73be0925ea65.png)

**Comment by mattl** [comment]
![tote2](https://cloud.githubusercontent.com/assets/33296/11070421/2e793cc0-87a1-11e5-8a57-9208982d5b66.png)

**Comment by mmoreshead** [comment]
Isn't it a lowercase i?

**Comment by mattl** [comment]
I guess it is.

**Comment by mattl** [comment]
![6302912234_7d20e167ba_b](https://cloud.githubusercontent.com/assets/33296/11070538/bed97cc6-87a1-11e5-97cf-71f5dfc23b89.jpg)
 from @tvol's modelling days

**Comment by tvol** [comment]
i'm yet to see any royalties

**Comment by mattl** [comment]
![g10](https://cloud.githubusercontent.com/assets/33296/11070654/70c044b0-87a2-11e5-8efb-5f11d23efa4b.png)

Here you go.

**Comment by mmoreshead** [comment]
You took the words out of my mouth, @mattl

**Comment by mattl** [comment]
![tote](https://cloud.githubusercontent.com/assets/33296/11073248/63419264-87af-11e5-9531-2c941d7e7f94.png)
![tote2](https://cloud.githubusercontent.com/assets/33296/11073249/634324c6-87af-11e5-989b-9e3b83c9d41b.png)

**Comment by rebeccalendl** [comment]
I agree with your preference for the stacked version. What do you think about increasing the size of the CC logo so that it aligns with the length of the 'i love to share' above it? will you send final version to me via email in file type photoshop hi res. psd file, or vector artwork as an ai or eps file, or vector artwork in pdf format, (or can I just save from here without altering image quality?)

**Comment by mattl** [comment]
Yeah, I'll send you a PDF and a high res PNG. I don't know how to make the
others.
