### ISSUE TITLE
new page nested under supporters page for 1k level supporters

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#153]
Please bump the current 1k -1999 list to a new page that's linked to from the current supporters page. Add a single bullet point under the existing 1000 - 1999 header that says: "Thank you to our additional supporters" with 'additional supporters' linking to new page

**Comment by rebeccalendl** [comment]
@mattl Is it possible for this to happen today? There's a long backstory I can share on strategy if helpful/necessary.

**Comment by mattl** [comment]
Yeah, this should take me a couple minutes.

One sec.

**Comment by mattl** [comment]
All set. You should be able to tweak the styling of the link, etc.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccalendl** [comment]
I'm getting repeated server error when I try to update

**Comment by mattl** [comment]
try again in 15 mins and if you're still having problems, let me know

**Comment by mattl** [comment]
Looks like it worked now.
