### ISSUE TITLE
Week of 11/16 website update to include Open Business model plug

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#154]
Just setting up a ticket for this update. The plug will go in the bottom left corner of the homepage where 'relive the magic' currently lives.
@sarahpearson to draft copy and select image with link to medium
@mattl to update site by end of week Fri 11/20

**Comment by sarahpearson** [comment]
Sent copy and image via google doc to @mattl. Let me know if there is anything else you need!

**Comment by mattl** [comment]
![screenshot from 2015-11-13 09-16-39](https://cloud.githubusercontent.com/assets/33296/11149271/4ec2d872-89e7-11e5-92f7-c5cf42c1a7d5.png)

All set for next week.

**Comment by rebeccalendl** [comment]
@mattl can you update or let @sarahpearson know if you need anything additional?

**Comment by mattl** [comment]
Live.
