### ISSUE TITLE
develop TPP issue campaign text for Nov 24

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#155]
Tuesday 11/24 AM
TPP email; petition, capture email and country
will draft something based on 
https://creativecommons.org/weblog/entry/46455
https://creativecommons.org/campaigns/trans-pacific-partnership-would-harm-user-rights-and-the-commons

**Comment by tvol** [comment]
@mattl we need the signup form for the TPP campaign tomorrow. I put the draft text onto a page here https://creativecommons.org/campaigns/stop-the-tpp

**Comment by mattl** [comment]
And we want to collect Name, City, Country and a comment, right?

**Comment by tvol** [comment]
@mattl email too

**Comment by mattl** [comment]
Sorry yeah. Email too. And their MySpace profile.

**Comment by rebeccalendl** [comment]
good to go for tomorrow AM?

**Comment by tvol** [comment]
@rebeccalendl almost

**Comment by tvol** [comment]
![screen shot 2015-11-23 at 4 27 13 pm](https://cloud.githubusercontent.com/assets/231665/11354265/1d3c11ea-91ff-11e5-9d58-d15d700e4989.png)
@mattl can you made it so the text for the comment question does not break into 2 lines?

**Comment by mattl** [comment]
@tvol -- done. If you change the template to "Video Grid" in the WordPress editing interface, you can get rid of the sidebar too.

**Comment by tvol** [comment]
@mattl looks the same to me

**Comment by tvol** [comment]
@mattl @rebeccalendl  we need those unique links to get trackback information for email/facebook/twitter, right? can we just make them up based on what we did beforehand? https://docs.google.com/spreadsheets/d/1PfiMfQbUw6l69lELBJE1Bem77kFy5OpciikMCgbX_Lw/edit#gid=1200001469&vpid=A1

**Comment by mattl** [comment]
@tvol looks like you saved over my change :P one sec.

**Comment by tvol** [comment]
@mattl i'll go back to perusing myspace

**Comment by mattl** [comment]
good idea. fixed.

**Comment by mattl** [comment]
Updated the DNE email list. A few hundred people, many had an existing DNE
flag but also a bunch of dupes. Fixed both.

**Comment by tvol** [comment]
@mattl do you know how to generate the unique URLs for email/fb/tw tracking?

**Comment by tvol** [comment]
done https://creativecommons.org/campaigns/stop-the-tpp
