### ISSUE TITLE
confirm SOTC format works for translation process

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#156]
Sent draft SVG files from designer to your inbox, let me know if this works for our translation needs

**Comment by mattl** [comment]
I don't have any SVG files. Can you send them again?

**Comment by mattl** [comment]
Ignore that, they just came in.

**Comment by rebeccalendl** [comment]
Do you have 10 minutes to talk through this and a few other SOTC related items today?

**Comment by mattl** [comment]
Sure. my calendar is up to date

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccalendl** [comment]
Thanks! Just sent an invite but feel free to adjust if needed. I'm open today except for 11-12 pst.

**Comment by rebeccalendl** [comment]
Just sent you updated from the designer. Let me know what your needs are if any for smooth translation and push to web. Thanks!

**Comment by rebeccalendl** [comment]
@mattl if you agree will you add Happy Birthday to the language strings when you do the translation outreach? We can use them in the 12/16 email, easiest to grab them when we grab the SOTC translations.

**Comment by janeatcc** [comment]
Update: we'll have final condensed version by EOB today, then we'll need to input into Google form so I can send on to affiliates for translation.

**Comment by mattl** [comment]
Cool, we'll do that first thing on Monday

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccalendl** [comment]
Our affiliate translation deadline is today

**Comment by janeatcc** [comment]
@mattl if you want to create the basic google form, i can copy and paste in the final if you're off.

**Comment by mattl** [comment]
When will I get the copy? I'm done for Thanksgiving in 2 hours, and putting
it into a form takes a bit of time.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by mattl** [comment]
ok

**Comment by janeatcc** [comment]
great, please just send to me with edit capabilities when ready and i'll do the pasting and send on to affiliates by EOD. thanks!

**Comment by mattl** [comment]
![screenshot from 2015-11-25 16-10-44](https://cloud.githubusercontent.com/assets/33296/11410750/a103768a-938f-11e5-8311-3ba6a62c938c.png)


Shared the form with you. Basically you'll add a bunch of "Text" inputs on each page, and then split it up over the various pages of the report. The form text you enter will be the thing you want translated, and the response will be the translated text.
