### ISSUE TITLE
Remove wordpress from repo, get and install local composer.phar and use that!

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#158]

**Comment by mattl** [comment]
We'll need to move wp-config and maybe index.php too

**Comment by robmyers** [comment]
wp-config-local.php.in needs to move to /config . Check index.php . Diff other files?

Install composer via wget, as composer.phar in top level directory.

**Comment by robmyers** [comment]
We install wordpress in a subdirectory, so we can remove the existing install in docroot/wordpress, have composer install a fresh version into into docroot/wordpress. This also means we don't need to move index or config, as the versions we use are in docroot so will not be affected.

Change implemented.
