### ISSUE TITLE
Requested updates to https://donate.creativecommons.org/

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#159]
I'm open to discussing what is feasible; my requests are:

Add: $1000 as a pre-filled option.
Nix: I want to make a one-time contribution.
Email address collection to happen after Gift Choice with other fields (or is there a reason it's separate?)

Choose Your Gift section update:
New header: Thank you for your support! 
As our thank you for your contribution of $50 and above, or for setting your donation at any amount to recur monthly, we'd like to send you a Creative Commons tote bag!
Yes, please send me a CC tote.
[Image]

Add website field to the list of info collected from donor.

Yes, I'd like to be acknowledged on Creative Commons public list of supporters.
Contributions at $1,000 and above will be recognized on our public list of supporters with the individual or company name and a website link.

**Comment by rebeccalendl** [comment]
One more: "Process Contribution" button should read: "Donate Now"

And is there a place in wordpress where I can update the copy inside the right side panels myself or does that need to go through you?

**Comment by mattl** [comment]
* Adding $1000 -- no problem. Should we drop $50, and have $10, $25, $100, $250, $1000, other?

* If we nix that, we can't really take recurring donations as there's no way to unselect that option. We should probably leave it.

* I believe there's a reason it's separate, but I'll see if it can be moved.

Text changes should be easy enough, just the one gift is no problem. They'll need to select that they want a gift, and we'll need to double check someone didn't make a one-time donation of < $50 before we send them a tote.

Website should be no problem, and I can make that text change.

**Comment by mattl** [comment]
I'll see if we can change the button text.

The copy is in CiviCRM, I'm happy to update.

**Comment by rebeccalendl** [comment]
We'll want $50 because of the tote. Can we add Other below the stacked 6 options?
Possible to just click the check mark again to unselect? 
I'm assuming there's no way to not be allowed to click Yes for the tote if under 50 or not recurring?
I'll send civicrm copy updates shortly (or you can point me toward it to do myself?)
What are the chances that we can update by next week to grab black friday and giving tuesday traffic?

**Comment by mattl** [comment]
Yeah, doing the tote with a recurring donation is not going to work as
someone could very well pay $10 a month and cancel after one month.

The way to do it would be to look at who's giving us money and send to them
after they've given $50, but that might be a lot of work for a tote bag.

I can make it require $50.

I don't think we can add "other" under the others, and we need to be
mindful of how this looks on mobile, so adding another row of buttons is a
lot of screen real estate.

Take a look at
https://donate.creativecommons.org/civicrm/contribute/transact?reset=1&id=34&action=preview
-- where I've implemented some of these changes.

**Comment by rebeccalendl** [comment]
If someone really wants a $5 CC tote that much, I'm fine to send it to them. Would like to incentivize recurring. So let's not make it require $50 unless it can free it up for recurring.

Possible for "other" to be in text and not a button to limit real estate?

Can website URL be the only additional field and just sit neatly with the other info collected?

Nix CC tote descriptor. Make image bigger. Easier for them to just see it than us tell them about what is depicted.

I have other edits but looks like it's still in process so will hold (or let me know if you want all now).

**Comment by mattl** [comment]
For the website thing, we actually need both fields as the purpose of donating to get a link on our site depends on the text of the link as well as the URL. However, I'll see if we can hide the dropdown menu.

Tote is now $0 minimum, so perfect for recurring donations.

I reduced the description down to a few words (it looks weird without any text there) and the preview is much bigger now. Also, it's clickable.

Send your edits, and I'll try and get them done.

**Comment by rebeccalendl** [comment]
The text of the link is now set to default to the company or individual name (as stated in updated text at the top of this issue). No custom text. All copy should be updated with new copy at top of the issue...lots of small changes but I'd like to make them.

Possible for "other" to be in text and not a button to limit real estate? Don't want to lose the other levels since they are the 6 most common and 'other' is not very common.

If you have to leave both radio buttons, please update, "Yes, I want to contribute this amount monthly and receive a thank you gift from CC!"

Tote image should be the full new tote image we sent to designer. Text looks weird. Possible to have the updated copy above it be next to it: "As our thank you for your contribution of $50 and above, or for setting your donation at any amount to recur monthly, we'd like to send you a Creative Commons tote bag!"

Copy under the CC heart should read: "Invest in a creative, free, and open internet. Support Creative Commons today."

Remove 'where your donation goes' panel entirely.

**Comment by mattl** [comment]
I believe a lack of custom text will mean nobody will give $1000 for a link.

No, other needs to be a button for now. 

That doesn't make sense, because people may still wish to make a contribution without receiving a gift. Forcing a gift would force everyone making a recurring donation to enter their mailing information, which is the thing we're trying to avoid.

The full image doesn't look good when scaled down and the text is unreadable. Suggest we mention the text in the description. The text above seems to be baked into the template, so I'll get that updated when we go live with this.

Sidebar changes are common across the whole site so we'll hold off changing those for now.

**Comment by rebeccalendl** [comment]
No custom text please. The supporters page is designed to recognize our supporters, not for ad space. Although it hasn't been the case thus far and I don't think it will be, I'm fine if this policy prevents a donation or two.

If it needs to be a button, please do 10, 25, 50, 100, 1000, other.

Can't they opt out by click No for the thank you gift?

Sidebar 'where your donation goes" can't be removed?

Please update all copy listed at top, still seeing old copy. Is that because I need to clear cache?

**Comment by mattl** [comment]
A radio button that says "Yes, I want to contribute this amount monthly and receive a thank you gift from CC!" doesn't make sense if they've selected no gift. I suggest we add something to the gift section that explains recurring donors getting a tote after $50 or whatever.

Sidebar changes are common across the whole site so we'll hold off changing those for now, as they'll be reflected across the whole site. We'll want to do some testing before making any changes to the live donation page.

Which copy are you referring to? Please attach a screenshot. https://support.apple.com/en-us/HT201361

**Comment by rebeccalendl** [comment]
Is this in civi? perhaps you can point me to it and I can make a few small changes (without touches the sidebars as you noted)?

**Comment by mattl** [comment]
Sorry, which part do you want to change? There's a few different places for the various things.

**Comment by rebeccalendl** [comment]
I have a few small changes for each section.

**Comment by mattl** [comment]
You can change a lot of things here: https://donate.creativecommons.org/civicrm/admin/contribute/settings?reset=1&action=update&id=34

You can configure the tote bag here: https://donate.creativecommons.org/civicrm/admin/contribute/managePremiums?action=update&id=35&reset=1

And this is the profile that's displayed at the bottom (be careful with this one, it's live)

https://donate.creativecommons.org/civicrm/admin/uf/group/field?reset=1&action=browse&gid=17

**Comment by mattl** [comment]
I re-enabled the contributor source on the Mailing and Supporter List Opt-in profile. This helps us identify where the donation comes from in Civi.

**Comment by rebeccalendl** [comment]
Ok, I've made some updates. A few notes:
-all look ok to you?
-can we switch the order on the premium section to be yes first, then no?
-I added URL to the shipping profile, but can't figure out how to add to billing profile so it's not showing up still. I'd prefer it there to the mailing list section.
-Some copy I can't find to update (mailing list intro section for example)

**Comment by mattl** [comment]
There is no billing profile, only a shipping profile. PayPal and Stripe handle the billing part of things.

We can move it back to the mailing and supporter list opt-in profile and put text around it to make it a distinct field. 

I believe the premium order isn't something we can change right now.

**Comment by rebeccalendl** [comment]
Let's leave URL off for now if we can't tuck it into the shipping/billing section. Rather keep the page clean. Still feels a bit clunky overall, but I think it's the best we can do given the limitations. Thanks for all the updates, and sending me into civi to dig around. Helpful for me to see where we can and cannot customize.

**Comment by mattl** [comment]
There's a lot more that could be done here, but that would require some more development time from Giant Rabbit.

**Comment by rebeccalendl** [comment]
Ok. For now, please do pull URL and move copy back under the check box.

**Comment by mattl** [comment]
Done. Hidden the "Where does your contribution go?" box on all donation pages, and gave it a quick test on mobile. Seems okay. How does it look for you?

**Comment by rebeccalendl** [comment]
Yep, definite improvement. Thanks!

**Comment by rebeccalendl** [comment]
Can this go live on Wednesday? Can other merch items be moved to our online shop?

**Comment by mattl** [comment]
I can put it live on Wednesday, please coordinate with @mmoreshead to get things up on the store.

**Comment by mmoreshead** [comment]
Happy to help with this.  Will add the product now & make it live whenever you say.  @rebeccalendl - have you coordinated with Noonaco?

**Comment by rebeccalendl** [comment]
@mmoreshead  not yet but have an email queued up for today. I'll keep you in copy.

**Comment by mmoreshead** [comment]
@rebeccalendl what do you want it to say in the store about it in the description section?

**Comment by mmoreshead** [comment]
To be clear, all items currently appearing on donation page: heart logo/ilovetoshare/othertote/hoodie are to be moved to the store -- is that right?  

Not all items there have a description in our store but it might be nice if they did.  We can update that part anytime, what is important now is price.  Does this look about right or shall I adjust, @rebeccalendl ?

**I love to share - Heather Grey**
Price: $25
**I love to share - Navy Blue**
Price: $25
**Tote Bag (plain logo) - Black**
Price: $20
**Hoodie - Black**
Price: $50

Mari will also alert Noonaco of this change once it's done so they can adjust accordingly.

**Comment by rebeccalendl** [comment]
Made a few updates below. Will you also add the item type to the titles of the first few tees so it's clear? 

I love to share - Heather Grey
Price: $20
I love to share - Navy Blue
Price: $20
Tote Bag (plain logo) - Black
Price: $10
Hoodie - Black
Price: $35

**Comment by rebeccalendl** [comment]
@mattl Requesting information on why dollar option is now 999?

**Comment by mattl** [comment]
Eric identified a bug with the page on mobile where any amount over 999
doesn't fit, we can fix it, but for now it's a stopgap.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccalendl** [comment]
Ok. Please use $500 as stopgap. What's the timeline on the fix?

**Comment by mattl** [comment]
No timeline yet. You can change the number in Civi as you were doing before.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC
