### ISSUE TITLE
add twitter cards to cc.org

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#161]
Can we get twitter cards so that users automatically get a CC icon preview in twitter posts when there is no image provided? It seems to be importing a thumbnail when there is an image in the blog post. For example, https://twitter.com/creativecommons/status/667716179549523968. But when there is no image,  it's just blank. For example, https://twitter.com/cgreen/status/666316018768285696. 

Looking at source on our homepage it looks like we might have something already setup, but I can't tell what it actually is doing. EFF has it setup nicely so that when a user copies a URL from one of their blog posts in order to put on twitter or facebook you get a nice image (https://www.eff.org/files/2015/03/02/eff-og-3.png) if there's none provided within the post itself.

**Comment by mattl** [comment]
Okay, this is done.
