### ISSUE TITLE
CC open gift guide 

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#162]
Would like to launch an open gift guide this week to include in our Friday email, will send draft to staff for review today and open for discussion on staff call. Attaching here a screenshot of the draft guide, also a few examples on how we can integrate with our website (inline frame, frameset, or just a link) let me know what you think is best. Possible to get this live by EOD Wednesday?
<img width="777" alt="open gift guide" src="https://cloud.githubusercontent.com/assets/13322149/11348728/17af88b4-91dd-11e5-9a44-52a2f35548b9.png">
<img width="986" alt="astore embedding" src="https://cloud.githubusercontent.com/assets/13322149/11348731/198752e8-91dd-11e5-8d0a-dd2e3a43e185.png">

**Comment by rebeccalendl** [comment]
@mattl do you have a URL for the store? want to share with peeps who have offered to send out promo

**Comment by mattl** [comment]
http://creativecommons.org/openstore -- nothing there yet, but i will make sure that link works for those people who come there

**Comment by rebeccalendl** [comment]
Smaller copy, smaller overall real estate per item (or is that a necessity for mobile?). possible menu type headers at top to browse by category? overall just takes some effort to absorb the range of possible products and potentially lowering likelihood of a purchase (without scrolling I only see two halves of two products)

**Comment by rebeccalendl** [comment]
items smaller still? and main header also eats up a lot of space.

**Comment by rebeccalendl** [comment]
thats great. just that header shrink saves a ton of space. good to go. you agree?

**Comment by mattl** [comment]
yep. i'm good to put this up on the site.


---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccalendl** [comment]
maybe we can update one of the website content panels on homepage lower left in the next few weeks so we can promote the shop a bit before the holidays. I'll add to the list of website stuff for YE.

**Comment by mattl** [comment]
Cool

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC
