### ISSUE TITLE
Donor reporting by region

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#163]
Can you set up a reliable system for me to be able to accomplish this and similar without tech support?:

Does civi let me pull a report that eliminates duplicates? I'm looking to pull total quantity and names of donors in NY state. The donor report pulls all donation instances of the same donor so can't tell qty without spending time manually deletes dupes. Know any tricks?

**Comment by mattl** [comment]
when do you need this report?

**Comment by rebeccalendl** [comment]
This specific report I can hold until Monday or Tuesday of next week, but in general this is a great example of common database function that I'd need to have handy anytime.

**Comment by mattl** [comment]
Sent you something in email, let me know what you think.
