### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#164]
Making some prototypes for the open gift guide
![genimg](https://cloud.githubusercontent.com/assets/33296/11384211/9d56f30c-92d3-11e5-89d6-63e91ec5e0a2.png)

**Comment by mattl** [comment]
Same exact size as our existing button, which works nicely.

**Comment by mattl** [comment]
Also color options, etc.
![hotpinkbysa](https://cloud.githubusercontent.com/assets/33296/11384420/2f72c6e8-92d5-11e5-9d2e-f1445a59cf7b.png)


![bysa](https://cloud.githubusercontent.com/assets/33296/11384406/0942aa6a-92d5-11e5-8595-1a0b45c0bffb.png)

**Comment by janeatcc** [comment]
Looks great to me.. but did you mean to assign rebecca?

**Comment by mattl** [comment]
Nope, just keeping you in the loop.

**Comment by janeatcc** [comment]
Nice. I think in addition to grey we want black on white versions for platforms.

**Comment by mattl** [comment]
Yeah, I'm going to set it up so you'll have a form where you can set
colors, size and the name of the platform and it'll generate all the files
and put them on licensebuttons.net
