### ISSUE TITLE
12/1 #GivingTuesday email send

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#165]
Don't think there was a ticket for this previously so adding now.

Copy will be finalized by EOD today and lives here:
https://docs.google.com/document/d/1RG-kni7o7LqN2rodpDSW9Xm6_vBr08RlwU-JrXoPXwE/edit

Email to be sent to full list on Tuesday 12/1 AM PT

**Comment by rebeccalendl** [comment]
Do you need anything else from me on this? Can you send a test please so we can ship this AM?

**Comment by mattl** [comment]
yep, test should be with you in about 5 mins.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC
