### ISSUE TITLE
Add video to videos page

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#167]
Please add this video:
https://vimeo.com/147551334
to:
http://creativecommons.org/videos 

@cablegreen do you have a suggestion for title & short description?

**Comment by cablegreen** [comment]
Thanks for opening a ticket ;)

Suggested title: CC in New Zealand Schools

**Comment by cablegreen** [comment]
checking in... thanks

**Comment by little-wow** [comment]
done
