### ISSUE TITLE
Changes to board page

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#169]
http://creativecommons.org/board  This must be updated with departing members and new members as well as advisory. Mari to provide info shortly.

**Comment by mmoreshead** [comment]
I'll wait for the blog post announcement before I make these changes.

**Comment by mmoreshead** [comment]
Please make the following changs to: http://creativecommons.org/board
1) Move Hal, Laurie, Eric S, Molly, Esther, and Mike C to the Advisory Council
2) Change Audit Committee members to: Christopher Springman, Johnathan Nightingale, Dorothy Gordon
3) Add new board members.  I'll drop Bios and images into next comment.

**Comment by mmoreshead** [comment]
Johnathan Nightingale is the Chief Product Officer at Hubba, and was formerly the head of Firefox for Mozilla. He was among the first to graduate from the University of Toronto’s Cognitive Science and Artificial Intelligence program in 2001. In his role at Mozilla he was responsible for the engineering, product management, marketing, and design of the Firefox web browser on desktop and mobile platforms; a suite of products developed by a global community, used by over 400 million people worldwide, and localized into more than 80 languages. He has been an invited expert to the UK’s house of lords on issues of surveillance and tracking, sat for 3 years on the w3c’s usable security working group, and has spoken often at industry conferences on issues of technology and security. He is an avid photographer, a wikipedian, author of the ubiquitous linux command line tool, “beep”, and a proud parent in a house full of minecraft.

Image: https://www.flickr.com/photos/johnath/8243468396/

**Comment by mmoreshead** [comment]
Kate's bio is coming.  
![spelman_kate_headshot](https://cloud.githubusercontent.com/assets/11162279/11634157/f588cfec-9cdc-11e5-82ca-875c4cf65ba4.jpg)

**Comment by mmoreshead** [comment]
Kate Spelman, partner at K&L Gates, represents many of the players in the content distribution ecosystem: author, university, nonprofit, publisher, and technology developer both nationally and internationally. She serves on several copyright task forces and advisory committees, among them the American Bar Association Intellectual Property Section Task Force on Copyright Reform; American Law Institute Restatement of Copyright; and the American Intellectual Property Law Association Amicus Committee.  A graduate of the University of Wisconsin Madison and the University of Michigan, Kate also has further education in technology and engineering from the University of California Berkeley.

**Comment by mmoreshead** [comment]
Let me know if you need anything else.

**Comment by mattl** [comment]
Can someone take a pass on Jonathan's bio? I notice a bunch of it seems oddly capitalized, for example W3C, Linux, Wikipedian, House of Lords, etc.

**Comment by mmoreshead** [comment]
This directly from him - I'd hesitate to change it.

**Comment by mmoreshead** [comment]
Also:
Note by Chris Thorne that he is now Vice Chair.
Note by Chris Sprigman (only in Audit section) that he's chair of that committee.

**Comment by mmoreshead** [comment]
That's a yes from Ryan to change these, making it  (if I haven't missed anything) now:

Johnathan Nightingale is the Chief Product Officer at Hubba, and was formerly the head of Firefox for Mozilla. He was among the first to graduate from the University of Toronto’s Cognitive Science and Artificial Intelligence program in 2001. In his role at Mozilla he was responsible for the engineering, product management, marketing, and design of the Firefox web browser on desktop and mobile platforms; a suite of products developed by a global community, used by over 400 million people worldwide, and localized into more than 80 languages. He has been an invited expert to the UK’s House of Lords on issues of surveillance and tracking, sat for 3 years on the W3C’s usable security working group, and has spoken often at industry conferences on issues of technology and security. He is an avid photographer, a Wikipedian, author of the ubiquitous Linux command line tool, “beep”, and a proud parent in a house full of Minecraft.

Image: https://www.flickr.com/photos/johnath/8243468396/

**Comment by robmyers** [comment]
Changes 1) 2) 3) made.

Two notes added.

@mmoreshead Please can you take a quick look at this and close it if it's OK?

**Comment by mmoreshead** [comment]
Yay, looks great, thanks Rob!
