### ISSUE TITLE
YE #5 to send Tuesday 12/22

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#174]
Final copy lives here:
https://docs.google.com/document/d/1lPMCaO83_QqL5vJG9w2ClkqC6943OHtiTbRX0dx3jnM/edit?pli=1

Segmented outreach to: 1) donors (giving last 36 months) and 2) non-donors (no giving history last 36 months). Omit civi group "Do Not Email YE 2015" from both segments.

Please send tests to Rebecca, Ryan, Tim, and Trilogy for advance review.

**Comment by tvol** [comment]
@rebeccalendl i put text into blog post. http://creativecommons.org/?p=46762&preview_id=46762&preview_nonce=139dbad8dc&preview=true looks kinda sparse. do you think it's ok, or should we try to add a bit more?

**Comment by rebeccalendl** [comment]
Agreed, looks sparse/uninteresting. Let's do a post with Esther's testimonial around OER instead. Her email is queued for tomorrow, we could blog post on Monday. Sound ok @tvol ?

**Comment by tvol** [comment]
done http://creativecommons.org/weblog/2015/12/21/46762

**Comment by robmyers** [comment]
This email has gone out.
