### ISSUE TITLE
YE #6 to send Saturday 12/26

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#175]
Final copy lives here:
https://docs.google.com/document/d/1lPMCaO83_QqL5vJG9w2ClkqC6943OHtiTbRX0dx3jnM/edit?pli=1

Segmented outreach to: 1) donors (giving last 36 months) and 2) non-donors (no giving history last 36 months). Omit civi group "Do Not Email YE 2015" from both segments.

Please send tests to Rebecca, Ryan, Tim, and Trilogy for advance review.

**Comment by robmyers** [comment]
This is now queued.
