### ISSUE TITLE
YE #7 to send Monday 12/28

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#176]
Final copy lives here:
https://docs.google.com/document/d/1lPMCaO83_QqL5vJG9w2ClkqC6943OHtiTbRX0dx3jnM/edit?pli=1

No segmenting needed! Single send to full list.
Omit "Do Not Email YE 2015"

Please send tests to Rebecca, Ryan, Tim, and Trilogy for advance review.

**Comment by robmyers** [comment]
This is now queued.
