### ISSUE TITLE
YE #9 to send Thursday 12/31

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#178]
Final copy lives here:
https://docs.google.com/document/d/1lPMCaO83_QqL5vJG9w2ClkqC6943OHtiTbRX0dx3jnM/edit?pli=1

NEW Segments!: 

1) Individuals who have given in 2015
2) Individuals with NO giving history in 2015

Omit civi group "Do Not Email YE 2015" from both segments

Please send tests to Rebecca, Ryan, Tim, and Trilogy for advance review.

**Comment by robmyers** [comment]
This is now queued.
