### ISSUE TITLE
YE #10 to send Friday 1/1

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#179]
Final copy lives here:
https://docs.google.com/document/d/1lPMCaO83_QqL5vJG9w2ClkqC6943OHtiTbRX0dx3jnM/edit?pli=1

No segments needed. One send to full list. 

Note! No need to omit "Do Not Email YE 2015" as this is not an ask. Please include all!

Please send tests to Rebecca, Ryan, Tim, and Trilogy for advance review.

**Comment by robmyers** [comment]
Not segmented.

This is now queued.
