### ISSUE TITLE
Blog post Wednesday 12/16: Happy Birthday CC license suite

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#180]
Final copy + image pulled from YE#3 here:

https://docs.google.com/document/d/1lPMCaO83_QqL5vJG9w2ClkqC6943OHtiTbRX0dx3jnM/edit?pli=1

**Comment by peterspdx** [comment]
added just a few tweaks to the 13th b'day message.

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC

**Comment by tvol** [comment]
@rebeccalendl do you want the blog post to be authored by Larry?

**Comment by tvol** [comment]
@rebeccalendl also, can you point out to me where the image is?

**Comment by rebeccalendl** [comment]
Yep this ticket is just a placeholder; I loaded it up alongside all the year end stuff to keep us all synched up.  

All is still in process, though close to finalizing. Getting signoff from Larry now, working on graphics via Trilogy and Matt. We can talk through anything outstanding on Friday call.

**Comment by tvol** [comment]
@rebeccalendl yep sounds fine. also i'm building out referral links for all the rest of the YE comms here: https://docs.google.com/spreadsheets/d/1PfiMfQbUw6l69lELBJE1Bem77kFy5OpciikMCgbX_Lw/edit#gid=1200001469 let's talk on friday to make sure it's what we want

**Comment by rebeccalendl** [comment]
oh thats awesome. yes lets add to fri agenda.

**Comment by tvol** [comment]
blog post preview http://creativecommons.org/?p=46712&preview=true

**Comment by tvol** [comment]
https://creativecommons.org/weblog/2015/12/16/46712
