### ISSUE TITLE
2 more changes to /board page

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#182]
Esther Wojcicki should also be moved from board to advisory.
I guess I should be on the page as Assistant Secretary too.

Let me know if you have questions.  

Thanks, 
Mari

**Comment by peterspdx** [comment]
Agree Mari should be on the page as assistant secretary.

I'm a board member, though non voting. I should be moved up under board members, but a notation made in parenthetical (Secretary, non voting). Thanks.

**Comment by mattl** [comment]
@mmoreshead You should be able to make these changes with your new shiny WordPress account.

**Comment by mmoreshead** [comment]
Oh fancy!  Thanks for the heads up @mattl

**Comment by mmoreshead** [comment]
Moved Esther, updated Diane, will fix myself tomorrow (Friday).

**Comment by mattl** [comment]
Think this was done. closing.
