### ISSUE TITLE
Add Noura's book to the open store

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/creativecommons.org#183]
Please add Noura's book about Bassel to the open store. Not an Amazon referral, but it is CC0 and we want to help.

http://www.lulu.com/shop/noura-ghazi-safadi/waiting/ebook/product-22486378.html

Please do not post it live until we hear from them that it is public.

r.

**Comment by ryanmerkley** [comment]
adding @peterspdx to notify when it is public.

**Comment by peterspdx** [comment]
It's live here: http://waiting4bassel.cc

@mattl, @ryanmerkley

**Comment by mattl** [comment]
Working on this now.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by mattl** [comment]
https://creativecommons.org/discover/gift-guide/

@tvol can you promote this on social media?
