### ISSUE TITLE
fix image upload error on cc blog

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#184]
![screen shot 2015-12-14 at 3 33 37 pm](https://cloud.githubusercontent.com/assets/231665/11797483/1ba699ca-a278-11e5-8ca8-51e4844e1cdd.png)

**Comment by mattl** [comment]
@robmyers I think recent updates didn't chmod www-data:www-data -R /home/creativecommons/docroot

**Comment by robmyers** [comment]
We never chmod www-data, just chgrp www-data, which should be sufficient?

Checking.

**Comment by mattl** [comment]
chown, sorry

**Comment by mattl** [comment]
I always chown, I never chgrp.

**Comment by robmyers** [comment]
And you seem to be right to do so, it's now fixed.

@tvol You should be able to upload images now.

**Comment by mattl** [comment]
Thanks @robmyers

**Comment by tvol** [comment]
thanks @mattl @robmyers
