### ISSUE TITLE
Email glitch

### ISSUE THREAD

**Issue by NaeemaCC** [creativecommons/creativecommons.org#188]
Hello there @mattl & @robmyers 
I'm being a good girl and there filing my first ticket ever :D 
I've been having some email glitches lately at naeema@creativecommons.org some emails never get delivered to my inbox and later people forward them to me or receiving them with delay in time; I would suddenly receive a bunch of emails on one day with back dates up to two weeks!  

Can you please advise
Naeema

**Comment by mattl** [comment]
I'll look at this today and get back to you.

Are you accessing your mail via the Google Mail website or something
different?

**Comment by mattl** [comment]
Nothing report as not working, but you also haven't replied to this, so I'm wondering if there's some issue on your end? Either way, we'll figure it out.

**Comment by NaeemaCC** [comment]
Just received this! Im accessing through Google Mail

On Fri, Dec 18, 2015 at 10:31 PM, Matt Lee <notifications@github.com> wrote:

> Nothing report as not working, but you also haven't replied to this, so
> I'm wondering if there's some issue on your end? Either way, we'll figure
> it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/188#issuecomment-165891837>
> .
>



-- 
Naeema Zarif
Regional Coordinator | Arab World
Creative Commons
creativecommons.org
naeema@creativecommons.org

Skype: NaeemaZarif
Twitter: @naeema

Please support CC in shaping the future of sharing:
https://creativecommons.net/donate/

**Comment by mattl** [comment]
Is this resolved now?

**Comment by NaeemaCC** [comment]
I guess it is! Usually I cant know until I start getting the missing emails
or people start reaching out via different channels or personal email :D
Will wait and see

N

On Wed, Mar 23, 2016 at 7:38 PM, Matt Lee <notifications@github.com> wrote:

> Is this resolved now?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/188#issuecomment-200459446>
>



-- 
Naeema Zarif
Regional Coordinator | Arab World
Creative Commons
creativecommons.org
naeema@creativecommons.org

Skype: NaeemaZarif
Twitter: @naeema

Please support CC in shaping the future of sharing:
https://creativecommons.net/donate/
