### ISSUE TITLE
cc admin pages not displaying correctly on Chrome Version 47.0.2526.106 (64-bit)

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#190]
![screen shot 2015-12-21 at 11 58 27 am](https://cloud.githubusercontent.com/assets/231665/11937499/5570ed92-a7da-11e5-9e41-94e1ff8a455f.png)

![screen shot 2015-12-21 at 11 57 47 am](https://cloud.githubusercontent.com/assets/231665/11937502/592a1030-a7da-11e5-9579-e5436abd808d.png)

**Comment by mattl** [comment]
We decided that CSS was overrated, and wanted to capture the essence of late 90s websites. You want me to fix that?

**Comment by mattl** [comment]
Admin loads over HTTPS now. 

https://github.com/creativecommons/creativecommons.org/commit/a9b17d7eec09f3889bd5ecb9d51e829d27f2d7ef
