### ISSUE TITLE
You broke the semantic web

### ISSUE THREAD

**Issue by mlinksva** [creativecommons/creativecommons.org#194]
http://creativecommons.org/ns 404

:grimacing:

**Comment by mattl** [comment]
@robmyers Likely related to the rebuild of the repo

**Comment by robmyers** [comment]
Looking.

**Comment by robmyers** [comment]
I've restored the symlinks that this relies on, and added the code to create them to the build system.

http://creativecommons.org/ns now works.

@mlinksva Thank you for reporting this!

**Comment by mattl** [comment]
:+1:
