### ISSUE TITLE
Wrong links in FAQ

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#197]
In the FAQ  https://creativecommons.org/faq/ , there's a list of links under "Can Creative Commons give legal advice about its licenses or other tools, or help with CC license enforcement?"  They don't link to the right places.

Marking practices for creators should link to https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license
Marking practices for reusers should link to https://wiki.creativecommons.org/wiki/Best_practices_for_attribution

I'd fix it myself but I don't see that page being a wordpress page I can update.  (right?)

Thanks!
Mari

**Comment by mattl** [comment]
It's not WordPress, but a Markdown file on GitHub... https://github.com/creativecommons/faq/edit/master/faq-en.md

Line 112 is where you'd update it, if you're interested...

It won't appear on the site immediately, you'll need one of us to do that part.

**Comment by mmoreshead** [comment]
Updated!

**Comment by tvol** [comment]
@mattl i don't think so. many of the other links are bad too. unless you didn't merge the pull request yet?

What is the proper markdown conventions to direct to the wiki page we want? For example, in faq-en.md, there's this: [Marking practices for creators](wiki/Marking_your_work_with_a_CC_license "wikilink") but that link isn't right. But we want it to go to wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license, no?

**Comment by mattl** [comment]
Sorry, you'll need to look at the preview of the page on GitHub, it hasn't been pulled yet.

Yeah, it needs to be a full URL with a http:// or https:// prefix (http is fine, it'll redirect to HTTPS if/when we have that)

**Comment by mmoreshead** [comment]
I just fixed mine.

**Comment by mmoreshead** [comment]
Also, I bet there's lots of broken ones that were links to wiki pages and now need full urls.  I'm happy to sift through and fix these if that helps.

**Comment by mattl** [comment]
That would be useful. See some earlier chat in #creativecommons about this link https://creativecommons.org.au/learn-more/fact-sheets/which-creative-commons-licence-is-right-for-me-poster (which doesn't work) which is in the 'how should I decide which license to choose' section of the FAQ for example.

**Comment by mattl** [comment]
Updated the website with the latest version from here, but yeah... a bunch of broken links still.

**Comment by mattl** [comment]
https://validator.w3.org/checklink?uri=https%3A%2F%2Fcreativecommons.org%2Ffaq%2F&hide_type=all&depth=&check=Check

**Comment by mmoreshead** [comment]
@mattl I can identify and fix these by the end of this week, sound good?

**Comment by mattl** [comment]
Sounds great

**Comment by mmoreshead** [comment]
I've got myself organized for this, just need to trudge through and actually make the changes.  I reserve the right to do this on Monday when the US folks are off and there aren't as many interruptions.

**Comment by mattl** [comment]
Any update on this? I have to put up some new page for Jane today, so it would be good to do all this in one swoop.

**Comment by mmoreshead** [comment]
Sorry about the delay, got swamped and pushed this down.  Will see how much more I can do in the next 40 minutes.

**Comment by mattl** [comment]
Not urgent :)

**Comment by mmoreshead** [comment]
I got a little less than half way through (total).  You can send these changes now and I'll work on more next week?

**Comment by mattl** [comment]
Sounds good.

**Comment by mmoreshead** [comment]
Finally, I finished this.  Just committed my changes.

Sorry for the delay, feel free to shame me.

**Comment by mattl** [comment]
awesome :) i'll push it to the site now

**Comment by mattl** [comment]
Looks good.

Pushed https://github.com/creativecommons/faq/commit/cfa300aeebf1a3c81a043011206d406c6b3ce884 to production.

**Comment by peterspdx** [comment]
In reality, you're my hero. Thanks!
