### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by reagle** [creativecommons/creativecommons.org#200]
I just did this search and get a directory: http://labs.creativecommons.org/demos/search/?q=apple+barrell

**Comment by mattl** [comment]
Where did you start your search?

**Comment by reagle** [comment]
It's a Web shortcut I've had for at least a year. Given an empty URL is definitely weird. Is the service still available? Why not redirect?

**Comment by mattl** [comment]
@robmyers Can you get a redirect in place for this?

@reagle https://search.creativecommons.org

**Comment by robmyers** [comment]
@mattl Will do tomorrow. I have a couple of labs fixes to get in place now.

**Comment by robmyers** [comment]
Redirect now in place.
