### ISSUE TITLE
Updates to Korean translation of the deeds

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#210]
(From @soohyunpae via email )

Could you have a look at the [Korean Deeds](https://creativecommons.org/licenses/by/2.0/kr/) page and let me know how I can get the untranslated texts updated?

(and)

I just updated some strings for Korean Deeds. Could you help me get them live?
https://www.transifex.com/nkinkade/CC/viewstrings/#ko/deeds-choosers/2858697

**Comment by robmyers** [comment]
@sarahpearson @mattl what is the procedure for this, please? :-)

**Comment by sarahpearson** [comment]
Good question! @mattl should know how we push those live.
