### ISSUE TITLE
Tag archive pages say Matt Lee authored all blog posts

### ISSUE THREAD

**Issue by mlinksva** [creativecommons/creativecommons.org#212]
eg https://blog.creativecommons.org/tag/au/

**Comment by mattl** [comment]
hey Mike,

I'm very proficient with my time machine. This is something we're aware of and will be fixing soon.

**Comment by mattl** [comment]
I think you're fixing this, right?

**Comment by tvol** [comment]
@mattl unless there's some easy way to revert to previous authors, let's just leave it. I do not plan on going back through all the blog posts and changing them back manually--if i could even remember who wrote what

**Comment by mattl** [comment]
Yeah, I guess just change them when its obvious.

**Comment by mlinksva** [comment]
Hmm, when I filed this issue I assumed it was a problem in whatever renders tag pages -- authors were showing up correctly on individual post pages, and authors had the ids they'd always had (see below). But now just about everything is authored by Matt Lee, which I see is user id 1 because https://creativecommons.org/weblog/?author=1

And I see that I'm user id 2. I believe I was 14 or something. I guess you guys must have done some kind of database re-import to get to the current state. Seems like a pretty unfortunate breakage, but at least the old /weblog/nnnn URLs redirect, so not a total disaster. But still kinda lame for an organization that cares about metadata & provenance.

I also notice that old (& nearly useless) "press hits" have been merged into the main blog archives.

**Comment by mattl** [comment]
I'm not even sure what the press hits are/were.

I don't know if we were ever exposing author/archives to the public. I will update the blog to list 'Creative Commons' as the author, not myself, as I think I've published maybe 1 blog post ever.

**Comment by mattl** [comment]
Removing posts from the blog, going to try another import

**Comment by mlinksva** [comment]
The press hits were a side blog, not intended to be presented with the main blog.

There was never navigation item with author archives, but I frequently used the ?author=n functionality eg when introducing people via email.

I guess changing your name to CC is a good way to paper over the damage. Good thing CC didn't (that I recall anyway) publish any third party material under CC-BY and use the article metadata to ensure proper attribution, or you'd be out of compliance now. :wink:

**Comment by mattl** [comment]
https://blog.creativecommons.org/author/mike/

**Comment by mattl** [comment]
We'll fix up the names in the next few days, but everyone's posts are fixed.

**Comment by mlinksva** [comment]
Thanks for caring and acting. :sparkles: or other appropriate emoji I don't understand.

**Comment by peterspdx** [comment]
Just my own opinion, but I think it's unfortunate that original authorship is lost. I think it's a nice way for individuals to indicate they're a public voice, and on which topics. As for attribution non compliance as a matter of the license, that would only be a problem for those who were not employees at the time of publication. All content written by employees within scope of duties = CC owned content. Not, of course, that it's not good to have the individual identified, but I don't think it's a license violation for those.

**Comment by mattl** [comment]
It's fixed now anyway :)

Authors are back.

**Comment by peterspdx** [comment]
missed matts' post that it was all fixed. yeah, and all good as indicated. thanks, mattl!
