### ISSUE TITLE
Update board member bio/photo

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/creativecommons.org#213]
Please update Board Director Tom Rubin's bio to the following:

"Thomas C. Rubin is a Lecturer on Law at Harvard Law School and Special Counsel at the law firm Quinn Emanuel. For many years, he was Chief Intellectual Property Strategy Counsel at Microsoft, where he led product development and global policy related to copyrights, trademarks, and trade secrets. He has testified about orphan works before the U.S. Senate Judiciary Committee and addressed issues at the intersection of content and technology before government, NGO, academic, and industry forums throughout the world. A fervent supporter of Creative Commons since its inception – including by driving the creation of CC license add-ins for Microsoft Office documents and CC license filters for Bing image search – Tom has taught seminars at Harvard, Stanford and Yale and been a longtime fellow at the Stanford Center for Internet and Society."

Also, please update his photo with the attached image. Thanks.
![tom rubin](https://cloud.githubusercontent.com/assets/8919701/12514586/1173f554-c0f2-11e5-8c8c-159da0d7c4b1.jpg)

**Comment by mattl** [comment]
I think you were doing this, pardon if not the case

**Comment by robmyers** [comment]
I have updated Tom's bio and picture.
