### ISSUE TITLE
slidedeck embeds do not display on https://creativecommons.org/education/

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#216]

**Comment by mattl** [comment]
Are these from Slideshare?

**Comment by tvol** [comment]
@mattl i fixed the slideshare problem

**Comment by tvol** [comment]
@mattl @cablegreen but the others are some carousel thing

**Comment by cablegreen** [comment]
Thanks: @tvol  Right. @mattl There are two remaining problems:

(1) At the top - just below "Get Involved" : [SlideDeck2 id=38644 iframe=1]
(2) Below "Case Studies": [SlideDeck2 id=38628 iframe=1]

I think these broke when WordPress was updated.  Thanks for fixing.

**Comment by mattl** [comment]
Where are these presentations hosted?

**Comment by tvol** [comment]
i think it's something internal--by that i mean they're not stand alone presentations on slideshare, etc. 

isn't SlideDeck a WP plugin?

**Comment by mattl** [comment]
I'll have a look.
