### ISSUE TITLE
CiviCRM upgrade to 4.6

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#219]
Yay! Thanks. We'll table the other clean up efforts until this is in place. Aiming for end of Feb.

**Comment by mattl** [comment]
4.6 is a long term support release, so we're going to push to go live on that. I'm asking Giant Rabbit about then trying to get us onto a rolling release schedule every 6 months. If we go live on 4.7 so soon after release we'll hit bugs.

**Comment by rebeccalendl** [comment]
Status? Giant Rabbit said good to go on their end.

**Comment by mattl** [comment]
Meeting on Monday to go live on Tuesday.
