### ISSUE TITLE
Create mailing list for CC Global network strategy

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/creativecommons.org#220]
CC will conduct a strategic process for the affiliate network in 2016. The steering committee - about 15 people - will need a mailing list to conduct their work and share information. Please create a list at strategy@creativecommons.email.

**Comment by mattl** [comment]
Will anyone be able to read it or will that be only for those who are involved?

**Comment by ryanmerkley** [comment]
For now only those involved. Steering Committee may decide to open it up, which I'd be okay with, but I want them to decide.
