### ISSUE TITLE
Update CEO bio

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/creativecommons.org#221]
My bio also appears on this page: https://creativecommons.org/board/

Please update to match the one on the main /staff page.

Thanks.

**Comment by robmyers** [comment]
I have updated the text to match. Do you still want the LinkedIn etc. links on the board page or shall I remove those?

**Comment by ryanmerkley** [comment]
Just twitter pls.

**Comment by robmyers** [comment]
This was updated to just show the Twitter link.
