### ISSUE TITLE
Eric's bio on staff page

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#222]
Hey @ericsteuer  if you don't want to update your bio, then we can just move you up into staff. https://creativecommons.org/staff/  But maybe you want to update your bio or photo - that's your call.  If you are happy how it is, reassign this to Rob but if you want to change, can you drop the changes in before you assign it?

Thanks!
Mari

**Comment by mattl** [comment]
Please assign to me, as the staff page is a pain to update :)

**Comment by ericsteuer** [comment]
Title should be changed to "Director of Content and Community"
