### ISSUE TITLE
Error when merging Tags in Civi

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#223]
Screenshot:
<img width="930" alt="screen shot 2016-02-04 at 12 52 11 pm" src="https://cloud.githubusercontent.com/assets/13322149/12829355/7ed6a2da-cb3e-11e5-9f25-66dbded1e1b4.png">

Browser: 
http://whatsmybrowser.org/b/YJ73Y7S

**Comment by mattl** [comment]
Would you provide some context here? It looks like you're trying to merge the Education task (that's nested under Interests) into something else? I would advise we leave those tags alone, as they're recently created, and merge another tag into those instead.

**Comment by mattl** [comment]
It might be worth installing Firefox as well on your computer, so we can see if these problems are just confined to your version of Chrome.
