### ISSUE TITLE
Wiki Marking pages could use an update

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#224]
We're missing a case where people make structural use of CC on their business, in their headers or footers or other permanent design aspects of their sites.

See also https://github.com/creativecommons/mp/issues/51

**Comment by mattl** [comment]
I suspect we'll bring this into the website as part of the website update.

**Comment by lynkuboiak** [comment]
224

**Comment by peterspdx** [comment]
Outdated. Closing. Can reopen if this become an issue again.
