### ISSUE TITLE
creativecommons.org/blog reverts to old page 

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#229]
using chrome and firefox
<img width="1280" alt="screen shot 2016-02-12 at 12 04 30 pm" src="https://cloud.githubusercontent.com/assets/13322149/13018852/f1a57c08-d180-11e5-9ec6-53c7c32a4979.png">

**Comment by mattl** [comment]
https://creativecommons.org/weblog/ is the address the blog was at.

**Comment by rebeccalendl** [comment]
right. possible to redirect any common conventions like (cc.org/blog) to current blog? found that link in an old doc, not sure if it's floating around anywhere else. likely rare, but best to get everyone to the intended place.

**Comment by mattl** [comment]
sure, we can do it sometime.

if the published URL were doing the wrong thing, we'd fix it immediately.

**Comment by rebeccalendl** [comment]
thanks, yes I realize it's just good housekeeping but flagging so it's in the queue

**Comment by mattl** [comment]
Yep, thank you :)

You can never have too many things in the queue.

**Comment by rebeccalendl** [comment]
nope never! ;)
