### ISSUE TITLE
NC FAQ from Licnese Deed

### ISSUE THREAD

**Issue by cablegreen** [creativecommons/creativecommons.org#236]
https://creativecommons.org/licenses/by-nc/4.0/

click on: commercial purposes

takes you to: https://creativecommons.org/faq/#Does_my_use_violate_the_NonCommercial_clause_of_the_licenses.3F

should link to:

https://creativecommons.org/faq/#does-my-use-violate-the-noncommercial-clause-of-the-licenses

**Comment by mattl** [comment]
@robmyers -- my thinking here is that i'll pass all FAQ links to a script, which removes non-alpha characters and lowercases any anchors and querystrings and then redirects to the FAQ.. Sound reasonable?
