### ISSUE TITLE
3 new job postings

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#237]
I was sure the opportunities page was wp but it's not so I need help posting 3 jobs.  This should be done today if possible.  Tell me how I can help.

Mari

**Comment by mattl** [comment]
It is... I'll take a look.

**Comment by mattl** [comment]
https://creativecommons.org/wordpress/wp-admin/post.php?post=7469&action=edit

**Comment by mmoreshead** [comment]
I followed your instructions on Feb 1 to transfer my account over (thanks!) but the link above doesn't accept my CCID for login (says invalid username).  Sorry, I know this is lame.

**Comment by mattl** [comment]
Ah, sorry.

CCID is only for the blog. The website still uses the regular username/password.

**Comment by mmoreshead** [comment]
That explain it, thanks!
