### ISSUE TITLE
add cc.org/platform to main menu

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#239]
Just published a quick and dirty landing page for platforms at https://creativecommons.org/platform/. Where should we logically link to it in the menu (in the interim before website redesign)? Under Licenses, Developers? Or under Projects?

**Comment by janeatcc** [comment]
We should probably also add a link to the toolkit under Developers maybe? https://creativecommons.org/platform/toolkit/

I know, the menu is unwieldy already, but might as well as long as we have it.

**Comment by mattl** [comment]
https://github.com/creativecommons/cc-wp-theme/commit/23c58b051db9d28079057cddef0c7809545167c2
