### ISSUE TITLE
Sticker Design Change

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#241]
Hello hello!  You know our regular sticker design?  @rebeccalendl & I were thinking of printing some new ones with "i love to share" instead of "some rights reserved" but I know nothing of design.  Help?  I have the ai file if you can't find (github doesn't support the file type so wouldn't let me drop it in here).

**Comment by peterspdx** [comment]
Any thought given to letting our community help come up with designs? We used to swag logo contests. See: https://creativecommons.net/contest/.

**Comment by mmoreshead** [comment]
@rebeccalendl see the note above from @peterspdx

**Comment by mattl** [comment]
Please send the AI file to me directly, and I'll get this figured out in the next couple days.

**Comment by rebeccalendl** [comment]
@peterspdx and @mmoreshead love the idea of community support around the new shop items. we are gonna invite affiliate network and anyone to send their tshirt design files to us and we'll set up an item in the shop where customers can download and DIY their own prints from these files. trying to keep the other items fairly streamlined just due to limited capacity for merch program.

**Comment by claudioruiz** [comment]
A slide note: I've been thinking about this and it would be a great idea to reach the CC community on this. In the future, maybe we should think about ways to engage with people from our affiliated list who have in-house designers to collaborate in a more formal way with us. I don't know exactly how, but maybe in the same way we have been developing translations in the past?

**Comment by pgstacey** [comment]
I agree with Claudio, this seems like a great way to engage our global
talent pool and engage our community in forging our visual identity .
On a similar vein Sarah and I have been thinking we'd reach out to see if
anyone is interested in designing the cover for our open business models
book.

Paul

On Thu, Apr 7, 2016 at 5:57 AM, Claudio Ruiz <notifications@github.com>
wrote:

> A slide note: I've been thinking about this and it would be a great idea
> to reach the CC community on this. In the future, maybe we should think
> about ways to engage with people from our affiliated list who have in-house
> designers to collaborate in a more formal way with us. I don't know exactly
> how, but maybe in the same way we have been developing translations in the
> past?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/241#issuecomment-206882775>
>



-- 
Paul Stacey
Associate Director of Global Learning
Vancouver, Canada


We're hiring! Help us make the Commons more discoverable, usable, and
connected. Opportunities in tech, communications, and fundraising:
http://bit.ly/1OZ46OF

**Comment by mmoreshead** [comment]
Sticker file sent to @mattl 

This instance is a quick one-off special thing.  Like @rebeccalendl said, something with community involvement is on the books!

**Comment by mmoreshead** [comment]
Hey @mattl - just the gentlest nudge here :)

**Comment by rebeccalendl** [comment]
@mattl let us know if you can tackle by Wed. or if you're too swamped, please let us know and we'll go another route.

**Comment by mattl** [comment]
![g4669](https://cloud.githubusercontent.com/assets/33296/14961685/7c643096-1060-11e6-9f7a-9976bc9e8c5f.png)

**Comment by mmoreshead** [comment]
One hundred thousand thank you's!

**Comment by mattl** [comment]
[i-love-to-share-sticker.pdf](https://github.com/creativecommons/creativecommons.org/files/245592/i-love-to-share-sticker.pdf)

Here's the print quality file
