### ISSUE TITLE
all images resize to 300px wide

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#242]
even in html editor.

**Comment by mattl** [comment]
Can you attach the image here?

**Comment by janeatcc** [comment]
sure but it's not 300px. 
![openedsearchapp](https://cloud.githubusercontent.com/assets/6394777/14391141/2c4af5bc-fd6f-11e5-9d8b-957cd8aabe8c.jpg)

**Comment by janeatcc** [comment]
I need to publish a blog post in the next couple days. Will this be fixed soon? Or is there a workaround I can use
