### ISSUE TITLE
Add summary of Swedish case involving CC licenses to case law database

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#246]
Here's the text to be added -- not sure how to add it myself.

<<>>

Case name: Äventyrsgruvan i Tuna Hästberg v. Gunnarsson

Court name: SVEA HOVRÄTT

Published: 2016-02-25

Summary: Photographer licensed a photo using the Swedish port of CC BY-NC-ND version 2.5. When the photo was reused by the defendant, he attributed the company that published the photograph but not the original photographer. The case was dismissed because the plaintiff was unable to demonstrate that they owned rights to the photograph. The decision was upheld on appeal.

**Comment by mattl** [comment]
This is the CC wiki I think..

**Comment by robmyers** [comment]
Yes. Will take a look.

**Comment by robmyers** [comment]
Added, and linked from the list page:

https://wiki.creativecommons.org/wiki/%C3%84ventyrsgruvan_i_Tuna_H%C3%A4stberg_v._Gunnarsson

https://wiki.creativecommons.org/wiki/Case_Law

**Comment by mattl** [comment]
Can you document the steps to adding an issue here, so @peterspdx can add them?

**Comment by robmyers** [comment]
To adding a case law item to the wiki? Yes will do.

**Comment by robmyers** [comment]
We are looking at revising the database system, so this is no longer relevant.
