### ISSUE TITLE
access to events@creativecommons.org email address

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#248]
@mattl  can you give me access to events@creativecommons.org email address?

**Comment by mattl** [comment]
Reopening this now.

**Comment by mattl** [comment]
Okay, all set.

**Comment by mmoreshead** [comment]
Need to be able to send an email from events@ -- there are lots of available from emails in Freshdesk but sadly not events@

**Comment by mattl** [comment]
Should be all set now.

**Comment by mmoreshead** [comment]
Mucho Thank You Beaucoup.
