### ISSUE TITLE
landing page for next email outreach scheduled for Monday 5/9 AM PT

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#249]
@mattl see googledoc just shared with you

**Comment by ryanmerkley** [comment]
Why are we using a gdoc to collect PII? It looks really poor on us. I'm re-opening. Rob, can we not have a simple form that is secure and collects for us? We have other forms we've used for this.

**Comment by mattl** [comment]
@ryanmerkley We can, I queried this too.

**Comment by mattl** [comment]
All we need to do is:

* Build a profile in CiviCRM, which has the fields needed (nickname, email address, a comment field -- custom field created for this)
* Add those people to a group when they complete the profile
* Copy the HTML snippet from the profile to a page on creativecommons.org which has the info OR just link from the email to the profile's public page on CiviCRM

**Comment by robmyers** [comment]
HTML for the form can be found here -

https://donate.creativecommons.org/civicrm/admin/uf/group?action=profile&gid=64

The form probably needs a better name, that can be set here:

https://donate.creativecommons.org/civicrm/admin/uf/group/update?action=update&id=64&context=group
