### ISSUE TITLE
Domain names

### ISSUE THREAD

**Issue by gwenfranck** [creativecommons/creativecommons.org#251]
The Russian domain name needs to be renewed before June 6  -  creativecommons.ru

Right place?

**Comment by peterspdx** [comment]
Yes, if the registration is in our name. Some affiliates register the names themselves and pay the fees, though under the terms of our Internet Services Policy they hold it in trust for us. Assume this is ours, in which case @mattl will renew.

**Comment by mattl** [comment]
This was done earlier today. Note in my calendar to renew next year.
