### ISSUE TITLE
Give Gwen access to John's documents

### ISSUE THREAD

**Issue by gwenfranck** [creativecommons/creativecommons.org#254]
- https://docs.google.com/document/u/2/d/1EhqSeHYaptjR1kdLhhhwqQkiX6uaaxspuwm67BKIDBU/edit
- https://docs.google.com/document/u/2/d/1BBQpW5dE2K6lpIFNf3Yb9lbO2JhiHB25DJZgF0M4TnU/edithttps://docs.google.com/document/u/2/d/1KG8I_Pc1OXwMrbXfb6DucO_XeHAVaBTMs0VHFF-jZvU/edit
- https://docs.google.com/document/u/2/d/1yOJBKxj1vSAVPSKqV5jiGPE2aVwpe6rTvpfBkj4xOf4/edit
- https://docs.google.com/document/u/2/d/1iCbkHyzLse8YRWYx686HCWE_uQkteiu8lQvFeXRfD7c/edit
- https://docs.google.com/document/u/2/d/1Am4wP7iqDUtAzq-X0Sb-WMztCKcQQyp09PAj3NfSf-Y/edit
- https://docs.google.com/document/u/2/d/1rILRp9Z_Wwj_HoesP-Q5jWtm7B9w_LV-xkK4SvKmOdk/edit
- https://docs.google.com/document/u/2/d/1Q-3YAXcpnpAWFM4UEeSr_JBgAa6gurKO91kzTk31tFo/edit
- https://docs.google.com/document/u/2/d/1Mx3Uuz4qpLwNN5m3hAEJ0tSClgVxlqMbCKtW-UgEgBs/edit
https://docs.google.com/document/u/2/d/1zCL-nIJqzjY6GZk2xaLXphgrUSPQkfSOc9JqYEMeKdE/edit
https://docs.google.com/document/u/2/d/1xj8QG9wtafcHT4oodSTlNAromcoNR8vEmCFowzlvlHI/edit
https://docs.google.com/document/u/2/d/1H0h_YIe6q4Sng9oFWpCucIqBBM8lKVHMyCkIppe5eCM/edit
https://docs.google.com/document/u/2/d/1dX4FPSj2XIGOylEALv5pqaYUyajN3SE5W4H7SBLsYKE/edit

**Comment by mattl** [comment]
Okay, I've assigned *all* of John's documents to @tvol -- who can transfer these to you or give you access...

**Comment by gwenfranck** [comment]
ok, thanks @mattl . Please don't close the ticket, there might be others coming soon.

**Comment by mattl** [comment]
I won't close it, I'm going to unsubscribe from it as @tvol has all of John's documents now. If you need anyone else's documents (unlikely) but you can ask them directly, or make a new ticket if they've left too..

**Comment by tvol** [comment]
done
