### ISSUE TITLE
VM(s) for API and Deeds

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#255]
We discussed moving the Deeds and API (and the SemWeb stuff) to a separate server and proxying them via the main site.

Does this still sound like a good idea? Should we create a couple of VMs and implement this for the new site?

**Comment by mattl** [comment]
Yeah, this is a good idea. I made a start on this last week. Let's get it done this week

**Comment by peterspdx** [comment]
I don't see any downside, but alert me if there's something I may not be aware of especially wrt the deeds.

**Comment by mattl** [comment]
Built and salted.

**Comment by robmyers** [comment]
These are now in place and reverse proxied.
