### ISSUE TITLE
Programs not linking to a page

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#257]
Thanks for reporting an issue, to help us file this efficiently we made this template. Feel free to ignore the template if you wish :) 

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here: 

https://staging.creativecommons.org/about/

![screenshot from 2016-06-21 14-02-34](https://cloud.githubusercontent.com/assets/33296/16242606/d8b60660-37b8-11e6-804c-f827170a309f.png)

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @mattl

**Comment by little-wow** [comment]
fixed
