### ISSUE TITLE
Resolve and redirect different urls for platform pages

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#258]
Platform page is currently at https://creativecommons.org/platform/ .. new staging puts it at https://staging.creativecommons.org/about/platform/ .. Let's make sure both direct to the same place once launched.

Also for toolkit, it currently sits at https://creativecommons.org/platform/toolkit/ .. new staging puts it at https://staging.creativecommons.org/about/platform/integration-toolkit/ .. let's make sure both direct to same page

**Comment by robmyers** [comment]
There are now redirects in place from the old locations to the new.
