### ISSUE TITLE
Legal issues with term "partner"?

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#259]
@peterspdx any legal issues with wording on calling these platforms our partners? If not, let's keep. If so, we should wordsmith to "collaborate with.." for now until we can figure it out.. eg. see https://staging.creativecommons.org/share-your-work/
 
cc: @little-wow

**Comment by peterspdx** [comment]
moving this to email since it involves legal advice.

**Comment by little-wow** [comment]
I changed the language on this page: https://staging.creativecommons.org/share-your-work/

**Comment by peterspdx** [comment]
Perfect.

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC

**Comment by janeatcc** [comment]
Further edited. Closing.
