### ISSUE TITLE
"Program Areas" Structural Change

### ISSUE THREAD

**Issue by pgstacey** [creativecommons/creativecommons.org#260]
https://staging.creativecommons.org/about/program-areas/

Recommend:
- Program Areas be re-defined as per current Logic Model to be Discovery, Collaboration, and Advocacy
- Descriptions for each Program Area (Discovery, Collaboration, and Advocacy) be created based on: https://docs.google.com/document/d/10hgKxCFVHcV6afAqSWlXBjLdh5nL3PWA7tH1YxSfHSk/edit 
- To each area the specific initiatives CC has underway be added as mapped out during ITW https://docs.google.com/document/d/1LgX4uWfG_7AXCBklw1B4MmIN5_EUKpOCEppNoIXn7vE/edit 
- What is currently called Program Areas be renamed to Impact Areas
- Each Impact Area be structured to have three parts: 1. description of what the area is all about, 2. real examples from the field, 3. projects CC HQ and/or Affiliates have underway

**Comment by ericsteuer** [comment]
good stuff. ryan will need to be involved in this. will come back to this post soft launch and resurface.
