### ISSUE TITLE
Add link to FAQ on right hand side of main page under In This Section

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#263]
And please change color of link to FAQ at bottom of page so that it stands out separate from the contact information that is just below it.

**Comment by robmyers** [comment]
The link has been addded to the right hand side of /about/ (thank you @little-wow for explaining what was required!).

**Comment by robmyers** [comment]
@ageeroms please can the FAQ link in the footer be visually differentiated from the contact links about it?

**Comment by mattl** [comment]
I made the footer link different
