### ISSUE TITLE
why do we have "website by affinity bridge" text on front page?

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#264]
I don't think we need that, and it gives real estate to a third party. Suggest removing.

**Comment by mattl** [comment]
@peterspdx I know this was in the contract, I think we chose to scrub it and put it on the donors page?

**Comment by mattl** [comment]
Okay, removed here https://github.com/creativecommons/new-www-theme/commit/ea5b1378399f2159278e365c52f0fac124178ac2 and  I'll figure out where it goes on the site.

**Comment by peterspdx** [comment]
Please, someone do tell AB. We can change it again, but as a courtesy it should be communicated that at least for the soft launch X location is where it will appear.
