### ISSUE TITLE
someone is missing on the page with the board members

### ISSUE THREAD

**Issue by paul2keller** [creativecommons/creativecommons.org#268]
https://staging.creativecommons.org/about/team/#our-board
![screen shot 2016-06-22 at 10 20 34](https://cloud.githubusercontent.com/assets/5593766/16259457/1ad77dd0-3863-11e6-880c-f4d1eca8a8ad.png)

**Comment by peterspdx** [comment]
And several members of the advisory council are also missing. Here is the composition through 2016:

Joi Ito, Larry Lessig (Chair), Mohamed Nanabhay, Spencer Hyman, John Abele, Brian Fitzgerald, Sue Gardner, Jimmy Wales, Annette Thomas, Cathy Casserly, Ryan Merkley, Hal Abelson, Michael Carroll, Laurie Racine, Eric Saltzman, Molly Van Houweling, Esther Wojcicki

**Comment by peterspdx** [comment]
Also, Kate Spelman's bio is out of date, she is no longer with K&L Gates. I've asked her to send updated text.

**Comment by little-wow** [comment]
That's very strange-- I added all those people. (I realize that the images
are blurry) Let me look, and sorry Paul!

On Wednesday, June 22, 2016, Diane Peters <notifications@github.com> wrote:

> Also, Kate Spelman's bio is out of date, she is no longer with K&L Gates.
> I've asked her to send updated text.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/268#issuecomment-227714574>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGw-TrTaR7H_OJaiY1XJKx_ws9eRwOGaks5qORpJgaJpZM4I7hOv>
> .
>


-- 
---
Jennie Rose Halperin
Communications Manager
Creative Commons
Invest in an open future. Support Creative Commons today:
http://bit.ly/19IjSKl

**Comment by peterspdx** [comment]
I don't see even blurry images for those missing from the advisory council page. Thanks for helping correct those omissions @little-wow

**Comment by peterspdx** [comment]
@little-wow 

Here is updated text for Kate's bio on the board page. 

Katherine C. Spelman is a Shareholder at Lane Powell and focuses her practice on copyright and digital publishing.  She has more than 30 years of experience advising clients on cutting-edge copyright matters, and provides strategic advice, design and implementation counsel for large, mid-sized and startup companies, including those engaging in personal digital devices and wireless technology. Kate is a frequent speaker and author on the progress of emerging copyright and digital publishing issues and is a member of the Board of Trustees for the Copyright Society of the USA. Kate received her J.D. from the University of Wisconsin Law School and her B.A. in Classics and Latin from the University of Michigan.

**Comment by little-wow** [comment]
@mattl my admin status was revoked somehow and now I can no longer edit that page

**Comment by mattl** [comment]
@ageeroms Paul is marked as being in the board group on the site, but isn't showing up. 

Also, there are various members of the advisory board missing.

I've updated Kate's bio.

**Comment by ageeroms** [comment]
Hey folks, @little-wow i working on content entry here, so missing folks are her department, unless adding someone does not cause them to appear?

Folks are listed alphabetically by last name, so Paul Brest is first in featured section at the top and also in the 3rd position of the first row of board members. @mattl , is that the Paul you mean?

**Comment by mattl** [comment]
Paul Keller -- has a user profile in WordPress, is checked as board member... doesn't appear on the site.

**Comment by little-wow** [comment]
@ageeroms it's the latter, and also I don't have access to the admin panel anymore, so I can't add people

**Comment by mattl** [comment]
@little-wow We can get you admin access for today :)

**Comment by ageeroms** [comment]
@mattl , I previously escalated Jennie's permission to administrator re
editing widgets and users. But that was reverted. Is that due to CCID?

Alos, Paul isn't showing because the Group "Our Board" was not checked.
I've changed.

On Wed, Jun 22, 2016 at 9:52 AM, Jennie Rose Halperin <
notifications@github.com> wrote:

> @ageeroms <https://github.com/ageeroms> it's the latter, and also I don't
> have access to the admin panel anymore, so I can't add people
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/268#issuecomment-227806545>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGXZDm7D0QF8NZLCMLqDIyhxYSci44NTks5qOWhVgaJpZM4I7hOv>
> .
>



-- 
Anna Geeroms | Business Analyst
Affinity Bridge

http://affinitybridge.com
T. 604.569.0510 | E. anna@affinitybridge.com

710 - 207 W. Hastings St.
Vancouver, BC
V6B 1H7

**Comment by mattl** [comment]
Bizarre. I had checked it... okay. well, Jennie can add the remaining people now.

**Comment by little-wow** [comment]
All board members are added. Better photos to come
