### ISSUE TITLE
Text change to https://staging.creativecommons.org/share-your-work/licensing-types-examples/public-domain/

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#269]
https://staging.creativecommons.org/share-your-work/licensing-types-examples/public-domain/

Under the CC0 description, change:

"Use this universal tool if you are a holder of copyright or database rights, and you wish to waive all of your interests in your work worldwide."

to

"...., and you wish to waive all of your interests that may exist in your work worldwide."

**Comment by peterspdx** [comment]
Hit publish too quickly. Additionally, on that same page after the edited sentence mentioned above, add this additional sentence as part of the same paragraph:

Because copyright laws differ around the world, you may use this tool even though you may not have copyright in your jurisdiction, but want to be sure to eliminate any copyrights you may have in other jurisdictions. Let me know if you have questions.

**Comment by peterspdx** [comment]
(and the Let me know if you have questions shouldn't be part of the added text, it's a message to jennie :-))

**Comment by little-wow** [comment]
@peterspdx is this still an issue?

**Comment by peterspdx** [comment]
Yes, I have been out and haven't had time to make the change. Please feel free to go ahead @little-wow

**Comment by little-wow** [comment]
done
