### ISSUE TITLE
Give Diane permission to edit: https://wiki.creativecommons.org/wiki/CC0_FAQ

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#271]
I'm signed in, but have lost privileges to edit these FAQs. Probably elsewhere as well, but for now this one is important.
@mattl @robmyers 

Noting here that I seem to have lost the ability to also assign issues to mattl. No idea! So mentioning you both here instead. Thanks!

**Comment by mattl** [comment]
Hey Diane,

You should be able to assign to me. Perhaps something was not working earlier, but feel free to try again. We'll get this fixed for you ASAP, but given the site launch later today, it'll probably be tomorrow.

**Comment by peterspdx** [comment]
Here's the text doc with changes and additions marked. let me know if you have questions. Thanks so much mattl!
[CC0 FAQ tweaks.docx](https://github.com/creativecommons/creativecommons.org/files/328227/CC0.FAQ.tweaks.docx)

**Comment by peterspdx** [comment]
PS mattl: ok if tomorrow or even Friday. Just want these made in this initial round of changes. They've been in the wings for a bit. Appreciated.

**Comment by mattl** [comment]
Can you confirm your username on the wiki?

**Comment by peterspdx** [comment]
peterspdx

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC

**Comment by robmyers** [comment]
@peterspdx please try now and let me know how you get on.
