### ISSUE TITLE
Text Change: https://staging.creativecommons.org/choose/zero/

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#272]
@little-wow 

Here is revised text for the first three paragraphs of this page.
[Text changes to choose zero.docx](https://github.com/creativecommons/creativecommons.org/files/328024/Text.changes.to.choose.zero.docx)

**Comment by peterspdx** [comment]
@little-wow I would be happy to make the text changes myself, but i don't seem to have authorization.

**Comment by mattl** [comment]
Rob or I will have to do this, as the chooser is not in WordPress.

**Comment by peterspdx** [comment]
Thanks, as with other changes it's not urgent for today but we do want these small tweaks incorporated with the general roll out of the new site as they're important for some adopters. Appreciated mattl!

**Comment by little-wow** [comment]
I think this issue is resolved. Reopen if it's not!
