### ISSUE TITLE
Ask board for new photos

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#277]
Thanks for reporting an issue, to help us file this efficiently we made this template. Feel free to ignore the template if you wish :) 

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here:

Please tell us the steps to reproduce the problem, if needed:

1.
2. 
3. 

Please tell us a little bit about how you're accessing the site or page, such as which web browser and which version of the browser:

(You can also vist https://aboutmybrowser.com/ which will give you a link you can share with us that'll tell us everything we need to know)

You can also attach a screenshot to this issue if you have a visual bug to report. That'll help us figure it out faster. http://www.take-a-screenshot.org/ has instructions on taking screenshots.

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @mattl @little-wow

**Comment by mmoreshead** [comment]
I can reach out and see if any of them have updated photos for us if you like @mattl and @little-wow

**Comment by little-wow** [comment]
@steuer is handling this I think

On Thursday, June 23, 2016, Mari Moreshead <notifications@github.com> wrote:

> I can reach out and see if any of them have updated photos for us if you
> like @mattl <https://github.com/mattl> and @little-wow
> <https://github.com/little-wow>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/277#issuecomment-228049455>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGw-TsUecjjlOhrGEtcp1CjGaOgixJlEks5qOon6gaJpZM4I8FB->
> .
>


-- 
---
Jennie Rose Halperin
Communications Manager
Creative Commons
Invest in an open future. Support Creative Commons today:
http://bit.ly/19IjSKl
