### ISSUE TITLE
Google Analytics event tracking

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#278]
https://github.com/creativecommons/new-creativecommons.org/issues/16

**Comment by mattl** [comment]
@ageeroms has asked for these events only to be tracked:

click donate button in header
click donate in footer
complete donation via form on donate page
sign up for newsletter on homepage
sign up for newsletter in sidebar inside page
I think we currently have a lot more GA events on the CC page, and I would like to be able to track user flow in addition to knowing who donated. I can begin by adding GA to these events as per Anna's screenshot, but I'd like more info on where GA is/will be added, etc, etc. I feel like I was brought in late to this and possibly don't understand how we're going to be using GA for this page.

**Comment by mattl** [comment]
@little-wow , per my email here are the instructions for configuring the event tracking on forms:

Once this plugin is activated, you can browse to the Gravity Forms settings and find a new sub-menu item called Event Tracker. There, you will enter your Google Analytics Tracking Code.

The plugin provides some default event categories, labels, and actions. You can override these per form by going into the individual form's settings.

Within Google Analytics, you will want to set up an event-based goal and match the event label, event category, and event action with the ones you set up.

On each form, you need to make sure to setup an Event Tracking Feed. Open each forms settings, go to the "Event Tracking" section, and set one up. Leave the fields blank to use the default values.

**Comment by ageeroms** [comment]
I confirmed that events are being tracked in Events Overview in Analytics. Check event label. So phew, something is being tracked.

**Comment by little-wow** [comment]
So tracking code appears to be on across the site in GA-- these are the only tracking settings I could set (tracking code is hidden by me)

<img width="872" alt="screen shot 2016-06-30 at 11 31 09 am" src="https://cloud.githubusercontent.com/assets/7093838/16494176/4d604544-3eb6-11e6-9c96-62eae7dc58ed.png">

**Comment by ageeroms** [comment]
@mattl @little-wow, here are the instructions from the developer for deeper
configuration of the GF Event tracker:
https://github.com/ronalfy/wordpress-gravity-forms-event-tracking . Besides
the location you screen-shotted, the plugin adds an Event tab to the
configuration of each form. Please review and poke Mack or Robin if you
need support.

Thanks,
Anna

On Thu, Jun 30, 2016 at 8:32 AM, Jennie Rose Halperin <
notifications@github.com> wrote:

> So tracking code appears to be on across the site in GA-- these are the
> only tracking settings I could set (tracking code is hidden by me)
>
> [image: screen shot 2016-06-30 at 11 31 09 am]
> <https://cloud.githubusercontent.com/assets/7093838/16494176/4d604544-3eb6-11e6-9c96-62eae7dc58ed.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/278#issuecomment-229696273>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGXZDtwE65viJK72S9QqFoe-IdRYOt2Tks5qQ-GJgaJpZM4I8FDA>
> .
>



-- 
Anna Geeroms | Business Analyst
Affinity Bridge

http://affinitybridge.com
T. 604.569.0510 | E. anna@affinitybridge.com

710 - 207 W. Hastings St.
Vancouver, BC
V6B 1H7

*Vacation Advisory: I'm out of the office July 1- 8, returning to the
office on Monday, July 11.*

**Comment by little-wow** [comment]
@robmyers can we go over how to pull this data?
