### ISSUE TITLE
Spacing is off in list of platforms

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#279]
![](https://cloud.githubusercontent.com/assets/7093838/16254612/925d96e0-37f6-11e6-976a-7b6ab1e90c06.png)

**Comment by ageeroms** [comment]
@mattl this has been corrected: 

![screen shot 2016-06-23 at 11 25 14 am](https://cloud.githubusercontent.com/assets/6674702/16314967/2f61ca8a-3935-11e6-9e85-ef9867084ec8.png)

please confirm/close. Thanks!
