### ISSUE TITLE
CSS bug on the license chooser

### ISSUE THREAD

**Issue by Aeva** [creativecommons/creativecommons.org#28]
As the designer of the new license chooser, this has been bugging me for a while:

The div elements of id "freedoms" and "license" should have the style attribute read "min-height: 348px" instead of "height: 294px", such that the arrow pointing from the freedoms box to the license box points to the middle of the circle icons.  (this broke when the update to 4.0 removed the license jurisdiction field).

I'll gladly submit a patch if need be, though I can't seem to find the repository for cc.engine...?

**Comment by mattl** [comment]
This will be a good starter issue for you, Rob.

**Comment by Aeva** [comment]
@robmyers I'll be happy to answer any questions about the license chooser if you need it.  My handle on freenode is "aeva" if that is a better way of getting in touch.

**Comment by robmyers** [comment]
@aeva Thank you! I've implemented your suggestions and committed the changes.

**Comment by Aeva** [comment]
^_____________^ thanks!

**Comment by mattl** [comment]
+1
