### ISSUE TITLE
Staff - Paul Stacey Description

### ISSUE THREAD

**Issue by pgstacey** [creativecommons/creativecommons.org#280]
Not urgent but current description is very out of date.
https://staging.creativecommons.org/author/pstaceycreativecommons-org/

Recommended changes

Below picture:
Paul supports adoption and use of Creative Commons.

To right of picture below name:
Paul helps government, organizations, and businesses around the world adopt Creative Commons based open policy, business models, and practices. Paul excels at facilitating and supporting groups in defining strategies and implementation practices for Creative Commons use. He is an advocate for  the commons as a means of maximizing citizen participation in culture and creating a more equitable and sustainable economy.

Paul has over 25 years of technology, online learning, and open education experience in both the public and private sectors. Prior to Creative Commons Paul helped found BCcampus and its open education initiative. Paul holds four degrees including an MEd in Adult Learning and Global Change. He lives just outside Vancouver Canada where he enjoys gardening and the Pacific Northwest wilderness.

**Comment by little-wow** [comment]
you're good @pgstacey
