### ISSUE TITLE
Typo in the donation form

### ISSUE THREAD

**Issue by fmann** [creativecommons/creativecommons.org#282]
1. Start a donation
2. Select a custom one-time amount.
3. Click "Next" and notice that it says " (monthly)" at the top of the screen.

https://github.com/creativecommons/new-www-plugin/blob/master/cc-donate/cc-donate.php#L105

Should say " (one-time)" rather than " (monthly)".

**Comment by fmann** [comment]
Fix committed. Pull request issued here:

https://github.com/creativecommons/new-www-plugin/pull/4

**Comment by ageeroms** [comment]
@mattl this is an important fix, as it could cause people to be confused and abandon donation process if not applied. Could you please take a look, when you get a second?

**Comment by mattl** [comment]
This has been applied to the site. Sorry, didn't see this... @creativecommons/affinity-bridge should be able to assign tickets to people on this repo. I fixed that last
