### ISSUE TITLE
Site Footer "We'd love to hear from you!" content formatting

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#284]
On e.g. https://creativecommons.org , when you view the footer, Frequently Asked Questions is white with no hover state. This was a change made by @mattl to address a request from @peterspdx regarding need to emphasize FAQ relative to the other possible ways to connect.

I spoke with our designer and she suggested these two options:
1. add hover state (underline) on FAQ to be consistent with "We'd love to hear from you" 

![screen shot 2016-06-22 at 3 28 11 pm](https://cloud.githubusercontent.com/assets/6674702/16286138/588a7214-388f-11e6-9a2e-f7faca68604e.png)

OR
1. adjust the FAQ to be blue with white hover state.

![screen shot 2016-06-22 at 3 27 19 pm](https://cloud.githubusercontent.com/assets/6674702/16286142/5dbc8844-388f-11e6-8e89-f271f2266e42.png)

In either case, we think email and phone should be grey to de-emphasize those options, to show clear priority for that information and keep the footer a little calmer.

@peterspdx which is your preference?

**Comment by peterspdx** [comment]
I don't feel too strongly, but slightly prefer the blue because it stands out more from the text above with other ways to contact CC. Agree on de-emphasizing the other ways to contact CC. Indeed, I have to wonder about having a phone number there at all, but that's a side point.

Thanks for working this with the designer

**Comment by ageeroms** [comment]
@mattl , please assign to @DylanMcCall 

Dylan, please implement the following:

1. remove inline coding on Frequently Asked Questions 
2. change Frequently Asked Questions to blue with white hover state
3. make email and phone grey, like address above, with white hover state

Thanks!
