### ISSUE TITLE
Mobile alignment issue

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#287]
Screenshot attached, but arrow is floating off the screen.  iPhone 5, Safari

![img_0230](https://cloud.githubusercontent.com/assets/7093838/16287464/1ade5864-3898-11e6-858a-1e0cf71f8820.PNG)
![img_0231](https://cloud.githubusercontent.com/assets/7093838/16287466/1c4448bc-3898-11e6-9990-b0d80d4e72b0.PNG)

**Comment by DylanMcCall** [comment]
Thanks for reporting this. We spotted it a little earlier, too, and I fixed it in this commit: https://github.com/creativecommons/new-www-theme/commit/80dfec3c48f2d2fcca1705aa5ed3c1b9bb2cb388

Hopefully the updated theme branch can be pulled on production soonish.

**Comment by robmyers** [comment]
I've deployed the changes on production.

The alignment looks OK on my phone now.
