### ISSUE TITLE
Amazon Store Missing in Action

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#288]
I noticed that when I visit http://creativecommons.org/discover/gift-guide/ , that is not resolving to the Amazon store. 

Actions to replicate:
1. Visit http://creativecommons.org/discover/gift-guide/
2. See WP 404, "Oops! That page can’t be found."

I'm wondering if it was lost in the shuffle? Ideally, it would receive the new static template, so I was just checking to see if that was in place.

@mattl

**Comment by robmyers** [comment]
The gift guide is a build of this Jekyll-based site:

    https://github.com/creativecommons/gift-guide

so it needs re-theming to match the new site. Take a look at the version I've restored on staging to see the problem.

We should probably either re-create it in WordPress or just remove any mentions to it for now.

**Comment by ageeroms** [comment]
@fmann , can you look into this. I think we need to get a sense of how much work this is to determine if it can go under maintenance or needs an estimate.

**Comment by fmann** [comment]
This is one page of rarely updated markup. This seems precisely what a CMS is for.

**Comment by robmyers** [comment]
Yes if we're going to keep the page rather than remove it then it should be recreated in WordPress.

**Comment by robmyers** [comment]
At this point in the year we might be best off replacing it with a new one for this holiday season. :-)

**Comment by robmyers** [comment]
Change this to a redirect. See #507 .

**Comment by kgodey** [comment]
We no longer reference this URL anywhere AFAIK so I'm closing this issue.
