### ISSUE TITLE
Too many emails generated by contact form or otherwise?

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#290]
If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here: https://creativecommons.org/about/contact/

1.  This form sends an email to info@ (Freshdesk) -- this is no problem
2. info@ gets an email every time someone signs up for the newsletter
3. info@ also gets an email every time someone makes a donation

So I don't know if 2 and 3 are supposed to trigger an action on my part.  I think no?  Still, I doubt that everyone who signs up for the newsletter wants to get a "A ticket has been opened" email from FD, same goes for donors.  

Not sure there's really a problem here or not, but thought I ought to flag it.

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @mattl

**Comment by mmoreshead** [comment]
Also want to make sure this isn't causing the same problem as the old google groups (that I mark spam and the marked is CC instead of the spammer).

**Comment by mattl** [comment]
I will stop the last two.

**Comment by mattl** [comment]
Let me think about the spammer thing.

**Comment by mattl** [comment]
I'm not sure what marking as a spammer in Freshdesk does -- does it just block them, or does it report them...

**Comment by mattl** [comment]
Freshdesk case opened.

Regarding number 2 and 3, they were going to the webmaster queue, so they shouldn't be getting a confirmation email.

**Comment by mmoreshead** [comment]
Awesome, thanks @mattl
