### ISSUE TITLE
 some /licenses urls are broken

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#291]
An email from info@:

* Currently getting HTTP 503 errors seemingly on all paths beginning with
`/licenses/`, e.g.:
https://creativecommons.org/licenses/by/3.0/us/legalcode
https://creativecommons.org/licenses/
https://creativecommons.org/licenses/by/4.0/

* On "Share your work > Licensing types"
(https://creativecommons.org/share-your-work/licensing-types-examples/)
there are names of license types (e.g. "Attribution") that are links, and
update the URL fragment ID, but don't otherwise appear to do anything. This
is in Win 7 / Chrome 51 with JS enabled.

* If I click to "What we do > Program areas > Legal tools / licenses" I get
an essentially blank page. Same thing if I click to "Legal tools / licenses
resources". 

---------------------

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @mattl

**Comment by mmoreshead** [comment]
Actually maybe all of them.

**Comment by peterspdx** [comment]
Can you please keep peterspdx apprised?

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC

**Comment by mmoreshead** [comment]
@mattl is working on it right now.

**Comment by mmoreshead** [comment]
Meant to also flag that to @peterspdx

**Comment by mattl** [comment]
They're all back. Apache (the webserver) had stopped. We'll put in a check for that and have it bring itself back if that happens.

**Comment by robmyers** [comment]
@mattl I'm assigned to add the check?

**Comment by mattl** [comment]
We should probably use monit. Let's worry about that soon, for now let's keep an eye on it.

**Comment by robmyers** [comment]
OK. :-)

**Comment by mmoreshead** [comment]
I think they're down again @robmyers @mattl

**Comment by robmyers** [comment]
@mattl licenses.production is not happy, I can't ssh to it.

**Comment by robmyers** [comment]
@mmoreshead In the original report, the second issue (On "Share your work > Licensing types") is a design one - who is best to report that to?

**Comment by mmoreshead** [comment]
@mattl and @robmyers Licenses now are 404 not found :(

**Comment by mmoreshead** [comment]
They're back!  Yay!
