### ISSUE TITLE
CC zero deed not found

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#292]
Hello! The CC0 license summary link seems broken: https://creativecommons.org/publicdomain/zero/1.0/ … (linked from https://creativecommons.org/share-your-work/licensing-types-examples/public-domain/cc0/ …). Has it moved?

nickstenning on Twitter.

---

I suspect we're not proxying it correctly since yesterday trying to get the legalcode deeds to work?

**Comment by robmyers** [comment]
One of the redirects is rewriting:

    https://creativecommons.org/publicdomain/zero/1.0/

to:

    https://creativecommons.org/share-your-work/public-domain/zero/1.0/

Investigating.

**Comment by robmyers** [comment]
@mattl I've changed the redirect and restarted Apache. Do we need to flush a cache?

**Comment by mattl** [comment]
@robmyers Is that URL being proxied to the licenses box?

**Comment by mattl** [comment]
It doesn't look like it is.

**Comment by robmyers** [comment]
@mattl Yes that was the problem now. Thank you. I've added the proxy configuration, it works once the browser cache is cleared.
