### ISSUE TITLE
Update to Stripe Receipt Customer Email

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#294]
Stripe says:

_To customize things a bit further, you can upload a custom logo and specify some basic details about your business from the emails section (https://dashboard.stripe.com/account/emails) of your account settings. Using your logo’s colors, we’ll automatically detect the optimal header color for your receipts, however you may override this setting by specifying a hexadecimal (hex) color reference for the header on your receipts. The largest file size permitted for a custom logo image is 524kb. For best results, we recommend that your logo is a square image larger than 128 x 128 pixels. JPG, PNG, and GIF file types are supported._

_As a note, we’ll only send email receipts for payments that are made with your live API key or through your live dashboard. If you’d like to see what a test email receipt looks like, you can click the “View Receipt” link on a live or test payment’s page. You can also send a test email from your email settings._

Could you please try adding the square logo attached and setting the hex colour to #ee5b32 ?

I'm hoping that will set the blue band to orange and and logo to white.

I've also included a rectangle logo, in case that works better. Try sending a test email per their instruction to confirm that it looks OK. https://dashboard.stripe.com/account/emails

![cc-logo](https://cloud.githubusercontent.com/assets/6674702/16310571/ea99ac28-3921-11e6-8da3-cc5c6bfe4e47.png)
![creative-commons-logo](https://cloud.githubusercontent.com/assets/6674702/16310572/eaaac8c8-3921-11e6-927b-e8650180cf35.png)

@rebeccalendl

**Comment by mattl** [comment]
We'll need to get you access from @Scott-CC

**Comment by ageeroms** [comment]
@mmoreshead any action on this ticket? I think the objective was to upload a couple of images to make receipts from the store look nicer. Please let me know if it's helpful for me to connect with Scott via email? thx

**Comment by mmoreshead** [comment]
Hi @ageeroms -- totally missed this, I'm sorry.  You'll have to reach out to Scott for this, I can't help. Sorry :(

**Comment by rebeccalendl** [comment]
Leaving all payment processor notifications generic. Will send personalized TY notes from CC via mailchimp.
