### ISSUE TITLE
Transfer two missing posts

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#297]
https://blog.creativecommons.org/2016/06/13/tell-european-commission-fixcopyright/ and https://blog.creativecommons.org/2016/06/16/new-chilean-law-make-harder-authors-freely-share-audiovisual-works/ are two posts that got missed being transferred. Please add them.

**Comment by little-wow** [comment]
@mattl my fault for not getting to this sooner, but Wayback Machine didn't archive the second post and blog.cc.org is down...  I got the first one up but the second I can't find. Help?

**Comment by tvol** [comment]
i fixed it https://creativecommons.org/2016/06/16/new-chilean-law-make-harder-authors-freely-share-audiovisual-works/
