### ISSUE TITLE
Update Supports List

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#298]
@mattl , I missed grabbing the last copy of /supporters. I see that there are few missing when I compare the list I see on the wayback machine https://web.archive.org/web/20160616051646/https://creativecommons.org/supporters/ to production https://creativecommons.org/supporters . Can you please update?

**Comment by ageeroms** [comment]
[supporters.txt](https://github.com/creativecommons/creativecommons.org/files/330510/supporters.txt)

**Comment by mmoreshead** [comment]
I added Fort Worth Criminal Defense Attorneys and linked to https://www.versustexas.com  on June 13th but I don't see it now.

**Comment by little-wow** [comment]
done

**Comment by ageeroms** [comment]
@rebeccalendl please confirm that the folks all look to be there now? Also, question does https://creativecommons.org/supporters/additional-supporters-2015/ look to be current version?

**Comment by rebeccalendl** [comment]
Yes, the Supporters page is looking great to me now. Thanks all. Re: that Additional Supporters page, it isn't active and can be archived. It was originally part of a move to visually separate and highlight higher level donors, but ended up deciding to leave all on a single Supporters page.

**Comment by ageeroms** [comment]
@mattl I think this ticket can be closed. Thanks all!
