### ISSUE TITLE
404s for Public Domain

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#299]
I noticed a bunch of 404s in relation to Public Domain in Google Analytics, e.g. 

https://creativecommons.org/404.html?page=/share-your-work/public-domain/zero/1.0/&from=

Public Domain is located at https://creativecommons.org/share-your-work/licensing-types-examples/public-domain/ now, which i think was changed quite recently. So maybe a redirect is needed?

Also, on https://creativecommons.org/share-your-work/licensing-types-examples/public-domain/ , the Use This Tool does to 404 and I'm not sure where that should be pointed?

@mattl

**Comment by mmoreshead** [comment]
@ageeroms issue is here I think https://github.com/creativecommons/creativecommons.org/issues/292

**Comment by robmyers** [comment]
Oh from a design point of view I missed the import of this.

The pages about the licenses and public domain in genreal at /licenses/ and /publicdomain/ should probably redirect to the pages in /share-your-work/ *but* the license deeds and PD deeds are in subdirectories of /licenses/ and /publicdomain/, and we can't change that without breaking the Internet. :-)

So as per #292 , I've removed the redirect and restored access to the PD deeds under /publicdomain/ .

I personally would like to switch to the new /share-your-work/ pages for the descriptions, but we should talk about where things should go in the site hierarchy (with apologies for missing this until now). @mattl and @peterspdx what do you think?

**Comment by mmoreshead** [comment]
@robmyers  It's still redirecting to https://creativecommons.org/share-your-work/public-domain/zero/1.0/ which has a Oops! That page can’t be found. message.

**Comment by mmoreshead** [comment]
Also the CC0 waiver is broken but maybe that should be a new issue or maybe it's because of this issue?  https://creativecommons.org/choose/zero/waiver

**Comment by robmyers** [comment]
Oh this is the trailing slash problem. Thank you for reporting it. Looking...

**Comment by robmyers** [comment]
Ah, no, my mistake. There was a bad redirect I missed. That's fixed now, thank you for reporting it.

**Comment by robmyers** [comment]
@mmoreshead Please can you create a new issue for that and ping mattl regarding it? Thank you.

**Comment by mmoreshead** [comment]
Done and done, thanks @robmyers!

**Comment by robmyers** [comment]
@mmoreshead Thank you! :-)

**Comment by mattl** [comment]
I believe this is fixed
