### ISSUE TITLE
Chooser looks bad

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#300]
@mattl when I try to use the chooser on my iphone 6s, I find the radio buttons too small to click, with the first one being considerably smaller than the others.

![img_2128 1](https://cloud.githubusercontent.com/assets/6674702/16315835/bc4e5104-3938-11e6-80ed-023288be24b3.jpg)

I think they may be smallish on the other forms on the site as well, thought I hadn't noticed a size inconsistency. Perhaps a global update to the size is in order?

Please let us know if you'd like us to make a theme update to address this.

**Comment by ageeroms** [comment]
@robmyers , I think this bug is still open. Please let us know if you'd like our team to help.

**Comment by little-wow** [comment]
Still open on iPhone 8
