### ISSUE TITLE
Icons are different sizes on mobile

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#303]
![img_0240](https://cloud.githubusercontent.com/assets/7093838/16317035/11a549aa-393e-11e6-804b-8445bd20d337.PNG)
![img_0241](https://cloud.githubusercontent.com/assets/7093838/16317038/12f3ed0c-393e-11e6-8f1d-427e05b99c4d.PNG)

iOS iphone 5s on Safari, but it looks the same on Android too

**Comment by mattl** [comment]
So they're smaller on longer lines of text...

**Comment by little-wow** [comment]
I'm not sure if it's consistent, and also the word "Technolog-y"

**Comment by ageeroms** [comment]
@little-wow please assign to @DylanMcCall 

Dylan, can you please take a look at this issue? Though reported on 5s, I just realized that the new iphone SE is the same resolution as 5s, so it would be good to take a quick look.
