### ISSUE TITLE
Lots of things overlap when the webfont isn't loaded

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#305]
For privacy reasons, many people block webfonts loading from Google.

We should move any resources we want to load to ccstatic.org

![clqicxnugaaw2a-](https://cloud.githubusercontent.com/assets/33296/16320351/ddd9e210-395c-11e6-9696-62fded916f78.jpg)

**Comment by mattl** [comment]
I think there's two pieces of work here.

1. Bringing the web font over to our server. 
2. Ensuring things can degrade nicely without the font.

**Comment by mattl** [comment]
![screenshot from 2016-06-23 16-17-22](https://cloud.githubusercontent.com/assets/33296/16320569/0aeb12e6-395e-11e6-9e78-ff33cd3921fb.png)
![screenshot from 2016-06-23 16-17-20](https://cloud.githubusercontent.com/assets/33296/16320570/0af800a0-395e-11e6-8ba7-7f97c40fc208.png)

Things seem a lot more graceful in Chromium. 

To reproduce, install the Privacy Badger extension, and disable anything on the page that isn't from Creative Commons.

**Comment by mlissner** [comment]
If you were self-hosting the file, I wouldn't worry about the graceful degradation, personally.

**Comment by ageeroms** [comment]
The site has a lot of CSS that depends on the specifics of the font being used, which comes from fonts.google.com. Moving the font onto your server is a good idea.

We could provide some support narrowing down the particular font faces you need to serve (looks like right now we've selected a lot), and if you need help finding where in the theme to change where they come from, please let us know.

We also thought of adding Arial Narrow to your the font stack ahead of Sans Serif, which could help with degradation.

**Comment by dhruvkb** [comment]
Linking to the [CC fonts](https://github.com/creativecommons/vocabulary/tree/master/packages/fonts) package for future reference.
