### ISSUE TITLE
Spelling error on staff page

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#306]
Naeema's first name misspelled in two spots:

https://creativecommons.org/about/team/
https://creativecommons.org/author/naeema/

**Comment by little-wow** [comment]
I fixed her name, but her username can't be changed, so the URL is still naeema.  I don't have the original of her photo, so if I were to reupload it, it would be blurry.

**Comment by mmoreshead** [comment]
Happy to share a copy of her photo.  
![naeema z](https://cloud.githubusercontent.com/assets/11162279/16321683/4972968e-396c-11e6-94e5-08858422b726.jpg)

**Comment by ageeroms** [comment]
Ouch, sorry about the spelling errors! User names can get changed in the database via method described here http://www.wpbeginner.com/wp-tutorials/how-to-change-your-wordpress-username/ if you want to ask your dev team to help. Alternately, you can delete that account and add a new one and here is a folder with the photos i cropped for this project:
[cc.zip](https://github.com/creativecommons/creativecommons.org/files/330900/cc.zip)
