### ISSUE TITLE
Link to board page near bottom of https://creativecommons.org/about/contact/ is broken (maybe broken everywhere)

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#307]
Fix.

Additionally, on the Board page there is no identification of the Audit Committee members, but the contact page says that those members are identified there. Let's add somehow a note to those members' profiles that they are members of that committee (Chris Sprigman (Chair), Dorothy Gordon, Johnathan Nightingale).

**Comment by mattl** [comment]
Where does the link take you? It takes me the staff + board page, and at the part of the page with the board.

**Comment by peterspdx** [comment]
Gives me an error message. See screenshot attached.
<img width="1070" alt="screen shot 2016-06-28 at 9 20 48 am" src="https://cloud.githubusercontent.com/assets/6127036/16423667/d528e2b6-3d11-11e6-999a-01cf1aad634b.png">

**Comment by mattl** [comment]
Can you copy the URL on the original page and then resulting URL and paste them in here?

FWIW, I'm seeing a link to https://creativecommons.org/board which works for me and redirects to https://creativecommons.org/about/team//#our-board

**Comment by peterspdx** [comment]
When I click on the link at the bottom of the page (noted in the title of this issue), it brings me here: https://creativecommons.org/about/team/%5C

Same thing when I copy and paste into my browser (Safari Version 9.1.1 (11601.6.17)) this link: https://creativecommons.org/board.

This doesn't happen when I use Chrome. Is it just Safari then?

**Comment by mattl** [comment]
Can you try the page again? Hopefully I've fixed it now.

**Comment by peterspdx** [comment]
So sorry, nope. And I refreshed several times. I don't think this is a high priority. Most people will get to the Board page from the Team tab anyway. But yeah, wish I could say otherwise.

**Comment by mattl** [comment]
It's a good end of the day issue to fix when I'm watching a bunch of other stuff...

**Comment by mattl** [comment]
Okay, I believe it has been fixed. You may have a bad link in your cache for now.

**Comment by little-wow** [comment]
also added in audit committee, so this issue I believe is resolved. @mattl please reopen if it is still an issue!
![Uploading Screen Shot 2016-06-30 at 9.34.49 AM.png…]()

**Comment by mattl** [comment]
Wrong issue :)

**Comment by mattl** [comment]
Oh wait, two issues in one.

**Comment by mattl** [comment]
@peterspdx I think this is fixed now. If you can check that board link on https://creativecommons.org/about/contact/ and if its still not working, reopen this please.

**Comment by peterspdx** [comment]
Thanks, @mattl! Fixed.

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC
