### ISSUE TITLE
Platform toolkit is HTML view only

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#308]
Can we format to style with rest of site? https://creativecommons.org/platform/toolkit/

![toolkit new site](https://cloud.githubusercontent.com/assets/6394777/16322164/2414f686-3956-11e6-87b3-a8067d248349.jpg)

**Comment by mattl** [comment]
@robmyers is working on this.

**Comment by robmyers** [comment]
This is now fixed. It wasn't like that for long, fortunately.

Please flush the cache and reload the page (ctrl-shift-r in Chrome).

**Comment by janeatcc** [comment]
Nice. Any way to make the TOC optionally expand?

Also there's "English / French" translation at top, but that only works for
FAQ. Should nix b/c toolkit isn't translated.

On Thu, Jun 23, 2016 at 4:33 PM, Rob Myers <notifications@github.com> wrote:

> This is now fixed. It wasn't like that for long, fortunately.
>
> Please flush the cache and reload the page (ctrl-shift-r in Chrome).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/308#issuecomment-228216306>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGGTmV51FWbSxFizM_c8IaFFTNgOz_Z_ks5qOxfLgaJpZM4I9TAH>
> .
>



-- 
Jane Park
Director of Platforms and Partnerships
Creative Commons
@janedaily

Get updates: http://bit.ly/commonsnews
Invest in the commons: https://donate.creativecommons.org/

**Comment by robmyers** [comment]
@mattl ^
