### ISSUE TITLE
CiviCRM is currently receiving and tracking contributions from new site

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#309]
Thought donations were going into the gravity forms and being held there until we build Civi bridge? Obviously simpler this way but I'm confused since I thought it wasn't possible?

**Comment by ageeroms** [comment]
https://donate.creativecommons.org is still active, so maybe folks are getting there from somewhere other than the website font end?

**Comment by mattl** [comment]
Yeah, I suspect people are just donating on the old page for now.

**Comment by rebeccalendl** [comment]
can those folks be redirected to the new page?

**Comment by ageeroms** [comment]
We need to consider that the CTAs on deed/license pages are still pointing at https://donate.creativecommons.org . A plan needs to be put in place to swap that out.

**Comment by mattl** [comment]
The homepage of donate now redirects to the donate form.
