### ISSUE TITLE
Additional supporters prominence

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#310]
The current page layout means that the Additional Supporters page (https://creativecommons.org/supporters/additional-supporters-2015/) is now more prominent than it was on the old site.

<img width="1272" alt="screen shot 2016-06-23 at 4 15 42 pm" src="https://cloud.githubusercontent.com/assets/7093838/16323241/24c4c2fc-395e-11e6-9720-b633ed00231e.png">

@ageeroms made two suggestions: 
1. We could hide In This Section on those pages? This can be configured by @mattl via visibility settings in widgets configuration interface

2. The name is a little weird in the subnav too. I'm wondering about removing it from the navigation, creating a redirect so old url keeps working and putting tiny hyperlink at the bottom of the main supporters page to it.

@rebeccalendl what do you think?

**Comment by rebeccalendl** [comment]
Yep, please remove/hide/archive or whatever is standard practice for old/outdated pages. It is no longer in use.

**Comment by ageeroms** [comment]
If the information is already represented on /supporters, then I'd suggest
you trash the page
https://creativecommons.org/supporters/additional-supporters-2015/ and
redirect that URL to /supporters.



On Fri, Jun 24, 2016 at 8:53 AM, rebeccalendl <notifications@github.com>
wrote:

> Yep, please remove/hide/archive or whatever is standard practice for
> old/outdated pages. It is no longer in use.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/310#issuecomment-228383678>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGXZDrTWaAFFTmm5yZ-i2S6uTb41AB1nks5qO_1-gaJpZM4I9XL9>
> .
>



-- 
Anna Geeroms | Business Analyst
Affinity Bridge

http://affinitybridge.com
T. 604.569.0510 | E. anna@affinitybridge.com

710 - 207 W. Hastings St.
Vancouver, BC
V6B 1H7

**Comment by little-wow** [comment]
@ageeroms I deleted the page and divorced it from its parent, but it's still showing up in the sidebar and providing a 404, and I'm not sure how to totally get rid of it.

<img width="1266" alt="screen shot 2016-06-29 at 11 43 04 am" src="https://cloud.githubusercontent.com/assets/7093838/16459036/721eaf82-3def-11e6-85a3-9cb1550bbc65.png">

**Comment by mattl** [comment]
Looking at this now

**Comment by mattl** [comment]
Seems like it was just a cache, link has now gone.
