### ISSUE TITLE
Getting lots of spam in my inbox

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#311]
@mattl this is more of an FYI - just wanted to let you know I got about a dozen yest. Wanted to see if there's an easy fix or anything in particular I should do about it or we can do to my email address on the site to avoid it? If not, qty is still relatively manageable and I'll just mark as spam and delete.

**Comment by ageeroms** [comment]
Email is on https://creativecommons.org/donate/ . Two thoughts:

1. throw an obfuscation plugin on there to stop email from getting scraped, e.g. https://en-ca.wordpress.org/plugins/email-encoder-bundle/ 
1. swap that link to hyperlink to contact form and add a category there in "Type of information you need" select for Donation support.

**Comment by mattl** [comment]
@rebeccalendl Can you forward one to me? Please don't mark as spam.

**Comment by rebeccalendl** [comment]
@mattl sure, just fwded and won't mark as anything

**Comment by mattl** [comment]
Okay, as they're just random people emailing you... you can mark those as spam, just be careful not to mark any emails from the various contact forms as spam.

I've updated the link to point to the generic contact form now.

**Comment by rebeccalendl** [comment]
Still receiving random emails with no subject line and/or incoherent ramblings, about 10-12 daily since the site launch. Possible to resolve?

**Comment by mattl** [comment]
I found another page with your email address on it. Fixed.
