### ISSUE TITLE
CC License Picker for Free Music Archive experiencing issues

### ISSUE THREAD

**Issue by cheyennehohman** [creativecommons/creativecommons.org#312]
Hi! 

This is Cheyenne from www.freemusicarchive.org. I work with @bonusroom and @hecanjog who are our steadfast software developers. 

Sometimes our curators (people or entities who upload music to our site) will want to upload items under different licenses than their "default" license. A default license is a profile setting we give to them based on their preferences. It used to take them to a stripped-down license picker page that looked like this: 
![ye olde license picker](https://cloud.githubusercontent.com/assets/9011511/16347000/446e4820-3a18-11e6-9fef-1a0c564d12f3.png)

Now, when I click on a link that should take me to the old interface, it dumps me onto your home page with a really long URL (below). 
https://creativecommons.org/?partner=FreeMusicArchive&jurisdiction_choose=0&exit_url=https%253A%252F%252Ffreemusicarchive.org%252Fcontribute%252FccLicense%252Ftest_1795%253Flicense_url%253D%255Blicense_url%255D%2526license_name%253D%255Blicense_name%255D%2526license_button%253D%255Blicense_button%255D%2526deed_url%253D%255Bdeed_url%255D

Is there a way to restore this function? Once the license was chosen, it would display on our site as a small, metadata-rich icon and link that would help our users know how to use a work. They look like this: 
![cute lil license](https://cloud.githubusercontent.com/assets/9011511/16347078/c6d1fac8-3a18-11e6-9b3d-a45ca4bcae64.png)

We have a workaround but would prefer to restore this feature for our users if possible. 

Thanks a zillion! 

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @mattl @little-wow

**Comment by mattl** [comment]
Yes, absolutely. We can get this back and working for you.

Where on your site do you link to our license chooser? @robmyers

**Comment by cheyennehohman** [comment]
In our uploader. If a user wants a different license, they click this link:
http://creativecommons.org/license/?partner=FreeMusicArchive&jurisdiction_choose=0&exit_url=https://freemusicarchive.org/manage/albums/ccLicense/23890?license_url=[license_url]%26license_name=[license_name]%26license_button=[license_button]%26deed_url=[deed_url] 
and the license chooser pops up for them.

**Comment by cheyennehohman** [comment]
A sample license confirmation URL is https://freemusicarchive.org/manage/albums/license/The_Depot?id=23890

**Comment by robmyers** [comment]
I've put a rewrite in. @cheyennehohman please can you try now?

**Comment by cheyennehohman** [comment]
Hmm, @robmyers I'm still getting the CC landing page in Firefox and Safari.

**Comment by robmyers** [comment]
@mattl http vs. https, and trailing slash. Working on it.

**Comment by bonusroom** [comment]
The URL to the CC site is generated in our code.  I can change it as
appropriate.

But is there a better way to choose licenses?  Do you have some kind of API
for that?  I'd like to avoid redirecting to another site if possible.

Best,
Ross Oldenburg
FMA Developer

**Comment by robmyers** [comment]
That is now fixed. Thank you for your help and patience!

We do also have an API -

https://api.creativecommons.org/

**Comment by cheyennehohman** [comment]
Thank you all SO MUCH!

**Comment by mattl** [comment]
@cheyennehohman We're going to close this, but please reopen it if you have any questions
