### ISSUE TITLE
Swap footer/sidebar email newsletter signup to CiviCRM

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#315]
@mattl 

I think we agreed that it would be ideal to swap the homepage footer and right sidebar email signup form to a CiviCRM form. I think there may be a configured widget sitting in the widgets Inactive Widgets section that could be dragged into Homepage Below Content and Sidebar positions and remain styled. If not, let us know and we can provides classes to be applied to help with styling.

Also, please note that sidebar visibility settings should mirror existing.

Attached is the code from the original sidebar widget:

[Connect with Creative Commons.txt](https://github.com/creativecommons/creativecommons.org/files/332774/Connect.with.Creative.Commons.txt)

**Comment by mattl** [comment]
This is done.
