### ISSUE TITLE
Ensure Giant Rabbit configures CiviBridge to catch email subscriptions

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#316]
When someone ticks the box on the Donation form to subscribe to the newsletter, "Yes, please subscribe me to the CC newsletter" (https://creativecommons.org/donate/#gf_3) , that information needs to get pulled by the CiviBridge and put into CiviCRM.

@rebeccalendl

**Comment by mattl** [comment]
We're just going to handle this by making the person part of the existing donor "smart group" in Civi, so nothing extra needs to happen.

**Comment by ageeroms** [comment]
@mattl , @rebeccalendl can confirm, but I think this is s still outstanding.

**Comment by rebeccalendl** [comment]
Confirmed, still open. GR is working on it.

**Comment by rebeccalendl** [comment]
Ah, sorry just re-reading above. That smart group piece is indeed closed. And the donor check box subscribers are also taken care of. So this is actually all set I think. Thanks.
