### ISSUE TITLE
weird text/link insertion into blog post

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#317]
on https://creativecommons.org/2016/05/27/council-european-union-calls-full-open-access-scientific-research-2020/

"Use the free table generator to create the perfect HTML tables for your website."

![screen shot 2016-06-26 at 8 59 53 pm](https://cloud.githubusercontent.com/assets/231665/16368324/010ffe72-3be2-11e6-98ae-f5ac54d0e879.png)

**Comment by ageeroms** [comment]
oops, that's cruft left behind from me using a free tool to strip extraneous HTML. Sorry about that folks!

**Comment by mattl** [comment]
Fixed. Also fixed a "here" link.
