### ISSUE TITLE
Guest posts on the blog

### ISSUE THREAD

**Issue by tarkowski** [creativecommons/creativecommons.org#318]
https://creativecommons.org/blog/

Guest posts appear regularly on the CC blog. There is information about the guest author in the post body, but the system assigns authorship to the person who publishes the post, and has an account in the system. This is confusing and inelegant. Obviously the best solution would be to give accounts to guest authors - but this is probably not feasible. A simple alternative is to create a "Guest author" generic / collective account - making it clear, that the reader should pay attention to author info in the post. 

 @mattl @little-wow

**Comment by little-wow** [comment]
I could honestly do either-- a guest account would be do-able, but so would creating dummy accounts for all guest posts so that they are published under their names. @ericsteuer what do you think?

**Comment by ericsteuer** [comment]
creating dummy accounts for guest posts would be the best solution. (fwiw, it's less creating new accounts and more just using the feature that enables you to manually enter the author's name). I know it's pretty easy and i've done it in wordpress at another job, but i've had trouble figuring out how to do it on the cc blog, so i haven't dealt with it. definitely a good thing to flag and figure out.

**Comment by tarkowski** [comment]
Hi Eric and Jenny,

not sure what the netiquette for issue discussion is - I don’t file them too often, but I appreciate your quick responses and thinking on this.

thanks
Alek

> On 27 Jun 2016, at 18:54, Eric Steuer <notifications@github.com> wrote:
> 
> creating dummy accounts for guest posts would be the best solution. (fwiw, it's less creating new accounts and more just using the feature that enables you to manually enter the author's name). I know it's pretty easy and i've done it in wordpress at another job, but i've had trouble figuring out how to do it on the cc blog, so i haven't dealt with it. definitely a good thing to flag and figure out.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/creativecommons/creativecommons.org/issues/318#issuecomment-228805805>, or mute the thread <https://github.com/notifications/unsubscribe/AAkT7nWW1mzX_HV4TWuGt5sF4Bpz7cJhks5qQAA6gaJpZM4I_Qlt>.
> 

--
dyrektor, Centrum Cyfrowe 
Twitter: @atarkowski 
WWW: centrumcyfrowe.pl / creativecommons.pl

polecam: 
uwolnij.podrecznik.org / otwartawiedza.pl / otwartengo.pl / otwartezabytki.pl

**Comment by ericsteuer** [comment]
Absolutely. I appreciate you taking the time to flag this.

**Comment by mattl** [comment]
Alek, you did everything perfectly :)

**Comment by mattl** [comment]
@ericsteuer -- does this look like the plugin that was being used to do all that? https://wordpress.org/plugins/co-authors-plus/screenshots/

**Comment by ericsteuer** [comment]
Yes! That "add a guest author" part.

On Tue, Jun 28, 2016 at 2:20 PM, Matt Lee <notifications@github.com> wrote:

> @ericsteuer <https://github.com/ericsteuer> -- does this look like the
> plugin that was being used to do all that?
> https://wordpress.org/plugins/co-authors-plus/screenshots/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/318#issuecomment-229187380>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIga0mKrNyQuX-y5SyOJRtS94UYaxAP5ks5qQZAYgaJpZM4I_Qlt>
> .
>



-- 
Invest in an open future. Support Creative Commons today:
http://bit.ly/19IjSKl

**Comment by mattl** [comment]
Great. I'll add it to the site soon :)

**Comment by mattl** [comment]
Guest authors now available on the site, and I've added Alek. @little-wow @robmyers @mattl can add new people.
