### ISSUE TITLE
Adjust payment methods in the store

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#319]
@rebeccalendl @Scott-CC , per my email, adding a ticket re payment methods in the store. With the new theme on the store, we noticed icons for Bitcoin, Dogecoin, Litecoin popping up in the footer. This is because in https://creative-commons.myshopify.com/admin/settings/payments -- the payment gateways section, GoCoin is enabled, which includes BitCoin Litecoin, and Dogecoin. The theme could be altered to not show those in the footer, but probably disabling that payment option makes more sense, if you don't want to accept that type of payment.

**Comment by mattl** [comment]
@robmyers

**Comment by mmoreshead** [comment]
According to shopify, we accept PayPal Express Checkout, Stripe, GoCoin.  I can disable GoCoin.  Just say the word.

**Comment by mattl** [comment]
Please disable GoCoin for now.

**Comment by mmoreshead** [comment]
Disabled GoCoin.
