### ISSUE TITLE
Page traffic seems down, Webmaster tools

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#321]
I was looking at analytics today and noticed that site traffic is way down and appears to be decreasing.

<img width="1015" alt="screen shot 2016-06-29 at 11 55 32 am" src="https://cloud.githubusercontent.com/assets/7093838/16459315/60f6da76-3df0-11e6-9cec-4b78e3cdb364.png">

A few weeks ago, this is what the Creative Commons search looked like, which was sub-optimal, but at least descriptive

<img width="499" alt="screen shot 2016-06-29 at 11 57 12 am" src="https://cloud.githubusercontent.com/assets/7093838/16459365/91f40d42-3df0-11e6-8e50-72024ccdd781.png">

I searched on incognito this week and came up with this

<img width="524" alt="screen shot 2016-06-29 at 11 58 10 am" src="https://cloud.githubusercontent.com/assets/7093838/16459412/b3778cd2-3df0-11e6-87e5-2f2afbc9f6f3.png">

I looked in Webmaster tools and it appears that the new CC.org is missing metadata. I'm happy to fix it, but I want some feedback from others as to what's going on/what's already been done. Did we submit a new sitemap? Why do you think this is happening? Should we be concerned about this?

**Comment by mattl** [comment]
I'd give it a little bit of time for them to reindex our new site.

**Comment by little-wow** [comment]
Do we have a sitemap we can submit?

**Comment by mattl** [comment]
It's already submitted.

**Comment by robmyers** [comment]
Let's check this at the end of the week.

**Comment by mattl** [comment]
Another thing to bear in mind is that it may be showing us a comparison against HTTP vs HTTPS.

**Comment by mattl** [comment]
Seems like this is back to normal
