### ISSUE TITLE
Fellows missing from CC website

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#322]
@peterspdx @cablegreen @ryanmerkley

**Comment by peterspdx** [comment]
Our only active fellows (under a current dated agreement) are ML and DW. @mmoreshead to confirm, but those are our only two, to  my knowledge.

**Comment by mattl** [comment]
yep, i was replying to DW and realized they were missing

**Comment by ageeroms** [comment]
Hey, I don't see a category for that on the user profiles. However, if you create a new Group called Fellows (in User > Group section of the site at /wp-admin/edit-tags.php?taxonomy=group ) and then you paste this shortcode on your team page [cc-team group="fellows"] , and then categorize someone as a fellow, that will make them display on the Team page. @mattl

**Comment by mmoreshead** [comment]
Yup, those are the only two that i know of!

**Comment by mmoreshead** [comment]
Wait, let me double check a few things before we move forward on this!

**Comment by little-wow** [comment]
@mmoreshead any update on this to close the ticket?

**Comment by mmoreshead** [comment]
@little-wow just waiting on a reply from one person.

**Comment by little-wow** [comment]
@mmoreshead checking on this one again!

**Comment by mmoreshead** [comment]
Contracts sorted, now to obtain bio and photo from AT (and see if DW wants to update his).
