### ISSUE TITLE
/compatiblelicenses 404

### ISSUE THREAD

**Issue by mlinksva** [creativecommons/creativecommons.org#323]
1. Visit https://creativecommons.org/compatiblelicenses/
2. Obtain 404

This is linked from https://creativecommons.org/licenses/by-sa/4.0/legalcode and elsewhere

Became are of because another project checks external links in its build: https://travis-ci.org/github/choosealicense.com/builds/141204505#L354

@mattl @little-wow

**Comment by mattl** [comment]
Hey Mike, that's been fixed now. 

It'll redirect you to https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/
