### ISSUE TITLE
Donation error

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#324]
Some kind human wrote in with this issue:
1. I go to creativecommons.org (in Chromium on Ubuntu Studio 15.04)
2. I click the "Donate now" button in the banner near the top
3. It brings me to a https://creativecommons.org/donate/. On this page, the "Other" field is crowded up against the other figures.
4. I enter an amount into "other" and click "Next"
5. It sends me to https://creativecommons.org/donate/#gf_3, which doesn't appear to have recognized that I entered an "other" amount. In fact, it doesn't have any real next steps at all. It just says "Other ways to give" and has no further action I can take.
6. For lack of a better option, I click "Check". It sends me to https://creativecommons.org/donate/other-ways-to-give/#check, where I finally see a link that says "Credit card or paypal" at the top (ironically, under "Other ways to give".
7. I click the paypal link and it sends me to http://dev.cc.affinitybridge.com/donate/, but that page has an HTTP Auth dialog that pops up and won't let me enter without a user name and password :(.

**Comment by mattl** [comment]
@creativecommons/affinity-bridge help? :)

**Comment by robinpuga** [comment]
Hey Matt, 

We don't have login access on prod to edit any pages do I? If you can go in and edit this page https://creativecommons.org/donate/other-ways-to-give/ you should be able to update the link to go back to /donate/ 

While you're doing that I'll look at seeing if we can setup a test for the strange behaviour on the "Other" field. 

Thanks, 
R.

**Comment by mattl** [comment]
PayPal link was fixed a while ago.
