### ISSUE TITLE
Cant log in to CC wordpress!

### ISSUE THREAD

**Issue by NaeemaCC** [creativecommons/creativecommons.org#326]
Thanks for reporting an issue, to help us file this efficiently we made this template. Feel free to ignore the template if you wish :) 

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here: https://creativecommons.org:80/wordpress/wp-login.php?redirect_to=https%3A%2F%2Fcreativecommons.org%2Fwordpress%2Fwp-admin%2F&ticket=ST-1467627739r79qpKJA3ldnObVxuiK

Please tell us the steps to reproduce the problem, if needed:

1. There seem to be an SSL error and I cant log in to the CC WordPress to post about the public discussion. Help you mighty tech gurus! :)  
2. Miss our little hangouts after work! See you in Berlin
3. 

Please tell us a little bit about how you're accessing the site or page, such as which web browser and which version of the browser: Firefox (latest update) and I tried from Chrome as well 

(You can also vist https://aboutmybrowser.com/ which will give you a link you can share with us that'll tell us everything we need to know)

You can also attach a screenshot to this issue if you have a visual bug to report. That'll help us figure it out faster. http://www.take-a-screenshot.org/ has instructions on taking screenshots. 
<img width="1421" alt="screen shot 2016-07-04 at 1 22 58 pm" src="https://cloud.githubusercontent.com/assets/16336462/16557894/10ef1986-41eb-11e6-80b1-c322fd1d2d57.png">

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @mattl @little-wow

**Comment by little-wow** [comment]
@NaeemaCC you have to remove the :80 from the URL and try again.

**Comment by mattl** [comment]
@NaeemaCC Once you get to this point, go back to https://creativecommons.org/wordpress/wp-admin/ and you'll be logged in.

**Comment by NaeemaCC** [comment]
Hello there folks... thank you for the feedback I was able to log in based on Matt advise yet it seems I don't have privileges to post content
<img width="1421" alt="screen shot 2016-07-10 at 1 50 09 pm" src="https://cloud.githubusercontent.com/assets/16336462/16713106/79df567c-46a5-11e6-896d-a306885ac3a4.png">

Kindly advise 
N
