### ISSUE TITLE
Survey on FAQ 404s

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#328]
https://creativecommons.org/faq/Defining_Noncommercial

pointed out to us on Twitter

**Comment by mmoreshead** [comment]
Thanks Jennie, this is part of a broken link in faq issue I've been working though in issue #197 (wow, I'm really taking my time on that, for shame!)

If you'd like to give the user the link, you'll find it here: https://wiki.creativecommons.org/wiki/Defining_Noncommercial
