### ISSUE TITLE
New posts on the blog aren't getting featured

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#329]
New posts on the blog aren't getting featured and the featured image is rendering strangely, see this post: https://creativecommons.org/2016/07/05/icymi-june-oer-roundup/

**Comment by mattl** [comment]
Seems like some posts have the 'Featured' highlights set and two have 'Hero'

https://creativecommons.org/wordpress/wp-admin/edit.php?cc_highlight=featured

https://creativecommons.org/wordpress/wp-admin/edit.php?cc_highlight=hero

I guess you'll either need to set this on the next post, or unset it from previous posts.

**Comment by little-wow** [comment]
The trick appears to be to set the "Highlight" as "hero"
