### ISSUE TITLE
CC0 still uses mixed http/https content

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#33]
Going to https://creativecommons.org/publicdomain/zero/1.0/ on Chrome breaks the disclaimer button, due to scripts that are run over http.

gives the following errors:
[blocked] The page at 'https://creativecommons.org/publicdomain/zero/1.0/' was loaded over HTTPS, but ran insecure content from 'http://yui.yahooapis.com/2.6.0/build/yahoo-dom-event/yahoo-dom-event.js': this content should also be loaded over HTTPS.
 (index):1
[blocked] The page at 'https://creativecommons.org/publicdomain/zero/1.0/' was loaded over HTTPS, but ran insecure content from 'http://yui.yahooapis.com/2.6.0/build/connection/connection-min.js': this content should also be loaded over HTTPS.
 (index):1
[blocked] The page at 'https://creativecommons.org/publicdomain/zero/1.0/' was loaded over HTTPS, but ran insecure content from 'http://yui.yahooapis.com/2.6.0/build/json/json-min.js': this content should also be loaded over HTTPS.
 (index):1
[blocked] The page at 'https://creativecommons.org/publicdomain/zero/1.0/' was loaded over HTTPS, but ran insecure content from 'http://scraper.creativecommons.org/js/pddeed.js': this content should also be loaded over HTTPS.
 (index):1
Uncaught ReferenceError: YAHOO is not defined help.js:38
[blocked] The page at 'https://creativecommons.org/publicdomain/zero/1.0/' was loaded over HTTPS, but ran insecure content from 'http://yui.yahooapis.com/2.6.0/build/container/container-min.js': this content should also be loaded over HTTPS.
 (index):1
[blocked] The page at 'https://creativecommons.org/publicdomain/zero/1.0/' was loaded over HTTPS, but ran insecure content from 'http://scraper.creativecommons.org/apps/pddeed?url=&license_uri=https%3A%2F…eativecommons.org%2Fpublicdomain%2Fzero%2F1.0%2F&callback=YAHOO.cc.success': this content should also be loaded over HTTPS.

**Comment by ewilfong** [comment]
The mixed content issue on the page above appears to be resolved.  I am seeing a similar issue on https://creativecommons.org/publicdomain/mark/1.0/
