### ISSUE TITLE
Links to Old CC Blog Post URLs - Auto-Direct to new URL?

### ISSUE THREAD

**Issue by cablegreen** [creativecommons/creativecommons.org#331]
I see edX: https://open.edx.org/blog/open-edx-releases-creative-commons-licensing 

is pointing to our blog post (pre-shift)  - links to: http://creativecommons.org/weblog/entry/45593

and the user sees: "Oops! That page can’t be found." 

It should link to: https://creativecommons.org/2015/06/02/edx-makes-it-easy-for-authors-to-share-under-creative-commons (this is the new URL for the old CC blog post)

Is it possible to do auto-forward on old CC blog post links .... so folks linking to old CC URLs find their way to the same page under the new CC URLs?

@mattl

**Comment by mattl** [comment]
All set. You can test it by opening the link in an incognito window and it'll redirect :)

**Comment by mattl** [comment]
@robmyers Added line 404 (appropriately) to live config

**Comment by cablegreen** [comment]
Thanks!

Cable
