### ISSUE TITLE
Spacing in visual editor is wonky

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#332]
Single spaces have been double spacing in the visual editor.  

When I switch to the text editor, it seems to fix itself.

**Comment by mattl** [comment]
Screenshot? :)

**Comment by little-wow** [comment]
![visual_editor](https://cloud.githubusercontent.com/assets/7093838/16630295/c5d16622-4387-11e6-8b38-ef93b2010886.gif)

At one point it was putting in a nonbreaking space, but it's not doing that every time and I couldn't screengrab it

**Comment by mattl** [comment]
It looks like its inserting a paragraph, which feels like the correct behavior. If you want a break, shift-enter will get you there.

**Comment by little-wow** [comment]
I only commented on it because it wasn't doing that when the site first launched...  It was adding a break then

**Comment by mattl** [comment]
Hmm, could be something they fixed in a recent WordPress release. We have updated a little since the launch.
