### ISSUE TITLE
Add a new WordPress template

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#333]
If I wanted to do custom CSS or html on a page in WP, how would I do that?

Here are some examples of things I want to play with, but not across the whole site, just maybe for a landing page or something:

<img width="1269" alt="mockup" src="https://cloud.githubusercontent.com/assets/7093838/16658465/7fb171d4-4434-11e6-90c1-6427f9b43cfc.png">

This ticket is a note to self to ask about in the future. No need to take action.

**Comment by mattl** [comment]
We could make a template in WordPress to do all this, and you'd be able to select it when you made a new page.
