### ISSUE TITLE
board.creativecommons.org CCID Workflow Needs Fixing

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#336]
The CCID login for the board site takes you to a password login rather than logging you in.

This results in the CAS credentials not going into the database.

I assume this is just for (would-be) new users.

**Comment by mmoreshead** [comment]
There will be lots of "new users" because some of them didn't ever create their CCID so they never got access. I've been working on some stuff lately that will put them to go there to view.  I'll wait until this is resolved to move forward with that.

**Comment by mattl** [comment]
If I login, it bounces me to CCID and then to a form on the wiki to sign in again, but I am signed in with my CCID.

**Comment by robmyers** [comment]
@mattl you have an account there. Not sure what happens if the user doesn't. But in either case that form shouldn't display.

**Comment by peterspdx** [comment]
Really appreciate the effort everyone is making here. Just as a reminder, the only people that *should* be able to get access to the board wiki are board members, so keep that in mind!
