### ISSUE TITLE
Older blog posts not loading correctly

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#339]
Someone pinged us about old blog posts not being there.  I was able to pull up the post in Wayback Machine, but the archives could be useful for reference purposes.

Also, Google search results do show these posts as being there, but they redirect to the main site: https://www.google.com/#safe=off&q=Announcing+(and+explaining)+our+new+2.0+licences+%C2%BB%2C+25+may+2004%2C+creative+commons

See conversation: https://twitter.com/alex_giann/status/751876018441453568

**Comment by mattl** [comment]
@robmyers Look at this weird one... 

you can even search for "Versioning - Public Review Begins" in the search box at the bottom of our site -- you get a single result, but clicking it takes it to the homepage.

Redirects ftw :/

**Comment by mattl** [comment]
This affects all URLs starting /2004 - /2010 maybe earlier

**Comment by mattl** [comment]
Commenting out line 320 in Apache Config. 

RewriteRule ^/200.* http://%{SERVER_NAME}/ [L,R=301]

**Comment by robmyers** [comment]
That was a weird rule. It had been like that since before the new site.

Why are those all rewriting to http rather than https? I feel you explained this to me but I can't remember the reason. They used to be to ${proto}, we could use %{REQUEST_SCHEME} (available in Apache >= 2.4 ).
