### ISSUE TITLE
Outdated donation social media share

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#341]
I just donated to @creativecommons! bit.ly/1i1Vo71 #teamopen

Is what people tweet out after they donate, and the link is wrong. Where can we change this?

**Comment by mattl** [comment]
where did you see this?

**Comment by mattl** [comment]
and the link works just fine :) http://bit.ly/1i1Vo71

**Comment by little-wow** [comment]
<img width="353" alt="screen shot 2016-07-11 at 5 47 30 pm" src="https://cloud.githubusercontent.com/assets/7093838/16748007/a173688c-478f-11e6-994a-a2668ceb96f9.png">

<img width="593" alt="screen shot 2016-07-11 at 5 49 54 pm" src="https://cloud.githubusercontent.com/assets/7093838/16748055/ea6fd66a-478f-11e6-84db-d9fa6fa2462e.png">
<img width="588" alt="screen shot 2016-07-11 at 5 49 49 pm" src="https://cloud.githubusercontent.com/assets/7093838/16748054/ea6f4ce0-478f-11e6-9e8b-b3d1707614e2.png">

it's a redirect, and initially directs to the old site. In any case, I'd like to know where this lives.

**Comment by mattl** [comment]
This is probably people donating on an old CiviCRM donation page.

**Comment by mattl** [comment]
The migration will redirect all these public facing pages to the new website.
