### ISSUE TITLE
Posting Privileges 

### ISSUE THREAD

**Issue by NaeemaCC** [creativecommons/creativecommons.org#342]
Hello there folks... thank you for the feedback I was able to log in based on Matt advise yet it seems I don't have privileges to post content

<img width="1421" alt="screen shot 2016-07-10 at 1 50 09 pm" src="https://cloud.githubusercontent.com/assets/16336462/16767221/14589586-4847-11e6-9896-660a46f0ee16.png">

Kindly advise
N

Thanks for reporting an issue, to help us file this efficiently we made this template. Feel free to ignore the template if you wish :) 

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here:

Please tell us the steps to reproduce the problem, if needed:

1.
2. 
3. 

Please tell us a little bit about how you're accessing the site or page, such as which web browser and which version of the browser:

(You can also vist https://aboutmybrowser.com/ which will give you a link you can share with us that'll tell us everything we need to know)

You can also attach a screenshot to this issue if you have a visual bug to report. That'll help us figure it out faster. http://www.take-a-screenshot.org/ has instructions on taking screenshots.

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @mattl @little-wow

**Comment by little-wow** [comment]
@NaeemaCC I reset your role.  Tell me if you're still having issues.

**Comment by NaeemaCC** [comment]
Still no access to write a blog post :( 
<img width="1423" alt="screen shot 2016-07-12 at 7 47 31 pm" src="https://cloud.githubusercontent.com/assets/16336462/16775508/9cbdef08-4869-11e6-976b-8561ca038789.png">

**Comment by NaeemaCC** [comment]
Still the same 
<img width="1425" alt="screen shot 2016-07-12 at 7 53 25 pm" src="https://cloud.githubusercontent.com/assets/16336462/16775643/417a7af2-486a-11e6-88a4-1f29c9199e33.png">

**Comment by little-wow** [comment]
You're now listed as an author, so I don't know why it's not reflecting. Did you try clearing your cache?

**Comment by mattl** [comment]
I think I know what's up, one sec

**Comment by mattl** [comment]
You should be all set now.

**Comment by NaeemaCC** [comment]
It is <3 I posted one in English and now I'm going for an Arabic post


On Tue, Jul 12, 2016 at 7:56 PM, Matt Lee <notifications@github.com> wrote:

> You should be all set now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/342#issuecomment-232108950>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APlGTngPTMIUBomtYoU2Rwl8VfEdUjIVks5qU8dagaJpZM4JKWgZ>
> .
>



-- 
Naeema Zarif
Regional Coordinator | Arab World
Creative Commons
creativecommons.org
naeema@creativecommons.org

Skype: NaeemaZarif
Twitter: @naeema

Please support CC in shaping the future of sharing:
https://creativecommons.net/donate/

**Comment by NaeemaCC** [comment]
Thank you guys it worked perfectly :) 👍
