### ISSUE TITLE
affiliate programme spam

### ISSUE THREAD

**Issue by gwenfranck** [creativecommons/creativecommons.org#343]
Hi guys, 

there is an incredible amount of spam coming through on "affiliate-program@creativecommons.org" <affiliate-program@creativecommons.org> 

According to teamspace this is a mailing list managed by legal, but afaik it is not actively used.

**Comment by peterspdx** [comment]
It is used for third parties to submit questions // info about becoming an affiliate or how to become involved with CC. We do receive some submissions, though not an undue amount. If we want to discontinue -- and I'll leave that to Gwen since she's in charge of the affiliate program at present -- then we should be sure to replace any references to it on our website with a new submission portal such as info@.

**Comment by mattl** [comment]
@gwenfranck Does that work for you? Just moving it to info@creativecommons.org

**Comment by gwenfranck** [comment]
Yes, kill it please. Is there a way to track and replace all the spots on
the site where the old address is metioned @mattl ?

**Comment by mattl** [comment]
I don't see it on the website, perhaps its on the wiki....

**Comment by mattl** [comment]
Anyway, this is all set. Emails going to the old address will now go to info@ -- @mmoreshead -- look out for anything vaguely sensible that comes to the info queue for affiliates, but it'll probably mostly be very little.

**Comment by peterspdx** [comment]
We'll maintain the archives, somehow @mattl?

Quickly looking for even one example brought me to this page: https://wiki.creativecommons.org/images/9/94/Introduction_to_CC_and_Affiliate_Teams.pdf

You can see where we ask people to contact us through that email portal if they have questions about the affiliate network. That is a very old document and will surely be updated if not removed altogether once the affiliate network strategy is completed. 

I'm wondering if a better way than killing it right now would be to forward any email inbound to that email address to info@?

**Comment by mattl** [comment]
Oh, the address isn't dead, it just forwards to the info@ address.

All the old stuff is archived.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by peterspdx** [comment]
Ah, I misunderstood. I thought kill was kill forever and always, not forward. Thanks, mattl!
