### ISSUE TITLE
Text formatting on the homepage

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#345]
<img width="527" alt="screen shot 2016-07-12 at 5 28 15 pm" src="https://cloud.githubusercontent.com/assets/7093838/16784565/4b02bbc4-4857-11e6-8e6a-4ad2ade023f5.png">

I tried a variety of categories and they are all formatting this way

**Comment by mattl** [comment]
I enabled the excerpt field... 

![screenshot from 2016-07-12 16-40-17](https://cloud.githubusercontent.com/assets/33296/16784650/5f8624ee-484f-11e6-8d6f-c9470d11c42b.png)

It'll appear at the bottom of the page, you can enter a small summary sentence or two here, which fixes this.
