### ISSUE TITLE
Homepage newsletter signup section lost formatting

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#346]
Hey @mattl, I noticed when you swapped back to the Civi form for newsletter signup on the homepage lost its formatting. It used to look like http://jennchristenson.com/client/AffinityBridge/CC/r4b/home_v1.html . Do you need support from us on restoring that?

**Comment by ageeroms** [comment]
@mattl , do you need our support on this ticket? It would be really great to get that styling back, as it feels funny and floaty without the styles.

**Comment by mattl** [comment]
If you want to fix it on the staging server and update this ticket when I have something I can copy/paste over that'd be great.

**Comment by ageeroms** [comment]
@mattl https://staging.creativecommons.org/ is showing the correct newsletter formatting. 

Please be aware this code is in a different branch issue-228-news_letter_signup_widget and it will need to be merged.

Also, Alberto had to tweak the widget code somewhat. This file contains the updated code:

[widget.txt](https://github.com/creativecommons/creativecommons.org/files/389336/widget.txt) 

So please update that widget on production as well.

**Comment by mattl** [comment]
Okay, I merged the branch -- you should all have permissions to make a pull request, let me know if Alberto doesn't. 

Updated the widget. It doesn't look quite right, but it does look better.

**Comment by mattl** [comment]
![screenshot from 2016-07-28 16-08-19](https://cloud.githubusercontent.com/assets/33296/17229524/83eddb2a-54dd-11e6-93a7-2cd7effbdf31.png)

**Comment by ageeroms** [comment]
@mattl , Alberto just pushed a solution into the "issue-228-news_letter_signup_widget" for that Chrome bug shown above.

**Comment by mattl** [comment]
Looks good.

**Comment by mattl** [comment]
@ageeroms In #401 -- @fmann is seeing the box looking bad in Safari.

**Comment by fmann** [comment]
@mattl I just submitted a pull request for a fix for that.  https://github.com/creativecommons/new-www-theme/pull/8

**Comment by ageeroms** [comment]
@robmyers please close

**Comment by robmyers** [comment]
Closing as per request.
