### ISSUE TITLE
More News link on home page goes to 2013 article not news listing page

### ISSUE THREAD

**Issue by robinpuga** [creativecommons/creativecommons.org#348]
1. Go to home page, scroll to What's Happening section 
2. Click on More News link at bottom of section
3. See that the redirect goes to some 2013 article - should go to /blog

Link to More News should go to /blog and not /news (original news blog listing URL).

**Comment by mattl** [comment]
How do I edit that link?

**Comment by robinpuga** [comment]
Here's the link: /wp-admin/plugin-editor.php?file=cc-widgets%2Fwidgets%2Fcc-homepage-whatshappening-widget.php&plugin=cc-widgets%2Fcc-widgets.php 

Once updated please commit the code to the repo.

**Comment by mattl** [comment]
https://github.com/creativecommons/new-www-plugin/commit/88f0d51180e5aac147c48bf04619c7c76e0cf8f6
