### ISSUE TITLE
Video max width borking design on Press page

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#350]
@mattl on https://creativecommons.org/about/contact/press/ , I'm noticing that the video might be a fixed width or something, as the sidebar content is being dropped to the bottom of that page. I'm not sure why that is happening without being able to login. I notice on other video pages https://creativecommons.org/about/videos/ that this isn't happening.
![screen shot 2016-07-13 at 2 44 18 pm](https://cloud.githubusercontent.com/assets/6674702/16820912/5302abca-4908-11e6-9ed7-7d442cb76a7e.png)

**Comment by mattl** [comment]
Removed the video and readded it, page seems okay now.
