### ISSUE TITLE
Can we backdate blogposts ?

### ISSUE THREAD

**Issue by NaeemaCC** [creativecommons/creativecommons.org#351]
Hello there amazing Tech team 
The new website have inspired lots of affiliates to share their highlights and they have a number of amazing blog posts about "past" affiliate highlights and events that they are eager to share on the CC blog. Would it be possible to install a plugin that will allow us to backdate posts?

P.S. They promised to send the future blog posts in timely manner :D 
Pweaaaaaaaassseeeee #puppyeyes

**Comment by little-wow** [comment]
Go to posts, "Quick Edit" and then follow these directions:

<img width="841" alt="screen shot 2016-07-14 at 10 10 35 am" src="https://cloud.githubusercontent.com/assets/7093838/16842398/5ac8a230-49ab-11e6-8ef5-152d4dff6a71.png">
<img width="834" alt="screen shot 2016-07-14 at 10 10 53 am" src="https://cloud.githubusercontent.com/assets/7093838/16842399/5ac8fa00-49ab-11e6-913c-2fb4a19e93b8.png">
