### ISSUE TITLE
Link to licence Chooser Too Obscure

### ISSUE THREAD

**Issue by AndrewRens** [creativecommons/creativecommons.org#352]
The link to the Licence chooser has been removed from the top line. Instead it is now buried in the page - see screenshot
![ccfrontpage 2016-07-14 05 57 17](https://cloud.githubusercontenret.com/assets/15172223/16835733/044f472e-4988-11e6-881c-7c9218ea11c4.png)

I frequently verbally refer people to the CC website to generate thier own licences  BUT now it will be difficult for them, first time users, to find the correct link. The result is to dis-empower people.

**Comment by kgodey** [comment]
We plan to revamp the CC homepage menu/navigation in June/July to make finding important pages like the license chooser easier to find. We will make individual tickets for the changes we plan to make (including this one) in June; so I'm going to close this ticket.
