### ISSUE TITLE
Page resembles apartheid South African Flag

### ISSUE THREAD

**Issue by AndrewRens** [creativecommons/creativecommons.org#353]
The new cc webpage, shown in the screenshot resembles the flag of the apartheid regime in South Africa.

Screensjot
![ccfrontpage 2016-07-14 05 57 17](https://cloud.githubusercontent.com/assets/15172223/16835864/b49dd29e-4988-11e6-913d-b293b85eb72e.png)

Previous South African flag

![oldsaflag](https://cloud.githubusercontent.com/assets/15172223/16835873/c34a9372-4988-11e6-849f-d34a297a86d6.jpeg)

The resemblance is not just a strip of orange and then white and then blue but also by having other logos on the middle strip.  The previous South African flag is associated with the discredited apartheid system by millions of South Africans. The resemblance of the webpage to that flag will have unfortunate, probably unconscious resonance not only for South Africans but many others.

**Comment by mattl** [comment]
@ryanmerkley @peterspdx

**Comment by robmyers** [comment]
Current design is now orange and yellow.
