### ISSUE TITLE
Featured content on front page workflow

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#355]
This workflow is cumbersome and needlessly confusing. While these images look great, I foresee this workflow becoming an issue in the near future.

Current workflow:
<img width="250" alt="screen shot 2016-07-14 at 10 46 35 am" src="https://cloud.githubusercontent.com/assets/7093838/16843720/7254cb72-49b0-11e6-8054-07b1dfa506c5.png">

<img width="873" alt="screen shot 2016-07-14 at 10 47 05 am" src="https://cloud.githubusercontent.com/assets/7093838/16843779/afb8ee08-49b0-11e6-92ae-ea450b68835c.png">

<img width="258" alt="screen shot 2016-07-14 at 10 48 54 am" src="https://cloud.githubusercontent.com/assets/7093838/16843790/b7047c68-49b0-11e6-95d7-e7560e99370c.png">

<img width="274" alt="screen shot 2016-07-14 at 10 49 03 am" src="https://cloud.githubusercontent.com/assets/7093838/16843799/c0b417f0-49b0-11e6-9b17-ff92ba0b126e.png">

@mattl had some recommendations, so I'll let him drop them here before weighing in.

**Comment by mattl** [comment]
Yeah, I want separate fields for Title, License, Creator Name, etc.

**Comment by robinpuga** [comment]
Hi Jennie and Matt, 

We originally had separate fields for attribution, but found that there was a handful of resources that didn't quite conform to the specific attribution layout. 

Knowing that Matt and Rob are working on an CC Attribution Plugin for WordPress that would be ready shortly, we opted for a flexible solution that would meet your needs. This single field is able to accommodate any attribution format required for this content type. 

Jennie, let us know if you would like us to review this process with you. Happy to chat more about it. 

Also, if you would like our team to assist in development of the attribution plugin we would be happy to help. 

Best, 

Robin

**Comment by mattl** [comment]
Do you have any recollection of the items that didn't quite fit?

**Comment by ageeroms** [comment]
We were originally uncertain about the implication that all images are cropped in our design. If an image allows modifications, should it be attributed with that noted? e.g. 

"Creative Commons 10th Birthday Celebration San Francisco" by tvol, used under CC BY / **Cropped from original**

However, we kind of let that one go and that wasn't a concern that Diane voiced, when we sent for review. 

Here are other examples:

![screen shot 2016-07-19 at 10 04 59 am](https://cloud.githubusercontent.com/assets/6674702/16959260/0f2f9ac6-4d99-11e6-9ef8-aacf191a4319.png)
![screen shot 2016-07-19 at 10 04 27 am](https://cloud.githubusercontent.com/assets/6674702/16959261/0f36286e-4d99-11e6-83e2-9c2061818c16.png)

Items with multiple linked authors, items with listed editors (but no author), or items with ambiguous authorship are all difficult to feature using the best practices indicated on the Wiki.

**Comment by DylanMcCall** [comment]
Another issue we ran into is that we wanted all of the images in the library to have attribution in their captions, but we also need to provide the same sort of attribution for resources that *aren't* images in the library. (For example, music and writing). The interface we have is naturally pretty clunky, but we preferred to stick with defaults initially so it's clear how to keep building.

I'm not sure if it's documented, but for what it's worth the resource tiles will show the Resource caption field by default, and fall back to the featured image caption only if that is empty.

(Personal opinion: I think ideally we'd have some fancy attribution fields for WordPress's media library as well as for Resource tiles, and tweak the editor interface so it copies those fields from the featured image by default. Then the attribution stuff should all appear up front, in one place).

**Comment by mattl** [comment]
Our plugin will expose attribution fields to the media library, so let's reevaluate this a little later.
