### ISSUE TITLE
Where is feedburner?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#356]
On ccthing, there's a feedburner signup, which brings you the ccthing.

It's been a thing of the day and a thing of the week, so now the email says you're getting lots of things.

Where can I edit this?

<img width="980" alt="screen shot 2016-07-14 at 11 22 41 am" src="https://cloud.githubusercontent.com/assets/7093838/16844996/5b109676-49b5-11e6-896a-6cf8d34bf6f5.png">

**Comment by mattl** [comment]
This is on Tumblr? What should it say?

**Comment by little-wow** [comment]
This is an email that comes from feedburner-- I think it's just an RSS.  I searched through the HTML on the Tumblr to see if it said "thing of the day" anywhere but couldn't find any more instances.

Just CC thing is fine :)

**Comment by mattl** [comment]
That's not attached to my Google account, so I don't think we can edit it. Maybe @tvol or @mmoreshead have it on theirs? http://feedburner.google.com/fb/a/myfeeds

**Comment by mmoreshead** [comment]
Nope, not me.  Sorry.

**Comment by little-wow** [comment]
This list has well over 1000 people on it, so I don't want to lose it, but I also don't want to keep sending out emails that look like that.

**Comment by mattl** [comment]
How can you see how big the list is?

**Comment by little-wow** [comment]
So I went back through and realized that the number I was thinking of was our tumblr subscribers, which are over 5000. Feedburner has no support I can reach out to because they stopped updating their product in 2011. 
While this may be a "won't fix" issue, I still think we should have an idea of who owns our feeds...  Not sure what the best course of action is here.

**Comment by little-wow** [comment]
@mattl reminding you to see if Elliot owns it!

**Comment by mattl** [comment]
Confirming Elliot owned it, transferring it to me but could take 72 hours.

**Comment by mattl** [comment]
I didn't get this message from Feedburner. I'll try again.

**Comment by mattl** [comment]
Tried again. Let's see if we ever get this.

**Comment by mattl** [comment]
So, I think the ability to transfer things is broken. We should make this a CiviCRM list, and I have exported the data. We should email the active people and ask them to join the new list we can manage from Civi.

**Comment by mattl** [comment]
Also, you'll note only 11 people signed up this year. 

https://docs.google.com/a/creativecommons.org/spreadsheets/d/1H1mpnwpsqQvaNBwCtWWUjOfyrP4PwSJN11Mj-G5AcUY/edit?usp=sharing

**Comment by tvol** [comment]
😭

**Comment by little-wow** [comment]
Needs not be asked, but this spreadsheet is closed, right?

**Comment by little-wow** [comment]
Yeah, after I started running metrics on the link clicks on those posts, I realized they weren't really worth my time, but I will add them to a Civi list.

**Comment by mattl** [comment]
Spreadsheet is for CC eyes only.

We can't just add them to a list. We need to invite them to join our newsletter.

**Comment by little-wow** [comment]
Matt, I know that. I will just make it a list, like you said in the ticket

**Comment by mattl** [comment]
Suggest we do the following...

1. Make a new group in Civi, check the mailing list box.
2. Delete all the pending people from the spreadsheet, export as CSV.
3. Add all the active people (Contacts > Import Contacts) to the group.
4. Send a simple email with a link to a page where they can join our newsletter.
5. Delete the group once the email has been sent.

**Comment by little-wow** [comment]
will do, thanks
