### ISSUE TITLE
editing rights on the wiki

### ISSUE THREAD

**Issue by gwenfranck** [creativecommons/creativecommons.org#358]
Hi guys, is it possible that I don't have editing rights for the Affiliate network page on the wiki?
https://wiki.creativecommons.org/wiki/CC_Affiliate_Network

**Comment by little-wow** [comment]
Is this taken care of?

**Comment by mmoreshead** [comment]
She has edit rights but still can't edit that page. I think it's locked or something maybe @robmyers ?

**Comment by robmyers** [comment]
@mmoreshead yes you are right. I've made it so approved users can edit it. @gwenfranck please try now and let me know if it's OK.

**Comment by mmoreshead** [comment]
Thanks @robmyers!
