### ISSUE TITLE
donation error

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#359]
<img width="1171" alt="screen shot 2016-07-15 at 8 51 19 am" src="https://cloud.githubusercontent.com/assets/13322149/16880297/736b38de-4a69-11e6-967c-408147eed97f.png">

**Comment by mattl** [comment]
Yeah, that will occasionally happen when the site is receiving a bunch of traffic. We have a ticket open for it.

**Comment by mattl** [comment]
https://github.com/creativecommons/creativecommons.org/issues/320
