### ISSUE TITLE
Repetition in blog content

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#360]
Because the "Featured" tag and the "Hero" tag are different, it means that blog content appears twice on the page when something is tagged both as featured and hero.

This can be fixed by removing the "Featured" tag from the Hero image, but that means that in order to get the "Hero" post to show up as Featured in the future, you have to go back into the post and mark it as featured. This is not ideal because it means that posts are being listed in a non-chronological order, making them difficult to find.

I understand why this is happening this way, and that this allows for maximum flexibility with the featured posts, but the workflow is so complicated that it's defeating the purpose of the flexibility.
I'd be fine with just having posts appear chronologically.  This issue is very similar to #354 but it's different enough that I'm opening another ticket and would love feedback from @ageeroms about how we can make this better.

Screenshots below:

<img width="610" alt="screen shot 2016-07-15 at 12 28 09 pm" src="https://cloud.githubusercontent.com/assets/7093838/16881313/9f700fd6-4a87-11e6-86e5-6fc519b21798.png">
<img width="897" alt="screen shot 2016-07-15 at 12 27 45 pm" src="https://cloud.githubusercontent.com/assets/7093838/16881312/9f6b08ce-4a87-11e6-9dfa-1abece3ba698.png">

**Comment by ageeroms** [comment]
@little-wow , I think the idea was that the Hero would be quite a strong piece that had really good visuals, not just the most recent thing that you want featured. So maybe there would be a new development re OER and the piece would use that development as a jumping off point, but then provide an outline of the issue in general. These hero posts would act as a primer to the issues that CC is working on, so it would be a good jumping in point for someone who doesn't have a lot of familiarity with the work you do. The items below, "Featured," should be things that are notable enough to hit homepage, but appealing more to the audience that knows CC's work more in-depth.  So in that scenario, a Hero item would not ever become a Featured item later.

Anyway, if that flow doesn't work for you, we should chat more about the actual type of content/workflow that you envision.

**Comment by little-wow** [comment]
The Letters post is tagged both featured and hero and is being superceded by "Open Textbooks for Africa." It is also the featured post and it's appearing twice on the front page as well. When posts are tagged "Featured" and "Hero," they appear twice, so I've unfeatured posts to make them show up in the hero and not on other parts of the page. In order to make something no longer be the hero but also be featured, you have to go back into the hero post and make it featured. In addition, even though I've tagged other posts as "Featured," it's still featuring these posts from May as the featured posts, pushing our latest posts to the bottom of the page and making it seem like we post far less frequently than we do.

The space that's currently "Featured" on the front page is also not labeled "Featured," but instead "What's Happening," which would, to me, indicate the latest posts, but it's showing posts from May. I'm not sure if this is just me not understanding the workflow or there being something wrong with the way that posts are displayed. Looping in @ericsteuer and we'll discuss it today.

![screencapture-creativecommons-org-blog-1468936945762](https://cloud.githubusercontent.com/assets/7093838/16952897/22e44206-4d99-11e6-97f5-8121b645061d.png)

**Comment by ageeroms** [comment]
I see what you are saying, featured and hero posts are being repeated in the list of regular posts below! OK, we can look into omitting those. Please assign to Floyd @fmann . 

Other items:

I think the hero/featured are in order that we intended. 
![banners_and_alerts_and_blog_-_creative_commons_and_when_we_share__everyone_wins_-_creative_commons](https://cloud.githubusercontent.com/assets/6674702/16994883/3d262b14-4e5e-11e6-8085-0ef05443ab8f.png)

Regarding the What's Happening vs News, that is something that came up previously and was kept that way on purpose. Now that you've changed the label to Blog, that might be too many things? Let's chat about that at our meeting.

**Comment by fmann** [comment]
I issued two pull requests here, one in the theme and one in the plugins, that I think address many of  @little-wow's concerns.

- With these changes, in both the homepage What's Happening widget and the Featured widget at the top of the News section, if a post is marked with both Hero and Featured it will only display in one location or the other. So if it is the newest Hero, it will display there. If there is a newer Hero, it will be display in Featured.
- On the News page, if a post is a Hero or a Featured item and also is in the listings below on the first page of results (pre-AJAX infinite scroll reload), it will only display once, in the Hero or Featured section, and not in the listings below.

I think that will make content authoring better, requiring less (now no) editing of posts to move them from Hero to Featured. And, yes, less repetition of post teasers is good.

I've tested it on my local site, which has a pre-launch database full of dummy content in it. I don't foresee any issues with the production database, but I've been wrong about that more than once before.

**Comment by little-wow** [comment]
Hey @fmann I don't see this on the staging site?

**Comment by fmann** [comment]
No, no one had pulled after the merge. It is now.

**Comment by fmann** [comment]
*Now* it is fully on stage. I'd forgotten there were two parts to it, both theme and plugin changes.

**Comment by fmann** [comment]
@little-wow Hey! I want to keep the discussion on this single thread rather than the pull requests.

Fixed now. I had some branch management issues with us having at least 3 active threads on the same staging server this moment. I just checked stage and you can see this behaving as we'd like there now.

**Comment by ageeroms** [comment]
@mattl can you please deploy to production?

**Comment by mattl** [comment]
@little-wow Deployed. Please confirm you're seeing the fix.

**Comment by little-wow** [comment]
Looks good!  Thanks everyone!
