### ISSUE TITLE
Requesting CiviCRM login

### ISSUE THREAD

**Issue by evarogers** [creativecommons/creativecommons.org#362]
Looking forward to getting into the sparkly new database! Thanks in advance @mattl

**Comment by rebeccalendl** [comment]
@mattl the original repo for this (ER onboarding) seems to have disappeared. mari or eva got 404 I think? In any case, it's an old ticket and she's still without access. Possible to prioritize?

**Comment by mattl** [comment]
Just waiting on GR to clear up this one last bug: https://support.giantrabbit.com/issues/24001

**Comment by mmoreshead** [comment]
it's totally weird that https://github.com/creativecommons/er-onboarding this is vanished, yes?

**Comment by mattl** [comment]
I removed it once the last bug was closed -- trying to shut down the issues on most repos so we can have a central place for issues.

**Comment by mmoreshead** [comment]
Ok cool!

**Comment by rebeccalendl** [comment]
Can't we just close them instead of delete? Some issues were prob open, including this one about Eva's civi access.

**Comment by mattl** [comment]
It was closed, because Eva has an account on the old server, I believe...
@robmyers? Any accounts on the old server will be on the new one now.

They're not deleted, they're just not accessible to the world.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by evarogers** [comment]
I didn't receive an account - was waiting on the upgrade, and was then given Rob's access info to start to get around in the database while it was transitioning.

**Comment by mattl** [comment]
Ah, okay. I thought Rob gave you his password for the new server, and made
you an account on the old one.

We'll get you an account ASAP, we're just waiting on Giant Rabbit to finish
something up.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by evarogers** [comment]
Kewl, can't wait to wrangle all that sweet civi data!

**Comment by mattl** [comment]
Oh, it's going to be exciting.

**Comment by robmyers** [comment]
Yes I didn't create Eva an account on the old server , which now looks much more like an oversight. Sorry Eva!

**Comment by mattl** [comment]
@evarogers Permissions are fixed... please login to CiviCRM :)
