### ISSUE TITLE
Please add PIA to supporters footer on homepage

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#363]
PIA name with logo (you should have on file from the global summit) should be listed among this group, which is in alpha order with the exception of hewlett who should remain at the top. If there's a 6 supporter max in terms of space, please remove ford to make room. Thanks!

<img width="1196" alt="screen shot 2016-07-15 at 10 56 30 am" src="https://cloud.githubusercontent.com/assets/13322149/16883911/5fecd292-4a7b-11e6-8af6-77729ffa5987.png">

**Comment by mattl** [comment]
This one?
![](https://summit.creativecommons.org/2015/img/logos/privateinternetaccess.png)

**Comment by rebeccalendl** [comment]
There's a better one with a bit more. Just fwded higher res via email.

**Comment by mattl** [comment]
Putting them here

[pia-logos.zip](https://github.com/creativecommons/creativecommons.org/files/366802/pia-logos.zip)

**Comment by mattl** [comment]
Logos in email

**Comment by rebeccalendl** [comment]
Thank ya :)

**Comment by rebeccalendl** [comment]
By EOD would be a dream. It is part of our agreement and was a miss on my part not to have included it with the new site launch. Much appreciated.

**Comment by mattl** [comment]
I can get it up on Monday, wrapping up a few other things today

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccalendl** [comment]
All set thanks for jumping in @evarogers and @little-wow!
