### ISSUE TITLE
http://blog.creativecommons.org/ needs a redirect

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#365]
http://blog.creativecommons.org/ produces an error. Should redirect to http://creativecommons.org/blog/

**Comment by mattl** [comment]
Did you find a link to http://blog.creativecommons.org in the wild? Note that the redirect works over HTTPS, which is all that site ever served.

**Comment by janeatcc** [comment]
Ah, got it. No just in my browser history. Closing.
