### ISSUE TITLE
Old donation page from /remix

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#386]
If you find yourself here https://creativecommons.org/use-remix/ideas/ and you take a minute to fill out that form (where do those answers go? a question for another day), you get sent to this page:

https://donate.creativecommons.org/civicrm/contribute/transact?reset=1&id=31
GASP! It's an old donation page, old design, old info about getting on the supporters page, and it still gives gifts for donations or a certain amount. 

Can you have /remix send to a new donation page?
How can I disable/delete that old one that I found so that it never appears to anyone again?

Thanks!
Mari

@rebeccalendl -- just flagging for you so you see that it's filed!

**Comment by mattl** [comment]
Perfect, I added a rule that should redirect any old donation pages.

Anything starting "/civicrm/contribute/transact"
