### ISSUE TITLE
CC Rel by example is missing

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#387]
http://labs.creativecommons.org/2011/ccrel-guide/

https://wiki.creativecommons.org/wiki/CC_REL

https://twitter.com/kkvie/status/755826294928076800

**Comment by robmyers** [comment]
@little-wow Oh this was in a git submodule we didn't check out.

I've checked that out and rebuilt the labs site now, the ccrel-guide now works.

Thank you for reporting this!

@mattl the Twitter report also mentions /ns being broken, not sure if it's primarlity a redirect problem or not.

**Comment by mattl** [comment]
https://github.com/creativecommons/creativecommons.org/issues/344

**Comment by robmyers** [comment]
Cool. Increasing priority of #344 and closing this one.
