### ISSUE TITLE
Why won't this email start sending?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#388]
<img width="1036" alt="screen shot 2016-07-20 at 4 39 45 pm" src="https://cloud.githubusercontent.com/assets/7093838/17002298/a24a27ea-4e98-11e6-9c5f-633bbd9e4a06.png">

**Comment by mattl** [comment]
As with CiviCRM previously, you need to manually push the emails out the door.

Go to Adminster > System Settings > Scheduled Jobs and Execute the mailing job.

![screenshot from 2016-07-21 11-53-18](https://cloud.githubusercontent.com/assets/33296/17031450/e49101d6-4f39-11e6-8303-486610496d47.png)

**Comment by mattl** [comment]
Want to get some time this week to talk about this with @ericsteuer and @little-wow
