### ISSUE TITLE
Civi keeps redirecting to the homepage

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#389]
When I click on certain links on Civi it redirects back to the CC homepage with a notice that says "This page has moved." Here is one URL where that happens: https://donate.creativecommons.org/civicrm/admin/messageTemplates?reset=1

**Comment by mattl** [comment]
Yeah, that's intentional because it's redirecting you to the donate page. You should be able to login at /user/ and do anything in CiviCRM under /civicrm/ without hitting the homepage.

**Comment by little-wow** [comment]
Hi @robmyers ! This is happening again and I can't seem to fix it.
Rebecca says it has to do Civi outgoing message templates that you all talked about recently.
Thanks!

**Comment by rebeccalendl** [comment]
Yeah, when I go to Admin / Comms / Message Templates to kill that outgoing message we discussed that shouldn't be sending, it redirects me to the CC website donate page. Anna thinks it may have something to do with a /donate automatic redirect that needs an exception. Any ideas? It's this https://creativecommons.org/donate/?utm_campaign=redirect_donate_ccorg&utm_source=redirect_donate_ccorg

**Comment by robmyers** [comment]
Yikes. That's not happening for other links under /admin/comms, just the one.

It's a 403 error (Access Forbidden), which then results in a redirect.

I'm investigating why it's causing a 403.

**Comment by robmyers** [comment]
The "Edit Message Templates" permission wasn't checked for administrators(!). I've enabled it.

We should now be able to follow that link.

**Comment by rebeccalendl** [comment]
That works! Thanks so much.
