### ISSUE TITLE
Send me a profile and a headshot

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#39]
@mmoreshead -- you were left off the spreadsheet cause i copied the names from the staff page.

Let's fix that.

See www.creativecommons.org/staff for typical profile.

**Comment by mmoreshead** [comment]
Yes, it's on my to-do list!

**Comment by mmoreshead** [comment]
Is this too boring?  

Toronto, Ontario
Started: February 2015

Mari comes to CC after three years at the Mozilla Foundation in administration.  Prior to that, she held similar roles at a legal technology start up and the Playful Invention Company.  She's lived in a number of Canadian cities but now calls Toronto home where she lives with her partner and their two cats.

**Comment by mattl** [comment]
No, this is good. Drag and drop a photo in here, and I'll put you up on the site.

**Comment by mmoreshead** [comment]
![mari_moreshead-6278](https://cloud.githubusercontent.com/assets/11162279/6399648/d2f509dc-bdc1-11e4-833d-aa5ecc157160.jpg)

**Comment by mattl** [comment]
You're up. Welcome to CC.

**Comment by mattl** [comment]
* Mari works through 0941176 B.C. Ltd., a wholly owned subsidiary of Creative Commons whose sole activity is to provide services to CC. 0941176 B.C. Ltd. is operated separately from our CC Canada affiliate.

Need to add disclaimer

**Comment by peterspdx** [comment]
Mari, it's great.  And what a beautiful photo!

Diane

On Thu, Feb 26, 2015 at 3:23 PM, Matt Lee <notifications@github.com> wrote:

>
>    - Mari works through 0941176 B.C. Ltd., a wholly owned subsidiary of
>    Creative Commons whose sole activity is to provide services to CC. 0941176
>    B.C. Ltd. is operated separately from our CC Canada affiliate.
>
> Need to add disclaimer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/creativecommons.org/issues/39#issuecomment-76297553>
> .
>



-- 
Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
