### ISSUE TITLE
New Turkish subtitles for CC Remix video

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#392]
This one: https://vimeo.com/151666798

Do we have anyone who checks these?  Should I run them by the turkish affiliates first?

**Comment by peterspdx** [comment]
That would be great, @mmoreshead though there's no formal process or need for translations (the CC license allows it). If you need the email address for the lead, let me know.

**Comment by mmoreshead** [comment]
About to send a note to Turkey, but  -- @mattl how do I advice them to open this .srt file?

**Comment by mattl** [comment]
Suggest they download the video from https://vimeo.com/151666798 and then use a tool like VLC to play with the file. http://www.wikihow.com/Add-Subtitles-to-a-Movie/Video-on-VLC

**Comment by mmoreshead** [comment]
Thanks @mattl - sent to our Turkish friends for review!

**Comment by mattl** [comment]
:+1:

**Comment by mmoreshead** [comment]
I'll nudge the affiliate.

**Comment by mmoreshead** [comment]
Ilkay reached out to the two men who translated it and they all agreed on a few changes.  They returned this file to me.  I'm not sure if this is the right format for it though.  Let me know.

[new cc remix master.tr.srt.txt](https://github.com/creativecommons/creativecommons.org/files/516194/new.cc.remix.master.tr.srt.txt)

**Comment by robmyers** [comment]
It doesn't need the .txt suffix but otherwise looks good.

**Comment by mmoreshead** [comment]
How do I add it @robmyers ?

**Comment by robmyers** [comment]
You'll need the Vimeo login, and then you should be able to upload it to go with the video -

https://vimeo.com/help/faq/managing-your-videos/captions-and-subtitles#how-do-i-add-caption-and-subtitle-files-to-my-videos

**Comment by mmoreshead** [comment]
Ok!

**Comment by mmoreshead** [comment]
I DID IT, I DID IT!
