### ISSUE TITLE
3D Printing form appears to only be providing answers of "1"

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#393]
I tested this form, so it may be that someone is just typing in "1," but just in case it's not, I'm making this ticket

<img width="1117" alt="screen shot 2016-07-25 at 3 03 50 pm" src="https://cloud.githubusercontent.com/assets/7093838/17113500/06a1127e-5279-11e6-8f43-d9f01e467d55.png">

**Comment by mattl** [comment]
Is there other data besides your email address and these 1s?

**Comment by little-wow** [comment]
now there's another test and it seems to have entered just fine
