### ISSUE TITLE
Trying to find a few data points

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#394]
1. Is there a way to see newsletter growth over time?
2. Is there a way to view individual emails in Sendgrid or do I have to filter stats by day?
3. I still can't find the "newsletter" signup email

**Comment by mattl** [comment]
1. You can run queries in CiviCRM against the group based on periods of time. Another way we used to keep track of this at the FSF was to put the number of subscribers in the email. You can see it here: http://www.fsf.org/free-software-supporter/2016/july

2. You can see the emails in CiviCRM under "Scheduled and Sent" -- you can see all the previous emails and you'll be able to see their delivery numbers.

3. Do you have a ticket open for it?

**Comment by little-wow** [comment]
I'm looking for individual email open and CTRs, not for number sent.

And yes-- https://github.com/creativecommons/communications/issues/18#issuecomment-231399042

That's not where it lives anymore

**Comment by mattl** [comment]
I think there's also this ticket? https://github.com/creativecommons/creativecommons.org/issues/390

Let's get a list of all these things ready for tomorrow's meeting.
