### ISSUE TITLE
Author being displayed in Google results for team members

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#395]
@fmann , @little-wow noticed that Author is seen in Google result for some team members. e.g. 

https://www.google.ca/?ion=1&espv=2#q=Eva+Rogers+creative+commons

![screen shot 2016-07-25 at 2 45 35 pm](https://cloud.githubusercontent.com/assets/6674702/17118986/2ae5a93e-5278-11e6-98d3-e9f221da6d60.png)

I think that is because Author makes it into the page title for certain users, like https://creativecommons.org/author/eva-rogers/ . Thought it doesn't seem to always happen, e.g. https://creativecommons.org/author/jenniecreativecommons-org/ . Is it possible to adjust to 

Eva Rogers, Creative Commons

**Comment by fmann** [comment]
@ageeroms  I don't have access to log into the site, but it looks to me like that is managed by a Yoast SEO setting.  Look under SEO > Titles & Meta > Archives

![screen shot 2016-07-25 at 3 14 20 pm](https://cloud.githubusercontent.com/assets/711497/17119402/80d70ec6-527a-11e6-8b23-724b9f224402.png)

I think the default author archive title can be modified there.

**Comment by ageeroms** [comment]
Thanks @fmann ! @little-wow Floyd is pointing at where this setting needs to be updated. Can you please take a look there? Once you've removed the Author string, verify that has removed it by checking team member page source. It might take a little while for Google to update their results.

Cheers,
Anna

**Comment by little-wow** [comment]
Made the change and waiting for it to show up
