### ISSUE TITLE
develop way to automatically add a new language to language list at bottom of legal code

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#396]
Once a new legal code translation is published, we currently have to manually add a link to it in the files of all previously published license translation files (6 for each language) in order to have it appear as an option in the language list at the bottom of the legal code. Is there a way to automate this process? 

Assigning to @robmyers as discussed in the last legal/tech chat. Thanks!

**Comment by robmyers** [comment]
@sarahpearson Without wishing to appear lazy, I wonder if this is something we could discuss with the web design people? Might be a good opportunity to implement this.

**Comment by sarahpearson** [comment]
We all know how lazy you are, @robmyers. But this sounds like a good idea
to me! Do you know what the process for that is?

**Comment by robmyers** [comment]
I implemented a script to add links for licenses.. It's been used for the last couple of translations and seems to be working well.
