### ISSUE TITLE
Staging server is up, please confirm you can access it

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#397]
ssh affinitybridge@stag.creativecommons.org

You should have sudo access. Your password is the first word of your company name. Please change this immediately and keep it secure amongst yourselves. I've taken some pull requests, so the repos in /var/www/ will need to be pulled and updated. 

The whole site is "protected" by htpasswd 'creative'/'commons' :)

WordPress is https://staging.creativecommons.org/wordpress/wp-admin/

Anna has admin access. Feel free to give anyone else at AB admin access.

**Comment by fmann** [comment]
Yes, I can ssh in.

**Comment by mattl** [comment]
Excellent. I'll close this, and make a new ticket for anything else that comes up, or if you need @robmyers or I to do something else  :)

Happy hacking
