### ISSUE TITLE
Arab and Asia-Pacific regional pages on Wiki

### ISSUE THREAD

**Issue by soohyunpae** [creativecommons/creativecommons.org#398]
When I clicked CC Arab world(http://arabic.creativecommons.org/) and CC Asia-Pacific(http://creativecommons.asia/) on https://wiki.creativecommons.org/wiki/Affiliates, I was taken to a Lexus car repair website.

Could you fix the links to the original webpages or at least to CC blog for now?

Thanks!

**Comment by little-wow** [comment]
I checked all the other sites I could and found no others with an unusual redirect. I fixed those two.  Leaving the ticket open in case Matt sees anything else that's strange.

**Comment by mmoreshead** [comment]
I'm working with Rob to get rid of the new spam pages.  Yay!

**Comment by mattl** [comment]
It seems like an old IP address for an old website got reused by a car company.
