### ISSUE TITLE
Newsletter sign-up?

### ISSUE THREAD

**Issue by soohyunpae** [creativecommons/creativecommons.org#399]
I entered my email address to sign up for CC newsletter and then was directly taken to the Donate page. I think it'll be better to see a confirmation page with a link to the Donate page on it.
I didn't get any confirmation message to my mail box either yet.

Thanks!

**Comment by little-wow** [comment]
Have you gotten the confirmation email yet?  It can take a bit of time

**Comment by soohyunpae** [comment]
@little-wow No, I haven't yet.

**Comment by mattl** [comment]
Please try again, I just got the email within seconds.

**Comment by soohyunpae** [comment]
Hi @mattl I tried again, and this time it took me to next steps. Please see the screenshots below:
<img width="1280" alt="screen shot 2016-07-29 at 11 39 14 am" src="https://cloud.githubusercontent.com/assets/4001041/17236424/d7d501cc-5583-11e6-89bf-02a4cf3868c9.png">
<img width="1280" alt="screen shot 2016-07-29 at 11 43 32 am" src="https://cloud.githubusercontent.com/assets/4001041/17236426/d9da44be-5583-11e6-84ec-c20b274be8b3.png">

But I still haven't gotten the email yet.

**Comment by mattl** [comment]
You're probably already on our list?

Try name+test@example.com with your own email address. The +test let's you
try a new address.

**Comment by little-wow** [comment]
Also @soohyunpae did you check you spam folder?

**Comment by soohyunpae** [comment]
Ahh, you were right @mattl - I tried +test and it worked this time. So that means I'm already on the list, right? Sorry about the fuss!
