### ISSUE TITLE
Revealing jurisdictions on chooser doesn't display correctly across languages

### ISSUE THREAD

**Issue by vthunder** [creativecommons/creativecommons.org#4]
On most languages (other than English), revealing the jurisdictions drop-down does not resize the box it's in, causing the drop-down & text to overflow.

For example (using Italian), see screenshot:

![screen shot 2013-12-05 at 9 12 20 pm](https://f.cloud.github.com/assets/435972/1689970/0dd66a84-5e35-11e3-933b-c088f5031086.png)

**Comment by robmyers** [comment]
The chooser designed was changed, so this is no longer an issue.
