### ISSUE TITLE
Publish Dutch 4.0 translation

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#40]
Maarten approved the files, so they are ready to go live. Once it's done, let me know and I'll publish a blog post.

**Comment by mattl** [comment]
Everything here is ready to go? http://cc4-nl-legalcode.legal.creativecommons.org/licenses/by/4.0/legalcode.nl

**Comment by peterspdx** [comment]
These have my OK, having glanced one last time.  Please let Sarah respond as she was working the details of links and similar.  

Congrats, Maarten et.al., you're finishing a close second to the Finnish!

@Sarah, let's be sure to update this page (https://wiki.creativecommons.org/List_of_completed_translations) when the time comes.

Diane

**Comment by sarahpearson** [comment]
Yes, those are the updated files that Maarten gave his final signoff.
Thanks, Matt!

(@Diane, yes, that step plus a few others are on the final translation
checklist. I'll make sure it all gets done.)

S.

Sarah Hinchliff Pearson
Senior Counsel, Creative Commons
Donate to Creative Commons! donate.creativecommons.org
______________________________

Please note: the contents of this email are not intended to be legal
advice nor should they be relied upon as, or represented to be legal
advice.

**Comment by sarah** [comment]
Hello! 

Be aware when you type "@sarah" you get me, as that is my github name, not the person on your project.  I'm not sure if your project is private, but now I have access to it.... From my past experience with this, I will now have access in perpetuity b/c of the one email.   
Something to be aware of.
