### ISSUE TITLE
Upgrade to GravityForms 2

### ISSUE THREAD

**Issue by fmann** [creativecommons/creativecommons.org#401]
Starting a thread here for the GF upgrade. 

Data structure-wise it looks like things stay the same, but there are major changes to the front-end code between GF 1.x and 2.x. We need to upgrade GF on the staging site and fix the display code prior to upgrading production.

We also need to check if there are any changes to the API that impact the civicrm integration work.

**Comment by fmann** [comment]
Hey @mattl... Any idea why on stage when I replace the GF plugin with the 2.0 version it doesn't take? I see "Version 2.0.3" on the plugin screen but then it also says "There is a new version of Gravity Forms available. View version 2.0.3 details or update now".  I see ?ver=1.9.19 in the source of the pages too, so ... the new plugin is there but not taking.

I was going to poking around in the DB to see if I could find where that is cached, but there is no mysql client or mysqldump installed on the staging server. So.. I'm a bit stumped on how to proceed.

I've switched back to the 1.9.19 version at /var/www/tmp/plugins/gravityforms for now.

**Comment by fmann** [comment]
Restarting apache and varnish fixed it. Aggressive caching you've got there.

**Comment by fmann** [comment]
@mattl I've issued two pull requests for these changes, one for the theme and one for the plugins.

https://github.com/creativecommons/new-creativecommons.org/pull/29
https://github.com/creativecommons/new-www-theme/pull/7

**Comment by mattl** [comment]
@fmann -- there's a conflict on https://github.com/creativecommons/new-www-theme/pull/7 -- I think the changes made to support #346 -- can you incorporate those into your update?

**Comment by fmann** [comment]
@mattl Conflict cleared.

**Comment by mattl** [comment]
Great. Going to pull to the staging site

**Comment by mattl** [comment]
Looks good here -- https://staging.creativecommons.org/donate/

**Comment by fmann** [comment]
Hmm, one issue on the homepage email box.

**Comment by mattl** [comment]
What's the issue? I'm not seeing it.

**Comment by mattl** [comment]
![screenshot from 2016-07-29 12-57-08](https://cloud.githubusercontent.com/assets/33296/17258327/f904b1b4-558b-11e6-8440-8a68c3d7acfe.png)

**Comment by fmann** [comment]
Hm in Safari I'm seeing 
![screen shot 2016-07-29 at 11 01 51 am](https://cloud.githubusercontent.com/assets/711497/17258489/ed4a0172-557b-11e6-8114-af44bbcab749.png)

Trying to figure out if I just have something cached.

**Comment by mattl** [comment]
Do you see the same thing on https://creativecommons.org ?

**Comment by fmann** [comment]
Yeah, actually I do. So I guess it has nothing to do with this pull request.
