### ISSUE TITLE
Request to grant editing over the Wiki page of Egypt

### ISSUE THREAD

**Issue by hsawires** [creativecommons/creativecommons.org#402]
@mattl I need to grant editing over the Wiki page of Egypt.
[https://wiki.creativecommons.org/wiki/Egypt]
we have some updates, news and materials we want to post it.

**Comment by hsawires** [comment]
Hi @mmoreshead .. sorry I forgot to mention it.
It's hani.sawiress@bibalex.org but when I try to login I always be redirected to "ValidateReminder" page [https://wiki.creativecommons.org/wiki/ValidateReminder](url)

I have to tell you that because I didn't see my CCID in the wiki page, in spite of validating my email previously.

**Comment by mmoreshead** [comment]
Your CCID isn't your email address - it's a username.  I can't approve your account without it.

Maybe @robmyers can tell us what this error message is about. He'll be online in a few hours.

**Comment by hsawires** [comment]
but I did logged using my email at [https://login.creativecommons.org/login](url)
Anyway, I can wait for @robmyers, 
Thank you.

**Comment by mmoreshead** [comment]
Yes, you do login with your email address, you're not wrong.  The thing that I need to approve your account is the CCID username.  Even if you did know it now and I did approve your account, this wouldn't solve your validation error. Sorry :(

**Comment by mattl** [comment]
@hsawires you've not completed the steps for your CCID registration -- see https://wiki.creativecommons.org/wiki/ValidateReminder and follow those instructions. Then you'll be asked to set a username on your account, and then you'll need to give that username to @mmoreshead

**Comment by hsawires** [comment]
@mattl I have completed all required step I even reset my password several times. and I sent from long time ago to webmaster@creativecommons.org with this problem, following the instructions in the page [https://wiki.creativecommons.org/wiki/ValidateReminder](https://wiki.creativecommons.org/wiki/ValidateReminder) as mentioned 

> "If you have followed the instructions in the confirmation email but you're still seeing this page, we're very sorry! Please contact us and we'll investigate:
> 
> webmaster@creativecommons.org
> "

ad till now I cant login to the wiki page and I didn't receive any response from webmaster@creativecommons.org

**Comment by mattl** [comment]
@hsawires When you login to the wiki, do you see your name in the top right of the screen?

This is what I see:

![screenshot from 2016-08-01 14-50-23](https://cloud.githubusercontent.com/assets/33296/17306745/4af01032-57f7-11e6-8789-5d1921afb128.png)

**Comment by mmoreshead** [comment]
I had someone else who couldn't log in after they created their CCID - maybe related?  They knew their CCID but I can't find them when I look them up.

**Comment by mattl** [comment]
@mmoreshead sounds like they're not verified. Do you have their email address? Feel free to give me just the part before @ so I can look them up.

**Comment by mmoreshead** [comment]
mattl: it's Neelsanders -- I can't find them when I try to grant rights.  I tried with a small N too but no results.
