### ISSUE TITLE
audit@ mailing list

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#403]
Hi, we need to change the recipients of the audit at cc.org mailing list/or whatever it is.  Mari can supply email addresses privately.  Thanks!

**Comment by mattl** [comment]
@mmoreshead Send em over and I'll do it now.

**Comment by mattl** [comment]
m

**Comment by mmoreshead** [comment]
Thank @mattl !

**Comment by peterspdx** [comment]
Can you confirm that I'm still on that, however? One staff member (me at this point) needs to be there. Thanks, and thanks to Mari for picking up on this. I thought we had done it previously.

**Comment by mattl** [comment]
Yup, you're there, along with Ryan and 3 board members.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC
