### ISSUE TITLE
revive the DMCA page that was lost during site migration

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#406]
It looks like we lost the DMCA policy page when the new website went up: 

https://creativecommons.org/dmca

@mattl can you help put it back up? I was out during the site migration, so I'm not sure what the workflow is for these sorts of issues. Let me know if I should file this elsewhere, assign something else, etc. Thanks!

**Comment by mattl** [comment]
https://creativecommons.org/dmca/
