### ISSUE TITLE
Test Gravity Forms Extension Against Gravity Forms Update

### ISSUE THREAD

**Issue by alkrieger** [creativecommons/creativecommons.org#409]
From the Giant Rabbit Redmine Queue: https://support.giantrabbit.com/issues/26747

After the Gravity Forms upgrade in #401 , we need to test the GF extension with the new version of Gravity Forms. Affinity Bridge has installed the updated version and it's ready to rest on https://staging.creativecommons.org/.

**Comment by alkrieger** [comment]
@mattl It looks like I don't have assignee permissions - would you please assign this issue to @anemirovsky?

**Comment by alkrieger** [comment]
Hey @mattl 
Anthony began testing, but we'll need a new set of public/private API keys for both the staging and production Gravity Forms instances. Once we get those, we can resume testing. You or Affinity Bridge can shoot those to us with https://ots.giantrabbit.com/ if you'd like. Thanks!

**Comment by mattl** [comment]
Invited @anemirovsky to join CC's GitHub organization, then we can assign things to them. You should also have the power to assign now.

**Comment by mattl** [comment]
@alkrieger I don't think I have a login for OTS. I'll send them via email.

**Comment by alkrieger** [comment]
Thanks for these!

**Comment by mattl** [comment]
Let me know if we need to add an IP address exception to Apache to get around the htpasswd thing.

**Comment by mattl** [comment]
@ageeroms Can you ask Anthony to visit https://github.com/creativecommons and accept the invite?

**Comment by alkrieger** [comment]
We can leave this assigned to me - I can assign anything else in Redmine.

**Comment by alkrieger** [comment]
Hello @rebeccalendl 

We tried to access the gravity forms api on staging.creativecommons.org, and we are getting a 404 Not found. This is the url we used:
https://staging.creativecommons.org/gravityformsapi/forms/3/entries?api_key=3582045be1&signature=Xn9vqCiVh4qojU8hkI%252Fo%252FQmobM4%253D&expires=1474329161&paging%5Bpage_size%5D=100&search=%257B%2522field_filters%2522%253A%255B%257B%2522key%2522%253A%2522payment_status%2522%252C%2522operator%2522%253A%2522is%2522%252C%2522value%2522%253A%2522Paid%2522%257D%252C%257B%2522key%2522%253A%252223%2522%252C%2522operator%2522%253A%2522is%2 522%252C %2522value%2522%253A%25220%2522%257D%255D%257D

Can you let us know what the endpoint is for the api on staging?

**Comment by ageeroms** [comment]
@robmyers , please assign to @fmann

**Comment by fmann** [comment]
Using the url that @alkrieger posted I'm getting a 401 permission denied, not a 404, but I think that is just because it is expired.  A fresh request works fine for me.

These URLs should not be included on public ticket repos as they can contain sensitive information. The url in @alkrieger's post should be deleted.
