### ISSUE TITLE
Podcast Plugs, where'd they go?

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#420]
A user reached out to find out where the Podcast Plugs went.  They used to live at creativecommons.org/podcasting but that page now redirects to https://creativecommons.org/2006/11/28/podcasting-legal-guide/  The link on the wiki to the plugs is also cc.org/podcasting (https://wiki.creativecommons.org/wiki/Welcome_To_The_Podcasting_Legal_Guide )

Any idea where they went?

**Comment by mattl** [comment]
https://creativecommons.org/podcasting works for me

https://creativecommons.org/podcast will redirect to that blog post. 

@ericsteuer may want /podcast to go somewhere better

**Comment by mmoreshead** [comment]
Weird, they both redirect to the blog post for me.

**Comment by mattl** [comment]
that's weird. if i'm logged in, they work correctly, if i'm not they don't...

**Comment by mattl** [comment]
Okay, i resaved the plugs page and it seems to work for me logged out now. Can you confirm?

**Comment by mmoreshead** [comment]
Yay fixed!
