### ISSUE TITLE
old blog post not redirected to new site

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#421]
why doesn't https://creativecommons.org/blog/2016/06/13/tell-european-commission-fixcopyright/ redirect to https://creativecommons.org/2016/06/15/tell-european-commission-to-fixcopyright/?

**Comment by mattl** [comment]
Why would it?

Different names for the posts.

**Comment by tvol** [comment]
well that's how the original was posted, so i'm not sure why the new one has a different name/date?

**Comment by mattl** [comment]
i'm guessing the post was copied over from the old site to the new one?

**Comment by tvol** [comment]
@mattl you might be right. i think there were a few that had to be done manually, so maybe that's why it didn't map over

**Comment by mattl** [comment]
But those should never be on creativecommons.org/blog/ -- they might be blog.creativecommons.org -- or very old ones were creativecommons.org/weblog/

**Comment by tvol** [comment]
well, this tweet contains a link with blog.cc.org, but then it directs to the cc.org/blog that i mentioned https://twitter.com/creativecommons/status/742451629274763264

**Comment by mattl** [comment]
Edited the slug and the date :)
