### ISSUE TITLE
trying to update a page on the site, get "you've been blocked"

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#423]
i'm trying to update the text on https://creativecommons.org/about/program-areas/legal-tools-licenses/

when i attempt to preview my updates, i get this page:

<img width="1208" alt="screen shot 2016-08-04 at 12 29 37 pm" src="https://cloud.githubusercontent.com/assets/8919762/17415624/7b681ae4-5a3f-11e6-8ce5-4ff54da2c1f8.png">

**Comment by mattl** [comment]
can you give me the Ray ID at the bottom of the page?

**Comment by ericsteuer** [comment]
2cd46b23f0eb1e6b

**Comment by mattl** [comment]
one sec

**Comment by ericsteuer** [comment]
also happens when i hit update (and now my updates are gone, ugh!)

**Comment by mattl** [comment]
I'm sorry your updates are gone :(

Can you try making a very small update?

**Comment by ericsteuer** [comment]
It works. Thanks!
