### ISSUE TITLE
 Toolkit page weirdness

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#425]
https://creativecommons.org/platform/toolkit/

On this toolkit page, it has an English/Francais option on the top like the FAQ.  I thought, "I didn't know we'd translated the toolkit."  So I clicked French.  I was right!  We didn't translate the toolkit -- when you click Francais, it takes you to the French FAQ.

**Comment by mattl** [comment]
https://github.com/creativecommons/mp/commit/dff75a13d15d5b6fa1ea1153d12e2bb572c91897 fixes it.

I'll rebuild on the servers now.
