### ISSUE TITLE
Civi won't upload an image

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#426]
Screenshots below

<img width="514" alt="screen shot 2016-08-04 at 4 36 13 pm" src="https://cloud.githubusercontent.com/assets/7093838/17417500/b6facc7e-5a61-11e6-823d-a4f780c35753.png">
<img width="1242" alt="screen shot 2016-08-04 at 4 36 24 pm" src="https://cloud.githubusercontent.com/assets/7093838/17417503/b7002822-5a61-11e6-8d73-2dfe9be0fbc8.png">
<img width="798" alt="screen shot 2016-08-04 at 4 36 53 pm" src="https://cloud.githubusercontent.com/assets/7093838/17417507/b7153b9a-5a61-11e6-9a56-0a6f9b7bfc24.png">
<img width="1135" alt="screen shot 2016-08-04 at 4 37 02 pm" src="https://cloud.githubusercontent.com/assets/7093838/17417502/b6fefc5e-5a61-11e6-95c7-a94a60263418.png">

**Comment by mattl** [comment]
It works fine here. Can you try with another image? Double check that your image is actually a JPEG too.

**Comment by little-wow** [comment]
Same thing, and they have both been JPEGS.  This has happened to me before, and I basically had to just walk away

**Comment by little-wow** [comment]
I've refreshed the page and tried with a variety of images

**Comment by mattl** [comment]
Can you try it in an incognito browser window? Possible you have a browser add on that's messing with it.

Can you also attach the JPEGs here and I'll try them.

**Comment by little-wow** [comment]
that worked
