### ISSUE TITLE
No gap in between sections on the page

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#428]
Every other section has a consistent gap between them, except between what's happening and stay tuned to the commons, and the varying shades of mustard strike me as possibly not very accessible

<img width="1244" alt="screen shot 2016-08-04 at 5 16 53 pm" src="https://cloud.githubusercontent.com/assets/7093838/17418633/852d24fc-5a67-11e6-98b0-d7dabaa6f294.png">

**Comment by mattl** [comment]
I believe that's in the design that was agreed to. You can check the page out with a color blind simulation tool for starters. I'll leave it up to @ageeroms to confirm the design.

**Comment by ageeroms** [comment]
It was the design agreed to. Yellow is wrapped around the posts and newsletter to indicate they're all about what's happening with CC:
![home_v1__creative_commons_website_redesign__round_four_and_when_we_share__everyone_wins_-_creative_commons](https://cloud.githubusercontent.com/assets/6674702/17452098/fb761e3e-5b20-11e6-8102-7401b9b1c14c.png)

Also, I don't think their is an accessibility limitation here.  If you were colour blind, you could recognize the content is connected as well. See 

![screen shot 2016-08-05 at 3 25 35 pm](https://cloud.githubusercontent.com/assets/6674702/17452132/42f4710c-5b21-11e6-8325-7b1daf58570d.png)
![screen shot 2016-08-05 at 3 25 24 pm](https://cloud.githubusercontent.com/assets/6674702/17452134/42f7ed32-5b21-11e6-8b78-d4f3dcb7e139.png)
![screen shot 2016-08-05 at 3 25 13 pm](https://cloud.githubusercontent.com/assets/6674702/17452133/42f62ee8-5b21-11e6-904d-e2b5b13f9e9d.png)

**Comment by little-wow** [comment]
okay, thanks
