### ISSUE TITLE
Email newsletter signup on front page sends user through non-ideal workflow

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#431]
<img width="1240" alt="screen shot 2016-08-04 at 6 01 47 pm" src="https://cloud.githubusercontent.com/assets/7093838/17419899/9eefc204-5a6d-11e6-80a6-6472b7cbd630.png">
<img width="1234" alt="screen shot 2016-08-04 at 6 01 54 pm" src="https://cloud.githubusercontent.com/assets/7093838/17419901/a04374ca-5a6d-11e6-86c1-e25ff7a54762.png">

I tried this in incognito and with two browsers. I also used 2 different personal emails (not on list) as well and the same thing happened every time.

**Comment by mattl** [comment]
Fixed.
