### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#433]
Webmaster tools is showing that we haven't submitted a sitemap:

<img width="346" alt="screen shot 2016-08-08 at 2 15 02 pm" src="https://cloud.githubusercontent.com/assets/7093838/17490773/884be980-5d72-11e6-83bc-755ea2aff5c3.png">

**Comment by mattl** [comment]
I'm seeing one here -- https://www.google.com/webmasters/tools/sitemap-list?hl=en&siteUrl=http://creativecommons.org/#MAIN_TAB=0&CARD_TAB=-1
