### ISSUE TITLE
Put mission and vision back on site?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#435]
The mission and vision here:

<img width="707" alt="screen shot 2016-08-09 at 7 33 12 am" src="https://cloud.githubusercontent.com/assets/7093838/17514951/8b50a56c-5e03-11e6-91b2-9d383d425863.png">

Got lost in the content shuffle on the new site. Ryan and Eva were recently looking for it-- should we put some version of it on the new version of the site?

**Comment by rebeccalendl** [comment]
Yes, thanks

**Comment by little-wow** [comment]
creativecommons.org/about/mission-and-vission
