### ISSUE TITLE
Create py.creativecommons.org

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/creativecommons.org#437]
"A" 195.154.200.92
or 
"CNAME" to rafaelbarrett.tedic.net

(the affiliate prefer the latter).

thanks!

**Comment by morisbartyno** [comment]
![jc](https://cloud.githubusercontent.com/assets/14913140/17647533/9738a4ac-620d-11e6-8bc2-d2810b6d09e2.png)

**Comment by kgodey** [comment]
Closed per @claudioruiz on Slack.
