### ISSUE TITLE
change twitter feed on https://creativecommons.org/blog/ to just display tweets from CC account?

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#442]
I noticed it's mostly just retweets of whatever is our latest tweet. Maybe it's worth testing out only displaying the latest from the actual CC account so you can see a bit of diversity in tweets there? just an idea.

**Comment by ericsteuer** [comment]
ooh yeah, hadn't noticed that. that's no good.

**Comment by ageeroms** [comment]
@fmann , can you take a look at the possibilities here? As I understand it, CC team would prefer is the feed on https://creativecommons.org/blog/ only showed direct tweets, not retweets or replies.

Does the current plugin allow you to pick what type of Tweets? If not, is there another option, which would?

**Comment by fmann** [comment]
I think we're better off ditching the plugin and just using a widget direct from Twitter.  I went here:

https://publish.twitter.com/#

And generated I sidebar widget that is now on:

https://staging.creativecommons.org/blog/

It displays the correct content without all the retweets.

**Comment by ageeroms** [comment]
That looks great @fmann. Thanks for looking at that. @little-wow , you agree? If so, @robmyers , can you remove the atom feed and placed a text widget with the code Floyd generated instead?

**Comment by robmyers** [comment]
@little-wow let me know and I'll add this.

**Comment by little-wow** [comment]
This looks great!  I tried to modify the plugin yesterday but this looks much, much better. Thank you!

**Comment by robmyers** [comment]
Added to the live site, see here for example -

https://creativecommons.org/blog/

Thank you, this is great.

**Comment by little-wow** [comment]
@robmyers @fmann can we add a limit to these tweets? It's showing a lot on one page: https://creativecommons.org/blog

**Comment by fmann** [comment]
It looks like we can't set the number of tweets but there is a data-height attribute that can be added to limit the height.

```
<a class="twitter-timeline" data-height="400" href="https://twitter.com/creativecommons">Tweets by creativecommons</a>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

**Comment by robmyers** [comment]
It's in Appearance -> Widgets -> Sidebar -> Text.

The embed code is created at:

https://publish.twitter.com/

Here's one where the height can be modified (witdth must be > 220 according to the docs.)

<a class="twitter-timeline" data-width="220" data-height="200" href="https://twitter.com/robmyers">Tweets by robmyers</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by little-wow** [comment]
looks great @fmann ! Thank you!

**Comment by little-wow** [comment]
@fmann did this ever go live?

**Comment by robmyers** [comment]
@little-wow Take a peek in the widgets on the live site and copy it over if not?

**Comment by little-wow** [comment]
done
