### ISSUE TITLE
Add stock photo sites to the places to share page?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#443]
https://creativecommons.org/about/platform/

Doesn't have:
Unsplash
Pexels
+ a few more super common stock photo sites

Should we add them?

**Comment by mmoreshead** [comment]
We have this on the wiki if that helps. https://wiki.creativecommons.org/wiki/Category:Image_Directories

**Comment by janeatcc** [comment]
No. This page is not meant to be comprehensive.
