### ISSUE TITLE
FAQ link goes to staging

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#444]
The FAQ link in the footer on https://creativecommons.org/choose/ goes to staging so it doesn't work :(  

Not sure if this something you can help with @little-wow ?

**Comment by little-wow** [comment]
IDK where this lives!  This is a @robmyers question

**Comment by robmyers** [comment]
Fixed in a769dfa .

Deployed.

For future reference, the themes for the chooser and the licenses live in the python_env area of the repository.
