### ISSUE TITLE
Can I remove the related news module from the "What we do" page?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#445]
As far as I can tell, "Related news" only shows up on the "What we do" page, though it may be on other pages.  It is not pulling particularly relevant related news, and it looks weird to me.  

Can I please remove this module at least from this page? @mattl @robmyers @ericsteuer 

<img width="1239" alt="screen shot 2016-08-19 at 10 56 30 am" src="https://cloud.githubusercontent.com/assets/7093838/17814029/e17e6a64-65fb-11e6-9919-df335a08991d.png">

**Comment by robmyers** [comment]
I've no strong opinions about this. If it's not functioning as expected we should fix that, or if the related news isn't that related then I don't mind it being removed. It's part of the design though so we should consult AB.

@ageeroms what is your opinion?

**Comment by fmann** [comment]
Related News shows up on any Page that has a category set on it. "What We Do" had the "About" category set, so it was showing Posts with the "About" category.

Other Pages with categories include all of the Program Area Pages like:

https://creativecommons.org/about/program-areas/education-oer/
https://creativecommons.org/about/program-areas/legal-tools-licenses/

By just unsetting the "About" Category on "What We Do" the "Related News" widget will disappear.
