### ISSUE TITLE
Deleted pages

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#446]
A Q from info@ : 

It looks like you recently deleted the https://creativecommons.org/retiredlicenses/ page, but you still have links to it, e.g. on
https://creativecommons.org/2007/06/04/retiring-standalone-devnations-and-one-sampling-license/ 
and https://creativecommons.org/2015/10/08/cc-by-sa-4-0-now-one-way-compatible-with-gplv3/ 
and https://creativecommons.org/licenses/nc-sampling+/1.0/ 

and probably the other retired license pages...

Can you restore the page?

**Comment by peterspdx** [comment]
We should not have deleted that page -- it's important. Please do restore it. Thanks.

**Comment by mattl** [comment]
The page was still in WordPress, I saved it again and it magically reappeared -- @robmyers one to look into maybe.
