### ISSUE TITLE
Can't save drafts even on the VPN

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#450]
The "Error, you have been blocked" issue only seems to show up when saving drafts, not when publishing, which appears to work fine.

Also the attached screenshot was a new error when trying to save drafts.
<img width="1233" alt="screen shot 2016-08-30 at 2 20 45 pm" src="https://cloud.githubusercontent.com/assets/7093838/18127009/d8f908b4-6f4b-11e6-824e-176c383b438a.png">

This is happening on the VPN as well.

**Comment by robmyers** [comment]
Does the network you are on make any difference? e.g. is it the same at home and in the coffee shop/co-work space/etc., or is one better than the other?

It seems to be CloudFlare being over-protective but that shouldn't interfere with traffic over the VPN as it should be direct.

**Comment by little-wow** [comment]
Yes-- networks that have been explicitly whitelisted are generally fine

**Comment by robmyers** [comment]
OK following up in email. :-)
