### ISSUE TITLE
request from twitter to accept donations via paypal

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#451]
https://twitter.com/tytbone/status/771147238127104000

@rebeccalendl this is currently being worked on, no?

**Comment by rebeccalendl** [comment]
We def currently accept paypal, it's de-prioritized but the option sits below the submit button on the page where you enter your credit card number.


<img width="844" alt="screen shot 2016-09-01 at 11 49 36 am" src="https://cloud.githubusercontent.com/assets/13322149/18180174/87b514d0-703a-11e6-95f0-9813c5098d61.png">

**Comment by tvol** [comment]
haha, ok. yeah, i guess that is de-prioritized!
