### ISSUE TITLE
Switch owner on Creative Commons Canada site

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#453]
We should have ownership over creativecommons.ca.  It is currently owned by David Fewer.

**Comment by peterspdx** [comment]
We have a lot of affiliates to own domains that they hold in trust for us via our affiliate agreements and ISP policy. If we want to own it for some other reason, or want to clarify status with him, then please email. He is our CC Canada lead. Info on our wiki (or email off github and I can send it to you).

**Comment by little-wow** [comment]
Okay, that's fine – the CC Canada site is down and I was responding to a comment that Ryan made on IRC after someone asked about the site being down via Twitter. I'll email you for his email to ask about the status of it.

**Comment by robmyers** [comment]
@ryanmerkley mentioned this earlier. If CC CA are not using the site they can point the domain at ours, or if they would like new hosting we can offer them it.
