### ISSUE TITLE
Campaigns page is gone

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#455]
I found the page via the Wayback machine: https://web.archive.org/web/20160417200229/https://creativecommons.org/campaigns/

@tvol mentioned that it was never subsumed into the program areas page, but now there's all sorts of pages:
/campaigns and campaigns/ redirects here: https://creativecommons.org/about/program-areas/
https://creativecommons.org/campaign is its own page

What's the best practice on this?

**Comment by robmyers** [comment]
Yes that page isn't in WordPress any more (I think). We could recreate it and remove the redirect if desired, or ask AB to redesign it to be a better overview of the campaigns.

If we go minimal then it looks like it just listed the pages under it. There's code and plugins for that.

There's a bigger conversation to have about design and presentation of campaigns in the website, we should talk to AB about all this.
