### ISSUE TITLE
Horizontal Scrolling issue

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#457]
https://twitter.com/Ivoryblossum/status/774333541001924612

FF 38.8.0 Windows 7 

![twitter_scroll](https://cloud.githubusercontent.com/assets/7093838/18401136/f988120c-76a6-11e6-9960-5f6b6af2463c.jpg)

**Comment by fmann** [comment]
I've reproduced this in FF 38, 41, and 44.  It appears there was a period of about a year where Firefox interpret max-width differently than other browsers. 

The big image under [Can I combine material under different Creative Commons licenses in my work?](https://creativecommons.org/faq/#can-i-combine-material-under-different-creative-commons-licenses-in-my-work) is what pushing it beyond the viewport. 

If we can get at the markup that is including this image and add a class or even just a style attribute that includes "width: 100%" I believe it will fix this issue.

**Comment by hugosolar** [comment]
Fixed in pull request https://github.com/creativecommons/new-www-theme/pull/22
