### ISSUE TITLE
Twitter Widget on Search page

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#461]
<img width="1101" alt="screen shot 2016-09-21 at 9 36 27 am" src="https://cloud.githubusercontent.com/assets/7093838/18713178/5d189daa-7fdf-11e6-9e62-a2c782b0351d.png">

🤔 looks funny, eh?

**Comment by fmann** [comment]
The Twitter Widget is also showing up on the donate page. It is should not and makes the donation form render incorrectly.

In the Twitter widget settings on Production, someone needs to click on "Visibility" and set it to "Show" if "Page" is "Blog". This is the way it is currently set on the staging server.

**Comment by little-wow** [comment]
fixed
