### ISSUE TITLE
Dutch legalcode links refer to english legalcode pages

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#47]
Hi,

All Creative Commons Legal Tools (including CC0, C 4.0 and PDM) have been translated to Dutch. I expected that the links of all these tools from a deed.nl page would refer to a legalcode.nl page. This is not the case. 

Transifex already has this link incorporated into its translations:
![screen shot 2015-03-16 at 14 53 38](https://cloud.githubusercontent.com/assets/5627431/6667437/4c0abc3a-cbec-11e4-8750-678a22f8e041.png)

What do I need to change to have that?

Cheers,

Maarten

**Comment by sarahpearson** [comment]
We are not sure what is going on with this because the link is listed correctly in Transifex! It is happening with the other 4.0 translations as well..

**Comment by mattl** [comment]
The problem here is that our templates aren't set up for this. @RCEurope1 -- I think we'll need to add a new string to Transifex for the legalcode URI? Any idea on how to proceed with this?

**Comment by RCEurope1** [comment]
don't know, I never added any strings anywhere in Transifex

**Comment by mzeinstra** [comment]
@mattl can you explain why your templates are not set up for this, it does simply take the translation from transifex doesn't it? Can you point me to the template so I can have a look at it as well?

**Comment by mattl** [comment]
https://github.com/creativecommons/creativecommons.org/blob/master/python_env/src/cc.engine/cc/engine/templates/macros_templates/deed.html#L94 is the line in question.

As I understand it, {% trans %} blocks in zope.translate can't modify the properties of elements in the markup. So we'd need to have something like:

{% trans %}Yadda yadda yadda, see the <a href="{% endtrans %}{% trans %}legalcode{% endtrans %}{%trans %}">Legal code</a>{% endtrans %} at least as a stopgap.

**Comment by mzeinstra** [comment]
I can't reproduce this anymore. Closing for the sake of cleaning
