### ISSUE TITLE
CC0 chooser appears to be broken

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#475]
last step won't actually let me proceed to confirm: https://creativecommons.org/choose/zero/waiver

**Comment by janeatcc** [comment]
Also is this chooser where we would point folks to get CC0 metadata?

**Comment by mmoreshead** [comment]
Hey @janeatcc - ongoing issue here: https://github.com/creativecommons/creativecommons.org/issues/313

**Comment by janeatcc** [comment]
Got it.
