### ISSUE TITLE
Staging Site Settings for IPN Testing

### ISSUE THREAD

**Issue by alkrieger** [creativecommons/creativecommons.org#476]
This relates to [#27691](https://support.giantrabbit.com/issues/27691) in Redmine and the Recurring Contributions Extension testing:

Here's the staging site for the new Creative Commons Gravity Forms donation page:

https://staging.creativecommons.org/donate/

September 16th we started discussing with Affinity Bridge how we would handle the IPN messages from PayPal after a transaction occurs. We said that the Civi extension we are writing needs IPN messages in order to create a new Civi contribution when a recurring contribution occurs. It doesn't look like Paypal IPN messages can be sent to multiple urls, so all the messages need to go to a single url and we need to figure out how to get both platforms the info they need.

Affinity Bridge said that they do not need the IPN messages. To that end, we agreed that CiviCRM will maintain donation tracking.

CiviCRM can get all the information it needs to track the user and transaction records through the IPN. If the relevant IPN message contains a unique GF_entry_ID that we can use to relate the IPN message back to the Gravity Forms entry, that would be great. So, since everyone agrees that Gravity Forms doesn't need to receive any IPN messages from Paypal, it would be fine to point the IPN to CiviCRM when we launch the CiviCRM part of this project.

NOTE: We said that we would not want to update the notify_url before the CiviCRM part of this project launches, because then any interim notification messages would not be recorded or processed by anyone.

Robin from Affinity Bridge said:

> 1) CiviCRM is the authority on donation tracking (one-time and recurring). Gravity Forms (GF) does not need to host an authoritative copy of the transactional data (ie. records of PayPal Transaction ID or subsequent recurring payment records). Gravity Forms is currently doing this but does not necessarily need to. 
> 
> 2) CiviCRM can get all the information it needs to track the user and transaction records though the IPN (or some other mechanism, like GF API callbacks). 
> 
> Can you confirm these assumption are correct? 
> 
> Our team did some testing with the PayPal sandbox settings on the stage server. If we do not point the IPN on PayPal back to Gravity Forms we still can offer the person making the donation the same user experience; we simply do not get the PayPal transaction id pushed back to Gravity Forms. 
> 
> So if our assumptions are correct we might just wish to point the IPN to CiviCRM. It is good to also note that the IPN response includes a custom field with a value for GF_entry_ID which maps to the entry in Gravity Forms (good for tracking from Civi to GF). 
> 
> If our assumptions are incorrect, then we should discuss the development of the IPN broadcasters as you suggested below. My feeling is that your team is in the best position to develop this piece. 

Given that, on October 4th we asked Creative Commons to help us set up their staging site to use our test PayPal account, and to stop setting an IPN endpoint in your PayPal requests. That way we would be able to control the IPN endpoint via our test PayPal account and then have any IPN messages sent to our developer. The end goal is to be able to make and track test payments on the CC staging site (only) through PayPal.

The settings for the test Paypal account we are using are as follows:

> Merchant Account Email: jliu@giantrabbit.com
> Site URL + Recurring Payments URL: https://www.sandbox.paypal.com/

After some setup with Rob, it appeared that the notify_url in the PayPal link was still set to the staging site url instead of being left blank: 
https://www.sandbox.paypal.com/cgi-bin/webscr/?notify_url=https%3A%2F%2Fstaging.creativecommons.org%2F%3Fpage%3Dgf_paypal_ipn&charset=UTF-8&currency_code=USD&business=jliu%40giantrabbit.com&custom=74356|a26e8869a48ade3dbe6c76b27169af32&first_name=Giant&last_name=Rabbit&email=jliu%2Bdonate%40giantrabbit.com&address1=2748+Adeline+St.%2C+Suite+A&city=Berkeley&state=CA&zip=94703&country=US&cbt=Click%20here%20to%20continue&no_note=1&no_shipping=1&return=https%3A%2F%2Fstaging.creativecommons.org%2Fdonate%2F%3Fgf_paypal_return%3DaWRzPTN8NzQzNTYmaGFzaD04NjkzZGU2ZmY4NmY3ZWEzNTdkNThlYWRmOTBlMGRmMA%3D&rm=2&cmd=_xclick-subscriptions&item_name=Amount&a3=15&p3=1&t3=M&src=1&sra=0&bn=Rocketgenius_SP#gf_3

On October 6th, Floyd from Affinity Bridge said:

> Yes, it looks like the GravityForms PayPal plugin hardcodes that parameter in the query string.
> 
> https://github.com/creativecommons/new-creativecommons.org/blob/master/plugins/gravityformspaypal/class-gf-paypal.php#L607-L613
> 
> It could be patched to not include that parameter.

We are currently discussing with Affinity Bridge if the sandbox testing from September 20th is representative of what is currently on the staging site, in which case the patch should probably be applied or if the staging site settings have changed since Robin tested not pointing the IPN back to Gravity Forms and we can simply reapply his settings.

**Comment by fmann** [comment]
@robmyers a pull request for removing the IPN from the GF requests has been submitted in the new site repos.

https://github.com/creativecommons/new-creativecommons.org/pull/30

**Comment by alkrieger** [comment]
It looks like we are now able to receive PayPal IPN messages for test donations to our development environment:
![desctop screenshot](https://cloud.githubusercontent.com/assets/20407951/19320972/57a357ae-9068-11e6-81b1-2043eb6db64d.png)
