### ISSUE TITLE
page not found error - re blender post

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#479]
https://creativecommons.org/2016/06/16/blender-institutes-ton-roosendaal-open-licensing-artistic-success/

**Comment by little-wow** [comment]
New URL: https://creativecommons.org/2016/10/12/blender-institutes-ton-roosendaal-open-licensing-artistic-success/
It got posted with the old URL via twitter yesterday, but I fixed it everywhere else.
