### ISSUE TITLE
Updates to summit.creativecommons.org

### ISSUE THREAD

**Issue by alisonanalog** [creativecommons/creativecommons.org#483]
Please update the summit placeholder page - still has Korea info on there, so let's remove that.

CC Global Summit 2017, coming to Toronto, Canada April 28-30.

Link to https://creativecommons.org/2016/09/08/announcing-2017-creative-commons-global-summit/

**Comment by robmyers** [comment]
OK cool! Should this replace the existing static site or should we bring this into WordPress somehow?

**Comment by alisoncreativecommons** [comment]
Please bring it into Wordpress!

**Comment by robmyers** [comment]
Sure, I will take a look at that later today.

**Comment by robmyers** [comment]
That was a long day. :-(

The page is here:

https://creativecommons.org/global-summit-2017/

And summit.creativecommons.org now redirects to it. That was the easiest way of handling this.
