### ISSUE TITLE
A wrong translation of motto

### ISSUE THREAD

**Issue by RussianBruin** [creativecommons/creativecommons.org#484]
There is a mis-translation at Russian version of https://creativecommons.org/choose/
(at https://creativecommons.org/choose/?lang=ru).

The wrong line is "Это свободная лицензия на произведение культуры!" (Original: This is a Free Culture License!), ([div id="fc_approved_box"]). That rough line can be translated back as "This is a free license for (any) cultural work!". It means only "a license for your product" and says nothing about Free Culture.

I suggest using the line "Такая лицензия соответствует идеалам Свободной Культуры!" or something like that instead, so the meaning would be clear. Such a translation is used at Wikipedia (about "Free culture movement") for example.

Have noticed @robmyers dealing with translations.

I think, there is no need to attach PC info or anything similar.
Anyway, thanks a lot to anyone who translated all the page (exept for page header (in the top), which is still in English)
(and exept for license summary, though that had already been mentioned by @rizomaa 19 days ago and was replied).
Sorry, if there are any mistakes or errors, I'm not a native English speaker.

**Comment by peterspdx** [comment]
Thanks for this. We'll look into it by contacting the Russian translation team.
