### ISSUE TITLE
Update to donate page

### ISSUE THREAD

**Issue by rebeccalendl** [creativecommons/creativecommons.org#485]
https://creativecommons.org/donate/ offers an option to be included in the Public Supporters list when a donor enters $2000. The minimum threshold should be updated to $3000. Screenshot attached.
<img width="961" alt="donate page" src="https://cloud.githubusercontent.com/assets/13322149/19527902/b7f60b58-95de-11e6-9455-47751a4b1532.png">

**Comment by robmyers** [comment]
Somebody has already changed that(!).

**Comment by robmyers** [comment]
I misunderstood the problem, I'm sorry about that.

It is now *actually* fixed on live and staging.
