### ISSUE TITLE
No joint authorship on blog posts

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#488]
Joint authorship seems to not be working on the blog.
Example:

<img width="347" alt="screen shot 2016-10-20 at 11 26 16 am" src="https://cloud.githubusercontent.com/assets/7093838/19566389/0fcedfa6-96b8-11e6-9ef6-055e9f87971c.png">
<img width="1109" alt="screen shot 2016-10-20 at 11 26 01 am" src="https://cloud.githubusercontent.com/assets/7093838/19566390/0fd91534-96b8-11e6-90ac-601820eeafb5.png">

**Comment by robmyers** [comment]
We're getting multiple authors through the "Co-Authors Plus" plugin, but if the theme doesn't know about this then it wouldn't render the information.

**Comment by mackh** [comment]
We'll take a look

**Comment by robmyers** [comment]
@mackh thank you!

**Comment by fmann** [comment]
I've integrated the appropriate tags for the co-author plus with fallback to single author if that plugin ever gets disabled.  

It looks like this now:
 
![screen shot 2016-10-20 at 1 05 42 pm](https://cloud.githubusercontent.com/assets/711497/19575983/1b10fc10-96c6-11e6-92c6-d91d3beee49a.png)

There are changes in both the theme and the plugins repos, the latter required to add support for co-authors to the featured/hero blog entry displays.

**Comment by robmyers** [comment]
Thank you @fmann , I've tested that on staging, merged and deployed. It looks great.
