### ISSUE TITLE
Add new donor  ONLINE ONLY OÜ  to supporters page

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#49]
We have a new Remixer supporter!  Since Online Only OÜ donated $1000, please add them to the supporters page, here's their website that you can link to: http://websitesetup.org

**Comment by mmoreshead** [comment]
He asks: "Would you be able to change the "Online Only" from http://creativecommons.org/supporters#remixer to "Website Setup". The website address will stay the same, though."

**Comment by robmyers** [comment]
Removed at submitter request.

See helpdesk 367.
