### ISSUE TITLE
Turn off CiviMail messages to donors

### ISSUE THREAD

**Issue by alkrieger** [creativecommons/creativecommons.org#491]
Reflected in Redmine ticket https://support.giantrabbit.com/issues/27855

Rebecca says:

> As we move to MailChimp for all our donor/audience communications, I need to make sure that any and all automated CiviCRM messages to donors/audience are set to off. I've found one instance where donors are still receiving from CiviCRM and that's for recurring donations. My question is, when I go to manage system workflow messages, I can't figure out where exactly to turn it off. I just see options to edit settings. 
> 
> I also am wondering if there are any other outgoing CiviCRM messages that I don't know about. Is there any sort of mast switch where I can ensure they are all set to off?

We asked if CC would need to send any mail from CiviCRM once they made the switch to MailChimp and the answer appeared to be 'no'.

Anthony had two initial thoughts on how to do this:

First, we can try to prevent Civi from sending any mail by changing the SMTP setting. We don't know what the implications of that might be as far as whether everything else continues to work if CiviCRM can't send an email and something else stops working. Also, we'll want to figure out how to continue sending mail for the extensions we're building when an error happens.

Second, we can try disabling the Send Scheduled Reminders cron job.

I'm inclined to opt for the second option. I've assigned to our on-call developer to take a look when they get a chance.

**Comment by robmyers** [comment]
Do we need to send recurring donation receipts for the donors' tax purposes or are the PayPal (etc.) receipts sufficient for that?

The "Receipt Tab" contains the option to disable email receipts for each Contribution Page.

See Contributions > Manage Contribution Pages > Configure link (next to each page listing).

or see "Receipt Tab" here:

https://docs.civicrm.org/user/en/4.6/contributions/online-contributions/

I'm not sure how that would relate to repeated donation emails though.

Of the two options I agree that the second is better.

**Comment by peterspdx** [comment]
I think the best practice if for CC itself to generate the receipt and not rely on paypal or another to maintain records and send those. It's our obligation. We should be sending that to them via email. If that can be done automatically, great.

**Comment by rebeccalendl** [comment]
@peterspdx yes, the automated donor onboarding email process has been a year-long effort to clean up and streamline...happy to fill you in. This particular ticket is to turn off an unwanted email from CiviCRM which is outdated in both style and content and will be replaced by the new systems we're launching in the coming weeks.

**Comment by peterspdx** [comment]
got it, thanks rebeccalendl
