### ISSUE TITLE
Add "Special Feature" to homepage.

### ISSUE THREAD

**Issue by fmann** [creativecommons/creativecommons.org#492]
There was a request from CC staff to have a "Special Feature" in the homepage "What's Happening" area. This feature is sticky-ish in that, if there is a post with the "Special Feature" tag set, it will always show up in the fourth position of the "What's Happening" block.

This feature has been added to the [feature/homepage_special_feature branch](https://github.com/creativecommons/new-www-plugin/tree/feature/homepage_special_feature) of the new-www-plugin repos.

I also branched a develop branch off master and merged feature/homepage_special_feature branch into it, so we could test this feature and any others awaiting deployment without committing directly to master.

One content management piece is also required for this: adding a new term to the Highlight taxonomy. Term name "Special Feature", slug "special-feature". 

I've switch the staging site to the develop branch and added the "Special Feature" term there. There is a test special feature, which you can see on the staging homepage.

I can submit a pull request (or @robmyers can merge the branch into master) after confirmation this meets the need.

**Comment by robmyers** [comment]
I've pinged the staff to take a look. Thank you!

**Comment by robmyers** [comment]
I can't see the special feature on https://staging.creativecommons.org/ . The new-www-plugin is on develop and is current.

**Comment by fmann** [comment]
![special_feature_staging](https://cloud.githubusercontent.com/assets/711497/19785118/116f8a46-9c4d-11e6-8f74-391ca35185fb.jpg)

Odd. I am seeing it.

**Comment by rebeccalendl** [comment]
Thx @fmann! We didn't have credentials, but just got them from Anna so we're all set and can see it. Looks good to me, just waiting on Rob and Jennie that it works for them.

**Comment by robmyers** [comment]
Ah my mistake. Seen but not seen. ;-) I'm sorry about that.

Yes this looks good if everyone else is happy.

**Comment by rebeccalendl** [comment]
I heard back from Jennie too via email so we have a full round of approval from CC. Let's do it, @fmann

**Comment by fmann** [comment]
I've submitted a pull request to @robmyers https://github.com/creativecommons/new-www-plugin/pull/8

As well as updating the code on prod, a reminder that there is one content management deployment step: adding a new term to the Highlight taxonomy. Term name "Special Feature", slug "special-feature".  With that in place it should be good to go.

**Comment by robmyers** [comment]
I've merged the new-www-plugin pull request and deployed master on production and staging.

This feature is now live.

**Comment by rebeccalendl** [comment]
Question for you @fmann. Is the special feature now something that will be available for us to turn off and on (preferred), or will that last spot now always be persistent?

**Comment by fmann** [comment]
Thanks @robmyers !

@rebeccalendl If no posts are tagged with "Special Feature" it will revert to the previous behaviour and show four featured posts.

**Comment by rebeccalendl** [comment]
Dreamy. Thanks again to everyone!

**Comment by little-wow** [comment]
@fmann @robmyers I'm not sure why, but I don't know if this change ever made it to production? Let me know what's up with it. Thank you and sorry about that! Here's a screenshot of what i'm seeing right now:

<img width="269" alt="screen shot 2017-02-03 at 4 52 27 pm" src="https://cloud.githubusercontent.com/assets/7093838/22610594/2e765ce8-ea34-11e6-98d2-131b61c91d88.png">

**Comment by ageeroms** [comment]
@rebeccalendl @little-wow I added the new term on prod and it appears to work now. Please confirm and close ticket.

**Comment by little-wow** [comment]
Looks great @ageeroms ! Thank you!
