### ISSUE TITLE
Image Cropper in WP is broken

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#493]
The 2:3 aspect ratio is consistently an issue for our blog workflow and a lot of images look bad because of it. 

Is there any way to automatically resize the image so it just fits in the box? I spoke with @fmann about it, and he said there possibly was.

Thanks!

**Comment by ageeroms** [comment]
@fmann can you please let me know what the options are here?

**Comment by fmann** [comment]
Hi @little-wow. Sorry it has taken me a bit to look into this.  

Just to be clear, we are talking about Feature Image thumbnails used on the homepage for blog posts in the What's Happening block, yes? The four images in a horizontal row?

I've looked into plugins we could add a bit, and I'm having a hard time finding anything that seems like it'd obviously be better.  Also, I think we may not have given you all the information you need to get satisfactory output. So... I want thinking of going through the existing behaviour/functionality a bit, see if we can get you to a point that you are satisfied with the tool (or else identify the places where it really bothers you). Does that sound alright?

Investigating this a bit, one important tidbits I discovered is the thumbnail that is displayed there isn't actually 3x2 (257x172 in actual pixels). There is a 3x2 box there surrounding the image, but it has a bit of padding on it. The visible portion of the image is actually 257x151px, which is much closer to a 16x9 or a 50x29 ratio. Using 257x151, 50x29, or even 16x9 gets you a much more satisfactory crop that displays much closer to the way you'd expect it to.

With that in mind, if you upload a featured image that already has 257x151 aspect ratio, it'll work perfectly, no cropping or hidden pieces of the image. 

If you upload something taller, like a portrait image, and do not crop it'll fill to width and vertically center align the image. I picked a random portrait image out of the gallery and actually was quite pleased with the centering it did and the automatic crop selected.

![screen shot 2016-11-01 at 11 04 36 am](https://cloud.githubusercontent.com/assets/711497/19901094/1b0b3f76-a023-11e6-942c-4388a98a05eb.png)

Custom cropping takes a bit of practice, but I think it actually does a great job. The steps are basically:
 - Upload the image
 - Click "Edit Image"
 - Drag your mouse to draw a crop box roughly in the size, shape, and position you want.
 - Click over to "Aspect Ratio" and enter your proportions, like 16 x 9. As soon as you tab it'll adjust the crop box to be 16 x 9.  
![screen shot 2016-11-01 at 11 22 15 am](https://cloud.githubusercontent.com/assets/711497/19902152/eb8c0cb8-a026-11e6-8324-1a00ad71b714.png)
 - Move/adjust the cropbox until you have a more precise crop. If you've changed the proportions significantly, tab through the Aspect ration fields again to snap it to the right proportions again.  
 - Important! When you have the crop you want, click the crop tool button in the upper left of the window. I missed that step the first few times I tried using this tool. Until you do that the "Save" button is greyed out. You can only hit "Back", which does not apply the crop.
 - After the crop has been applied, click the "Save" button.
 - Select the image and set as featured image.
 - Save the blog post. Now you should have the crop you expected.
![screen shot 2016-11-01 at 11 31 54 am](https://cloud.githubusercontent.com/assets/711497/19902177/fcf4871e-a026-11e6-8f6f-22b75587789c.png)

Give it a try and let me know if that gets you to a better result. If not, I'd love to hear more about what is giving you trouble or maybe see an few images you've not had luck with.

**Comment by little-wow** [comment]
Closing this ticket because it's not P1. Thanks for the instructions @fmann !

**Comment by little-wow** [comment]
Hey @fmann @robinpuga So now I can't use the Image Cropper at all? I'll add a screenshot in a moment

**Comment by hugosolar** [comment]
The Image cropper is working again since php-gd was installed on the server
