### ISSUE TITLE
push Polish 4.0 translation live

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#496]
@georgehari has corrected the files and checked the HTML, so these files are ready to go live. This ticket is simply me giving formal green light for publication. George submitted a pull request. Thanks!

**Comment by peterspdx** [comment]
Let's do this! Thanks to Sarah, George, and Rob. Is there a blog post on the horizon?

**Comment by sarahpearson** [comment]
There is not one in the works. For some reason, I thought we were moving away from doing a blog post announcement with every translation.

**Comment by peterspdx** [comment]
I don't remember discussing that with Gwen or others. I think it would be
nice assuming it's highlighting the people who are volunteers and how it
fits into the larger picture of making our licenses accessible to more
persons.

I'll let you decide. I definitely want posts for those that require major
lifts across borders and that received funding, including Arabic, French
and Spanish.

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC

**Comment by sarahpearson** [comment]
Jennie is going to work with the team to get a blog post up next week. Closing this ticket as the translations are now live. Yay!
