### ISSUE TITLE
Update the Apache config to a new, saner, less regexp way of handling the myriad of translations

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#50]
Including @peterspdx @mzeinstra on this.

**Comment by mattl** [comment]
@robmyers can you take a look at this one? I know you want to get the most up-to-date config for CC.org into git too. If you look at the way we handle translations right now in the Apache config, it's a mess of regexps, and would be better handled by explicitly listing the various languages and versions of languages, IMO. WDYT?

**Comment by robmyers** [comment]
@mattl There are currently 769 versions/translations in legalcode/ vs 13 legalcode, 11 rdf, and  25 other rewrites for licenses. These rewrites handle both version/translation mapping and various regularization and bug-correcting tasks.

So they're less verbose than a list of 769 urls plus a list of the various rewrites applied 769 times each, but they're too complex to reason about reliably. Simplifying them would therefore be good. We really shouldn't be correcting /licesne for example.

I think if we stick with regexes to map urls onto files, but start explicitly redirecting from non-canonical urls to canonical ones that would be a step in the right direction.

Does that sound worthwhile?

**Comment by robmyers** [comment]
There are no links on the web to samplingplus_1.0.br.html that I can find outside of our own legal deed. We could fix the filename and remove the mapping for that.

**Comment by mattl** [comment]
I don't think we expose the filenames anywhere -- how would you fix them? I think that file loads https://creativecommons.org/licenses/sampling+/1.0/deed.pt_BR fwiw

**Comment by robmyers** [comment]
The files in that folder match ^([a-z]+-)*[a-zA-Z]+_[0-9.]+((_[a-z]+)*(-[A-Za-z]+)?)?.(html|txt)$ *except* for samplingplus_1.0.br.html (and r, but we'll ignore that). So I'd "fix" that one by removing it and just keeping samplingplus_1.0_br.html , which is there alongside it.

The comment in the .conf is interesting:
    # FIXME: eval whether we should use the LHS as the actual file structure so we don't need the rewrites
If we did this (after discussion with the translation team) it would mean we wouldn't even have to explicitly map to the files.

**Comment by mattl** [comment]
@sarahpearson supports this effort too.

**Comment by robmyers** [comment]
I support this effort, I'm just concerned about swapping uncommented
regexes for either a 500 line config file or
something that doesn't catch ${EDGE_CASE}[MAX_INT].

Having a build system generated config file seems like a good way of making
this understandable, manageable and efficient. And it's not on the website
tasks... Should we add it?

**Comment by mattl** [comment]
Yeah, please add it at the same time of moving to Jekyll.

**Comment by robmyers** [comment]
Added.

**Comment by aldenstpage** [comment]
Closing this because it's out of date. I don't think anybody plans to rewrite all of the redirects.
