### ISSUE TITLE
Remove redirect for store on stage

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#501]
Hey @robmyers , we've been working on resurrecting the Amazon store, as shown here: http://dev.cc.affinitybridge.com/about/store/ (username: affinity and password: bridge) . You can see that we added content on the main store page, instead of just redirecting that page. We also added the Open Store page, which is featured there.

I'm adding a separate ticket for Floyd to make a pull request the CSS changes needed. 

In the meantime, could you please remove the redirect of /about/store on stage? That way we can put the pages up on stage for your team to review/approve.

Thanks!

**Comment by robmyers** [comment]
(Apologies for the delay, I'm on vacation at the moment but I am watching for blockers).

I've removed the redirect on stage.
