### ISSUE TITLE
Pull request for Amazon store CSS

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#502]
Hey @fmann , can you please request your CSS for the Amazon store be put on https://staging.creativecommons.org? Or deploy it to stage (if we have that permission). Thanks!

**Comment by fmann** [comment]
Staging is on the develop branch, which has the store CSS in it already. Go ahead and pop the store page up there and let me know if you discover any problems.

**Comment by robmyers** [comment]
Closing as CSS is already deployed.
