### ISSUE TITLE
Launch Amazon Store

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#507]
Hello Rob,

I think we're all lined up to launch the Amazon store.

Here are the steps to launch Amazon Store:

1. Create Open Store page on production. It should be a child of the Store page. The content for that page is on Staging: https://staging.creativecommons.org/wordpress/wp-admin/post.php?post=50762&action=edit 
2. Copy content from Staging (https://staging.creativecommons.org/wordpress/wp-admin/post.php?post=48776&action=edit) for regular Store page on production to update that page.
3. Remove redirect for /store to https://store.creativecommons.org

@robmyers

**Comment by fmann** [comment]
You need to merge and deploy the CSS currently in the develop branch of the new-www-theme too.

https://github.com/creativecommons/new-www-theme/pull/11
