### ISSUE TITLE
Mailchimp Testing

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#508]
1. All "Please add me to your mailing list" check boxes need to be transferred from Civi to Gravity Forms:
<img width="988" alt="screen shot 2016-11-21 at 12 46 28 pm" src="https://cloud.githubusercontent.com/assets/7093838/20493884/8d0e9864-afe8-11e6-9b77-566359201f7d.png">

*Question: How do I make this checkbox?*

<img width="1197" alt="screen shot 2016-11-21 at 12 47 27 pm" src="https://cloud.githubusercontent.com/assets/7093838/20493914/af386f0a-afe8-11e6-98dd-abbc60acb11b.png">
<img width="694" alt="screen shot 2016-11-21 at 12 47 17 pm" src="https://cloud.githubusercontent.com/assets/7093838/20493915/af3921a2-afe8-11e6-8297-5cdc7537b33e.png">

According to a Wordpress search, these are the only instances of needing to replace these forms.

2. When does the Paypal data enter Mailchimp? 
According to my test, not until after the payment is made. 

3. What lists are we going to import into Mailchimp?

**Comment by robmyers** [comment]
Regarding 3, I'm doing the export Wednesday as discussed.

**Comment by little-wow** [comment]
@robmyers with the export, can you group them into a few groups:

1. Anyone who donated ever and specifically opted into the mailing list
2. Anyone who donated ever and is not listed as opted into the mailing list but is also not listed as opted out
3. Anyone who is listed as neither opted in nor opted out but is also not specifically listed as a donor.

Could you also make sure that the metadata of "Contribution amount, year, recurring," and other data about the donors goes with them. When in doubt, export too much data and I will delete the columns that we don't need.

Thank you so much!

Jennie

**Comment by robmyers** [comment]
If we have that information in Civi I can use it.

Would you like separate batches, or a column that indicates this?

**Comment by little-wow** [comment]
Separate batches that are clearly labeled, if that's okay?

**Comment by robmyers** [comment]
I have to write more code than I thought in order to do this. :-/ I won't finish until Friday now as tomorrow is blocked out. My apologies.

**Comment by little-wow** [comment]
Hey @robmyers just pinging on this work!

**Comment by robmyers** [comment]
Since I expect the process to be very slow, exporting every group doesn't make sense (take a look in Civi and you'll see lots of groups for contacts for previous members of staff etc.). I can export what look like the greatest hits, or you can provide a list of groups.

**Comment by little-wow** [comment]
@robmyers  Just ignore the groups that exist in Civi now and see if you can run custom searches for the groups listed above, if possible.
