### ISSUE TITLE
Mystery error "Are you sure you want to do this?"

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#509]
<img width="873" alt="screen shot 2016-11-22 at 8 06 59 am" src="https://cloud.githubusercontent.com/assets/7093838/20528704/40474158-b09b-11e6-931b-2fd52ec52731.png">

I usually get this error when I've been logged in for a while and try to update a page or post

**Comment by robmyers** [comment]
It's most likely caused by a random plugin or theme -

https://premium.wpmudev.org/blog/are-you-sure-you-want-to-do-this-error-wordpress/

Can you reproduce this on staging? I ask because if the answer is yes it will be *much* easier to track down the culprit there than on live.
