### ISSUE TITLE
Donation Error

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#511]
Steps to reproduce:

1) go through one time $1 donation process

2) When you get to the credit card part, put in 2016 for your expiration year, you'll get an error that says the year isn't valid (assuming this is because month is already past, my expiration month is past this year)

3) Fix expiration year, click submit, get this message:
"false is not supported. Please enter one of the supported credit cards."

(Using Firefox 49.)

**Comment by mmoreshead** [comment]
@ageeroms -- Rob said I should tag someone at AB :)

**Comment by robinpuga** [comment]
@mmoreshead Can you confirm that you are entering a past month and past date?  

When we test with a past month and past date we see the same error "false is not supported. Please enter one of the supported credit cards." This is a Stripe error message and obviously quite confusing. We will look into whether we can override Stripe's error messages from WordPress and get back to you.

**Comment by mmoreshead** [comment]
HI @robinpuga -- yes, I entered 09/16 as expiry.
