### ISSUE TITLE
Deploy holiday overlay and updates to GA tracking

### ISSUE THREAD

**Issue by fmann** [creativecommons/creativecommons.org#513]
First there are three pull requests for branches that need to be merged in:

https://github.com/creativecommons/creativecommons.org/pull/512
https://github.com/creativecommons/new-www-theme/pull/12
https://github.com/creativecommons/new-creativecommons.org/pull/32

Then we can deploy the code to prod and make the necessary changes in the CMS.

**Comment by robmyers** [comment]
All merged.

Thank you!
