### ISSUE TITLE
Update theme release version string, minimize the css.

### ISSUE THREAD

**Issue by fmann** [creativecommons/creativecommons.org#516]
I was not aware that we are setting a version string in our functions.php for cache busting. I'm making this a constant, changing the version string, and adding something to the README about it.

**Comment by Hawkmorgan101** [comment]
https://github.com/creativecommons/creativecommons.org/issues/516?_pjax=%23js-repo-pjax-container

**Comment by Hawkmorgan101** [comment]
https://github.com/creativecommons/creativecommons.org/issues/516?_pjax=%23js-repo-pjax-container

**Comment by Hawkmorgan101** [comment]
[prettu-firewings-master (1).zip](https://github.com/creativecommons/creativecommons.org/files/646147/prettu-firewings-master.1.zip)

[prettu-firewings-master (1).zip](https://github.com/creativecommons/creativecommons.org/files/646153/prettu-firewings-master.1.zip)

[clojure-1.8.0.zip](https://github.com/creativecommons/creativecommons.org/files/646154/clojure-1.8.0.zip)
[fileopen_plugin_reader_8.0.0.520.zip](https://github.com/creativecommons/creativecommons.org/files/646162/fileopen_plugin_reader_8.0.0.520.zip)
[fileopen_plugin_reader_8.0.0.520 (1).zip](https://github.com/creativecommons/creativecommons.org/files/646165/fileopen_plugin_reader_8.0.0.520.1.zip)

**Comment by Hawkmorgan101** [comment]
[fileopen_plugin_reader_8.0.0.520 (3).zip](https://github.com/creativecommons/creativecommons.org/files/646167/fileopen_plugin_reader_8.0.0.520.3.zip)

**Comment by Hawkmorgan101** [comment]
[prettu-firewings-master (2).zip](https://github.com/creativecommons/creativecommons.org/files/646175/prettu-firewings-master.2.zip)
[prettu-firewings-master (2).zip](https://github.com/creativecommons/creativecommons.org/files/646180/prettu-firewings-master.2.zip)

**Comment by kgodey** [comment]
This seems done.
