### ISSUE TITLE
Year end analytics

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#518]
We want to be able to track year end campaign with analytics through ecommerce tracking

As per our meeting, due to the difficulty of passing Paypal to Google Analytics accurately, we will calculate Paypal transactions manually.

This ticket is to track progress on that goal.

**Comment by robinpuga** [comment]
@little-wow Thanks for the tracking ticket for this issue. 

Our team will be looking at a patch to GA E-Commerce plugin to omit the transaction processing for PayPal payments for the time being.
