### ISSUE TITLE
Public Reports page on wiki is down

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#519]
https://wiki.creativecommons.org/wiki/Public_reports
<img width="1192" alt="screen shot 2016-11-30 at 2 26 07 am" src="https://cloud.githubusercontent.com/assets/6127036/20748769/63eaa5aa-b6a4-11e6-833e-6e588a81bb61.png">

**Comment by georgehari** [comment]
It is up now.

**Comment by robmyers** [comment]
Frustratingly, CloudFlare isn't showing me anything for that Ray ID. I've had that with several reports from staff recently. 

It looks like it was a transitory error. I apologise for the convenience
