### ISSUE TITLE
Portuguese License Deed Translation Incomplete

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#52]
http://creativecommons.org/licenses/by-nc-sa/4.0/deed.pt_BR

Attribution text is not fully translated:

Atribuição — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

(Reported via help - 2118 .)

**Comment by sarahpearson** [comment]
Thanks! I will raise this with the translation team that is working on the 4.0 translations.
