### ISSUE TITLE
Gravity Forms exports hanging, only exporting certain fields

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#520]
I am trying to export a large data set (3000 + rows) from Gravity Forms and it keeps hanging at zero:

<img width="654" alt="screen shot 2016-11-30 at 10 48 35 am" src="https://cloud.githubusercontent.com/assets/7093838/20759310/93534a4a-b6ea-11e6-8c29-422e67a1f223.png">

When it actually exports, it does not export all the columns I requested. (I need the column labeled "Email" and it has twice not exported this column even though the "Email" column was selected."

I spoke with Rob about this yesterday and it's not producing an error log, nor is the server particularly overloaded.

Please advise!

**Comment by robmyers** [comment]
I'll take a look but I couldn't reproduce it yesterday with a full export. Can you email us a screenshot (or two) of the options you are choosing so we can try to reproduce the exact scenario? Thank you.

**Comment by little-wow** [comment]
workaround discovered
