### ISSUE TITLE
Stop Gravity Forms -> Google Analytics Donation notifications for PayPal donations

### ISSUE THREAD

**Issue by fmann** [creativecommons/creativecommons.org#522]
GravityForms completes the form submission prior to payment being closed. The way it is configured now, GF notifies GA of a completed transaction immediately. Since a large number of PayPal payment link clicks never complete the donation, the numbers for supposed donations is highly inflated.

Our short-term fix is to not post PayPal transactions to GA, which requires a patch to the Gravity Forms + Google Analytics Ecommerce Tracking plug-in.

Longer term we're hoping that, upon IPN notification of successful transaction, GA can be notified. Whether it would be Civi or GF or something else to notify GA is TBD.

**Comment by fmann** [comment]
Patch issued and change staged to the staging server.

**Comment by zeyarnaung** [comment]
#522 refs #33 Restart GF from posting PayPal Donations to GA.

**Comment by fmann** [comment]
Merged and pushed live.
