### ISSUE TITLE
Release minor donation form CSS changes 

### ISSUE THREAD

**Issue by fmann** [creativecommons/creativecommons.org#523]
We've got a few CSS clean up tickets in our ticketing system, Unfuddle.

 - 247 - Error is tiny when I try to donate $.25
 - 249 - Field Placeholder looks like it got big and dark
 - 250 - Email field on step 2 of donation form not aligned

I'm going to issue a pull request for releasing those CSS tweaks.

**Comment by zeyarnaung** [comment]
#523

**Comment by zeyarnaung** [comment]
#15 Develop

**Comment by fmann** [comment]
Merged and pushed to prod.
