### ISSUE TITLE
Twitter cards 

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#527]
Nasir pointed out that because we don't have Twitter cards enabled, it makes tweets look like this when there's no image on the page:

<img width="592" alt="screen shot 2016-12-05 at 10 35 29 am" src="https://cloud.githubusercontent.com/assets/7093838/20891030/1f42950c-bad7-11e6-9b25-a5556ff86a89.png">

Posts with images only fair slightly betterL
<img width="591" alt="screen shot 2016-12-05 at 10 36 07 am" src="https://cloud.githubusercontent.com/assets/7093838/20891068/454b0e32-bad7-11e6-9964-5c816cd7d53c.png">

What's the best course of action here?

Here is the Twitter cards documentation. https://dev.twitter.com/cards/overview

Thanks!

**Comment by nasirkhan** [comment]
there is an another issue related to this donate page #528

**Comment by robmyers** [comment]
Same as #528 .
