### ISSUE TITLE
Slack-signup is returning a 503

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#529]
https://slack-signup.creativecommons.org/

<img width="1034" alt="screen shot 2016-12-07 at 10 28 46 am" src="https://cloud.githubusercontent.com/assets/7093838/20973796/f543b10e-bc67-11e6-99f4-e5fa9a798182.png">

**Comment by robmyers** [comment]
Thank you for reporting this!

It's back.

Making this more robust is on my pre-end-of-year todo list.
