### ISSUE TITLE
Donate Form Fields Allow Input Too Long For Civi To Handle

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#531]
In Civi, the Street Address has a maximum length of 96 characters and the Zip has a maximum length of 12 characters.

The Gravity Forms standard address input fields do not limit the length of this input.

The bridge is handling this by truncating the data inserted into Civi.

We should set the length of these inputs in the Donate Gravity Form though.

Possibly we could do this with a custom css style for the fields.

What do people think?

**Comment by fmann** [comment]
We have some field/address validation in the cc-donate plugin.  See cc_donate_price_validation
and cc_donate_address_validation functions there. 

String lengths could certainly be checked in cc_donate_address_validation and, if not truncated, at least errors thrown if greater than 96 character street addresses are posted. I can't imagine that is a common problem in real addresses.  

Another thing it'd be good to catch in cc_donate_price_validation is ridiculously large donations. Like those $99,999,999,999 gifts that were blowing up Google Analytics never should have gone through as valid form submissions. Online gifts over a certain amount -- like ... what? $20K? $50K? 100K? -- should trigger an error too, though perhaps a nicer one like "Please contact our donor relations team for a gift of this size."

**Comment by little-wow** [comment]
I have no strong feelings on this, but agree with Floyd that we should also limit the donation string. I haven't ever seen anything very, very large come through on the website that's legitimate.

**Comment by robmyers** [comment]
We are moving away from Civi so this is no longer an issue.
