### ISSUE TITLE
cc site not loading

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#536]
see attached error
![screenshot_658](https://cloud.githubusercontent.com/assets/6394777/21114213/3df6d92e-c061-11e6-9795-006715ab434f.jpg)

**Comment by robmyers** [comment]
It's loading OK here.

The Ray ID isn't in our dashboard. This has happened a few times recently, I'm contacting CloudFlare support.

**Comment by little-wow** [comment]
@robmyers okay if I close this issue?

**Comment by robmyers** [comment]
A closed issue is a happy issue. :-)

I think this was the same problem that was causing VPN and payment issues.
