### ISSUE TITLE
hidden CSS showing re: Summit announcement

### ISSUE THREAD

**Issue by evarogers** [creativecommons/creativecommons.org#539]
hi @little-wow - this shows up when I search global summit on our site, before clicking in to what is the form field (maybe something is in process right now?) - it looks like it was an earlier basic post before we released the more comprehensive summit post.
 
https://creativecommons.org/?s=global+summit
https://creativecommons.org/announcing-global-summit/

<img width="613" alt="screen shot 2016-12-14 at 9 46 29 am" src="https://cloud.githubusercontent.com/assets/19761819/21195623/67a5d2c8-c1e9-11e6-85a0-e31227cae87e.png">

**Comment by little-wow** [comment]
This should be fixed. Thanks for reporting, Eva!
