### ISSUE TITLE
503s

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#541]
I recognize that I'm a super user, so I probably encounter more 503s than others but is there an error log that says how many 503s users are getting? I feel like I've been encountering more than usual.

If this is patently false, feel free to just close this ticket. Thank you!

**Comment by robmyers** [comment]
It's not patently false, I'm working on changing the server configuration to tackle this.

The problem is super annoying, I'm sorry you're hitting it. :-(

**Comment by CheyenneFMA** [comment]
Hi friends! I wanted to chime in and say the FMA License Agreement form uses a tool that picks a license, and I was getting a 503, and now it's going to [this page](https://creativecommons.org/2006/12/08/license-compatibility-wizard-from-cc-taiwan/?partner=FreeMusicArchive&jurisdiction_choose=0&exit_url=https%3A%2F%2Ffreemusicarchive.org%2Fmanage%2Falbums%2FccLicense%2F25766%3Flicense_url%3D%5Blicense_url%5D%26license_name%3D%5Blicense_name%5D%26license_button%3D%5Blicense_button%5D%26deed_url%3D%5Bdeed_url%5D) which is a license compatibility tool for Taiwan. I have no idea if this will be helpful but I found it amusing. @robmyers if you're already working on this, just disregard my bizarre observation! :)

**Comment by robmyers** [comment]
@CheyenneFMA Was it going via /license ? That was briefly broken about the time you reported it as I was changing the server configuration to address this problem.

**Comment by CheyenneFMA** [comment]
Yep! Thanks @robmyers, it seems to be back up and working now!

**Comment by robmyers** [comment]
That's good to hear! I'm very sorry it was broken.
