### ISSUE TITLE
RDF link doesn't work.

### ISSUE THREAD

**Issue by buckett** [creativecommons/creativecommons.org#542]
The contents of a license (eg: https://creativecommons.org/licenses/by/4.0/ ) includes a link to a RDF version:

     <link rel="alternate" type="application/rdf+xml" href="rdf"/>

however attempting to visit that URL results in a 404.

https://creativecommons.org/licenses/by/4.0/rdf

**Comment by robmyers** [comment]
The link now returns the rdf for the license.

**Comment by rjkmurray** [comment]
I have the new license didn't you get a copy or was it only me

**Comment by robmyers** [comment]
How do you mean? :-)
