### ISSUE TITLE
Error "This site cannot provide a secure connection" when logging in

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#544]
The site is trying to run https on port 80 for some people and not for others. Screenshots are from both Firefox and Chrome:

<img width="1101" alt="screen shot 2016-12-20 at 10 20 32 am" src="https://cloud.githubusercontent.com/assets/7093838/21356992/a08dddda-c6a1-11e6-9a3d-acbb8ee0ddd1.png">

<img width="1192" alt="screen shot 2016-12-20 at 10 50 51 am" src="https://cloud.githubusercontent.com/assets/7093838/21357163/3c915e78-c6a2-11e6-9880-30ae71ba1827.png">

It seems to be an intermittent issue, and I tried the workaround from the old site, but it didn't seem to work. Thanks!

**Comment by robmyers** [comment]
Oh that's a weird one.

I just reproduced it.

It looks like CloudFlare is getting confused by https....:80.

As for what is incorrectly appending the :80, I'm investigating.

**Comment by robmyers** [comment]
OK the new caching set-up doesn't seem to be forwarding the port number in the way that the login plug-in was expecting.

I've changed the code to address that.

Please try to log in now.

**Comment by little-wow** [comment]
👍🏾 thank you much, Rob! Seems to be working now.

**Comment by robmyers** [comment]
You're welcome. :-) That's good to hear.
