### ISSUE TITLE
Add svenska to all existing CC0 translations

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#549]
After the merge of cc0-sv-legalcode into master, please add the new Swedish translation as “svenska” in the bottom of all published CC0 translations.

**Comment by sarahpearson** [comment]
On hold for now until we get CC0 live but then, as discussed just now, we'll have to do this manually.

**Comment by georgehari** [comment]
@sarahpearson , if you do that yourself, please add a comma between "English" and "Nederlands" in https://creativecommons.org/publicdomain/zero/1.0/legalcode.fr in the footer.

**Comment by sarahpearson** [comment]
Thanks, @georgehari! Just submitted the pull request and I made sure to add the missing comma.
