### ISSUE TITLE
Wrong link/redirection

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#550]
At https://creativecommons.org/licenses/zero/1.0/legalcode, the text "« Back to Commons Deed" in the footer goes to a wrong destination - http://licenses.productionwww.creativecommons.uk0.bigv.io/publicdomain/zero/1.0/ instead of https://creativecommons.org/licenses/zero/1.0/ (there is a redirection and it should go to https://creativecommons.org/publicdomain/zero/1.0/deed).

**Comment by sarahpearson** [comment]
I'm going to close this issue because I've noted it as a fix to include when we add svenska to the language list in CC0. It will be part of that pull request I'll make, hopefully later today.

**Comment by sarahpearson** [comment]
I was wrong! This isn't something I knew how to fix. Not sure what is going on there. But reopening for @robmyers.

**Comment by robmyers** [comment]
We're redirecting wrongly, I'll take a look.

**Comment by little-wow** [comment]
This appears to be fixed @sarahpearson can you check?

**Comment by sarahpearson** [comment]
Appears fixed to me, too. Will close the ticket. Thanks!
