### ISSUE TITLE
License chooser displays in Cyrillic

### ISSUE THREAD

**Issue by encukou** [creativecommons/creativecommons.org#551]
URL: https://creativecommons.org/choose/

Steps to reproduce the problem:

* On the main page, click "Share your work".
* Then click the "Get Started" button.

Apart from a header and footer, the (https://creativecommons.org/choose/)[license chooser] displays in Cyrillic. It has these headings:

* Выбор параметров
* Подходящая лицензия
* Помогите людям указать ваше авторство!
* Есть ли веб-страница?

I don't understand any language that uses Cyrillic. I am connecting from the Czech Republic, and Czech doesn't use these letters. Following English links to this page is quite confusing.

I managed to find a link saying "English" near the bottom of the site, which took me to an English version. I imagine others would not be so lucky, so I decided to report the issue.

I am using Firefox 50.0.2 on Fedora 24.

---

Mentions from the template: @robmyers @little-wow

**Comment by robmyers** [comment]
This is now fixed. Thank you for reporting it!
