### ISSUE TITLE
https://creativecommons.org/choose/ broken

### ISSUE THREAD

**Issue by Prutheus** [creativecommons/creativecommons.org#555]
URL: *https://creativecommons.org/choose/*

Error: 

> Error 503 Service Unavailable
> 
> Service Unavailable
> 
> Guru Meditation:
> 
> XID: 28845213
> 
> Varnish cache server

Since: first recognized on Wed 28 Dec, maybe it occurs also earlier, but I was first on it on Wed.

Browser: google-chrome-stable on ArchLinux

@robmyers @little-wow

**Comment by gho87** [comment]
It works right now, but there is another issue here: https://github.com/creativecommons/creativecommons.org/issues/743
