### ISSUE TITLE
Homepage email signup block renders poorly on mobile devices

### ISSUE THREAD

**Issue by fmann** [creativecommons/creativecommons.org#559]
The homepage email signup block renders poorly on small devices.

![screen_shot_2017-01-03_at_4 32 59_pm](https://cloud.githubusercontent.com/assets/711497/21652524/bf38cb8e-d261-11e6-9cf9-32f507480e71.png)

Minor CSS tweaks fix this.

**Comment by fmann** [comment]
Post CSS changes:

![screen shot 2017-01-04 at 9 39 03 am](https://cloud.githubusercontent.com/assets/711497/21652679/8394b1c8-d262-11e6-83e0-a8f745f6e1ab.png)

**Comment by kgodey** [comment]
No longer relevant.
