### ISSUE TITLE
https://creativecommons.org/publicdomain/zero/1.0/deed.en/ needs to redirect

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#563]
currently is an error

**Comment by janeatcc** [comment]
e.g. linked from http://sammlungonline.mkg-hamburg.de/en/termsandconditions

**Comment by jahid5532** [comment]
377712

**Comment by robmyers** [comment]
Given the text, that link should probably be to -

https://creativecommons.org/publicdomain/mark/1.0/

And the url is a page, so it doesn't have a trailing slash.

All that said, I've put a redirect in place. :-)
