### ISSUE TITLE
Need a featured image for Summit Registration page

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#564]
Would love there to be a featured image for Facebook and Twitter (and other social) shares of the Global Summit reg page (https://donate.creativecommons.org/civicrm/event/info?id=25&reset=1)

Currently, if you share that page on Facebook, it looks like this, with no featured image:
<img width="498" alt="screen shot 2017-01-09 at 11 20 43 am" src="https://cloud.githubusercontent.com/assets/8919762/21779990/c33470e8-d65e-11e6-8728-f90ea0f75e1c.png">

It is possible to manually add an image, like I did for our own recent share of this page on FB (https://www.facebook.com/creativecommons/posts/10154831177252777). But it is unlikely that the average person who might share this link on Facebook or Twitter would think to do this. Would be much better for there to be a featured image already set in the CMS.

**Comment by mmoreshead** [comment]
Let's edit this page to list the links we know: registration, call for subs, scholarship form https://creativecommons.org/global-summit-2017/   

FYI: this will be the summit site (not summit.creativecommons.org) 

Thoughts?

**Comment by ericsteuer** [comment]
That works for me. Can you handle that @little-wow? And then we can start promo-ing that page instead of the reg one I just tweeted/FB'd out.

The reg page (and all pages across the CC site) should still have a featured image set in case they're shared out by anyone (not only by us, but any random person who wants to share just the reg page on FB, for instance). @robmyers, is there a way to set a default featured image for pages like the summit registration page that don't have their own unique featured image?

And while we're on the subject, is there a CC Summit 2017 logo for any kind of image that we should be using to promo the summit? Not sure who to ask about that -- @mmoreshead? @alisonanalog?

**Comment by mmoreshead** [comment]
@ericsteuer Probably going to run a logo comp again like last time (but open to other ideas) -- that needs to get out the door sooner than later I guess :)

**Comment by ericsteuer** [comment]
Gotcha. Thanks for the info! Yeah, if we want to get going on promoting the summit heavily across all of our various public channels, feels like we need to have a logo soonish. Thanks again.

**Comment by little-wow** [comment]
I can handle this by our meeting tomorrow!

Thanks both!
