### ISSUE TITLE
redirect http://www.creativecommons.org/chooser to https://creativecommons.org/choose/

### ISSUE THREAD

**Issue by tvol** [creativecommons/creativecommons.org#568]
hi @robmyers this link was included in a Dept of Ed policy rule. Would it be possible to setup a redirect to our actual license chooser page? thanks. cc @cablegreen

**Comment by cablegreen** [comment]
Rob: could you please redirect ALL versions of the Dept of ED's incorrect link to the correct page?: http://www.creativecommons.org/chooser  &  https://www.creativecommons.org/chooser    &  http://creativecommons.org/chooser  &     https://creativecommons.org/chooser  -- redirect to: https://creativecommons.org/choose/

**Comment by robmyers** [comment]
This is now implemented.

**Comment by cablegreen** [comment]
Thanks Rob!
