### ISSUE TITLE
<iframe> embedded has stopped working

### ISSUE THREAD

**Issue by rubenboadana** [creativecommons/creativecommons.org#571]
Hi,

Yesterday we noticed that the submit functionality in our DSpace repository was not working just in "Choose your license" step, where the user can choose his Creative Commons license. We use an <iframe> to show the Creative Commons form, but suddenly this form doesn't show any response. I saw in Javascript console this error:

Refused to display 'https://creativecommons.org/choose/?partner=dspace&exit_url=http%3A%2F%2Ftd…297629176e7e3c1331065d%26cc_license_url%3D%5Blicense_url' in a frame because it set 'X-Frame-Options' to 'DENY'.

Searching for a patch to solve this issue I found many explanations saying that your response headers are changed and now it's not possible to use this kind of integration (if you don't allow). So, my question is if this can be solved easily and how. 

Thanks in advance

**Comment by robmyers** [comment]
The X-Frame-Options header was being set by HAProxy due to some code I added to its config to handle encryption certificate renewal.

I have removed the offending part of the code and the header is no longer being sent.

Thank you for reporting this issue!
