### ISSUE TITLE
Creativecommons.org/register is misdirecting

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#573]
cc.org/register redirects here: https://creativecommons.org/2005/05/27/registerfortheilawconferenceatharvarduniversityberkmanlawcenterjune22242005/

**Comment by robmyers** [comment]
It can't find it so WordPress is doing its best and sending us somewhere with "register" in the url.

Where should it go to?

**Comment by little-wow** [comment]
Probably https://summit.creativecommons.org/index.php/register/ I think. Thanks!

**Comment by robmyers** [comment]
Done.
