### ISSUE TITLE
create madewithcc.creativecommons.org

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#574]
or creativecommons.org/madewithcc

as the area where Made With Creative Commons will live

is there a preferred style (subdomain vs subdirectory)?

**Comment by robmyers** [comment]
Hullo!

The subdirectory /madewithcc will be part of the existing site, with the same log-in and themeing. Anyone can make this.

The subdomain madewithcc.cc.org will be a separate WordPress install with its own log-in. We can use the main site theme but it will still be a separate entity. I would have to make this (it won't take long).

I'm not sure which is better SEO and promotion-wise. If anyone is then let's do whichever one they think is best. :-)

**Comment by ericsteuer** [comment]
Thanks. If we opt for the subdirectory approach, is it possible at some point for this part of the site to be redesigned/updated to have a different design/theme than the rest of the main CC site? Or if it's a subdirectory, does it pretty much have to look like the rest of the site? Asking because @sarahpearson and @pgstacey may decide at some point that they want this part of the site to have more of its own identity.

**Comment by mackh** [comment]
You could theme it selectively on with the subdirectory approach within wordpress.  I'd avoid making a top level subdomain microsite until you really need one, you can always redirect the subdir elsewhere when its warranted

**Comment by little-wow** [comment]
+1 Mack.

Not to scope creep this ticket (okay, I'm scope creeping,) but could we also get madewith.cc to redirect to our site? I checked and the domain is available....

**Comment by ericsteuer** [comment]
We would definitely like to purchase madewith.cc  -- @robmyers, what is the process for CC w/r/t registering and managing domains?

**Comment by robmyers** [comment]
I'm working on it. Gandi.net are currently erroring on the order.

**Comment by robmyers** [comment]
gandi.net support were awesome. OK, we grabbed madewith.cc! I can redirect it to wherever we wish.

**Comment by little-wow** [comment]
@robmyers Thank you! So we'll have cc.org/madewithcc and madewith.cc ? Will they have the same theme as the main site?

**Comment by pgstacey** [comment]
@robmyers, @little-wow has created the web page https://creativecommons.org/made-with-cc/ on our main CC web site. Can you redirect madewith.cc to this page please. Muchas gracias.
Paul

**Comment by robmyers** [comment]
This is now redirected.
