### ISSUE TITLE
de.creativecommons.org SSL certificate broken

### ISSUE THREAD

**Issue by sleeksorrow** [creativecommons/creativecommons.org#576]
https://de.creativecommons.org inaccessible because SSL certificate error

When you go to https://de.creativecommons.org, the connection fails because the SSL cert is issued to common name "*.newthinking.de" and not to "de.creativecommons.org".

> NET::ERR_CERT_COMMON_NAME_INVALID
> Subject: *.newthinking.de
> Issuer: thawte DV SSL SHA256 CA
> Expires on: 07.12.2018
> Current date: 01.02.2017
> 
> [...]
> 
> You cannot visit  de.creativecommons.org right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.
> 

The site now is not accessible with this browser anymore. Even trying to access http://de.creativecommons.org now redirects to https://de.creativecommons.org which leads to this error. The site is now inaccessible to me.

I'm using Chrome 56 Linux 64-bit and verified the issue also with Firefox 51.0.1 Linux 64-bit

--

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow

**Comment by robmyers** [comment]
Thank you for reporting this!

We will forward this information to the CC Deutschland team.

**Comment by robmyers** [comment]
@sleeksorrow CC Deutschland are aware of the problem and are working to move to a new server but it will take them a while to do so.
