### ISSUE TITLE
License Types translations are out of sync

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#585]
Going to https://creativecommons.org/share-your-work/licensing-types-examples/

![image](https://cloud.githubusercontent.com/assets/5627431/22745605/7a5fd9c2-ee21-11e6-9513-589c0352a1e7.png)

and clicking a language (Nederlands) on the right side gives an old version of the page:

https://creativecommons.org/licenses/?lang=nl

![image](https://cloud.githubusercontent.com/assets/5627431/22745672/a8712cda-ee21-11e6-809b-f3813cb2aaf8.png)

Which in turn leads to an outdated english translation https://creativecommons.org/licenses/?lang=en

**Comment by robmyers** [comment]
Fixed.
