### ISSUE TITLE
Polish 4.0 translation not appearing in language list 

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#586]
This appears to only be happening sporadically, but today it isn't there. 

@robmyers can you check on this? I know you added polski to the list back when we published that translation. 

Thanks!

**Comment by robmyers** [comment]
Here?:
https://creativecommons.org/licenses/by-sa/4.0/legalcode

There was a bug in the link-adder script, I'll see if it missed any.

**Comment by sarahpearson** [comment]
@robmyers It still doesn't show up for me there, or any any of the English license versions. Very bizarre. I can see it there when I view the list in other languages though.
