### ISSUE TITLE
Wrong flow of languages in the Arabic translation

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#587]
It seems that the list of languages in the footer of the Arabic translations changes if the screen resolution changes. Can this be related to rtl.css? How can we be sure that the order of languages remains the same?

https://cc4-ar-legalcode.legal.creativecommons.org/licenses/by/4.0/legalcode.ar

![screen shot 2017-02-14 at 10 04 08](https://cloud.githubusercontent.com/assets/22502629/22920410/a1781cec-f29d-11e6-8d39-bde4cabf9f40.jpg)
![screen shot 2017-02-14 at 10 04 25](https://cloud.githubusercontent.com/assets/22502629/22920411/a17d492e-f29d-11e6-8176-b4612725d05e.jpg)

**Comment by robmyers** [comment]
I've just pushed a modified version of the 4.0 ar deeds that makes the following changes:

1. It stops link text breaking in links in the license list. So "Bahasa Indonesia" is at least not broken across lines.
2. It adds a <br> before the FAQ text, ensuring that does not get mixed in with the language links.

This does not fix the issue, but I believe we can go live with this then investigate the issue more thoroughly later.

@sarahpearson does that sound OK? I think we should ask Affinity Bridge for CSS expert help here (ping, @ageeroms :-) ).

**Comment by georgehari** [comment]
Yes, I think it's a good solution for the moment. Thanks, Rob!

**Comment by robmyers** [comment]
OK let's hold off on any further changes for now then.

**Comment by peterspdx** [comment]
Actually, this is one that can be fixed now and isn't dependent on my figuring out what happened as among the teams on the substantive pieces. If that was your motivation for putting on hold, then no need. Feel free to make it. Thanks!

**Comment by robmyers** [comment]
@peterspdx I've put a fix-ette in place, anything more would involve a CSS expert looking at it. It's OK for now IMO.

**Comment by peterspdx** [comment]
Great, then let's close this one unless you want to roll it into a long term fix. Up to you. Thanks!

**Comment by roddrec2013** [comment]
Great, then let's close this one unless you want to roll it into a long term fix. Up to you. Thanks!
