### ISSUE TITLE
Images are not processing for Facebook OG Debugger

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#588]
Here's a recent link I tried to process: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fgoo.gl%2FIl2ZFa

It works for Twitter, but not for FB, not sure why!

**Comment by robmyers** [comment]
"The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog."

How are we sharing? Is this a Jetpack configuration issue?

**Comment by ageeroms** [comment]
I think this might apply: https://kb.yoast.com/kb/warning-fb-app-id-hasnt-been-included-in-the-meta-tags/ .

**Comment by little-wow** [comment]
@robmyers are you okay with me doing this because it touches the WP SEO? Thank you!
