### ISSUE TITLE
Is there a high res version of this image?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#589]
https://creativecommons.org/about/global-affiliate-network/

Anyone have a high res version of this?

**Comment by ageeroms** [comment]
Hello Jennie,

Yes, Jenn has provided larger version and vector: [reisthereahighresversionofthisimage589.zip](https://github.com/creativecommons/creativecommons.org/files/781474/reisthereahighresversionofthisimage589.zip)

**Comment by simeonoriko** [comment]
Thank you @ageeroms
