### ISSUE TITLE
Please add Curaçao as a country in creativecommons.org donation form.

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#590]
Hi Floyd,

I think we were originally using the Gravity Forms provided list of countries on the donation form and then somehow you swapped to the custom list from Civi. Now, I'm not sure where to add additional items.

Can you please add Curaçao (note the accent on the second c) to form on creativecommons.org/donate?

Rob noted:

- It *is* in the list of available countries in Civi, I can add it here -
- https://donate.creativecommons.org/civicrm/admin/setting/localization?reset=1
- I'm slightly worried about the character encoding (this looks weird on my Laptop) -
- Bonaire, Saint Eustatius and SabaCuraÃ§aoKosovoSaint BarthÃ©lemySaint Martin (French part)Sint Maarten (Dutch Part)South Sudan
- Anyway, let's get it into Gravity Forms and go on from there. :-)

@fmann

**Comment by fmann** [comment]
We override the list of countries in the cc-donate plugin.

https://github.com/creativecommons/new-www-plugin/blob/master/cc-donate/cc-donate.php#L201

I've added Curaçao and issued a pull request.

**Comment by robmyers** [comment]
I've merged the pull request, deployed to live, and added the country to Civi.
