### ISSUE TITLE
Images for different media types?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#591]
A community member wants to know how they can use the media type icons in the "Growing Commons" section of the website: "foto camera, video camera, text in a circle."

Can someone help out with how that's done? Thank you!

**Comment by mackh** [comment]
hey Alberto, can you comment on which icon set it used for the growing commons section?

**Comment by ageeroms** [comment]
These are icons from Noun Project, which are noted here:  https://creativecommons.org/website-icons/

**Comment by altrugon** [comment]
It seems that Anna has already answered the question, thanks Anna.

**Comment by little-wow** [comment]
great, thank you!
