### ISSUE TITLE
Add donation banner to search

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#592]
@fmann , please add the same donation banner as is https://creativecommons.org/ to http://search.creativecommons.org - this bit:

<div id="donation-bar-wrapper" class="donation-bar-wrapper">
<div id="donation-bar-inner" class="donation-bar-inner">
<p class="donate-text">Help us build a vibrant, collaborative global commons</p>
<div class="donate-action"><a href="https://creativecommons.org/donate" class="button donate arrow">Donate<span class="hide-on-mobile"> Now</span></a></div>
</div>
</div>

**Comment by fmann** [comment]
I've added the donation stripe across the top and pushed the change to a new feature branch. 

https://github.com/creativecommons/search/tree/issues/592-add_donation_banner

I'm not sure if there is a place to stage search changes. It looks good on my local, but you might want to take a peek before merging and pushing it to prod @robmyers .

**Comment by little-wow** [comment]
@robmyers Was this ever decided on?

**Comment by kgodey** [comment]
Closing this since we are deprecating old Search soon.
