### ISSUE TITLE
english cc0 is german

### ISSUE THREAD

**Issue by grinapo** [creativecommons/creativecommons.org#593]
![englishorwhat](https://cloud.githubusercontent.com/assets/1056054/23383396/7cf34546-fd46-11e6-9d20-aef8cecec5df.png)

and the browser is surely not german. prefers english and supports hungarian, kein german on sight.

**Comment by peterspdx** [comment]
Opened similar issue on legal tool list a day or so ago. Assigning here to @robmyers to merge one place or another.

**Comment by robmyers** [comment]
It's reverted but this is frustrating. I'm sorry that this is happening, I will take a look tomorrow.

**Comment by robmyers** [comment]
I didn't get round to it but it's very near the top of the heap.

**Comment by robmyers** [comment]
This should be fixed now, please try it and let me know if it's not.
