### ISSUE TITLE
summit.creativecommons.org missing footer 

### ISSUE THREAD

**Issue by cogdog** [creativecommons/creativecommons.org#595]
Noticed the logo missing from bottom left or maybe it's the whole widget is blank from https://summit.creativecommons.org/

or maybe it's not wanted there?

(aws outage seems to be borking file uploads) see https://drive.google.com/file/d/0B3J3hv1B8VO1UDRNeWF4WXg0UGs/view?usp=sharing

Checked in Chrome and Safari.

Also, as a user I might expect to left cc logo on top menu bar to go to main site creativecommons.org not the home page of the summit.

Please tell us a little bit about how you're accessing the site or page, such as which web browser and which version of the browser: https://aboutmybrowser.com/8B3EMnCN

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow

**Comment by mmoreshead** [comment]
Hey @cogdog -- it's a work in progress for me. New logo going in soon, new content all the time.  Hoping to find time to polish it up soon!
