### ISSUE TITLE
Windows 8.1 IE 11 logo scaling issue

### ISSUE THREAD

**Issue by fmann** [creativecommons/creativecommons.org#598]
Apparently IE 10 and 11 have known issues scaling SVG images. This is noticeable on the site with odd scaling of the CC logo

![screen shot 2017-03-08 at 10 27 58 am](https://cloud.githubusercontent.com/assets/711497/23717870/5cc94ad6-03ea-11e7-9d2c-139414644a92.png)

A little bit of CSS targeting IE improves the situation. The logo is still scaled a bit small but it renders legibly.
 
![screen shot 2017-03-08 at 10 29 44 am](https://cloud.githubusercontent.com/assets/711497/23717892/6df9f6ac-03ea-11e7-996d-1fa44d60f27a.png)

This change should have no impact on Edge or other browsers.

**Comment by fmann** [comment]
@robmyers  I've issued a pull request for this issue here.  https://github.com/creativecommons/new-www-theme/pull/18

**Comment by robmyers** [comment]
Merged and deployed.

Thank you!
