### ISSUE TITLE
Error when attempting to email a metadata snippet

### ISSUE THREAD

**Issue by vthunder** [creativecommons/creativecommons.org#6]
There's an error message that pops up when people try to email themselves the HTML/embedded metadata for their [public domain mark](http://creativecommons.org/choose/zero/results).

Screenshot:
![image](https://f.cloud.github.com/assets/435972/1718974/bd294750-61e5-11e3-8ac9-a591c6c185f5.png)

**Comment by robmyers** [comment]
This was all fixed.
