### ISSUE TITLE
Broken Link CC BY 3.0 AT

### ISSUE THREAD

**Issue by cproof** [creativecommons/creativecommons.org#601]
The link to the full license on https://creativecommons.org/licenses/by/3.0/at/deed.de seems to be broken, it links to https://creativecommons.org/licenses/by/3.0/at/legalcode.de instead of https://creativecommons.org/licenses/by/3.0/at/legalcode
Can you please fix this?

**Comment by keonavy1987** [comment]
601

**Comment by cproof** [comment]
Seems to be fixed?
