### ISSUE TITLE
iframe Error 503 in DSpace Creative Commons step

### ISSUE THREAD

**Issue by JamesEvansGit** [creativecommons/creativecommons.org#606]
Hello,
Today we have noticed that the submission workflow in our DSpace repositories are not working in "Choose your license" step, where the user can choose a Creative Commons license. We use an <iframe> to show the Creative Commons form, but suddenly this form returns a 503 error

![cc_err503_iframe](https://cloud.githubusercontent.com/assets/7888555/24917748/0d4330c4-1ed6-11e7-9f47-634382801709.JPG)

Looking at the console it appear the iframe is coming from  https://creativecommons.org/choose/?partner=dspace&stylesheet=http%3A%2F%2Fuobrep.openrepository.com%2Fuobrep%2Fsubmit%2Fcreative-commons.css&exit_url=http%3A%2F%2Fuobrep.openrepository.com%2Fuobrep%2Fsubmit%2Fcc-license.jsp%3Flicense_url%3D[license_url]
Can you take a look at this?
Many thanks

 @robmyers @little-wow

**Comment by robmyers** [comment]
Thank you for reporting this.

The service that handles the iframe was (briefly) down. I have restarted it.

The form should now be working.

**Comment by keonavy1987** [comment]
On

**Comment by keonavy1987** [comment]
#606

**Comment by keonavy1987** [comment]
#606
