### ISSUE TITLE
Formatting issues on mobile

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#614]
Noticed last night that the supporters are tiny on pages that are not the front page and the box to search is offset:

![img_1160](https://cloud.githubusercontent.com/assets/7093838/26123174/f75555fc-3a47-11e7-9418-efc77c15088a.PNG)
![img_1161](https://cloud.githubusercontent.com/assets/7093838/26123175/f7587d86-3a47-11e7-89e2-13800ee2d594.PNG)

**Comment by little-wow** [comment]
Ping! This is still an issue :)

**Comment by kgodey** [comment]
The search box misalignment is still an issue.

**Comment by hugosolar** [comment]
The [supporters](https://creativecommons.org/supporters/) page have changed and [Use & Remix](https://creativecommons.org/use-remix/) does not have the search box anymore. Closing this issue
