### ISSUE TITLE
Add a link to the CC Store in the top nav and on front page

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/creativecommons.org#616]
There is no link to the CC Store on the main page of cc.org.

We should have a prominent link to the CC Store on the main page of the site. Menu item should be "CC Store" or just "Store" and should appear in the top nav alongside "Search the Commons". 

Also, suggest we put a link under "Get Involved" beside "Donate" so it is "Donate or Buy CC stuff" or similar.

**Comment by robmyers** [comment]
Done!

The "Buy CC stuff" may distract from "Donate" as it's larger, but there are larger links to Donate higher up on the page so I don't think that's a major issue.

I used "CC Store" as it's more descriptive but we can lose the CC if it's redundant.
