### ISSUE TITLE
adding Turkish to language list on 4.0 licenses

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#619]
@robmyers Once the Turkish translations are live, can you please run the script to add a link at the bottom of all other published 4.0 translations? The team has confirmed that the language should be listed as Türkçe (note capitalization). 

Let me know if you need anything else. Thank you!

**Comment by robmyers** [comment]
Added in e004b9c51451c8c946b76f5f0848e6082107706d .
