### ISSUE TITLE
SOTC footer link needs to be changed

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#622]
I think this is a carry-over from the main site, but noun project icon links to https://stateof.creativecommons.org/website-icons which is not a page. Where can I edit the footer of SOTC?

**Comment by fmann** [comment]
@janeatcc That link is in the text widget in the Footer Bottom Right region. So go to Appearance > Widgets and edit that widget.

**Comment by janeatcc** [comment]
Thanks!
