### ISSUE TITLE
CC wiki has strange user nicks

### ISSUE THREAD

**Issue by tarkowski** [creativecommons/creativecommons.org#629]
Hello, I'm not sure whether this is the right place to files this, but here goes:
after logging in to the CC wiki with my CCID login (tarkowski), I'm logged in as ccid-tarkowski, which is not a very pretty login. I know it's a small issue, but identities online count and are carefully managed, so hopefully this can be fixed? It would be nice to have a login without the prefix.

**Comment by robmyers** [comment]
This was chosen when we switched to login.creativecommons.org and needed to not overwrite people's existing identities on the Wiki when reconciling them with the new logins.

Unless we start using the wiki more seriously again I'm not inclined to fix this, although I do agree they are not the nicest looking names.
