### ISSUE TITLE
Board Mailing List

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#634]
Move board list to new mailing list.  

Archive must be maintained and backed up

**Comment by mmoreshead** [comment]
A number of docs are hosted in there too, will need to pull them to back them up too.

**Comment by mmoreshead** [comment]
Is it possible to make an auto responder on the old list so that if anyone tries to send mail, they get a note that says the list is closed?

**Comment by mmoreshead** [comment]
Hey  @robmyers , just picking this back up.  Is there a way for me/you/one to pull all the docs that are hosted on ibiblio? For instance: http://ibiblio.org/cccr/docs/990.pdf Or maybe this is a separate issue from the board mailing list.

(And to close my own loop on my last question, we'll remove them from the old list and they'll get an autoresponse that says they aren't on that list. Not sure there's a way to customize it but I think it's ok.)

**Comment by mmoreshead** [comment]
Is this all of them, do you think? http://www.ibiblio.org/cccr/docs/ I'll just download them and move them to drive/wiki?

**Comment by robmyers** [comment]
I can grab them pretty automatically and put them in drive.

**Comment by mmoreshead** [comment]
@robmyers Ok, do you want to do that and then share it with me and Diane and we can sort out what needs to be shared more and what needs to be filed away?  

Then after that do you think it'll be easy enough to get the gang on the new list?

**Comment by robmyers** [comment]
I have grabbed it, see email.

**Comment by robmyers** [comment]
I need to do some more checks and then implement the move but I'm pressed for time at the moment so I  won't be able to get back onto this until later in the week.

**Comment by robmyers** [comment]
@mmoreshead let's discuss this offline.

**Comment by robmyers** [comment]
@mmoreshead This seems to have become higher priority again? Let's look at it when I'm back next week?

**Comment by mmoreshead** [comment]
Yes please, whenever you're ready!

**Comment by robmyers** [comment]
We have moved the list!

**Comment by mmoreshead** [comment]
Transfer complete, @robmyers  is the best!
