### ISSUE TITLE
CC's French version of the website still has links to English versions

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#648]
Nicolas Jupillat said in an e-mail: 

"Just noticed that on CC's French version of the website (https://creativecommons.org/licenses/?lang=fr), "Voir le code juridique" always links ("see the code") to the English versions of the licenses. Could we maybe fix that so that Francophones directly end up on the French language legal code? To avoid any confusion, the page would also probably need to reflect the current names of the licenses "Pas d'Œuvre dérivée" instead of "Pas de modification" and "Utilisation non commerciale" instead of "Pas d'utilisation commerciale", etc.".

**Comment by robmyers** [comment]
Replacing with #758.
