### ISSUE TITLE
Arabic <ol><li>

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#649]
Arabic numbering is in Latin letters at https://igo-ar-legalcode.legal.creativecommons.org/licenses/by-sa/3.0/igo/legalcode.ar and the rest of the translations. Numbers are OK, but instead of a, b, c, d, Arabic letters should be used. I called and incorporated the CSS for RTL, but it seems it's not enough.

**Comment by robmyers** [comment]
With the Arabic 4.0 ports, there was a subtle problem with the nesting of the list tags.

I expect it's the same here. I'll check.

**Comment by robmyers** [comment]
OK, that wasn't it. :-)

To get the correct Arabic numerals to display for the top-level lists, change the stylesheet and script links to this:
```
<link rel="stylesheet" type="text/css" href="/includes/deed3.css" media="screen">
<link rel="stylesheet" type="text/css" href="/includes/deed3-rtl.css" media="all">
<link rel="stylesheet" type="text/css" href="/includes/deed3-print.css" media="print">
<!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="includes/deed3-ie.css" media="screen" /><![endif]-->
<script src="/includes/jquery-3.1.0.min.js"></script>
<script type="text/javascript" src="/includes/errata.js"></script>
<script type="text/javascript" src="/includes/arabic-ol.js"></script>
```
Then for each ol that should use the top-level list digits change:

    <ol type="a">

to:

    <ol class="lower-arabic arabic">

This leaves some nested lists of type="i" that display lowercase Roman numerals. Some of these should be changed to class="arabic-indic". See the 4.0 Arabic licenses for this.

It may be useful to add the id properties to the lists, e.g. from the 4.0 Arabic licenses:

```
    <p id="s2"><strong>القسم ٢ - النطاق:</strong></p>
        <ol class="lower-arabic arabic">
            <li id="s2a"><strong>مَنْح الرخصة:</strong>
            <ol class="arabic-indic">
                <li id="s2a1">مع مراعاة أحكام وشروط هذه الرخصة العمومية، يمنحك المرخِّص رخصة عالمية، دون إتاوات، وغير قابلة للترخيص من الباطن، وغير حَصْريَّة، وغير قابلة للإلغاء، لممارسة الحقوق المرخَّصة للمواد المرخَّصة؛ وذلك لأجْل:
                    <ol class="lower-arabic arabic">
                        <li id="s2a1A">نَسْخ ومشاركة المواد الُمرخَّصة كلِّيــًا أو جزئيًا؛ و</li>
                        <li id="s2a1B">إنتاج ونَسْخ ومشاركة المواد المحوَّرة.</li>
                    </ol>
                </li>
```
This will aid in working out how deeply nested each element is and therefore which list style should be applied.

After changing the styles and scripts, and applying the correct nested ol classes, the digits that have been included in the <li>s need removing.

Also the section digits need changing to the correct Arabic numerals.

For example:
```
<p><strong>1. تعاريف </strong></p>
<ol type=a"a">
<li><strong>أ.	تعني عبارة "منظمة حكومية دولية</strong> لأغراض هذا الترخيص لا غير، أية منظمة أنشئت بموجب معاهدة أو وثيقة أخرى يحكمها القانون الدولي وتتمتع بشخصية قانونية خاصة بها. وتعتبر المنظمات الأخرى المنشأة لتضطلع بأنشطة عابرة للحدود الوطنية وتتمتع وفقا لذلك بحصانة من الإجراءات القانونية منظمات حكومية دولية لأغراض هذا الترخيص لا غير. ويمكن أن تشمل المنظمات الحكومية الدولية في عضويتها، بالإضافة إلى الدول، كيانات أخرى.</li>
<li><strong>‌ب.	وتعني كلمة "مصنف"</strong> " المصنف الأدبي و/ أو الفني المؤهل للحماية بموجب حق المؤلف، أيا كان أسلوب أو شكل التعبير المستخدم فيه، بما في ذلك الشكل الرقمي، والمتاح وفقا لشروط هذا الترخيص. ومن المفهوم أن أي قاعدة بيانات تمثل إبداعا فكريا بالنظر إلى اختيار محتوياتها وترتيبها تعتبر مصنفا.</li>
```
should be:
```
<p id="s1"><strong>١. تعاريف</strong></p>
<ol class="lower-arabic arabic">
<li id="s1a"><strong>تعني عبارة "منظمة حكومية دولية</strong> لأغراض هذا الترخيص لا غير، أية منظمة أنشئت بموجب معاهدة أو وثيقة أخرى يحكمها القانون الدولي وتتمتع بشخصية قانونية خاصة بها. وتعتبر المنظمات الأخرى المنشأة لتضطلع بأنشطة عابرة للحدود الوطنية وتتمتع وفقا لذلك بحصانة من الإجراءات القانونية منظمات حكومية دولية لأغراض هذا الترخيص لا غير. ويمكن أن تشمل المنظمات الحكومية الدولية في عضويتها، بالإضافة إلى الدول، كيانات أخرى.</li>
<li id="s1b"><strong>‌وتعني كلمة "مصنف"</strong> " المصنف الأدبي و/ أو الفني المؤهل للحماية بموجب حق المؤلف، أيا كان أسلوب أو شكل التعبير المستخدم فيه، بما في ذلك الشكل الرقمي، والمتاح وفقا لشروط هذا الترخيص. ومن المفهوم أن أي قاعدة بيانات تمثل إبداعا فكريا بالنظر إلى اختيار محتوياتها وترتيبها تعتبر مصنفا.</li>
```

**Comment by georgehari** [comment]
I tried to work on the BY-NC-SA file, just to see if the solutions work. I did everything manually, it was more difficult to do Search-Replace. I think the <ol> and <li> are better defined now. If all OK with you, I will proceed with the other 5 files.

https://igo-ar-legalcode.legal.creativecommons.org/licenses/by-nc-sa/3.0/igo/legalcode.ar

**Comment by robmyers** [comment]
That's looking great!

The only thing I can see is that the sections are still numbered 1..8 rather than ١..٨ . *I am not sure if we are meant to be changing this*, but in the 4.0 licenses the section numbers follow this format, e.g. "Section 1 - Definitions." is:

القسم ١ - تعريفات:

It's worth making the other changes then asking about this, I think.

Thank you!

**Comment by georgehari** [comment]
I will change that in all files.
In fact, the live 4.0 licenses are numbered 1...8 in the sub-sections etc.:
https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.ar
but the staged versions are numbered correctly:
https://cc4-ar-legalcode.legal.creativecommons.org/licenses/by-nc-sa/4.0/legalcode.ar.
Do you know what happened?
