### ISSUE TITLE
Deed pages can produce 416 errors

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#65]
I use a link checker on creativecommons.nl to check whether links are broken or not. This link checker asks for the first 2048 bytes of any site I've linked. Something like

    curl --range 0-2048 -v https://creativecommons.org/licenses/by/4.0/deed.nl

This provides me with a 'HTTP/1.1 416 Requested Range Not Satisfiable' error which, if I understand it correctly, could indicate a problem with the caching of creativecommons.org services.

**Comment by robmyers** [comment]
Thank you for reporting this. I've checked and confirmed this behaviour.

Unfortunately this is a product of the CloudFlare caching we are using:

    curl --include --range 0-2048 -v https://creativecommons.org/licenses/by/4.0/deed.nl

shows that the page is being cached via CloudFlare's nginx servers:

    Server: cloudflare-nginx

I don't believe we can change this behaviour on CloudFlare.

After I requested the range a few times, it was served properly, but obviously that doesn't help with the link checker (or anything else requesting new ranges).

I'm open to suggestions for how to address this but I don't think we can disable caching for the license pages - they're the most popular section of the site.

**Comment by mzeinstra** [comment]
Ah, that makes sense. Its probably not a high priority issue. Maybe you can put it through to Cloudflare and see there response to this. A web search did not yield much resources that discuss this. 

I can imagine that CloudFlare takes your server settings into account. If you disable range options on your servers through your htaccess that might solve the problem downstream.

**Comment by robmyers** [comment]
I've disabled ranges in the Apache config. The CloudFlare response now includes the entire page, so hopefully everything requesting ranges doesn't read more than its buffer size...
