### ISSUE TITLE
License deed pop-ups don't work on Safari

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#653]
e.g. the ? hover on https://creativecommons.org/licenses/by/4.0/

Using Safari Version 10.1.1 (12603.2.4)

Might check other browsers while at it

**Comment by robmyers** [comment]
@janeatcc can you check this with current safari ? If it's still b0rked I'll take a look.

**Comment by janeatcc** [comment]
Still doesn't work, on 2.0 licenses either: https://creativecommons.org/licenses/by/2.0/. 

Using Safari Version 12.0.3 (13606.4.5.3.1)

**Comment by hugosolar** [comment]
This problem is caused due to a bug in Safari and links focus which cause bootstrap's popover doesn't work.
The issue was documented [here](https://github.com/twbs/bootstrap/issues/11788)
