### ISSUE TITLE
Image caption text is very very small

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#654]
Thanks for reporting an issue, to help us file this efficiently we made this template. Feel free to ignore the template if you wish :) 

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here: https://creativecommons.org/2017/08/03/announcing-bassel-khartabil-memorial-fund/ (but seems to be on every post)

https://aboutmybrowser.com/DoeeMEWW

![screenshot from 2017-08-03 14-36-46](https://user-images.githubusercontent.com/33296/28937605-64fb4ec8-7859-11e7-8860-482716729bec.png)

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow

**Comment by little-wow** [comment]
Hi! According to @ericsteuer this is how it's supposed to be. Thanks for reporting!
