### ISSUE TITLE
Fixing default image on opengraph

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#658]
Currently looks like this

<img width="525" alt="screen shot 2017-08-11 at 11 19 26 am" src="https://user-images.githubusercontent.com/7093838/29219775-0e0c2e50-7e87-11e7-9706-0a99f8931a94.png">

**Comment by little-wow** [comment]
Rob – I'll reach out if I need help

**Comment by robmyers** [comment]
Just to make sure I understand this:

The image is scaled and cropped in a way that doesn't look good.

Is it the correct image?

And does the image have a transparent background?

**Comment by robmyers** [comment]
The spec for images of this aspect ratio (2:1) seems to be here:

https://dev.twitter.com/cards/types/summary-large-image

Smaller cards are 1:1 though:

https://dev.twitter.com/cards/types/summary

**Comment by little-wow** [comment]
done!
