### ISSUE TITLE
Popup maker is broken

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#659]
<img width="313" alt="screen shot 2017-08-11 at 2 00 25 pm" src="https://user-images.githubusercontent.com/7093838/29225763-8fae0f08-7e9d-11e7-8560-a1ee5f8c9b47.png">

<img width="1071" alt="screen shot 2017-08-11 at 2 00 35 pm" src="https://user-images.githubusercontent.com/7093838/29225766-92ddc222-7e9d-11e7-85ed-3119d5c9d4c3.png">

<img width="1021" alt="screen shot 2017-08-11 at 2 00 59 pm" src="https://user-images.githubusercontent.com/7093838/29225773-96129224-7e9d-11e7-9352-98cbac844f9c.png">

**Comment by robmyers** [comment]
Yikes! Is that on staging?

**Comment by little-wow** [comment]
Yes – I thought it may be my own configuration of the popup, so I tested out a popup that we've used in the past, and it created the blank screen shown in the second image.

FWIW that's also what happens on prod

**Comment by robmyers** [comment]
OK I clicked the link and it seems happier now. This is the advantage of having Staging, though, we can test this stuff before trying it on Production.

See how it behaves now?

**Comment by little-wow** [comment]
Same problem. I also disabled my Ublock, etc etc

**Comment by robmyers** [comment]
Now I get:

![image](https://user-images.githubusercontent.com/21746/29227239-02d31f3c-7e8a-11e7-831c-503bf4987d31.png)

**Comment by robmyers** [comment]
OK try now? Flush your browser cache if it's still not behaving ( press F5 ).

**Comment by little-wow** [comment]
nope, same issue. Pinging AB.

**Comment by robmyers** [comment]
On staging? Can you try an incognito window?

**Comment by little-wow** [comment]
Still getting the same blank window. :(

**Comment by robmyers** [comment]
Oh yes the preview *is* broken. That may be a problem with our web server rewrite rules. I'll see if there's any documentation for this.

**Comment by robmyers** [comment]
Maybe:

http://docs.wppopupmaker.com/article/322-why-is-my-popup-preview-button-not-working

?

**Comment by little-wow** [comment]
nope :(

**Comment by fmann** [comment]
I added a popup to stage targetting just the about page and I'm seeing it.

https://staging.creativecommons.org/about/

I am also seeing a "Hello World! Let’s build a vibrant global commons!" popup on the homepage of the staging site when I hit the site in an incognito window, so it seems like the basic popup functionality is working there.

**Comment by fmann** [comment]
Ahh.... reading this thread more closely and chatting with @little-wow I see that, indeed, popups do not seem to Preview correctly. But saving them and triggering them to show up in a new window appears to do the trick.

**Comment by little-wow** [comment]
@robmyers the best way to integrate Mailchimp is through this extension, but it costs a little $$. What do you think? https://wppopupmaker.com/extensions/mailchimp-integration/

**Comment by robmyers** [comment]
I can't find the license for it - we're trying to stay out of the WordPress plugin licensing debate so if it's not obviously licensed I'd like to steer clear of it.

**Comment by robmyers** [comment]
Building on what fmann said, this is the advantage of working on Staging - we can test pop-ups there as much as we like on the actual (staging) site before adding them to Live
