### ISSUE TITLE
Blog search images are gigantic when searching the site

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#660]
https://creativecommons.org/page/5/?s=eric

Huge images when searching blog content!

**Comment by robmyers** [comment]
This is because we don't have the sidebar to constrain the column width and therefore the image size.

@robinpuga is this something that could be fixed simply?

**Comment by hugosolar** [comment]
Fixed in https://github.com/creativecommons/new-www-theme/commit/204e88e6e0c735a9adfa70c269c0073911a998f0
