### ISSUE TITLE
Remove Mailchimp Popup and add Popup maker popup

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#662]
Mailchimp popup is hardcoded into WP theme, but WP Popup maker is working on Staging now, so it's time to switch it over.

Two things to do:
* QA on Popup Maker on Staging for "Email Signup" Popup
* Remove Mailchimp theme
* Deploy Popup maker

Rob – before you move it over, can you check in with me to make sure that it's ready on staging before launch?

Search will probably keep the Mailchimp plugin because it's not on Wordpress.

**Comment by robmyers** [comment]
@little-wow Heya. Just checking in about the version on staging being good to go.

Also one note: this popup will use a different cookie from the mailchimp popup in the theme, so we will get reports from people who previously subscribed via or dismissed the theme-based popup that a pop-up is showing again. We can't do anything about that, we'll just have to be sympathetic to people reporting it.

**Comment by robmyers** [comment]
The MailChimp code has been removed from the theme and deployed.

The new popup has been copied over to Live and activated.
