### ISSUE TITLE
Arrow to sign up for mailing list looks wrong

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#663]
creativecommons.org/newsletter

<img width="820" alt="screen shot 2017-08-16 at 10 52 35 am" src="https://user-images.githubusercontent.com/7093838/29369658-3fc9605a-8271-11e7-9651-7a3b88ae539b.png">

**Comment by fmann** [comment]
I just fixed it. In the code it was:

`<div class="input-group"><input id="email-Primary" class="email" maxlength="64" name="EMAIL" required="" size="30" type="email" value="" placeholder="Your email" /><span class="input-group-btn"><button id="_qf_Edit_next" class="button primary arrow" name="subscribe" type="submit" value="Sign Up"></button>Sign Up</span></div>`

The text "Sign Up" needed to be inside of the button tag, like this:

`<div class="input-group"><input id="email-Primary" class="email" maxlength="64" name="EMAIL" required="" size="30" type="email" value="" placeholder="Your email" /><span class="input-group-btn"><button id="_qf_Edit_next" class="button primary arrow" name="subscribe" type="submit" value="Sign Up">Sign Up</button></span></div>`

**Comment by robmyers** [comment]
Thank you @fmann !

**Comment by Thorcik1704** [comment]
Yes, I was yesterday  there. Sometimes is too much for me. I dont
understand what to do many times when I surfing on  internet. I AM not
hacker, I just looking for some answers about history of my
fatherland...sorry and thanks for mailing. I hope you arent laptop but real
human 😀

17.08.2017 18:55 "Rob Myers" <notifications@github.com> napisał(a):
