### ISSUE TITLE
Mystery error when trying to post

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#668]
![screen shot 2017-09-05 at 12 28 59 pm](https://user-images.githubusercontent.com/7093838/30071745-eaf6557c-9235-11e7-86f7-25345e52796e.png)

I get this error frequently when trying to post to the blog and I'm not sure why.

**Comment by robmyers** [comment]
There are some weird errors in the logs, I will investigate.

**Comment by robmyers** [comment]
This was a harbinger of disk issues, which were fixed.
