### ISSUE TITLE
Create CC4 Russian branch

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#669]
Please create a cc4-ru-legalcode branch from master, with the purpose of staging the new license translation files.

**Comment by robmyers** [comment]
I've created it here -

https://github.com/creativecommons/creativecommons.org/tree/cc4-ru-legalcode

And I will run the staging script manually now to make sure it works.

**Comment by georgehari** [comment]
https://cc4-ru-legalcode.legal.creativecommons.org/licenses/by-nc-sa/4.0/legalcode.ru etc. were staged but they are not live.

**Comment by robmyers** [comment]
These are now serving.
