### ISSUE TITLE
adding search to chrome is broken

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#674]
If you're using Chrome on https://search.creativecommons.org/  and you click on "Add CC Search to your browser." nothing happens.  (Pop up works in FF)  

This might be as simple as :

"Add CC Search to your browser (may not work in all browsers)" or whatever the best practice is for this kind of thing.  I dunno :)

Someone flagged in an info@ inquiry.

**Comment by kgodey** [comment]
Closing this since we plan to deprecate search.creativecommons.org (old) in the next couple of months.

**Comment by peterspdx** [comment]
I have no context or history on this bug.
