### ISSUE TITLE
How is a new language added in the footer of the deeds?

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#675]
A translator in Bengali asked me on Transifex when will Bengali (বাংলা) be added to the list of languages in the deeds, for example in https://creativecommons.org/licenses/by-nc-sa/4.0/, after "This page is available in the following languages". They translated the deeds&choosers by 63% and the search is fully translated.

I only know that the new translated strings are pushed live every Monday, but I don't know the answer to the question above.

**Comment by sarahpearson** [comment]
It gets automatically included in the language list once they translate enough of the strings, which I think is about 85%.

**Comment by georgehari** [comment]
Thanks!
