### ISSUE TITLE
Site for Open Access Week

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#676]
I'm building a site for open access week that I'm hoping can be published at action.creativecommons.org/open-access-week. Follow along here https://little-wow.github.io/open-in-action/

Repo: https://github.com/little-wow/open-in-action

Date of OA Week is October 23-27

**Comment by robmyers** [comment]
Hey awesome!

I assume we're just serving that directory directly at the url on action.cc.org ?

Ping me the week before and we can get that set up (or sooner if needed, but after ITW :-) ).

On a purely technical level I would add a .gitignore file to the project that just contains the following line:

    .DS_Store

**Comment by pyaephyoswe** [comment]
pyaephyoswe569@gmail.com

**Comment by tvol** [comment]
@little-wow @robmyers i think the widget idea is cool, but do we need a separate site? can't it just be embedded into a blog post or a page on cc.org?

**Comment by little-wow** [comment]
It should be a landing conversion page so that people can easily sign up for the email list. The page will sit at action.cc.org
