### ISSUE TITLE
"Copy this code [...]" boxes: Selecting a fragment selects all

### ISSUE THREAD

**Issue by Chealer** [creativecommons/creativecommons.org#681]
If I go to https://creativecommons.org/choose/?lang=en and try selecting - for example - a URL in the "Copy this code to let your visitors know!" textarea, the actual selection becomes the whole textarea's content when I release the primary mouse button.

This happens at least in Microsoft Internet Explorer and Google Chrome 61.

**Comment by robmyers** [comment]
This is intentional behaviour to help people copy the metadata block correctly.

I agree that it's frustrating when one wishes to copy only part of it, but that's the less common case and we can always copy it to a text editor to extract the required section.

**Comment by Chealer** [comment]
Thanks @robmyers,
It could be intentional, except the selection should then encompass the whole text as soon as the primary button is pushed, not just when it is released (as happens after one has tried to select a fragment once).

Other avenues to fix while still being very friendly with those who want the whole code:

1. Make "Copy this code" a button to select all
2. Simply make the code zone larger so there is no scroll bar. Just using the whole width would probably suffice.

Adding buttons to select just URL-s would also reduce impact.
