### ISSUE TITLE
Markdown displayed instead of link

### ISSUE THREAD

**Issue by mrpaco85** [creativecommons/creativecommons.org#685]
Thanks for reporting an issue, to help us file this efficiently we made this template. Feel free to ignore the template if you wish :) 

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here:  https://creativecommons.org/faq/#what-are-creative-commons-licenses

You can also attach a screenshot to this issue if you have a visual bug to report. That'll help us figure it out faster. http://www.take-a-screenshot.org/ has instructions on taking screenshots.

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow
![image](https://user-images.githubusercontent.com/25771628/31259505-260d9642-aa15-11e7-9600-ce36ce6e3e2c.png)

**Comment by little-wow** [comment]
@mmoreshead

**Comment by little-wow** [comment]
@mmoreshead Just giving a ping on this because I can't edit this page :)

**Comment by robmyers** [comment]
The FAQ is not in WordPress, it's stored in a separate Git repo here:

https://github.com/creativecommons/faq

It's a static site to help track changes and facilitate translation. We have to be very careful when changing it but I *think* fixing a broken link is OK. I'll need to deploy any changes.

**Comment by robmyers** [comment]
Thank you for reporting this!

This issue has now been fixed.
