### ISSUE TITLE
Help people on the deeds sign up for the mailing list

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#687]
U know what I mean @robmyers

**Comment by robmyers** [comment]
😉

**Comment by robmyers** [comment]
Something like the one that used to be on the front page?

**Comment by little-wow** [comment]
Remind me?

**Comment by robmyers** [comment]
The "stay tuned to the commons" strip, it's still on Staging (halfway down the page) -

https://staging.creativecommons.org/

**Comment by little-wow** [comment]
Aha, yeah, exactly, though maybe in a more match-y color We took that off because of popup, yes?

**Comment by robmyers** [comment]
We did. I wonder if it is worth passing this to AB or if my efforts will be acceptable... :-)

**Comment by little-wow** [comment]
We shall see!
