### ISSUE TITLE
Add unbounce to action.cc

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#688]
Using unbounce for conversion/ab testing for OA Week. Need to put it on the server. Ping me for details.

**Comment by robmyers** [comment]
Can we point the domain at unbounce or do we need to use the WordPress plugin? Action.cc isn't a WordPress site so this would be a lift and I'm pushed for time this week.

**Comment by robmyers** [comment]
OK so I assume we will do this -

https://documentation.unbounce.com/hc/en-us/articles/203661044-Connecting-Your-Domain-to-Unbounce-with-CNAMEs

Email me the details and I will set up the cname? :-)

**Comment by little-wow** [comment]
Will do

**Comment by robmyers** [comment]
I've added the cname, it will take a few hours to show up.

**Comment by robmyers** [comment]
https://action.creativecommons.org/ now gives a 404.

@little-wow is this expected or is there some further setup either of us needs to do to fix it?

**Comment by robmyers** [comment]
action.cc is not on wordpress. It just points at unbounce via the cname.

**Comment by little-wow** [comment]
It's currently pointing at Unbounce but it says on the app that it's not working – a bit concerned our stats will be off. Would you mind taking a look at it?

**Comment by little-wow** [comment]
Hi – CNAME is still not reading in Unbounce. Any reason why, you think?

**Comment by robmyers** [comment]
I turned off the CloudFlare http proxy. Try now?

**Comment by robmyers** [comment]
That seems to have disabled https. :-/

See here -

https://community.unbounce.com/t/how-do-i-use-ssl-on-a-cname-subdomain-redirect/4184/3
