### ISSUE TITLE
stats.creativecommons.org has a invalid SSL certifcate

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#689]
Hi,

stats.creativecommons.org has a invalid SSL certifcate causing a security error on the deed pages in the console on Chrome Version 61, MacOS 10.13 (when forcing SSL). This can cause your piwik not to track these users.

![stats cc](https://user-images.githubusercontent.com/5627431/31811787-2773f00e-b581-11e7-80a6-511cefa60a1c.png)

**Comment by DineshkumarAgrawal4** [comment]
20

**Comment by DineshkumarAgrawal4** [comment]
DINESHKUMARAGRAWAL71@GMAIL.COM

**Comment by robmyers** [comment]
Thank you for reporting this!

I have fixed Let's Encrypt on this server. The certificate is now good.

**Comment by mzeinstra** [comment]
Great!

Now you probably also want to add redirect on the root of https://stats.creativecommons.org/ to https://creativecommons.org/ to remove your default debian page. :)
