### ISSUE TITLE
WP image upload error

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#69]
See attached file. Not sure what's the problem.
![wp image upload error](https://cloud.githubusercontent.com/assets/6394777/8386522/e26e6302-1c05-11e5-92d2-ed6d6644c95b.jpg)

Need to upload image by next Tues morning pacific time.

**Comment by mattl** [comment]
We're working on the site right now until it's back you'll have a hard time uploading new images.

**Comment by mattl** [comment]
Okay, you should be all set now. If you have problems, reopen this and we'll take a look for you. Thanks for your patience.
