### ISSUE TITLE
Donate page is showing Year End Image Metadata on Open Graph

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#691]
The featured image is the big green donate heart but it's pulling the YE campaign image from last year. Not sure why this is.
![screen shot 2017-10-24 at 10 27 38 am](https://user-images.githubusercontent.com/7093838/31948913-fef1059a-b8a5-11e7-813f-0cb698632dd7.png)
![screen shot 2017-10-24 at 10 28 00 am](https://user-images.githubusercontent.com/7093838/31948928-08ab1170-b8a6-11e7-8704-cd379fbf28fd.png)

![screen shot 2017-10-24 at 10 28 15 am](https://user-images.githubusercontent.com/7093838/31948942-139aa7e4-b8a6-11e7-8bc9-502094845d16.png)

**Comment by little-wow** [comment]
ping @robmyers can you help??

**Comment by robmyers** [comment]
Oh regarding still seeing 2015 utms, people have linked to /donate/ with them so that might explain it. e.g. - https://arakaliamogh.wordpress.com/copyright-all-rights-reserved/

**Comment by little-wow** [comment]
@robmyers Not sure what you mean?

**Comment by little-wow** [comment]
This is YE 2016

**Comment by robmyers** [comment]
Unrelated comment on ticket. ;-)

**Comment by robmyers** [comment]
See "Explicitly Tell Facebook To Use Thumbnail of Your Choice" here -

http://www.wpbeginner.com/wp-tutorials/how-to-fix-facebook-incorrect-thumbnail-issue-in-wordpress/

**Comment by little-wow** [comment]
Fixed!
