### ISSUE TITLE
Visual bug on deed page

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#692]
See attached image.

My browser is Chrome 62.0.3202.62 on mac 10.13.0 with adblocker and ghostery (tracking blocking).

![cc visual bug](https://user-images.githubusercontent.com/5627431/31951328-0dbb0b24-b8de-11e7-8364-12dde56d6c7d.png)

**Comment by mzeinstra** [comment]
Can we fix this? It has been almost 6 months since I reported that second logo left to non-commercial has a duplicate image.

It seems to occur when the NC wants to display the currency of the area (e.g. Euro or the Japanese Yen) in the old design but the dollar in the new design.

It is due to this file: https://github.com/creativecommons/creativecommons.org/blob/master/docroot/includes/jurisdictions.css
and occurs on the licenses with NC for Belgium, Finland, France, Guatemala, Italy, Japan, Luxembourg, Netherlands, and Spain.

**Comment by robmyers** [comment]
@robinpuga was this a conscious decision? I forget.

**Comment by mzeinstra** [comment]
I think it was never taken as a feature for the new designs of the new deed pages and is an artifact of the older ones. I like the feature, but I can imagine that it overcomplicates. I suggest removing the reference to that css file on the deed page and create a feature request to re-introduce these icons based on their respective currency.
