### ISSUE TITLE
icons download page missing the eps file for public domain mark

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#693]
https://creativecommons.org/about/downloads/

under "icons"

the public domain mark icon's eps file is missing

need it for a project

**Comment by little-wow** [comment]
@robmyers IDK where this lives.

**Comment by robmyers** [comment]
That is weird! We don't have EPS for everything. :-/

Inkscape and Illustrator can load and convert the SVG to EPS.

Attached is a quick conversion. We should probably add the missing ones to the mirror and to the page.

[publicdomain.zip](https://github.com/creativecommons/creativecommons.org/files/1435591/publicdomain.zip)

**Comment by ericsteuer** [comment]
@little-wow would you mind adding the eps rob made to the cc site on the downloads page?

i should know how to do that myself, but i don't because i am very dumb!

https://creativecommons.org/about/downloads/

under "icons"

the public domain mark icon

**Comment by little-wow** [comment]
done
