### ISSUE TITLE
'Back to deed link' on CC0 page is not working

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#694]
Go to:
https://creativecommons.org/licenses/zero/1.0/legalcode

Click on "« Back to Commons Deed" in the bottom of the page.

See that it redirects to "./" instead of a proper url. It redirects to http://licenses.productionwww.creativecommons.uk0.bigv.io/publicdomain/zero/1.0/

**Comment by robmyers** [comment]
Thank you for reporting this.

/licenses/zero/ is incorrect, it's /publicdomain/zero/ .

There is a redirect for this in the webserver config but it was broken (along with the one for /licenses/CC0...).

I have now fixed this.

**Comment by mzeinstra** [comment]
Unsure where I found that url last year, a google search actually shows some documents from CC-NL that refer to it.

**Comment by robmyers** [comment]
Yes it's in our redirects so we should handle it (by sending the user to the correct page).

We have a few like that. :-)
