### ISSUE TITLE
CC0 Lithuanian translation page not found (new branch created)

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#695]
The page at https://cc0-lt-legalcode.legal.creativecommons.org/publicdomain/zero/1.0/legalcode.lt is not found. It's the same bug when creating a new branch. This time, the branch is **cc0-lt-legalcode**.

**Comment by robmyers** [comment]
Gah it's worse than usual. :-( I probably need to upgrade Let's Encrypt. Looking...
