### ISSUE TITLE
Change donate page to have no header

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#701]
Based on what we're seeing on the donate page, I think we should remove the navigation on the page and bring the donate form up to the upper right hand "above the fold"

"We'd have to make a specific page template in the WordPress theme (create a php file) and modify the css for the form."

The goal is for the page to look more like this: https://act.350.org/donate/build/

Here's a wireframe of a Donate page without the header that I'd imagine:

![screen shot 2017-11-07 at 5 50 11 pm](https://user-images.githubusercontent.com/7093838/32522143-236a3bf0-c3e4-11e7-82b3-b085e855733f.png)

Background could be solid orange or if it's not too difficult, maybe something like this: https://www.flickr.com/photos/ter-burg/34167834392/in/album-72157683167560985/

**Comment by little-wow** [comment]
One last note on this is whether we can reemphasize paypal on the site!!

**Comment by robmyers** [comment]
Support for this is in new-www-theme 41070b84f567b9c7e91d1a09e513f789da31a8aa , which has been deployed on staging and live.

This provides a layout that centres the content in a single div in the middle of the page, and some css classes to support the layout in the wireframe using flex layout.

To use this layout select "Floating Content Template" as the page template then set the image that you wish to use as the background image as the page's Featured Image.

For the page content, use the content that we've created on staging.

**Comment by robmyers** [comment]
Everyone I've spoken to regards this as A Very Good Thing to Do. How should we revisit it?

**Comment by little-wow** [comment]
Once we get the OK from @Scott-CC @jayaw  to move forward on CRM project we will be able to.
