### ISSUE TITLE
Optimizely code for testing donate site

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#705]
We're testing the donate site! Yay.

We're going to need to add some bespoke code from Optimizely. I'll ping you as needed, this is a placeholder ticket.

Thanks!

**Comment by little-wow** [comment]
Tabling this and probably removing the code because the donate site is borking the whole site.

**Comment by robmyers** [comment]
The live site??? How so?

**Comment by little-wow** [comment]
sorry, no, the staging site. Don't think we'll get to switching up the donate page before YE and I don't want to bork live with this.

**Comment by robmyers** [comment]
OK phew. I will look at staging.
