### ISSUE TITLE
Version4 page is wonky

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#706]
https://creativecommons.org/share-your-work/licensing-considerations/version4/

**Comment by robmyers** [comment]
Eek it was more widespread. I've fixed it. Thank you for reporting it.

@little-wow this resulted from the theme changes for the donate page. Hold off on that for now, I'll investigate further in the morning.

**Comment by peterspdx** [comment]
Double eek. One serious problem is that there is a different, very important page that should be on the main website, not on the wiki where it is now, that should be linked to from the main licensing page. This is the real "before licensing considerations" page, that is linked to from the legal code of every translation 4.0: https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees

To have the page you link to above under a URL that suggests those are the considerations is a problem. Those aren't considerations, those are the features of 4.0, and IIRC they used to be located at creative commons.org/version4. 

@robmyers I'm happy to help sort this out. I don't recall decisions around moving the features page or how the official considerations that are linked to in every one of the 4.0 licenses was relegated to the wiki. Let's talk tomorrow during the legal-tech check in. @sarahpearson so she's aware too.

**Comment by little-wow** [comment]
Let me know how I can help this be rectified @peterspdx  – I am happy to put that page up.

The decisions with what's on the Wiki vs main site happened before my time, but the new site has a lot of the same basic structure as the old site, so some of those decisions may have been legacy decisions. If you can give me a list of pages to move over, I am happy to do it.

Rob – also let me know how I can help fix this. It's not an emergency to test out other formatting on the /donate page and we can hold off if needs be.

**Comment by little-wow** [comment]
Just pinging on this ticket @peterspdx to ask what's needed!

**Comment by peterspdx** [comment]
I worked through this with Rob late last week. It's not fatal at present,
but stuff got moved around with website changes and the links and content
aren't as they should ideally be. Prioritizing other work, but I'll send a
note with instructions.

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC

**Comment by peterspdx** [comment]
Sorted this out.

This Page here: https://creativecommons.org/share-your-work/licensing-considerations/version4/

Wrongly contains the content for What's New in 4.0! (see the side bar under In this section).

The page where the content for What's New in 4.0! should live here: https://creativecommons.org/Version4, as it did when we first launched that page in 2013; however, it now redirects to the first link above. 

The content that belongs at the first link above is the content that is here, currently on the wiki but that really ought be on the main website:
https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees#Considerations_for_licensors

Let me know if you have questions, @little-wow @robmyers

**Comment by little-wow** [comment]
Going through bugs and want to check @robmyers do you want to do this through redirects or through copying the pages over?

**Comment by robmyers** [comment]
If we are moving stuff off the wiki we should move it over (and replace the wiki page with a link to it).

**Comment by peterspdx** [comment]
This is still a problem. To pull it forward:

Sorted this out.

This Page here: https://creativecommons.org/share-your-work/licensing-considerations/version4/

Wrongly contains the content for What's New in 4.0! (see the side bar under In this section).

The page where the content for What's New in 4.0! should live here: https://creativecommons.org/Version4, as it did when we first launched that page in 2013; however, it now redirects to the first link above.

The content that belongs at the first link above is the content that is here, currently on the wiki but that really ought be on the main website:
https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees#Considerations_for_licensors

Happy to slack and talk through it.

**Comment by hugosolar** [comment]
I already update the content on https://creativecommons.org/share-your-work/licensing-considerations/version4/ and create a new page (https://creativecommons.org/version4) with the prior content of the first link.
The website still redirect the `/version4` to `/about/licensing-considerations/version4`  because an apache rule is performing that action. Line 181 should be commented/removed

Line 181 (creativecommons.org.conf):
```
Redirect permanent /version4 /about/licensing-considerations/version4
```
tagging @TimidRobot for this
