### ISSUE TITLE
Typo on the Brooklyn Museum example: license license

### ISSUE THREAD

**Issue by elopio** [creativecommons/creativecommons.org#709]
Thanks for reporting an issue, to help us file this efficiently we made this template. Feel free to ignore the template if you wish :) 

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here:
https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/#nc

Please tell us the steps to reproduce the problem, if needed:

1. Go to https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/#nc
2. Read the example of the Broolyn Museum
3. Note that in the end of the first sentence there is the word "license" repeated:

Please tell us a little bit about how you're accessing the site or page, such as which web browser and which version of the browser:

Mozilla Firefox Nightly for Ubuntu 58.0a1 (2017-11-05) (64-bit)

(You can also vist https://aboutmybrowser.com/ which will give you a link you can share with us that'll tell us everything we need to know)

You can also attach a screenshot to this issue if you have a visual bug to report. That'll help us figure it out faster. http://www.take-a-screenshot.org/ has instructions on taking screenshots.

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow

**Comment by little-wow** [comment]
fixed, thank you again :)
