### ISSUE TITLE
Open ed etherpad recovery

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#71]
See email thread with @soohyunpae. 

I was just about to send a reminder about the next Open Ed Call in two weeks when I realized that the etherpad with 2 years full of notes is gone still. Any chance we can recover by next week so I send out the reminder for the meeting?

Would like to recover these two pads:
http://etherpad.creativecommons.org/p/Open_Education_Call
http://etherpad.creativecommons.org/p/SOO_Africa

**Comment by robmyers** [comment]
I'll take a look.

**Comment by janeatcc** [comment]
Can we recover later this week so I can send out with reminder? Also, is the new pad.cc.org only accessible with a CC login now?

**Comment by robmyers** [comment]
I've not succeeded yet so I'll raise it in my meeting with @mattl tomorrow.

Anyone with a CCID can log in. Anyone can get a CCID, if they don't have
one yet they can register here -

https://login.creativecommons.org/register.php

**Comment by robmyers** [comment]
That was a bit more involved than expected. :-)

I've restored the content of the last version of each pad.

**Comment by mattl** [comment]
@robmyers please add a message at the top of every page on pad, telling
people it's not permanent and to keep a copy of the text elsewhere  :)

**Comment by robmyers** [comment]
Added to creation and pad pages.

Changeset:

diff --git a/src/static/css/pad.css b/src/static/css/pad.css
index 49a54fb..53efbe8 100644
--- a/src/static/css/pad.css
+++ b/src/static/css/pad.css
@@ -211,7 +211,7 @@ li[data-key=showusers] > a #online_count {
 
 #editorcontainer {
   position: absolute;
-  top: 37px; /* + 1px border */
+  top: 56px; /* + 1px border */
   left: 0px;
   right: 0px;
   bottom: 0px;
diff --git a/src/static/favicon.ico b/src/static/favicon.ico
index 938e955..483ac5d 100644
Binary files a/src/static/favicon.ico and b/src/static/favicon.ico differ
diff --git a/src/templates/index.html b/src/templates/index.html
index 626630e..a8887d3 100644
--- a/src/templates/index.html
+++ b/src/templates/index.html
@@ -159,7 +159,9 @@
 
         <div id="wrapper">
         <% e.begin_block("indexWrapper"); %>
-            <div id="inner">
+        <div id="inner">
+         <p><b><i>Please note that pads are not permanent - keep a copy of the text elsewhere!</i></b></p>
+         
                 <buttOn id="button" onclick="go2Random()" data-l10n-id="index.newPad"></button>
                 <label id="label" for="padname" data-l10n-id="index.createOpenPad"></label> 
                 <form action="#" onsubmit="go2Name();return false;"> 
diff --git a/src/templates/pad.html b/src/templates/pad.html
index dd26041..21024b9 100644
--- a/src/templates/pad.html
+++ b/src/templates/pad.html
@@ -71,6 +71,7 @@
                 <%- toolbar.menu(settings.toolbar.right) %>
                 <% e.end_block(); %>
             </ul>
+           <div id="warning">Please note that pads are not permanent - keep a copy of the text elsewhere!</div>
         </div>
         <% e.begin_block("afterEditbar"); %><% e.end_block(); %>

**Comment by mattl** [comment]
Great work, Rob.
