### ISSUE TITLE
There are two empty bullets in the Licenses and Examples page

### ISSUE THREAD

**Issue by elopio** [creativecommons/creativecommons.org#711]
Thanks for reporting an issue, to help us file this efficiently we made this template. Feel free to ignore the template if you wish :) 

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here:

https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/#nc

and

https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/#by-nc-sa

Please tell us the steps to reproduce the problem, if needed:

1. Go to the sections for nc and by-nc-sa of the licenses and examples page
2. Go to the end of the section
3. Note that there are empty bullets (see the attached screenshots)

Please tell us a little bit about how you're accessing the site or page, such as which web browser and which version of the browser:

Mozilla Firefox Nightly for Ubuntu 58.0a1 (2017-11-05) (64-bit)

(You can also vist https://aboutmybrowser.com/ which will give you a link you can share with us that'll tell us everything we need to know)

You can also attach a screenshot to this issue if you have a visual bug to report. That'll help us figure it out faster. http://www.take-a-screenshot.org/ has instructions on taking screenshots.

![cc1](https://user-images.githubusercontent.com/617831/33048201-439bc4d0-ce1f-11e7-9be3-79a71a2e4e3b.png)

![cc2](https://user-images.githubusercontent.com/617831/33048205-4782528a-ce1f-11e7-8939-55192a8aecf5.png)

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow

**Comment by little-wow** [comment]
I couldn't reproduce that, but I saw where in the code it may have been caused. Let me know if you're still seeing it and I'll reopen the ticket, but it should be solved.

**Comment by elopio** [comment]
Yeah, I don't see it anymore :/ Maybe it's because I'm using firefox nightly. Thanks for checking anyway!
