### ISSUE TITLE
Decommission Scraper tool

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#718]
The scraper tool that was designed to add additional metadata to a deed page from a referrer page can / needs to be scrapped (phun intended).

CC has moved to HTTPS only, which breaks this tool. 

This ticket was created as a follow up on a cc developers discussion on Slack.

**Comment by paul2keller** [comment]
I have no idea how widespread the use of this functionality was, but I know of at least two uses in the wild. Europeana used this for all of its 20+ million PD marked objects, and I used it on a demonstration website: http://www.voyantes.net/test/pdm.html my guess is that this was not widely used but I think as a responsible steward of the licenses CC should communicate when it retires functionality related to the licenses. Since this functionality was broken as a result of the switch to https i would assume this is actually a pretty easy story to sell. Something along the lines of: 

> we upgraded to https only which is great because yada yada yada. Unfortunately as part of this upgrade we had to decommission the scraper tool so the display of additional metadata on our deeds functionality is not available anymore

would be great if this could still be done

**Comment by robmyers** [comment]
Thank you for this!

That sounds good. I can make sure there's nothing that needs altering in the deed rendering code as a result (particularly anything that would affect security...). I'll talk to comms to see what we need to do but it's probably just a blog post. We should also update any references in the technical documentation on the Wiki that isn't part of a standard.

And we should dream up a future means of displaying license information on the deed. ;-)

**Comment by paul2keller** [comment]
thanks @robmyers for getting back on this. A blogpost noting this changes was really all I had in mind. in a perfect world scenario there would also be a change-log where CC documents all changes of the tools/licenses but I don't know if that is realistic (something like: http://rightsstatements.org/en/documentation/changelog.html)

**Comment by peterspdx** [comment]
+1. I was just noting that CC can do a better job documenting these same types of changes, and explaining rationales for doing so. E.g., the changes to our website, when the framing of the deeds changed, etc. Blog posts would be good for the bigger decisions, but at least a change log as Paul suggests would be great (as opposed to using Github -- something more central and available to everyone, not those just versed in Github).

**Comment by paul2keller** [comment]
@peterspdx @robmyers any news on this. We are working on a review of the Europeana data exchange agreement where we need to remove the obligation on Europeana to display the metadata use guidelines. This will be controversial and so we really need a public announcement by CC that this functionality does not exist anymore. We need tot by 10 January at the latest.

**Comment by peterspdx** [comment]
Rob and I have a legal-tech check in today. This will be a point we'll discuss, then we'll be back to you.

**Comment by peterspdx** [comment]
Rob's going to discuss further internally and will be back before the end of the year.

**Comment by robmyers** [comment]
OK we are going to officially decommission this on 5th January 2018.

I will get a blog post out about this.

**Comment by peterspdx** [comment]
@robmyers We discussed, but it occurs to me that it's possible this breaks CC's non standard deeds. Can you please confirm that decommissioning this tool won't affect the IGO 3.0 deed, which points out key differences between the IGO 3.0 licenses and the international 3.0 licenses and other ports at that version level?

**Comment by robmyers** [comment]
Yes I can confirm that. The "Notices" section is part of the deed text and is unaffected by the Scraper, which just adds attribution information.

**Comment by robmyers** [comment]
After discussing with comms., I added a notice to the Wiki page, which seems to be the most official document we have for the scraper.

I also moved the scraper code to the /cc-archive/ project on GitHub.

The Scraper is no more.

**Comment by paul2keller** [comment]
can you provide a link to the wiki page?

**Comment by robmyers** [comment]
The wiki page is here -

https://wiki.creativecommons.org/wiki/Metadata_Scraper
