### ISSUE TITLE
new mailing list for GS2018

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#723]
Hey @robmyers - could you set up mailing list for the summit scholarship evaluation committee and I'll populate it as admin?  Thank you!

**Comment by mmoreshead** [comment]
Thank you!

**Comment by robmyers** [comment]
You're welcome!

Sign-up is set to require the applicant to respond to an email and then you to approve them. We've had spammers recently...

**Comment by mmoreshead** [comment]
The scholarship evaluation committee would like one too if you can @robmyers ?

**Comment by KrungthongPhueanchaimi** [comment]
tuckcable
เมื่อ 11 ธ.ค. 2017 20:43 "Mari Moreshead" <notifications@github.com>
เขียนว่า:

**Comment by mmoreshead** [comment]
forget it, i see from TW that this was already created!

**Comment by KrungthongPhueanchaimi** [comment]
> A/C:003-1-94727-8
> supprot@casikornbank

เมื่อ 11 ธ.ค. 2017 20:43 "Mari Moreshead" <notifications@github.com>
เขียนว่า
>
> The scholarship evaluation committee would like one too if you can
@robmyers ?
