### ISSUE TITLE
Honeypot gravity forms

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#725]
I'd like to do an "abandoned cart" type of email for folks who don't make it through the donate form, but there's a lot of spam in the Gravity Forms instance.

Is there any way to eliminate the amount of spam that comes through with a honeypot? Thanks!

**Comment by robmyers** [comment]
We should definitely ask Affinity Bridge about this.

This would be a field in the form that says something like <field hidden=true id="name">Don't fill me in if you're not a machine , which the form checks for and ignores any submissions that have it filled out in?

**Comment by little-wow** [comment]
I'm thinking of more of an invisible Return Path type service, which will check all the emails inputted into the form against a send: https://www.senderscore.org/ not sure how much that costs though?

**Comment by EleanorCCarter** [comment]
Hi there, folks. 

Happy to discuss this in detail on the phone - for now, our team are advising against the above, given that its peak giving season & we want to ensure that we're not increasing any risks of form breakage. 

Thanks,
Eleanor
