### ISSUE TITLE
If you're asking for $5 a month, make $5 a month a default

### ISSUE THREAD

**Issue by mattl** [creativecommons/creativecommons.org#726]
Currently I see

<img width="614" alt="screen shot 2017-12-11 at 3 14 58 pm" src="https://user-images.githubusercontent.com/33296/33851784-144dc9ae-de86-11e7-8412-90630b5ca1bc.png">

Making $5 an option to match the banner would be nice.

**Comment by mattl** [comment]
@little-wow

**Comment by robmyers** [comment]
Thank you for reporting this @mattl !

@rebeccalendl @little-wow what is the correct amount on each page?

**Comment by little-wow** [comment]
<img width="1153" alt="screen shot 2017-12-11 at 3 19 01 pm" src="https://user-images.githubusercontent.com/7093838/33851942-a9e633fc-de86-11e7-99d5-af6755924c02.png">

Is what I see on /donate. What Matt's reporting I've seen on staging but never on prod!

**Comment by fmann** [comment]
The values that @mattl showed are the Monthly values. 

Agreed that it'd be a smoother user experience if there where buttons on the donation form that matched the values in the buttons on the banner/overlay, which would be $5 Monthly and $75 One-Time.

**Comment by little-wow** [comment]
Got it. Should be fixed. Thanks for reporting @mattl

**Comment by KrungthongPhueanchaimi** [comment]
Krungthongphueanchaimi@gmail.com

เมื่อ 12 ธ.ค. 2017 3:29 "Jennie Rose Halperin" <notifications@github.com>
เขียนว่า
