### ISSUE TITLE
/license/ gives a redirect to a blog post from 2015

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#727]
/license/ should probably not be picked up by Wordpress and default to a blog post from 2015. Is it possible to change the redirect over to the licenses? I know the URL is technically /licenses/, but is it possible to redirect to the licenses in case of typos?  

Here's the post it redirects to: https://creativecommons.org/2015/08/05/4-0-bahasa-indonesia-translation-and-a-book/

**Comment by robmyers** [comment]
/license/ historically redirected to /choose/ . That behaviour has been restored.
