### ISSUE TITLE
Mailing list not working

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#728]
The summit program committee list messages aren't being sent. @cablegreen sent one today and no one got it. Can you check to see if they're having issues again?

**Comment by robmyers** [comment]
Eek! Reported to email provider.

**Comment by mmoreshead** [comment]
Cable's came through this morning but there's another outstanding that TW sent.

**Comment by mmoreshead** [comment]
and Terry's just came through now.
