### ISSUE TITLE
NONE OF YOUR PODCASTS ARE WORKING ON APPLE APP :(

### ISSUE THREAD

**Issue by Leahey33** [creativecommons/creativecommons.org#729]
Howdy Guys,

As someone who is trying to dominate the startup world of Silicon Valley I regret to inform you that most all of the lectures from your "Building A Business" podcast do not play on itunes or the Podcast apple app :(

https://podcasts.ox.ac.uk/series/building-business

I even tried listening to them directly from the website but when I click on many it just gives me an error and says the file is not available anymore??? :( This deeply saddens me and the entire United States is in an uproar now do to these audio file errors :) Any chance you can fix this so we can get back to business as usual? :)

**Comment by mmoreshead** [comment]
Hi there, CC did not create and does not run any part of the site you've linked.  You will have to contact them directly to get this message to the people who do own it.

**Comment by Leahey33** [comment]
Oh ok! I saw your "CC" logo on on their podcast episodes hence why I
thought you guys are the media distributor?
