### ISSUE TITLE
push Maori deed translation live

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#73]
The deed strings are translated and reviewed in Transifex, but I think they may need to be manually pushed live because they are the only strings translated so far. We aren't going to publish the Maori 4.0 legal code translations until this is done, so if possible to do today or tomorrow, that would be awesome. Thanks!

**Comment by sarahpearson** [comment]
Thanks, mattl! The deeds look great. What do they need to do to get it to show up in the language list at the bottom of other deeds?

**Comment by mattl** [comment]
Those languages are manually added to all the other language deeds, so
you'd edit each of the other 4.0 deeds in a new branch and make a pull
request. You may want to add a link to the other translation that's coming
first.
