### ISSUE TITLE
update /policies page on main website

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#735]
Update text on https://creativecommons.org/policies to conform with edits submitted by @peterspdx to account for misc changes plus launch of CCGN membership site.

Archive effective version prior to making changes, and note at bottom of page as with earlier versions of the page.

Changes are contained in document: Policies changes (Oct 1, Nov 8, Jan 16), shared via email.

Assigned to @little-wow 

Copying @robmyers for his reference

**Comment by little-wow** [comment]
done
