### ISSUE TITLE
freemusicarchive.org Licensing Tool 503'ing

### ISSUE THREAD

**Issue by CheyenneFMA** [creativecommons/creativecommons.org#739]
When trying to use the integrated freemusicarchive.org license chooser, I get this: 
![screen shot 2018-01-22 at 11 47 45 am](https://user-images.githubusercontent.com/9011511/35241474-6d639ebe-ff6b-11e7-817d-0d3209d92898.png)

Text:

Error 503 Service Unavailable
Service Unavailable

Guru Meditation:
XID: 34867138

Varnish cache server

I have tried to access this tool using Chrome [https://aboutmybrowser.com/CQMmJnop](url) and Firefox [https://aboutmybrowser.com/bCZZP3II](url) on Mac; both give me the same result. 

The tool helps choose licenses for new uploads on freemusicarchive.org and typically looks like this: 
![screen shot 2018-01-22 at 12 03 42 pm](https://user-images.githubusercontent.com/9011511/35241743-52db0e32-ff6c-11e7-947a-006314c9ce73.png)

Thank you!

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow

**Comment by robmyers** [comment]
It's back now.

Thank you for reporting this!
