### ISSUE TITLE
There Is Some Weirdness in WordPress with Posts with Titles using British English Spelling

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#740]
Some historical articles have the ~~correct~~ other spelling of license as "licence" in their permalinks, but WordPress is rewriting this to "license" before searching the database for them. It therefore does not find them, as their permalinks do not match the rewritten version.

e.g.:

https://creativecommons.org/2015/07/13/new-translations-cc-4-0-licenses-now-available-in-te-reo-maori-and-japanese/

https://creativecommons.org/2007/11/09/cory-doctorow-on-how-to-use-cc-licenses/

This seems to be where you would expect the subject to use that spelling in context.

The spelling has been changed in the title for the article but not in the permalink.

I'm going to stop WordPress autocorrecting the spelling, rather than change the spelling in the permalinks as permalinks should not be changed.

@little-wow This should only improve our Google indexing and our SEO but do shout if I'm wrong. :-)

**Comment by kgodey** [comment]
Note: Create a WordPress best practices guide and talk to Eric and Jennie about other issues like this to document them in the guide.

**Comment by kgodey** [comment]
I'm not sure what needs to be done here so I'm closing it. Please reopen if needed.
