### ISSUE TITLE
CSS seems to be broken on https://creativecommons.org/about/downloads/

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#741]
All icons on the downloads page seem to be one long list, I don't believe this is what it should look like.

See https://creativecommons.org/about/downloads/

And I think it should look more like:
https://web.archive.org/web/20160108162902/https://creativecommons.org/about/downloads/

Also the page gives a 503 when trying to load resources from https://staging.creativecommons.org/wp-content/uploads/2017/08/envelope_cc_heart_crop.png

**Comment by robmyers** [comment]
Looks like this is something that was in the old theme but not the new one.

The heart issue was in the pop-over. That has been fixed.

**Comment by robmyers** [comment]
See also #273 .

**Comment by mzeinstra** [comment]
Alright, then maybe it is not broken. 

I would then argue that CC has a look at the layout of the page again, this does not provide a good overview of whats available.

**Comment by mzeinstra** [comment]
Happy to see that the first table of https://creativecommons.org/about/downloads/ is working again. The second table could still use some work.

**Comment by kgodey** [comment]
This was fixed by @little-wow.
