### ISSUE TITLE
Some big icons not appearing at the "Choose a license" page?

### ISSUE THREAD

**Issue by gho87** [creativecommons/creativecommons.org#743]
I went to the ["Choose a license" page](https://creativecommons.org/choose/). I found the icons at the "Selected License" panel invisible (but clickable). I sampled some others, but the icons are also invisible.

![selected license 1](https://user-images.githubusercontent.com/35939662/35539235-9ec65df8-0505-11e8-8a7c-4a4186bf530d.png)
![selected license 2](https://user-images.githubusercontent.com/35939662/35539236-9ee64c6c-0505-11e8-9c41-ba852dce5592.png)
![selected license 3](https://user-images.githubusercontent.com/35939662/35539237-9f061fba-0505-11e8-88df-bd0eb9043555.png)

I tried hitting the reload button, but the problem still persists.

I am using Windows 7. I updated my Google Chrome to the version 64, the latest. I also updated my JavaScript and Adobe Flash Player. I also tried Internet Explorer 11. The problem still persists.

**Comment by robmyers** [comment]
Thank you for catching this!
