### ISSUE TITLE
Deadlink in Japanese page

### ISSUE THREAD

**Issue by foomin10** [creativecommons/creativecommons.org#746]
https://creativecommons.org/licenses/by-sa/3.0/deed.ja

This Japanese page contains deadlink that is in “これは人が読んでわかりやすいようにしたライセンスの要約です。”

**Comment by foomin10** [comment]
Source

```html
<span class="summary">
これは人が読んでわかりやすいようにした<a href="legalcode.ja" class="fulltext">ライセンス</a>の要約です。(ライセンスの代わりになるものではありません。)
</span>
```

Probably ‘href="legalcode"’ is correct.

**Comment by aldenstpage** [comment]
@foomin10 It looks like there is no existing Japanese translation for the 3.0 licenses. I recommend using the 4.0 version located here: https://creativecommons.org/licenses/by-sa/4.0/deed.ja . The link to the license works there.

Can you tell me what led you to the 3.0 deed? How did you find a link to this page?

**Comment by peterspdx** [comment]
The definitive list of ported (we don't say translated for pre-4.0 ported licenses) is here: https://wiki.creativecommons.org/wiki/CC_Ports_by_Jurisdiction

The definitive list of translated legal code for the 4.0 licenses is here: https://wiki.creativecommons.org/wiki/Legal_Tools_Translation#Translation_status_of_the_4.0_licenses_and_of_CC0

Japan doesn't have a ported 3.0 license suite. The deed, however, is a different matter. Even without a port of the 3.0 legal code, there is a Japanese translation of the deed that is the same as the 4.0 deed but is rendered as 3.0 when a work is licensed under a 3.0 license whether generic or if ported to another jurisdiction. The version number is updated, but the text of all deeds for the pre-4.0 ports (1.0, 2.0 and 2.1) is identical to the deed that is rendered relative to the 4.0 legal code in Japanese.

**Comment by foomin10** [comment]
Has been fixed. There is nothing I want to claim.
