### ISSUE TITLE
push maori strings live again

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#75]
They changed the link on the deed so that it goes directly to the Maori translation. I think it has to be manually pushed again. Thanks!

**Comment by mattl** [comment]
Everything pulled, but not seeing anything new for Maori.

**Comment by sarahpearson** [comment]
Hmm, that's odd. I wonder if they didn't update the string correctly.

**Comment by mattl** [comment]
Do you know which string? Let me check Transifex.

**Comment by sarahpearson** [comment]
I'm trying to find it on Transifex but I'm not seeing it. In English it's "This is a human-readable summary of (and not a substitute for) the license." and the link should go to the Maori translation
