### ISSUE TITLE
I am not able to submit my ideas (website error)!

### ISSUE THREAD

**Issue by Raj2032** [creativecommons/creativecommons.org#751]
https://creativecommons.org/use-remix/ideas/

In this link, when I click on the submit button, I am getting an error message that states that cookies are not enabled. I have enabled my cookies and I have used different browsers but the same issue persists.

Please take a look at the image of this error.
https://i.stack.imgur.com/o1b99.png

**Comment by robmyers** [comment]
Confirmed.

@little-wow should we take this form down or talk to our Civi support about it?

**Comment by little-wow** [comment]
Let's just take the form down. If folks want to submit their ideas, they can email us at info@
