### ISSUE TITLE
CC GN vouching request

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#753]
i just received a global network vouching request

when i click on the link to approve the request, i am brought to the typical page asking me to log in with my ccid (attached)
<img width="963" alt="screen shot 2018-02-22 at 9 46 00 am" src="https://user-images.githubusercontent.com/8919762/36554898-60c8c0e6-17b5-11e8-9315-185a012901f1.png">

when i hit "log in," nothing happens. i'm just brought back to this same page.

**Comment by ericsteuer** [comment]
btw i'm using chrome (Google Chrome is up to date // Version 64.0.3282.167)

**Comment by robmyers** [comment]
If you force-reload the page it should work out that you are logged in.

I thought I had fixed this, I will take a look. Thank you for catching this!

**Comment by robmyers** [comment]
Nope, this was the one place this wasn't fixed.

Fixed in 8f0b8ee of commoners.
