### ISSUE TITLE
CC GN vouching request email

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#754]
this language is in the email that comes when you get a vouching request. shouldn't be "her" but "them," no?

"This person believes you can recognize her as an active contributor to the Creative Commons movement. That means you personally know her, you personally know her work and you can say to your peers you support this person be part of the CC Network community."

**Comment by robmyers** [comment]
I agree. We are talking about a specific individual here rather than a generic example, so on balance I believe there is a stronger case for using singular they.

**Comment by little-wow** [comment]
Was this resolved?

**Comment by robmyers** [comment]
I've just done this. Thank you for the reminder!
