### ISSUE TITLE
Migrate Icons For Chooser Out Of Old cc-wp-theme

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#755]
We should be able to remove the old creativecommons.org theme but the chooser relies on assets within it, notably the license icons.

Update the new theme with any missing assets and then change the path in the chooser code.

**Comment by hugosolar** [comment]
[This pull request](https://github.com/creativecommons/creativecommons.org/pull/1013) needs to be deployed before merge [this one](https://github.com/creativecommons/cc.engine/pull/15)
Closing this issue
