### ISSUE TITLE
Link to legalcode of CC BY-SA 3.0 Nederland broken and needs replacement

### ISSUE THREAD

**Issue by gho87** [creativecommons/creativecommons.org#756]
I went to https://creativecommons.org/licenses/by-sa/3.0/nl/, clicked https://creativecommons.org/licenses/by-sa/3.0/nl/legalcode.nl [which is hyperlinked as "licentie" (license)], and was directed to "Not found" page.

I think the link was supposed to go to https://creativecommons.org/licenses/by-sa/3.0/nl/legalcode

the ".nl" should be removed from "legalcode".

**Comment by kentvuong33** [comment]
My want donation but my bank is nothing now
