### ISSUE TITLE
Issues with the Chooser in French

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#758]
1. People reported that sometimes the chooser is 404. I encountered several 503 errors, here is one of them:

Error 503 Service Unavailable
Service Unavailable
Guru Meditation:
XID: 152031785
Varnish cache server

2. Links to licenses from the page https://creativecommons.org/choose/?lang=fr, in the phrase "Ce(tte) œuvre est mise à disposition selon les termes de la Licence Creative Commons ..." and in the HTML code that follows should be changed so that they point to the French versions, not the English ones.

**Comment by robmyers** [comment]
1. I've just updated the monitoring for the chooser server and flushed the cache, that should help with this. The 404 is weird, as you point out we more usually get 503s. Any more information we can get on this would be helpful.

2. The 4.0 licenses are not ported and so the Transifex string we use to link to them links to the canonical URL for the International version, which is in English. For metadata this is correct but for UI it will surprise people. We could usefully change the link *in this one location* (@peterspdx @sarahpearson what do you think?) by altering the Python code - it won't affect the generated metadata and will make more sense to users.

**Comment by robmyers** [comment]
See also #469 .

**Comment by robmyers** [comment]
And #97 .

**Comment by georgehari** [comment]
1. No screenshots, but the page is good now. I will ask for screenshots if the problem persists.
2. I think it's important for the users to have a clear idea of where they go if they click on a link, so I would say go ahead and alter the code for this case and the similar ones.

**Comment by aldenstpage** [comment]
@georgehari, should we close this issue?
