### ISSUE TITLE
Summit WP site needs updating of base WP version + two plugins

### ISSUE THREAD

**Issue by radiofreeterry** [creativecommons/creativecommons.org#765]
There are flags for required updates to the base WP version as well as two other plugins.

And while you're there, could you please have a peek at https://summit.creativecommons.org/sessions2018/ to make sure I updated the Sched Embed plugin coding properly? Seems to be working fine, but no one ever gave me any awards for programming so I want to make sure I haven't broken something else in the process.

Sched's instructions for this are at https://sched.com/support/guide/embed-options/#wordpress

Thanks!

**Comment by robmyers** [comment]
Done, and looks good.

Thank you!
