### ISSUE TITLE
Request for <target="_blank"> attribute in Summit WP site menu item

### ISSUE THREAD

**Issue by radiofreeterry** [creativecommons/creativecommons.org#766]
The item "Travel Wiki" in the secondary menu takes the user away from the Summit WP site. It would be better if this menu item opened in a new tab instead. Is that possible? I don't see it as a setting in the menu editor, and I don't see anywhere I can edit the HTML of the menu to add the <target="_blank"> attribute. Please let me know if it is possible to make this happen with this menu item. Thanks!

**Comment by mmoreshead** [comment]
FYI - I changed the name of this menu to Toronto because I didn't think Travel Wiki did it any justice.

**Comment by robmyers** [comment]
It is possible (which pleasantly surprised me), I have learnt -

https://richwp.com/open-wordpress-menu-links-in-new-window/

I've added the rel tag to the link using this method. :-)
