### ISSUE TITLE
Request for help with Summit WP site page template

### ISSUE THREAD

**Issue by radiofreeterry** [creativecommons/creativecommons.org#769]
I can't figure out how to arrange the sponsor logos on the page https://summit.creativecommons.org/sponsors/ into a grid or pyramid. As far as I know I'm using the same page template from last year, when it was apparently possible (or so reports Development). Any insight, or pointers to instructions, would be welcome. Thanks!

**Comment by robmyers** [comment]
It's not a grid in the archive.org view of the page.

I've created a grid, it won't work in older browsers, they'll see the same as last year.

If adding any new images, carefully wrap them up in a div as you can see in the page source.

**Comment by radiofreeterry** [comment]
Thanks for this change. The lower level only has two logos and appears justified left, rather than centered beneath the rows with 3. Is it possible for a row with 2 to be centered?

**Comment by radiofreeterry** [comment]
OK now I broke it somehow. All I did was change the contact info at the bottome!

**Comment by radiofreeterry** [comment]
I have closed the page so you won't be locked out

**Comment by radiofreeterry** [comment]
And by "broken it" I mean the logos are no longer showing up in the cells you made.

**Comment by robmyers** [comment]
The visual editor inserted <br /> tags into the style block, which broke it.

I've removed them and structured the style block so that shouldn't happen again.

The images are now gridded again.
