### ISSUE TITLE
Payment processing for Cert

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#772]
A few options as I see it:
1. Civi dashboard like for summit (but possibly lots of custom dev work?)
2. Using Eventbrite and connecting Eventbrite to Mailchimp
3. Routing people through the donate page

Any other options that you can think of?

**Comment by robmyers** [comment]
Donate goes to civi so those are related. :-)

We used PayPal invoices for the beta but that won't scale.

**Comment by little-wow** [comment]
I vote for Eventbrite with a Mailchimp integration and bypassing Civi altogether atm.

**Comment by robmyers** [comment]
Oh the other option would be GravityForms. We need various fields of information and Gravity or Civi would be good for that.

But I do agree that Eventbrite looks good. I will double check its capabilities.

**Comment by robmyers** [comment]
Yes Eventbrite has all the functions we need.

@little-wow Do we have a cc Eventbrite account or should we set one up for this and get it into the password manager?

**Comment by robmyers** [comment]
Collecting information from attendees -

https://www.eventbrite.ca/support/articles/en_US/How_To/how-to-collect-information-from-all-event-attendees

Spreadsheet export -

https://ewh.ieee.org/r6/scv/sps/eventbrite2listserver.html

Invitation-only tickets (if needed) -

https://www.eventbrite.com/support/articles/en_US/How_To/how-to-set-up-invitation-only-events

**Comment by mmoreshead** [comment]
We do have an eventbrite account.  it's connected to events@creativecommons.org which I *think* is an alias for development@ -- anyway, I get the emails connnected to it in Freshdesk.

**Comment by robmyers** [comment]
Cool! As soon as @jennryn can see issues we can co-ordinate with them. Thank you!

**Comment by jennryn** [comment]
Using the CC eventbright account sounds good. And the options for info collection work for me!

**Comment by jennryn** [comment]
I posted this in slack, but wanted to share it here:  Cable and I were wondering if there was an ETA on Salesforce?  Currently, we're getting charged an extra $18/ticket via Eventbrite, and don't want to be using that stop-gap measure longer than needed.  Would it be safe to say that we can switch registration/payment systems by or before the beginning of Q4?
