### ISSUE TITLE
Looking for JQuery in all the wrong places

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#773]
Gravity forms on the donate page is broken when typing in a custom amount.

![screen shot 2018-03-19 at 5 43 09 pm](https://user-images.githubusercontent.com/7093838/37624008-0b6f555a-2b9d-11e8-9440-03717c195a76.png)
![Uploading Screen Shot 2018-03-19 at 5.43.20 PM.png…]()

**Comment by robmyers** [comment]
I prefer this title. :-D

**Comment by little-wow** [comment]
haha "hold title" got copied!
