### ISSUE TITLE
Gravity forms breaks on custom amount

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#774]
Gravity forms on the donate page is broken when typing in a custom amount.

![screen shot 2018-03-19 at 5 43 09 pm](https://user-images.githubusercontent.com/7093838/37624008-0b6f555a-2b9d-11e8-9440-03717c195a76.png)
![screen shot 2018-03-19 at 5 43 20 pm](https://user-images.githubusercontent.com/7093838/37624012-0d3cc64c-2b9d-11e8-8d49-f77795b6a8a0.png)

**Comment by robmyers** [comment]
The conditional code module in Gravity Forms is trying to call jQuery as "$". This isn't supported in our WordPress setup.

It's not CloudFlare that's causing this (some people reported similar problems with a CloudFlare feature enabled, but we don't use that).

Investigating further.

**Comment by robmyers** [comment]
It was the same fix as this - https://github.com/creativecommons/new-creativecommons.org/commit/f6aedb696ee1c03069a4e2959f3157b02dfed73d

I've added a patch to the project as a reminder.

**Comment by robmyers** [comment]
Fixed in 31197adba04ed07cd07f304abb230c7d7e6548d9

**Comment by robmyers** [comment]
Fix has been deployed and tested.

You may need to force-refresh the page for it to work.

Thank you for reporting this!
