### ISSUE TITLE
German deeds of v4.0 licenses not linking to German legalcode

### ISSUE THREAD

**Issue by gho87** [creativecommons/creativecommons.org#776]
The German deed of CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/deed.de) does not link "Lizenz" to https://creativecommons.org/licenses/by-sa/4.0/legalcode.de

Instead, the link is https://creativecommons.org/licenses/by-sa/4.0/legalcode

Same for other below licenses:

CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/deed.de).
* Expected: https://creativecommons.org/licenses/by/4.0/legalcode.de
* Actual: https://creativecommons.org/licenses/by/4.0/legalcode

CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/deed.de)
* Expected: https://creativecommons.org/licenses/by-nd/4.0/legalcode.de
* Actual: https://creativecommons.org/licenses/by/4.0/legalcode

CC BY-NC 4.0 (https://creativecommons.org/licenses/by-nc/4.0/deed.de)
* Expected: https://creativecommons.org/licenses/by-nc/4.0/legalcode.de
* Actual: https://creativecommons.org/licenses/by-nc/4.0/legalcode

CC BY-NC-SA 4.0 (https://creativecommons.org/licenses/by-nc-sa/4.0/deed.de)
* Expected: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.de
* Actual: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode

CC BY-NC-ND 4.0 (https://creativecommons.org/licenses/by-nc-nd/4.0/deed.de)
* Expected: https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.de
* Actual: https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode

**Comment by robmyers** [comment]
@georgehari I can never remember which way is correct.

**Comment by georgehari** [comment]
The link should go to **legalcode.de**. I changed that on [Transifex](https://www.transifex.com/nkinkade/CC/translate/#de/deeds-choosers), it should go live Monday if the script works correctly.
