### ISSUE TITLE
mail merge to get names on CC Certificate template

### ISSUE THREAD

**Issue by jennryn** [creativecommons/creativecommons.org#777]
@robmyers Is there a way to get "graduated" Cert Beta group participants' names on the Certificate template we've created and mail merge to email them their certificates? If there's a nifty way to do this, great! If not, I'll manually enter everyone's names on individual Certificate pdf docs and email them their unique copies. We won't have the list of participant names till after the course ends on 4/2, btw. 

I added you to the template in canva. com, but you might be able to access it here too: https://www.canva.com/design/DACypJfweL4/I1qRHQb10VGCvVA3glQnFw/edit

**Comment by little-wow** [comment]
I can chime in here and say this will probably have to be manual.

**Comment by kgodey** [comment]
Closing this issue since there doesn't seem to be anything to do here.
