### ISSUE TITLE
Can we put Wordable on the site to better convert GDocs?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#778]
https://www.wordable.io/
Thanks much!

**Comment by robmyers** [comment]
What are the specific features of GDocs that support collaborative drafting?

I'm not trying to be obtuse - I can guess but I don't want to try to work out how to do the wrong thing based on a well-meaning but incorrect assumption on my part. :-)

**Comment by little-wow** [comment]
When I write a blog post (or anyone writes a blog post for that matter,) they write it in Google Docs rather than emailing text documents back and forth. Problem is Google Docs adds all sorts of weird markup when you copy and paste and also doesn't allow you to just copy images wholesale, so I run it through an html cleaner and then have to either screenshot or make a folder with the downloaded images. Matt T. recommended this plugin to simplify that workflow. Is that clearer?

**Comment by robmyers** [comment]
WordPress supports commenting on drafts. This would support a workflow within our CMS without having to worry about formatting issues or re-importing images -

https://en.support.wordpress.com/writing-helper/request-feedback/

**Comment by little-wow** [comment]
Okay! I'm going to close this ticket but I don't think that anyone is going to start using Wordpress to write blog posts, unfortunately.

**Comment by little-wow** [comment]
Can I reopen this because I just got another GDoc without proper photo attribution in my inbox? Thx

**Comment by robmyers** [comment]
Can you email me a couple of particularly challenging GDoc links so I can evaluate options (on Staging)? As with any proprietary software I'm happy to install it if it's the only way of doing the best thing but a) we need to make sure it works and b) I want to see if there's a better alternative.

**Comment by little-wow** [comment]
sure!

**Comment by kgodey** [comment]
Assigning to @little-wow to get staff consensus and decide how to proceed and moving to "needs more info".

**Comment by kgodey** [comment]
Talked with @little-wow on Slack and this is still a nice to have.

**Comment by kgodey** [comment]
I talked to @ericsteuer about this and he does not plan to use Wordable any time soon. I'm closing the issue and we'll revisit if we want this functionality in the future.
