### ISSUE TITLE
Display of "supporting" and "inkind" sponsors on Summit WP site isn't working

### ISSUE THREAD

**Issue by radiofreeterry** [creativecommons/creativecommons.org#779]
I added a new sponsor logo and URL (Intellus Learning) to the list of supporting sponsors, replicating the coding as exactly as I could, but I seem to have broken the layout: https://summit.creativecommons.org/sponsors

**Comment by robmyers** [comment]
The visual editor had mangled things.

I moved the CSS to the custom CSS field of the style editor so the visual editor doesn't upset that again, and I reworked the HTML on the page to add the correct classes and remove some formatting that was getting in the way.

It is all good now.
