### ISSUE TITLE
Request for link to open in new tab on Summit WP site

### ISSUE THREAD

**Issue by radiofreeterry** [creativecommons/creativecommons.org#780]
I have added a link to the Delta Hotel website in the third paragraph of text on the Summit WP main landing page (https://summit.creativecommons.org/). This was because one user expressed some confusion about which Delta Hotel was hosting Summit. Can this link please be made to open in a new tab? Thank you!

**Comment by robmyers** [comment]
If you add target="_blank" to the <a> tag for the link it will have that
effect.

**Comment by radiofreeterry** [comment]
I wasn't sure if that would work, and was thinking of the other method you discovered for making the menu item do that. But the method you suggest is now working find in this context. Thanks!
