### ISSUE TITLE
Problem with sponsor link on Summit WP page

### ISSUE THREAD

**Issue by radiofreeterry** [creativecommons/creativecommons.org#782]
Each of the logos on the Summit WP sponsors page has a link to that sponsor's website.

The link for Tophat was missing, so I edited into the correct field in the embedded logo file and updated the page.

The link for Tophat should go to "http://www.tophat.com/marketplace". But when you click it, you are instead re-directed to "https://summit.creativecommons.org/sponsors/www.tophat.com/marketplace"

**Comment by robmyers** [comment]
Cannot recreate. Did you fix this?

**Comment by radiofreeterry** [comment]
OK that's downright weird. It's happening in Chrome, where I'm logged in and seeing it in Preview mode. But it isn't happening in Firefox, where I'm not logged in.

**Comment by radiofreeterry** [comment]
OK, now it's not happening in Chrome. Maybe I need to get more sleep. But I swear it was really happening!!

**Comment by robmyers** [comment]
Web browsers can play up when they know we really need them to behave.

Do report if you see this again, it may indicate a problem somewhere further along the pipe.
