### ISSUE TITLE
Pull CCSearch Translations from Transifex

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#789]
It's not currently clear how to do this cleanly.

**Comment by georgehari** [comment]
I thought that the script that pulls-up the new translated strings of the deeds does that for Search too. So I will check my archives for people who asked me about this recently and I will let you know what other Search translations have to be pushed on the website.

**Comment by kgodey** [comment]
I'm closing this because it's not clear what this issue entails. We can create a new issue once there is a need for it.
