### ISSUE TITLE
Create the Basque branches

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#799]
I created the 1st version of 4.0 BY-NC-SA Basque and staged it in the cc4-eu-legalcode branch. Please check if the file at https://cc4-eu-legalcode.legal.creativecommons.org/licenses/by-nc-sa/4.0/legalcode.eu is visible. 

The same goes for the branch cc0-eu-legalcode (no file staged there yet).

**Comment by robmyers** [comment]
This has proven more involved than expected due to a certbot upgrade.

I am working on it...

**Comment by robmyers** [comment]
Certbot is fixed.

**Comment by robmyers** [comment]
Thanks to http://somethingabout.ru/post/certbot-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by robmyers** [comment]
I can't see legalcode.eu . Investigating.

**Comment by robmyers** [comment]
The cc0-eu-legalcode site is good.

**Comment by robmyers** [comment]
Previous versions were _es_eu , they are displaying OK but the _eu one isn't.

**Comment by robmyers** [comment]
OK fixed!

Thank you for your patience.
