### ISSUE TITLE
Add Rebecca's photo and bio to staff page

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#80]
Here's the bio (urls for the links are below) and photo: 

As Director of Development for Creative Commons, Rebecca leads the organization's fundraising and advancement efforts. With 15 years experience in nonprofit management, Rebecca has dedicated her career to supporting creativity and innovation. Before joining Creative Commons, Rebecca worked with leading cultural institutions in San Francisco and New York, including [Headlands Center for the Arts](http://www.headlands.org/), [Creative Time](http://creativetime.org/), the [New School's Vera List Center for Art and Politics](http://www.newschool.edu/vlc/), and [MoMA PS1](http://momaps1.org/), as well as the open source hardware company [Bug Labs](http://buglabs.net/). Rebecca has an undergraduate degree in visual studies from the New School, a graduate degree from Hunter College, and was a fellow at New York University. She lives with her husband and their two young children in the San Francisco Bay Area where they can be found gardening, building things, listening to music, making waffles, and adventuring around local beaches and trails.

![r_lendl](https://cloud.githubusercontent.com/assets/11162279/8660723/a64cd88a-2980-11e5-8d70-151a1e889b81.jpg)

**Comment by mattl** [comment]
All set :)

**Comment by rebeccalendl** [comment]
Sorry Matt, I made one small edit. Will you update? Thank you!: "With 15 years experience in nonprofit management, Rebecca has dedicated her career to supporting artists, creativity, and innovation through administration, finance, fundraising, and strategic planning in the cultural sector."
