### ISSUE TITLE
Is it intended that Malay translations on the website be declared as "Malaysian language"?

### ISSUE THREAD

**Issue by MuhdNurHidayat** [creativecommons/creativecommons.org#803]
The link to every Malay translations are written as "Bahasa Malaysia" ([Malaysian Language](https://en.wikipedia.org/wiki/Malaysian_language)) instead of the usual "Bahasa Melayu" ([Malay Language](https://en.wikipedia.org/wiki/Malay_language)). Is this really the intended behaviour, especially when the language code seemed to be <code>ms</code> (Malay) and not <code>ms_MY</code> (Malaysian)?

![image](https://user-images.githubusercontent.com/12217018/39971923-5ea0abf0-5737-11e8-9c08-b07bbb75d908.png)
The URL obviously wrote <code>https://creativecommons.org/licenses/by/4.0/deed.ms</code> there which ends with **ms** but the link wrote "Malaysian" instead of "Malay" language.

Just in case the devs doesn't know this fact, Malay is not only used in Malaysia, it's also used in Brunei, southernmost Thailand and Singapore among others. Also, Malay is not only written in Latin script called [Rumi](https://en.wikipedia.org/wiki/Malay_alphabet), but also written in Arabic script called [Jawi](https://en.wikipedia.org/wiki/Jawi_alphabet). Jawi is still in use to write Malay and not going to die anytime soon, and online materials usually tag them as <code>ms-Arab</code>.

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here: (It's on all license pages, eg. https://creativecommons.org/licenses/by/4.0/)

1. Go to any license pages.
2. Scroll down to the language selection area.
3. See the "Bahasa Malaysia" link.

Web browser: https://aboutmybrowser.com/Eoc8HgnL

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow

**Comment by georgehari** [comment]
So, your proposal is to change the name of the language in the footer to Bahasa Melayu?

**Comment by MuhdNurHidayat** [comment]
Depends on the original translators, like which translation are they actually been working on?

IMO, if it's really Malay (Malaysia) then "Bahasa Malaysia" should be keep but language code need to change to `ms_MY`.

Instead, if it's really a general Malay language which could be understood easily by Malay speakers without problems not only in Malaysia but also in other countries (mainly Brunei and Singapore) then the name should be changed to "Bahasa Melayu" with current language code `ms` kept as is.

I can't check all translations being use to decide which kind of translation is being used on the website, but a good indicator to differentiate is the use of loanwords. Malay (Malaysia) tends to use English loanwords as much as possible, as opposed to general Malay language which uses native words whenever possible. For example, using the loanwords "apresiasi", "edit", "editor", "program", "informasi" instead of native words "penghargaan", "sunting", "penyunting", "atur cara", "maklumat" as the translations for English words "appreciation", "edit", "editor", "program", "information".

**Comment by muidlatif** [comment]
Hi George @georgehari 
Referring to our email conversation, thank you for sharing the issue.

Hi Hidayat @MuhdNurHidayat 
Thanks for pointing out of the current naming convention for supposedly 'Malay Language' or 'Bahasa Malaysia' instead of 'Malaysian Language'.

We hope in future you could be one of the volunteer translators for Creative Commons projects, especially in translation of English to Bahasa Malaysia. In the past, we have few contributors to work on our translation on CC4/CC0 licenses, however for SotC, I have to translate all, and it will be a great help for our next version of SotC release. 

Again, thanks
