### ISSUE TITLE
CC Certificate: Canvas not emailing

### ISSUE THREAD

**Issue by jennryn** [creativecommons/creativecommons.org#809]
@robmyers 

It looks like the Canvas instance you created is still not letting us send out emails/invitations to people. Everyone I tried to invite yesterday has a "pending" next to their username, including my email to my personal address (adding myself as a student to test functionality). I never received the email in my personal email inbox or junk mail, and it's been about 24 hours. 

Here's where I am looking: https://lms.certificates.creativecommons.org/courses/1/users#.

The extra confusing thing is: it sounds like Cable and Tim received invites from last week, when you tried inviting them. Can you look into why I cannot add students?

**Comment by robmyers** [comment]
This may in part be due to this:

![image](https://user-images.githubusercontent.com/21746/41129260-1c280b3c-6a66-11e8-95ac-64d8efe55567.png)

**Comment by robmyers** [comment]
@jennryn Publishing then re-sending seems to be working. Let me know if you've received an email?

**Comment by robmyers** [comment]
Done. We had to publish the course. I Have Learned.
