### ISSUE TITLE
Add USB Memory Direct to In-Kind Supporters

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#81]
They were nice enough to send us 300 CC branded usb drives.  Can we add them to: http://creativecommons.org/supporters#in-kind

Anchor text: USB Memory Direct
Link: https://www.usbmemorydirect.com/

Thank you!
Mari

**Comment by mmoreshead** [comment]
Gentle nudge.

**Comment by robmyers** [comment]
Thank you for the reminder.

I have added this.
