### ISSUE TITLE
ABUSIVE CONTENT

### ISSUE THREAD

**Issue by anyotherway** [creativecommons/creativecommons.org#811]
https://search.creativecommons.org site is a page full of scams with all IMAGE searches leading to SIGN IN ACCESS to download image content or lacking image access. This is exactly as spastic as the unnecessary new Google 'image search' so-called 'copyright protection' that turns Image search into Web search. If not Google hiding images, all other image searches on search.creativecommons.org are SIGN IN ACCESS ONLY that is not just identical to but factually exactly how access works voting for a dictator with flack suit military leering at your voting ballot. GET RID OF LINKS TO SIGN IN ACCESS SITES or shove that sign in access detritus into page bottom box clearly marked CAUTION: SIGN IN ACCESS with image of garbage can in bottom right corner of those scam sites' garbage box.

Get serious Creative Commons, you are a joke, not just turning into a joke, a factual trash can joke. LOSE THE ABUSIVE INVASION YOU ARE FLAGRANTLY SUPPORTING AT THE EXPENSE OF FREE UNHINDERED ACCESS.

STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE! STOP SUPPORTING ABUSE!

**Comment by robmyers** [comment]
Heya @anotherway .

search.creativecommons.org is being replaced by our new search system, you can see a preview of the kind of thing we are working on at https://ccsearch.creativecommons.org/

In the meantime, which sites linked to via the options in search.creativecommons.org require a sign-in to access? I've just checked and I can't find any.

Thank you for your help in this matter.

**Comment by robmyers** [comment]
Closing due to lack of response
