### ISSUE TITLE
favicon on deed and license pages looks pixelated 

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#819]
compared to other pages across cc.org, the favicon on deed and license pages looks pretty pixelated / blurry

i.e. https://creativecommons.org/licenses/by/4.0/

here is a screen grab of two tabs open in my browser. one is cc by 4.0 deed page and the other is the cc homepage:
<img width="184" alt="screen shot 2018-06-19 at 8 59 25 am" src="https://user-images.githubusercontent.com/8919762/41609527-ce157054-739f-11e8-9c2b-a8b5c13edcec.png">

would be nice to update these soon, since we're pushing new deed and license pages out soon. adding @robinpuga to this in case it's something that can more easily be done by the AB team in tandem with the new design push?

**Comment by little-wow** [comment]
changed the dimensions to 512x512, should be fixed?

**Comment by robmyers** [comment]
We don't specify the Apple (etc.) icon in the Python templates.

Doing so won't alter the meaning of the pages, so we can copy the relevant code from the WordPress theme to the Python templates.

**Comment by little-wow** [comment]
Rob, the WP one was fixed

**Comment by robmyers** [comment]
It should have been OK since the New Site deployment? The Python site gets its image and style assets from the WordPress site but we have to tell browsers where to look, and I don't think the Python site does atm. I could be wrong (or people's browsers could be being smarter than me...) :-) .

**Comment by kgodey** [comment]
I'm closing this because it's unclear what work is remaining. Please reopen or create a new ticket if there's any further work.
