### ISSUE TITLE
Create three new pages off https://creativecommons.org/about/program-areas/legal-tools-licenses/

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#820]
https://creativecommons.org/about/program-areas/legal-tools-licenses/reversionary-rights

https://creativecommons.org/about/program-areas/legal-tools-licenses/author-addenda

https://creativecommons.org/about/program-areas/legal-tools-licenses/springing-licenses

@sarahpearson @robmyers 

Text will be forthcoming for the pages.

**Comment by peterspdx** [comment]
Thanks @robmyers!  Please leave open. @sarahpearson and I will close as we initially populate each page. Appreciated.

**Comment by sarahpearson** [comment]
The springing licenses page is now populated. I'll add links to the final report and Berkman memo once completed.

**Comment by kgodey** [comment]
This is done per @peterspdx and @sarahpearson on Slack, closing.
