### ISSUE TITLE
Gmail Offline Mail Security Setting

### ISSUE THREAD

**Issue by cablegreen** [creativecommons/creativecommons.org#823]
Hi Rob:

It looks like we need one more admin change on the security settings for offline CC Gmail.

On my personal Gmail account - I can download and view attachments offline. I cannot do so on my CC Mail account. Having access to my mail attachments offline is really helpful.

**Settings for CC Account say:**

Security: | Logging out of my Google account will remove locally stored dataFiles will not be stored on your computer after logging out. Data will need to be resynced when logging back into Creative Commons Mail, which may take a few hours.

=====================

**Settings for Personal Gmail Account say:**

  | Keep offline data on my computerData stored on your device will not be deleted when signing out of your Google account or when changing your password. To delete account data from your device disable offline mail and save changes. - **I check this one so I can keep my attachments offline.**

  | Remove offline data from my computerData will need to be resynced to your computer when logging back into Gmail. It may take a few hours to resync the mailbox.

**Comment by robmyers** [comment]
Heya Cable.

I've disabled "Force deletion of offline data on log out of Google account", which should have the desired effect.

I reserve the right to re-enable it should our revised document retention or other policies require it. :-)
