### ISSUE TITLE
SSL credentials for donate.creativecommons.org in Egnyte

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#826]
I think we'll need a new SSL cert to assist with Engaging Networks Setup, see: https://basecamp.com/2604761/projects/15544382/todos/356443179
http://support.engagingnetworks.net/ssl-certificates

**Comment by robmyers** [comment]
We use CloudFlare for our ssl frontend. I'll see if I can get a secondary certificate to send to EN, or if not I'll send them our main one but if there's a data breach at EN we'll have to make sure to update the certificate on all our servers that use it.

**Comment by robmyers** [comment]
I can create a CloudFlare Origin Certificate, will that do?

We're already using one on the current donate server.

**Comment by little-wow** [comment]
Sorry, should have closed this ticket – can you get our SSL credentials and put them in Egnyte? That's all we need :) Thanks!
