### ISSUE TITLE
move this wiki page to the main site

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#829]
Diane would like this page from the wiki (https://wiki.creativecommons.org/wiki/Legal_code) moved to the main CC site. It is a canonical explanation of what constitutes unchangeable legal code. 

Thanks!

**Comment by robmyers** [comment]
Do we have a url on the main site in mind for this?

**Comment by peterspdx** [comment]
Up to @sarahpearson , we may need to create a sentence or phrase on the main license explanation pages where a link could then be inserted.

**Comment by sarahpearson** [comment]
How about we add the following on the About Licenses page: "CC has committed to maintaining the legal code of its licenses completely unchanged after publication. See here [LINK to new page] for an explanation of what is considered legal code and what is not."

I don't really have any strong opinions about the URL for the new page. Maybe something like https://creativecommons.org/licenses/whatislegalcode ?

**Comment by peterspdx** [comment]
A small tweak to the sentences Sarah provided:

"CC maintains the legal code of each license version, port (pre 4.0), and official translation unchanged after publication. See here [LINK to new page] for an explanation of what is and is not considered legal code."

I feel slightly strongly that the URL not be a question. How about:

https://creativecommons.org/licenses/defininglegalcode
or
https://creativecommons.org/licenses/legalcodedefined

@sarahpearson @robmyers

**Comment by sarahpearson** [comment]
Sounds good.

**Comment by kgodey** [comment]
Per @peterspdx on Slack, @sarahpearson will find the place on the website to move this to and create the text. Assigning to her and moving this to "more info needed" since tech is waiting on that.

@sarahpearson please assign back to me when you're ready.

**Comment by sarahpearson** [comment]
Moved: https://creativecommons.org/legal-code-defined/

**Comment by robmyers** [comment]
:tada:
