### ISSUE TITLE
Chooser information boxes do not work in 'wordy' languages

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#833]
The Creative Commons License Chooser's information pop-ups do not work properly in other languages like Basque or Dutch (https://creativecommons.org/choose/?lang=nl). This happens on my 1440 x 900 screen.

The Dutch translation is longer than the English version essentially pushing the text below the fold, but no scrolling is possible. See screenshot

![image](https://user-images.githubusercontent.com/5627431/42561204-e0a5939c-84f8-11e8-8b4d-3176367b6799.png)

**Comment by robmyers** [comment]
Heya Maarten.

I'm sorry about this. Thank you for reporting it. It looks like it's been like this since the redesign.

@robinpuga is this something you can look at?

**Comment by robinpuga** [comment]
Wow, that is big and breaking the layout.  Our team can take a look on Monday.

**Comment by altrugon** [comment]
We just need to add a maximum height and control the overflow, you can see a working fix on the attached screen-shot below:

![choose_a_license](https://user-images.githubusercontent.com/398069/43131593-4fefda0e-8f31-11e8-840d-c16b79bc97e0.png)

I was going to do it myself, but it seems this page is somehow "special" and couldn't find it as a regular WP page, also all the code for this page is inline. Does anybody knows where this is coming from?

**Comment by mzeinstra** [comment]
I believe it is part of this: https://github.com/creativecommons/cc.engine/tree/master/cc/engine/templates/chooser_pages

That refers to two css files you could adopt, those are hosted by the Wordpress install as I understand the code.

**Comment by altrugon** [comment]
Yes @mzeinstra you are right, and here is where the code needs to be inserted:

https://github.com/creativecommons/cc.engine/blob/master/cc/engine/templates/chooser_pages/interactive_chooser.html#L671

I haven't been around this area of the code and when I inserted those 2 lines nothing happened at all. I'm not sure if extra steps are needed but just in case I left the solution on branch `feature/dialog-max-height`.

**Comment by robmyers** [comment]
I have merged the fix into cc.engine and deployed. We now get a scrollbar on the popover if the text would overflow.
