### ISSUE TITLE
Share your CC Work Plugin

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#840]
We want to run a campaign in the fall to better gather CC resources that Cert participants and communities have made. This is a placeholder ticket to explore gallery plugins and widgets.

**Comment by jennryn** [comment]
Sounds good. Adding @cablegreen for awareness too, since he is also instructing with Tim and me.

**Comment by little-wow** [comment]
Closing for now due to lack of staff interest in project

**Comment by jennryn** [comment]
@little-wow I could be confused, but I thought we were waiting for you to reschedule a call you canceled (to explain what you were looking for on this). Happy to learn more and help how I can.

**Comment by little-wow** [comment]
I discussed with a few people and there wasn't a lot of momentum, and then the departure of Rob made it difficult to set up, so I'm tabling until we have someone to do the tech work on it.
