### ISSUE TITLE
State of the Commons 2016 isn't working

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#843]
https://stateof.creativecommons.org/2016/

Console isn't helpful for me – all special characters

**Comment by robmyers** [comment]
When I got there some images were missing, I restored them.

How is it now?

**Comment by little-wow** [comment]
<img width="1231" alt="screen shot 2018-07-23 at 1 17 13 pm" src="https://user-images.githubusercontent.com/7093838/43092369-01b43dbe-8e7b-11e8-87d5-2a185866dc6f.png">

**Comment by little-wow** [comment]
I disabled all external plugins

**Comment by robmyers** [comment]
My logged-in-for work browser session loads it perfectly. My phone and a session on a server don't.

This is interesting in a bad way.

**Comment by little-wow** [comment]
Works for me logged in as well

**Comment by robmyers** [comment]
Try now? I think the object cache in w3-total-cache was corrupted.

**Comment by little-wow** [comment]
Works!

**Comment by robmyers** [comment]
Yay! Thank you for catching this!
