### ISSUE TITLE
Platform no longer an open platform displayed on page

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#849]
Someone sent a note to info@:

I just wanted to point out that on your "Share Your Work" page you have a link to what used to be Boundless. However, since Boundless has ceased operations it appears that their site name was purchased, and the link now goes to a 'marriage-based greencard application' service - which is definitely not an open platform :) 

----------

 @robmyers @little-wow

**Comment by little-wow** [comment]
fixed. Bummer about Boundless.
