### ISSUE TITLE
Alignment for /chooser boxes is off

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#85]
https://creativecommons.org/choose/

See screenshot (Chrome Version 43.0.2357.134 (64-bit)
<img width="642" alt="chooser box alignment" src="https://cloud.githubusercontent.com/assets/6394777/8711914/293649a8-2b0b-11e5-922d-01a6350d7b2b.png">

**Comment by robmyers** [comment]
We changed the chooser layout so this was no longer an issue.
