### ISSUE TITLE
Incorrect guidance on CC-BY-NC-ND 3.0 NZ Version

### ISSUE THREAD

**Issue by Aaron-M** [creativecommons/creativecommons.org#850]
Thanks for reporting an issue, to help us file this efficiently we made this template. Feel free to ignore the template if you wish :) 

If this is a bug or a problem with one of our websites or page on one of our sites, please put the URL or page address here:

On these pages https://creativecommons.org/licenses/by-nc-nd/3.0/nz/ and https://creativecommons.org/licenses/by-nd/3.0/nz/
I believe there is some misleading information.  It indicates that you can remix/transform as one of the terms (just not distribute): 

![image](https://user-images.githubusercontent.com/4842751/43620003-a31a7572-9724-11e8-8b5b-ec42c04d2e03.png)

Our advice is this is wrong for the 3.0 NZ version (correct for 4.0) - it is at odds with legal advice we have received (below), and the legal code behind CC-BY-NC-ND 3.0 NZ says “You must not…   make any Adaptations”

**Legal advice noted a significant difference between CC-BY-ND 3.0 New Zealand licence and CC-BY-ND 4.0 International licence**
_It may be important to note that the CC-BY-ND 3.0 New Zealand licence and the CC-BY-ND 4.0 International licence take different approaches to what is permitted in relation to adaptations. **Under the CC-BY-ND 3.0 New Zealand licence, the making of adaptations is prohibited**. The only exception is making “such modifications as are technically necessary to exercise the [licensed] rights in other media and formats”. By contrast, in the CC-BY-ND 4.0 International licence, Creative Commons deliberately took a different stance, allowing the production and reproduction, but not the sharing, of adapted material. This means that, under the 4.0 International licence, a business (for example) could adapt licensed copyright material for its internal business purposes but could not distribute it publicly or to other third parties._

Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow

**Comment by sarahpearson** [comment]
Thank you for reporting this. You are right that it is slightly confusing in light of that nuanced difference between versions 3.0 and 4.0. CC's historical policy has been to have a single deed that works for all versions of the particular license. In some cases, like this one, it made drafting a bit difficult. Here, we felt that the language chosen is technically true for all versions of the ND licenses, even if 3.0 prohibits more than what it is stated. If you think there are FAQs or other notices you can make more prominent on the CC NZ site about this point, we encourage you to work with others in the New Zealand CC Chapter to do so. We will also record this point for consideration in connection with future iterations of the deed in the next update. 

Thanks again!
