### ISSUE TITLE
Mask the CRM URL with our Donate Page

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#856]
When our CRM goes up, we'll need to mask the URL for the EN. To do September 5

**Comment by robmyers** [comment]
Mask the crm with https://creativecommons.org/donate/ ?

Do EN have any documentation for this so I can make sure I'm doing what is expected? I searched but couldn't find any.

**Comment by Vipadasangkaew** [comment]
WASHINGTON—U.S. Citizenship and Immigration Services (USCIS) announced today that current beneficiaries of Temporary Protected Status (TPS) under Somalia’s designation who want to maintain their status through the 18-month extension period ending on March 17, 2020, must re-register between August 27, 2018 - October 26, 2018.

Re-registration procedures, including how to renew employment authorization documents (EADs), have been published in the Federal Register and on uscis.gov/tps.

All applicants must submit Form I-821, Application for Temporary Protected Status. Applicants may also request an EAD by submitting, at the time they file Form I-821, Form I-765, Application for Employment Authorization, or separately at a later date. Like all USCIS forms, both forms are free for download from the USCIS website at uscis.gov/tps.

USCIS will issue new EADs with a March 17, 2020 expiration date to eligible Somalia TPS beneficiaries who timely re-register and apply for EADs. Given the timeframe involved with processing TPS re-registration applications, however, we recognize that not all re-registrants will receive new EADs before their current EADs expire on Sept. 17, 2018. Accordingly, we have automatically extended the validity of those EADs for 180 days, through March 16, 2019.

On July 19, 2018, Secretary of Homeland Security Kirstjen M. Nielsen announced that the statutory conditions supporting Somalia’s TPS designation on the basis of ongoing armed conflict and extraordinary conditions continue to exist and that the designation should be extended by 18 months.  Secretary Nielsen made her decision after reviewing country conditions and consulting with appropriate U.S. government agencies. As a result, Somalia’s TPS designation has been extended through March 17, 2020.

For more information on USCIS and its programs, please visit uscis.gov or follow us on Twitter (@uscis), Instagram (/uscis), YouTube (/uscis), and Facebook (/uscis).  

Please do not reply to this message.  See our Contact Us page for phone numbers and e-mail addresses.

USCIS signature
Emma

STAY CONNECTED:
Visit Us on Twitter	Visit us on Facebook	Visit us on YouTube	
Bookmark and Share

SUBSCRIBER SERVICES:
Manage Preferences  |   Unsubscribe   |  Help
Update your subscriptions, modify your password or email address, or stop subscriptions at any time on your Subscriber Preferences Page. You will need to use your email address to log in. If you have questions or problems with the subscription service, please contact Subscriber Help.
U.S. Citizenship and Immigration Services sending to Vipadasangkaew@gmail.com  20 Massachusetts Ave NW, Washington DC 20529  1-800-375-5283


"VIPADA SANGKAEW"
