### ISSUE TITLE
who uses cc, culture, related pages - misaligned images

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#86]
https://creativecommons.org/who-uses-cc
https://creativecommons.org/science
https://creativecommons.org/culture

eg., see attached
<img width="790" alt="who uses cc alignment" src="https://cloud.githubusercontent.com/assets/6394777/8711967/971a7516-2b0b-11e5-917b-2d09e459362b.png">

**Comment by janeatcc** [comment]
Also: 
https://creativecommons.org/music-communities
https://creativecommons.org/record-labels

**Comment by mattl** [comment]
Made things a bit better. All of these pages are misusing HTML tables in a drastic way, I'd like to get them updated properly.

**Comment by robmyers** [comment]
These were fixed or redirected.
