### ISSUE TITLE
Broken link on the policies page

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#861]
On: https://creativecommons.org/policies

There is a section called 'Chapter Social Media Accounts' which has a broken link to github: https://github.com/creativecommons/global-network-strategy/blob/master/docs/chapters-guidelines.md.

**Comment by claudioruiz** [comment]
fixed. thanks for that!

**Comment by mzeinstra** [comment]
Missed one, under 'Chapter Website Content' ;)
