### ISSUE TITLE
Subscription to newsletter form might be broken

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#867]
I filled in my companies mail address in the newsletter form here: https://creativecommons.org/about/contact/newsletter/

I got the following error message:
![image](https://user-images.githubusercontent.com/5627431/45414443-adeca580-b67b-11e8-89b8-93c84638391b.png)

Might be that the newsletter subscription is broken.

**Comment by little-wow** [comment]
Hi Maarten, the link on that page is fixed and was shortly after you submitted this comment :)
