### ISSUE TITLE
broken link in license (Dutch)

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#878]
From info@ 

  | Legal code missing.  At https://creativecommons.org/licenses/by/3.0/nl/, the link to the legal code from the word "licentie" points to https://creativecommons.org/licenses/by/3.0/nl/legalcode.nl - which responds with 404 Not Found error.
-- | --

**Comment by mzeinstra** [comment]
duplicate of #54

**Comment by kgodey** [comment]
Closing this, updates will be posted in #54. Thanks @mzeinstra.
