### ISSUE TITLE
Main CC web page pointing to search.cc.org

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons.org#890]
@little-wow alerted me to the fact that the main page on cc.org that points to CC search still is connected to search.cc.org (and not beta ccsearch.org): https://creativecommons.org/use-remix/

Thoughts on whether this should remain this way for now, and we review again in 2019, given that the beta only searches images? 

cc: @aldenstpage @pa-w @sebworks @sclachar @sarahpearson

**Comment by aldenstpage** [comment]
We should certainly link to CC image search somewhere on the front page, but people still need to find search.cc.org until we can fully replace it. I can't see us doing that until we have indexed a more complete catalog, including other content types besides images.

**Comment by janeatcc** [comment]
Yeah, I think I agree. 

Beta ccsearch is linked from search.cc.org. Not sure if there's a place to link to it on the main site. Maybe just on that same page say we have a beta CC search and link to it underneath the main one? thoughts @little-wow ?

**Comment by little-wow** [comment]
I think that's too much. I'm not sure what benefit search.cc.org has over ccsearch.creativecommons.org, but I don't feel like anyone is going to complain about that link going away and it could be a way to drive users to the new search and also improve SEO

**Comment by janeatcc** [comment]
Then I think we should keep status quo for now until search team is comfortable with replacing search.cc.org with the beta.

**Comment by kgodey** [comment]
Closing this since we're not ready to make the switch.
