### ISSUE TITLE
Issue Template Needs Updating :-)

### ISSUE THREAD

**Issue by robmyers** [creativecommons/creativecommons.org#907]
Heya!

The issue template currently ends with this text:

```Finally, we're going to put someone's name here, so they get alerted to the new issue and can assign it to the right person. @robmyers @little-wow```

It should be updated to remove me and add a more up-to-date contact. :-)

**Comment by kgodey** [comment]
@robmyers thanks for reporting! We've updated the template to remove you. I'm watching the repo and I get emails about any new issues that are created so I did not explicitly add myself.
