### ISSUE TITLE
Rest API certificate expired

### ISSUE THREAD

**Issue by philip-muench** [creativecommons/creativecommons.org#909]
The certificate of the REST API has expired on Jan. 1st 2019. Right now, this service is unusable. Try https://api.creativecommons.org/rest/1.5/details?license-uri=http://creativecommons.org/licenses/by/4.0

**Comment by aldenstpage** [comment]
Thanks for bringing this to our attention, I've fixed the issue. There was a problem with the cronjob set up to take care of renewal; we are taking steps to ensure this is the last time this happens.
