### ISSUE TITLE
Heart logo on Downloads page

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#916]
i'd like to offer the cc heart logo as a png, svg, and eps in both black and red on https://creativecommons.org/about/downloads

will work on this soon

**Comment by ericsteuer** [comment]
[cc_heart.zip](https://github.com/creativecommons/creativecommons.org/files/2841980/cc_heart.zip)

@little-wow would you get these on the /about/downloads page of the site sometime soon? i had the heart logo re-drawn so that it's available in black and red as high res (png, svg, eps files for each)

copying @ryanmerkley and @mmoreshead so they know we're adding these

**Comment by little-wow** [comment]
Noting that I will do this 2/12/2019

**Comment by little-wow** [comment]
done. I also finished the tables on the downloads page.
