### ISSUE TITLE
Button on downloads page shows dollars then downloads EU

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#922]
From the CC Certificate Slack channel:  "I am trying to find By-NC and BY-NC-SA svg  with US dollars not EU symbol. When I went to downloads page-https://creativecommons.org/about/downloads the image shows dollars then downloads EU. "

===================

Finally, we're going to put someone's name here, so they get alerted to the new
issue and can assign it to the right person. @little-wow

**Comment by little-wow** [comment]
This should be fixed!
