### ISSUE TITLE
where are the source code & assets for this animation?

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#923]
From the CC Certificate channel: 

"Does anyone know where to get the code for this animation? https://labs.creativecommons.org/2011/demos/license-layers/ I would like to use it in our libguide. The links in the attribution indicating where to get the code are dead. © 2011, Creative Commons, Nathan Yergler, Alex Roberts. Licensed to the public under CC BY 3.0 Unported. Creative Commons logo used under CC Trademark Policy.
Source code and assets available in the labs/license-layers git repository on code.creativecommons.org."

code.creativecommons.org never loads so not sure if it's there but can't get to it or not.

=====================

Finally, we're going to put someone's name here, so they get alerted to the new
issue and can assign it to the right person. @little-wow

**Comment by little-wow** [comment]
Tag @peterspdx @ericsteuer

**Comment by ericsteuer** [comment]
I don't know the origin of this animation nor have I ever seen source files. But coincidentally, I recently had a static version of it re-drawn by an illustrator so it would be high res enough to be used in the CC Cert book that the ALA and CC are working on. Hopefully it can be of some use here:

https://drive.google.com/open?id=1ZXA40a6nxE-kz8-CQL41UqtZIxdsxJZC

and in grey:
https://drive.google.com/open?id=1JpWJHGhfo5vRd5VL6b5AcUaHHs38e8sj

**Comment by ericsteuer** [comment]
Also, @little-wow, at one point, Cable had asked for this graphic to go on the /downloads page of cc.org. If you think there's an elegant way to make it available there for people, will you please add it?

**Comment by little-wow** [comment]
It's on the downloads page. I also added the attribution.
