### ISSUE TITLE
add CC license/PD tool video bumpers to cc/about/downloads

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/creativecommons.org#925]
@little-wow will you please add a link to [this](https://vimeo.com/album/5791214) on the [downloads page](https://creativecommons.org/about/downloads) somewhere that makes sense, and add a little description at the top to indicate what they are. Something like: "Feel free to use these animated video bumpers to mark your videos with the CC license or public domain tool of your choice."

**Comment by little-wow** [comment]
Done
