### ISSUE TITLE
Typo on "What we do" page

### ISSUE THREAD

**Issue by Hypolymer** [creativecommons/creativecommons.org#928]
Thanks for reporting an issue, to help us file this efficiently we made this
template. Feel free to ignore the template if you wish :)

If this is a bug or a problem with one of our websites or page on one of our
sites, please put the URL or page address here:

https://creativecommons.org/about/

Please tell us the steps to reproduce the problem, if needed:

I think that there's a typo under the heading "Creative Commons Platforms" where it has:

We work with the following organizations that are leaders in the content and knowledge sharing movement. Through these platforms, over 1.1 billions works have been shared and counting!

I think in that "1.1 billions works" needs to read "1.1 billion works".

Thanks!

**Comment by kgodey** [comment]
@little-wow I believe this is a WordPress content issue, let us know if you need tech to do anything about this.

**Comment by little-wow** [comment]
fixed. Also corrected number of CC licensed works on the web
