### ISSUE TITLE
Make repository contribution friendly.

### ISSUE THREAD

**Issue by kgodey** [creativecommons/creativecommons.org#936]
See: https://wikijs.creativecommons.org/tech/github-repo-guidelines

- [x] A `LICENSE` file.
- [x] Code owners should be defined in the [`CODEOWNERS` file](https://help.github.com/en/articles/about-code-owners) in the `.github` directory in the project root.
- [x] Add Code of Conduct in a [`CODE_OF_CONDUCT.md` file](https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project) in the root directory. We can use the standard file from our [`.github` repository](https://github.com/creativecommons/.github).
- [x] Add project-specific contributor guidelines in a [`CONTRIBUTORS.md` file](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) in the root directory. The standard file from our [`.github` repository](https://github.com/creativecommons/.github) can be used as-is or as a starting point.
- [x] Add the standard [CC metadata YAML file](/tech/open-source/cc-open-source-website#cc-metadata-file).
- [ ] Update `README.md` file in the root directory of the repository to document how to install and build the project locally and document a high level overview of the project and code structure. It should also link to any other available documentation.

**Comment by hugosolar** [comment]
We don't know yet how to build this project locally so I leave the README.md intact

**Comment by yrrahsilieb** [comment]
I'm sorry I Don't know how
