### ISSUE TITLE
Estonian translation not included in language list

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/creativecommons.org#939]
The 4.0 license deed is available in Estonian, but the language does not appear in the language list in the dropdown or at the bottom of the page. 

The translation is here: https://creativecommons.org/licenses/by/4.0/deed.et

@georgehari are you able to tell from Transifex how the language should be listed? (capitalized or not, etc) If not, could you please follow up with the translators to ask, and then reply on this ticket? Thanks!

**Comment by georgehari** [comment]
It should be listed as: 
eesti keel

**Comment by sarahpearson** [comment]
Thanks, @georgehari! 

@kgodey I'm not sure who to assign this to on your team, but we will need eesti keel added to the language dropdown and list at the footer of the license deeds. Let me know if you need any further information. Thanks!

**Comment by kgodey** [comment]
@sarahpearson we will assign it during our next sprint meeting on Tuesday.

**Comment by aldenstpage** [comment]
@sarahpearson or @georgehari, we need to make a small change in the scripts to fix this. We need the `et` translation of "This page is available in the following languages" for the language selector. I will also update the scripts to include `eesti keel` as an additional language. We'll need to have this information on hand for every new translation going forward.

**Comment by georgehari** [comment]
The translation is:

See lehekülg on kättesaadav järgmistes keeltes

I took it from here: https://creativecommons.org/licenses/sa/1.0/deed.et.

George.

**Comment by aldenstpage** [comment]
It's in the footer now. I believe that the reason that it's not showing up in the dropdown menu is because the deed has only been partially translated. It seems like the site has been set up not to show it until a certain threshold has been crossed.

![Estonian translation status in Transifex](https://i.imgur.com/80Js2r8.png)

**Comment by sarahpearson** [comment]
It appears that Estonian is now appearing in the legal code language list (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode) where it should not be because we don't yet have a legal code translation. But it doesn't appear in the deed language list (https://creativecommons.org/licenses/by-nc-sa/4.0), where we **do** have a translation (https://creativecommons.org/licenses/by/4.0/deed.et).  Is it possible the script accidentally updated the wrong files?

**Comment by aldenstpage** [comment]
Even though the deed page exists, it's only 60% translated on Transifex, meaning that our website thinks that it's not ready to be shown to users yet. The deed will not appear under the dropdown menu until 80% of the document has been translated. After that threshold is crossed, the deed dropdown menu will be automatically updated. You can access the deed by changing the URLs, but the same would be true for any language code that is only 1% translated; it has to cross the threshold before it's added to the dropdown.

I was under the mistaken impression that the full text of the license had been translated and was missing from the dropdown menu, so I'm going to revert that change.

**Comment by sarahpearson** [comment]
Interesting! I guess I always thought that the 80% threshold applied to whether it appeared live anywhere, not to whether it showed up in the language dropdown. In a situation like this, where the deed is fully translated, is there a way to make an exception for it? If not, we will alert the team that they need to translate the other strings in Transifex in order for it to show up. 

Thanks for reverting the other change. Sorry if I caused confusion there.

**Comment by aldenstpage** [comment]
I would recommend going the route of doing further translation. After all, 40% of the deed is unfinished, and the 80% threshold was likely put there for a good reason.

Alternatively, we can patch the `cc.i8n` to have a lower threshold (59%?), but that will of course mean a lot of unfinished deeds will start showing up. We could introduce an exceptions feature, where we can manually force certain deed translations through, but that will introduce more maintenance overhead for the deeds. I'll defer to you and @kgodey on that decision, but my suggestion is that we keep this process as automated as possible.

**Comment by peterspdx** [comment]
If we do anything on the threshold, it should be increased never decreased. 80% was put there for a good reason, but IMHO it's a very low bar. I would advocate for 90% or 95% at least. These are CC's products, and unless someone can read at least 80% but ideally even more than 90% in the language, we should not be publishing such a deed.
