### ISSUE TITLE
Remove mediation text from print view of 4.0 deeds

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/creativecommons.org#94]
there is a difference in content (text) between the printed version of the CC 4 deed and the screen view.  

The screen view excludes the following under the Notice elements, which appear under the print view (see attached).  

"The applicable mediation rules will be designated in the copyright notice published with the work, or if none then in the request for mediation. Unless otherwise designated in a copyright notice attached to the work, the UNCITRAL Arbitration Rules apply to any arbitration."

That text should ONLY appear on the special/unique 3.0 IGO deeds, not on any other deeds in either screen or print view.  And it SHOULD appear in both the screen or print views of those deeds.

**Comment by peterspdx** [comment]
And here's a screen shot of the print view, courtesy of an affiliate
[Creative Commons — Attribution 4.0 International — CC BY 4.pdf](https://github.com/creativecommons/creativecommons.org/files/798/Creative.Commons.Attribution.4.0.International.CC.BY.4.pdf)

**Comment by mattl** [comment]
Fixed. @robmyers worth noting that Chrom* has a bug which ignores print CSS pretty hard. Had to add a media rule to the file.
