### ISSUE TITLE
Where is https://licensebuttons.net/ repo?

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#953]
https://licensebuttons.net/ used to be a place where license buttons were placed and maintained. You could get icons in different quality from that site.

It was also intended to see the use of icons around the internet. It had some analytics running.

The site looks in disrepair and no repo can be found on it.

See: https://licensebuttons.net/ and click around.

Also, I would say that the way the directory is exposed at the moment could be a security issue if not properly set up or maintained.

**Comment by kgodey** [comment]
This is the repo that corresponds to it, although it's not up-to-date: https://github.com/creativecommons/www-i

Getting the site up to date is on our to-do list. We don't have a time frame for it yet, though.

**Comment by kgodey** [comment]
I made a separate ticket to track general licensebuttons.net issues (https://github.com/creativecommons/creativecommons.org/issues/955), closing this one.
