### ISSUE TITLE
PNG icons to small at /downloads

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/creativecommons.org#954]
https://creativecommons.org/about/downloads/ used to provide links to licensebuttons.net with a reasonable quality. Now the png icons are only 64x64 pixels. These are too small for common use on website.

Can we increase the size of the linked icons here.

Also see #953 for licensebuttons.net

**Comment by little-wow** [comment]
Odd – I copied these directly from the old downloads page so they shouldn't have changed. I'd recommend that you use the SVG and scale for the time being.

**Comment by mzeinstra** [comment]
Might be that I misremembered about the previous version. Issue remains, the PNG icons are to small to use. :)

**Comment by hugosolar** [comment]
Icons size increased to 1024x1024 px
also, Heart logos
