### ISSUE TITLE
Missing Full name of the license on the "choose" page

### ISSUE THREAD

**Issue by tshrinivasan** [creativecommons/creativecommons.org#967]
**Describe the bug**

https://creativecommons.org/choose/
In this page, when we select the desired options, the Full name of the license should be displayed. But currently, it is displayed without "Creative Commons" text.

**To Reproduce**
1. Go to https://creativecommons.org/choose/
2. Click on  
Allow adaptations of your work to be shared? = yes
Allow commercial uses of your work? = yes
3. In the box "Selected License" it is displayed as 
Attribution 4.0 International

**Expected behavior**
It should be displayed as 

Creative Commons Attribution 4.0 International

**How it will help?**
We encourage writers/bloggers to choose a license from this page and add the license info on their works.

They choose license and mention as 
Attribution 4.0 International
instead of 
Creative Commons Attribution 4.0 International

As they get only the text 
Attribution 4.0 International
on choosing.

If we improve this, it will help all to mention proper license name on their works.

**Screenshots**
Added screenshot

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 67

**Smartphone (please complete the following information):**

![cc-choose](https://user-images.githubusercontent.com/1268536/58149399-6eea0780-7c80-11e9-95c8-30faaebc321f.jpg)

**Comment by peterspdx** [comment]
I agree this would be a good fix.

**Comment by imskr** [comment]
Can I work on this issue ? Please assign this to me

**Comment by kgodey** [comment]
@imskr go ahead. I can't assign to you since you're not in the CC org but I'll mark it as in progress so people know it's claimed.

Be warned that we don't have documentation yet on setting this project up locally but you can talk to us on [Slack or IRC](https://creativecommons.github.io/community/) and we'll try to help if you run into any issues.

**Comment by devangmukherjee** [comment]
@dhruvkb @kgodey I would like to work on this, can you please assign it to me?

**Comment by dhruvkb** [comment]
@devangmukherjee you can work on it. 

See @kgodey's comment about not being able to formally "assign" it to you. You can still submit a PR.

**Comment by devangmukherjee** [comment]
@dhruvkb thank you, can you please tell me where can I find the code for this? there so many html files in legalcodes I can't find the "selected license" text and ```CHOOSER.CALL``` function.

**Comment by vishu2435** [comment]
is this issue open now can you assign this to me

**Comment by dhruvkb** [comment]
@vishu2435 you can work on it. 

See [the comment above](https://github.com/creativecommons/creativecommons.org/issues/967#issuecomment-515258193) that explains why we cannot formally "assign" it to you but you can submit a PR.

**Comment by vishu2435** [comment]
@dhruvkb but where is its html or js file i cant find it niether in docroot

**Comment by dhruvkb** [comment]
Sorry but I have no knowledge of this project or how to resolve this issue in particular.

**Comment by vishu2435** [comment]
I am a first time contributer can you give me some issue in which you can guide me . if you can help. I wanted to solve this one but i am unable to find files

**Comment by dhruvkb** [comment]
You should check out the [Issue Finder](https://opensource.creativecommons.org/contributing-code/issue-finder/) to find issues that are in your domain of experience.

**Comment by 2001asjad** [comment]
Hello, I would love to work on this issue as it would get me started with this org.
But can you just please guide me like which files to look?
Thank You

**Comment by dhruvkb** [comment]
@2001asjad since we are moving to the new [CC Chooser](https://github.com/creativecommons/chooser) very soon, I think your efforts would be better utilised there.
